### PR TITLE
Add failing Behat scenario for updating product position

### PR DESCRIPTION
**Pull request by bitbager**
| Q               | A
| --------------- | -----
| Branch?         | 1.0
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets |  mentioned in #9107 
| License         | MIT

### CODE REVIEW

**Comment by pamil** [comment]
Looks like the scenario fails because of undefined steps:
```
--- Use --snippets-for CLI option to generate snippets for following ui_managing_products suite steps:
    And this product has a position set to 1
    And this product has a position set to 2
    When I go to the list page for this products
    And I change the position for "Maserati Quattroporte" to 1
    And I change the position for "Lamborghini Gallardo Model" to 2
    And I click save positions
    Then I should be notified that the positions has been updated
    And "Maserati Quattroporte" should now have position set to 1
    And "Lamborghini Gallardo Model" should now have position set to 2
```

**Comment by bitbager** [comment]
Thought you want me to provide the Behat case only. I might not have time to provide a full PR and actually IMHO it is pointless to do the job partially just by providing a Behat tests.

**Comment by pamil** [comment]
That's fine as well, just the more complete the failing scenario is the more probable is that somebody would be willing to make it work :) I wouldn't say defining these steps is pointless, it's the casual process when fixing bugs - reproduce in tests, make tests green, refactor.

**Comment by pamil** [comment]
There's some point in providing that scenario - I could rerun it now and check if it still does not work - couldn't reproduce it manually on Sylius demo though.

**Pull request closed without merging**
