### PR TITLE
[CoreBundle][HwiOauth] Type error on HwiOauth authentication / Fix service definition

### LINKED ISSUE #5761: [CoreBundle][HwiOauth] Type error on HwiOauth authentication
Argument 2 passed to Sylius\Bundle\CoreBundle\OAuth\UserProvider::__construct() must implement interface Sylius\Component\Resource\Factory\FactoryInterface, instance of Sylius\Bundle\CustomerBundle\Doctrine\ORM\CustomerRepository given

From here https://github.com/Sylius/Sylius/commit/f26f57d0b5e86eb62cae4071e81c506b15563684

Forgot to update service definition in hwi_oauth.xml.

PR on the go

### PR DESCRIPTION
**Pull request by ylastapis**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Related tickets | fixes #5761 
| License         | MIT

### CODE REVIEW

**Comment by lchrusciel** [comment]
Please, can you change a name to something more meaningful?

**Comment by pamil** [comment]
It would be helpful to describe the fix in both commit message and PR title as 5761 does not say too much without context.

**Comment by Zales0123** [comment]
Agreed, as you mention fixes issue in ``Related tickets`` section, it would be pretty useful to know what's it issue about without checking it. Nevertheless, good to you for contributing! 👍  😄

**Comment by ylastapis** [comment]
You're right :)

I was wondering the usefulness of opening a ticket, related to a PR when there is not so much changes. Could I just open a PR ?

**Comment by pjedrzejewski** [comment]
@ylastapis Could you rebase, please? Thanks!

**Comment by ylastapis** [comment]
duplicate https://github.com/Sylius/Sylius/pull/6020 ?

**Comment by ylastapis** [comment]
ping @michalmarcinkowski @pamil could you merge this one ?
That will fix HwiOauth connection issues, even if not in the roadmap :)

**Comment by gdecorbiac** [comment]
@ylastapis : hwi_oauth.xml file has been changed since your bug fix. You should use the latest version of this file to fix the bug and avoid conflicts.

**Comment by michalmarcinkowski** [comment]
👍

**Comment by Mustabshir-K** [comment]
Hi, I am also using HWIOAuth in my sylius shop but i m stuck with following error, even i include 
new \HWI\Bundle\OAuthBundle\HWIOAuthBundle() in AppKernel.php File and i also follow your way to integrate HWIOAuth in sylius but coudlnt find any solution can any one provinde me simple tutorial for this provision.

I am facing this error

Fatal error: Uncaught exception 'Symfony\Component\DependencyInjection\Exception\InvalidArgumentException' with message 'There is no extension able to load the configuration for "hwi_oauth" (in C:\xampp\htdocs\gcapplication\app/config\config.yml). Looked for namespace "hwi_oauth", found "sylius_installer", "sylius_order", "sylius_money", "sylius_currency", "sylius_contact", "sylius_locale", "sylius_settings", "sylius_cart", "sylius_product", "sylius_archetype", "sylius_channel", "sylius_variation", "sylius_attribute", "sylius_taxation", "sylius_shipping", "sylius_payment", "sylius_mailer", "sylius_report", "sylius_promotion", "sylius_addressing", "sylius_inventory", "sylius_taxonomy", "sylius_flow", "sylius_pricing", "sylius_sequence", "sylius_content", "sylius_search", "sylius_rbac", "sylius_user", "sylius_ui", "sylius_admin", "sylius_metadata", "sylius_association", "sylius_review", "sylius_core", "sylius_web", "sylius_resource", "sylius_grid", "winzou_state_machine", "sylius_api", "sonata_block", "cmf_core", "cmf_block in C:\xampp\htdocs\gcapplication\vendor\symfony\symfony\src\Symfony\Component\Config\Loader\FileLoader.php on line 130

After include HWIOauth in AppKernel i found this issue

Fatal error: Uncaught exception 'Symfony\Component\DependencyInjection\Exception\InvalidArgumentException' with message 'There is no extension able to load the configuration for "firewalls" (in C:\xampp\htdocs\gcapplication\app/config\security.yml). Looked for namespace "firewalls", found "sylius_installer", "sylius_order", "sylius_money", "sylius_currency", "sylius_contact", "sylius_locale", "sylius_settings", "sylius_cart", "sylius_product", "sylius_archetype", "sylius_channel", "sylius_variation", "sylius_attribute", "sylius_taxation", "sylius_shipping", "sylius_payment", "sylius_mailer", "sylius_report", "sylius_promotion", "sylius_addressing", "sylius_inventory", "sylius_taxonomy", "sylius_flow", "sylius_pricing", "sylius_sequence", "sylius_content", "sylius_search", "sylius_rbac", "sylius_user", "sylius_ui", "sylius_admin", "sylius_metadata", "sylius_association", "sylius_review", "sylius_core", "sylius_web", "sylius_resource", "sylius_grid", "winzou_state_machine", "sylius_api", "sonata_block", "cmf_core", "cmf_blo in C:\xampp\htdocs\gcapplication\vendor\symfony\symfony\src\Symfony\Component\Config\Loader\FileLoader.php on line 130

Can anyone please help me ?
Thanks in advance.

**Pull request merged**
