### PR TITLE
Made: Payum links locale-based

### LINKED ISSUE #10942: [Payum] Authorize link not contain locale and gives an error
**Sylius version affected**: 1.6

**Description**  
When we have multi-channel store (say `US` and `DK`) and second channel don't have default locale (say have only `da_DK`, but haven't `en_US`), then after pressing pay button and redirecting to `http://127.0.0.1:8000/payment/authorize/BMhXXkSNJ9vxR8umzBTv8uWmNQzD_ISbcJPxZ1YmM4s`, we see: `The "en_US" locale is unavailable in this channel.`

**Possible Solution**  
- Make payum links locale-based (prepend `/locale/`)?

Also, I believe default fixtures should have multiple channels out of the box - that way more miltichannel-related bugs will be visible at demo => they will be fixed.

### PR DESCRIPTION
**Pull request by igormukhingmailcom**
| Q               | A
| --------------- | -----
| Branch?         | 1.5
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #10942
| License         | MIT

### CODE REVIEW

**Comment by Zales0123** [comment]
The base of this pull-request was changed, you need fetch and reset your local branch 
if you want to add new commits to this pull request. **Reset before you pull, else commits
may become messed-up.**

Unless you added new commits (to this branch) locally that you did not push yet, 
execute `git fetch origin && git reset "patch-4"` to update your local branch.
 
Feel free to ask for assistance when you get stuck :+1:

**Review by lchrusciel — APPROVED** [review]
I'm wondering however, if we can test it somehow to avoid regression in the future

**Review by pamil — COMMENTED** [review]
It looks like we had some reason for Payum links not being localised, that's why they're in `config/routes/sylius_shop.yaml` instead of inside SyliusShopBundle. Does anyone remember /cc @Zales0123 @lchrusciel @GSadee?

**Comment by lchrusciel** [comment]
No, I don't. And I regret that we didn't write ADR back then :(

**Comment by lchrusciel** [comment]
another question, would if it is a BC-Break, and probably it is, isn't it?

**Comment by igormukhingmailcom** [comment]
Do not stale

**Comment by vvasiloi** [comment]
The Payum routes were localized a few years ago, so you probably had a reason to remove the locale.
Here are some references, unfortunately there is not much context:
https://github.com/Sylius/Sylius/pull/7609
https://github.com/Sylius/Sylius/pull/7650

However, there's evidence that it causes issues without locale:
https://github.com/Sylius/Sylius/issues/10942
https://github.com/Sylius/Sylius/issues/8984

So maybe the problem is somewhere else?
I can't think of a reason these routes should be localized right now, but there might be some use-cases, so it should work both ways, just like the whole shop: https://docs.sylius.com/en/latest/cookbook/shop/disabling-localised-urls.html

I propose to move the routes back to shop bundle and make sure it works with and without locale.
I will write some scenarios later this week, if someone doesn't do it before.

**Comment by jakubtobiasz** [comment]
Hi @igormukhingmailcom!
Thanks for contributing. As it's easy to adjust this part, we decided not to include it in Sylius. Anyway, when we merge this PR it won't affect end-projects as they have their routing config.

**Pull request closed without merging**
