### PR TITLE
[Payum] Update payum to 1.3

### LINKED ISSUE #4413: [Bug] Update Payum to the latest version
Due to the bug described [here](https://github.com/Sylius/Sylius/issues/4405) we should update composer to use the latest version of Payum.

### PR DESCRIPTION
**Pull request by Niiko**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Related tickets | fixes #4413
| License         | MIT

Update of payum, i had to add "php-http/guzzle6-adapter" because payum 1.3 use now a virtual package "php-http/client-implementation". 

This virtual package remove all adapters, according to doc, i had this one.

see [https://github.com/Payum/Payum/blob/master/UPGRADE.md](Payum/Payum)

### CODE REVIEW

**Comment by makasim** [comment]
👍 

Would be good to upgrade payum bundle version (2.0).

**Comment by Niiko** [comment]
Yes, but i'm stuck on require : "symfony/twig-bundle": "~2.8|~3.0",

**Comment by makasim** [comment]
I am working on decoupling payum bundle from twig bundle at all. Still working in progress though

**Comment by pjedrzejewski** [comment]
Thank you Nicolas!

**Pull request merged**
