### PR TITLE
[User] Decoupled password encoders and updaters from UserInterface

### PR DESCRIPTION
**Pull request by pamil**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| License       | MIT

Introduced `CredentialingInterface` which implementation needs to be passed to password encoders and updaters instead of `UserInterface` with methods like `setCustomer()` etc.

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
Is this name a result of fun discussion in the office? :D

**Comment by TheMadeleine** [comment]
@pjedrzejewski, flawless observation. :+1:

**Comment by pjedrzejewski** [comment]
@TheMadeleine @pamil Are we sure it makes sense? Credentialing means something a bit different as far as I know/googled. Perhaps CredentialsHolderInterface or let's go full-Javan SecurityCredentialsHolderInterface?

**Comment by stloyd** [comment]
IMO this interface is useles... What's the real point for it? Are so commonly re-use this interface somehow?

**Comment by pamil** [comment]
@stloyd right now I have to implements UserBundle's `UserInterface` which ships with `Customer` relation, `OAuthAccount`s relation and all the stuff I don't really need in my project. This interface will let me use UserBundle's `PasswordUpdater` and `PasswordEncoder`.

**Comment by pamil** [comment]
@pjedrzejewski `CredentialsHolderInterface` looks promising and way more understandable, thanks! :)

**Comment by pjedrzejewski** [comment]
Thank you Kamil!

**Pull request merged**
