### PR TITLE
switch to template inheritance for checkout

### LINKED ISSUE #7418: Checkout-Layout duplicates normal layout instead of extending
Hey there,

i adjusted some meta tags and noticed that it didn't work in the checkout.
```ShopBundle\Checkout\layout.html.twig``` is not extending ```ShopBundle\layout.html.twig``` which leads to duplication.

I'd suggest to use Twigs ```extend``` and override the unnecessary ```block``` tags.
This needs some adjustments in ```ShopBundle\layout.html.twig``` e.g. the topbar and the header are not in a ```block```.

If you agree I'm happy to provide a PR.

### PR DESCRIPTION
**Pull request by psren**
| Q               | A
| --------------- | ---
| Bug fix?        | yes |
| New feature?    | no |
| BC breaks?      | no |
| Related tickets | fixes #7418 |
| License         | MIT |

The look remained the same:

bildschirmfoto 2017-02-07 um 15 21 20
bildschirmfoto 2017-02-07 um 15 21 54
bildschirmfoto 2017-02-07 um 15 22 14

### CODE REVIEW

**Comment by psren** [comment]
Mhh I'm not sure why travis is failing. Could you have a look, I'm quite sure it has nothing to do with this PR ?

**Comment by pjedrzejewski** [comment]
@psren Restarted the build. :)

**Comment by psren** [comment]
Thanks @pjedrzejewski it worked :-D

**Comment by pjedrzejewski** [comment]
Thanks Patrick, this is a great improvement! :)

**Pull request merged**
