### PR TITLE
Affiliate feature

### PR DESCRIPTION
**Pull request by pentarim**
Adds affiliate features. Based on  https://github.com/Sylius/Sylius/pull/2621 . 

Affiliate management

The goal of this PR is to build an affiliate system for Sylius. Main features are:
- Affiliate management
- Affiliate goal management (with rules and provisions)
- Banner management
- Provision history
- Backend and frontend interfaces

The strucutre of the affiliate related features are similar to how promotions are implemented, via rules (NthOrder, RouteVisit, UriVisit etc) and provisions that are associated with affiliate goals. This PR implements a new context that is aware of an affiliate (the check itself is cookie and query parameter based)

The main parts of it are:
- AffiliateContext
- Goals with associated rules and provisions
- ReferralSubscriber which listens to actions that are referrable
- ReferralProcessor which processes a referral

**Work on this PR was sponsored by [Locastic - Web & Mobile development](http://www.locastic.com)**

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
Why separate PR and why losing all the commits? :(

**Comment by pentarim** [comment]
Because there were some commits already present in the previous PR the havent landed in master yet and were beyond my gitfu to untangle

**Comment by peteward** [comment]
It would be really great to see a full description of the features of this feature and how it works, because at 8000 lines long it's not something you can quickly get to grips with.

**Comment by antonioperic** [comment]
@peteward here is short specification what this feature can do, maybe something are different but in basics that is it

Affiliate:
Affiliate partner is person who brings new customers to our webshop and get revorded in fix amout or in some percetange or if there is loyalty in some points (more about loyalty later).

Administrator must have complete insights in system and all trasactions and in any moment he can pause or ban some account.

Affiliate partner must have insights in his account including all transactions and statistics about records.

Affiliate use cases example:
- Shop owner provides some banners and links to Affiliate partner (every user can be affiliate partner). For every conversion or setup goal (for example new registration) affilate partner will get some provision (for example 5% of every order that new user completes) or fixed amount (or 1 dollar per registration)
- Affiliate partner can inivte his friends using web form via email. For every new registration user gets 1 dollar, and after every completed order he gets 2% of every order
- Affiliate user can share his link on social media and get revards same as in step before
- share your affilate link (user can take his link with code and share it)
- more level of affiliate partners - with specificate rules for revards
- history of payments
- history of earnings 
- my banners and links (place where user can take banners and links with his code)
- my affilate program (to see description of his affiliate program)
- my affiliate network - list of friends who are aquired via affiliate program and history of trasnactions with provision
- pay per lead/action - for example registraion
- pay per transaction - get some provison for every order that his friend complete in some period

Admin:
- simple controll of affilate partners - pause, turn off, changing affiliate group
- control of groups with rules for revards
- insights to every transaction and every user
- creating and publishing banners
- define time period while promotion is on (for example 20 days after click if user get register affilate partner will get rewarded)



Affiliate user:
- every registred user can also be affiliate partner
- he can inivte his friends using web form via email

**Comment by peteward** [comment]
Hi @antonioperic,

Sounds like a really great system, very powerful.
I've forwarded this onto our online marketing department but I can already see that this would be useful for a wide variety of Sylius users so it sounds like a great feature.

If I get some spare time soon I'll have a read through of the PR ;)

**Comment by antonioperic** [comment]
@peteward  yes, there is a lot of possibilities with it. Hope we can merge it very soon as I want to put it in production ASAP and we wanted to build it as feature

**Comment by antonioperic** [comment]
@pjedrzejewski @michalmarcinkowski can you help us marge soon? It is critical for one project that we are working on, or at least give us clue when we can expect your overview?

**Comment by pjedrzejewski** [comment]
@antonioperic This is a really cool feature, I hope to have a look at this code during this week, but still I doubt it will mergable. I suggest having it as a custom bundle right now. It requires few iterations of review to get this merged. I will do my best to make it happen as soon as possible, but that is still few weeks I guess, not days. We have some other big PR in the queue, which need to be merged soon. What prevents using it for Misi without it in the core?

**Comment by antonioperic** [comment]
@pjedrzejewski we will use fork for now for our project, I think that will work. But it will be nice if you can do that during next weeks to complete this PR as we prepare also LoyaltyFeature. 
It is for one other project not Misi :)

**Comment by rvanlaak** [comment]
Looks awesome :rocket:  Would be really great if this can be merged, then I'll can start testing it on `dev-master` for my scenarios :+1:

**Comment by antonioperic** [comment]
@rvanlaak I will love that also :)
cc @pjedrzejewski

**Comment by rvanlaak** [comment]
@pjedrzejewski can you give us a status update on this one?

**Comment by pjedrzejewski** [comment]
@rvanlaak Definitely not in scope of Sylius core... That should be a standalone bundle that extends the core.

**Comment by antonioperic** [comment]
@pjedrzejewski I think we can close this one, as not part of Core anymore

**Comment by antonioperic** [comment]
@rvanlaak if you are interested in this one you can ping me at antonio@locastic.com

**Comment by rvanlaak** [comment]
Oh, we're not using `core` so 👍 for making it a separate component + bundle. But, what does outside of core scope actually means? This PR will not be merged eventually?

**Comment by pentarim** [comment]
@rvanlaak It's available as a standalone bundle based on 0.19 on packagist
https://packagist.org/packages/pentarim/Sylius-affiliatebundle With the
current scope narrowing of core I doubt it will ever make it there

**Comment by rvanlaak** [comment]
Okay thanks for clarifying that, because that'll change our development schedule around an affiliate feature then :)

**Comment by rvanlaak** [comment]
What about closing this PR, or telling something about the future of an affiliate in Sylius 👍

**Comment by pamil** [comment]
For sure it's not in scope of Sylius itself, could be implemented as a plugin made by the community.

**Pull request closed without merging**
