### PR TITLE
[TaxonomyBundle] Fix display bug in choice list and enlarge area

### PR DESCRIPTION
**Pull request by psyray**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Related tickets | none
| License         | MIT

Taxon choice list is badly sorted by id.
To keep tree consistent I've made this PR

**My taxon list**
selection_490

**Before PR**
selection_488

**After PR**
selection_489

I've also enlarge the choice list height on product page, it's more readable whan you have a lot of taxons

Enjoy ;)

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
@psyray I noticed this bug recently too, quite annoying! I think that proper fix would be on the query level (sort taxons properly), wdyt?

**Comment by psyray** [comment]
I think the same thing before working on this PR, it's more elegant and a good practice to create a method in the Taxon repository.
You convinced me ;)

I will rework on it.
Sorting on the tree left seems to be good no ?

**Comment by psyray** [comment]
Done !
More concise, more elegant, same result ;)

**Comment by pjedrzejewski** [comment]
Nice, thanks Raynald! 👍

**Pull request merged**
