### PR TITLE
try headless chrome instead of selenium2

### PR DESCRIPTION
**Pull request by gabiudrescu**
| Q               | A
| --------------- | ---
| Bug fix?        | no |
| New feature?    | yes |
| BC breaks?      | no |
| Related tickets | n/a |
| License         | MIT |

trying to see how https://gitlab.com/DMore/behat-chrome-extension works.

### CODE REVIEW

**Comment by gabiudrescu** [comment]
tough luck :(

https://gitlab.com/DMore/behat-chrome-extension/issues/4

**Comment by pamil** [comment]
Wish you all the best to integrate our Behat suite with headless Chrome! 🎉  I'm getting too old for this kind of stuff :D

**Comment by gabiudrescu** [comment]
@pamil any tips and tricks you want to share? based on your previous experience?

**Comment by pamil** [comment]
Just be patient, seriously :) And watch out for Chrome version on Travis CI.

**Pull request closed without merging**
