### PR TITLE
[Promotion][Core][DX] Promotion eligibility checker refactoring

### PR DESCRIPTION
**Pull request by Zales0123**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | yes
| Deprecations?   | no
| Related tickets | 
| License         | MIT

While working with promotions, I've been struggling with lots of bad/worse/not-so-good code in eligibility checker. I tried to refactor it, by splitting responsibilities into different services and clean some code in them.

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
Great work Mateusz, thanks! :+1:

**Comment by inssein** [comment]
@Zales0123 Found a quick bug that may have been introduced by this PR. It seems that the eligibility checker runs when a product is being added to the cart, and when not eligible, it will throw flash messages. This should only happen when a coupon is manually entered.

Will debug this further later on tonight.

**Comment by Zales0123** [comment]
@inssein thanks for your comment, could you open an issue with problem description, as it will probably get lost here? I'll look into it as soon as possible ;)

**Comment by inssein** [comment]
@Zales0123 I added it to https://github.com/Sylius/Sylius/issues/4544 last night, but perhaps I should have created a new issue.

**Comment by rvanlaak** [comment]
Tried to upgrade from `0.17` to `0.18` today. We use the `PromotionBundle` standalone from any other  bundles, and did not find any upgrade instructions. If we look at [`CHANGELOG.md`](https://github.com/Sylius/Sylius/blob/master/CHANGELOG.md) for 'promotion' there were quite some changes though. Maybe you got some hints on the upgrade procedure?

**Pull request merged**
