### PR TITLE
[Core] Fixtures for addresses

### PR DESCRIPTION
**Pull request by NeverResponse**
| Q               | A
| --------------- | ---
| Bug fix?        | no |
| New feature?    | no |
| BC breaks?      | no |
| Related tickets | - |
| License         | MIT |

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
Thank you Jasiek!

**Comment by lchrusciel** [comment]
We have missed tests for this fixture and factory :(

**Comment by teohhanhui** [comment]
What are these addresses doing just hanging around? They're only useful when they're in a `Customer` or an `Order`, no?

**Comment by Zales0123** [comment]
They're by default set to a [random customer](https://github.com/Sylius/Sylius/pull/7021/files#diff-f4d8a7ac18cd6e0ac144056215fe6b2aR112)

**Pull request merged**
