### PR TITLE
replace jquery 2 with jquery 3

### LINKED ISSUE #8321: Upgrade jQuery to 3.0
Should be possible with Semantic-UI 2.2, which supports 3.0.

### PR DESCRIPTION
**Pull request by psren**
| Q               | A
| --------------- | ---
| Bug fix?        | no |
| New feature?    | no |
| BC breaks?      | yes, for jQuery usage |
| Related tickets | fixes #8321  |
| License         | MIT |

### CODE REVIEW

**Comment by psren** [comment]
Tests are failing, but this should not be related?

> Migration 20161209095131 was executed but did not result in any SQL statements.

**Comment by pamil** [comment]
Migration isn't causing the fail, Gulp is - https://travis-ci.org/Sylius/Sylius/jobs/257648887#L796

**Comment by psren** [comment]
I'm not quite sure what the actual error was.
Tests are green now. I had to require ```node-sass``` in the packages.json to make it work.

It already worked on my box ™️  but now works on travis, too.
Maybe this was a problem with the version in the .lock file and a problem with ubuntu?
(I'm on mac here)

I found something about this error [here](https://github.com/sass/node-sass/issues/1247#issuecomment-154285934) and the same error in an older version of node-sass [here](http://blog.johnwmatthews.com/enoent-no-such-file-or-directory-scandir-dot-dot-dot-slash-node-modules-slash-node-sass-slash-vendor)

**Comment by pjedrzejewski** [comment]
Thanks Patrick, great work! :)

**Pull request merged**
