### PR TITLE
Create sylius/contracts package

### PR DESCRIPTION
**Pull request by jakubtobiasz**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.13
| Bug fix?        | no/
| New feature?    | kinda
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| License         | MIT

### CODE REVIEW

**Comment by esserj** [comment]
Would it make sense to separate the contracts instead of creating a single repository?
i.e. `sylius/statemachine-contracts`

**Comment by esserj** [comment]
train of though here is, I may only want to depend on some components/bundles
and by merging all into one repo, we'll lose track of what relies on what

**Comment by esserj** [comment]
Maybe we should also avoid joining it into Components, but instead, like symfony also does, have it on the same level as component/bundle i.e. `Sylius/Contracts/StateMachine`

**Comment by jakubtobiasz** [comment]
Replaced by #15729

**Pull request closed without merging**
