### PR TITLE
[PayumBundle] Prevent hard-dependency error to CoreBundle

### PR DESCRIPTION
**Pull request by aramalipoor**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Related tickets | - |
| License | MIT |

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
I think SyliusPayumBundle should depend on Core. Are you using it without the core? :D

**Comment by pamil** [comment]
PayumBundle requires `sylius/core` but should require `sylius/core-bundle`.

**Comment by aramalipoor** [comment]
:D Yeah we're creating a very simple app and need some stuff in PayumBundle, so do you think moving them in our own AppBundle is OK?

**Comment by pamil** [comment]
I would just define own `sylius.invoice_number_generator` service then (interface is placed in Core component) or override the service that uses it.

**Comment by pjedrzejewski** [comment]
@aramalipoor Yeah and if it is generic and not related to Sylius, then I'd consider contributing it to PayumBundle. :)

**Pull request closed without merging**
