### PR TITLE
[Behat] [DX] Injecting shared storage as a first argument

### PR DESCRIPTION
**Pull request by lchrusciel**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Fixed tickets | [comment](https://github.com/Sylius/Sylius/pull/4235#discussion_r54007885)
| License       | MIT

### CODE REVIEW

**Comment by pamil** [comment]
:+1:

**Comment by Zales0123** [comment]
:+1:

**Comment by michalmarcinkowski** [comment]
:+1: but the specs are failing :)

**Comment by pjedrzejewski** [comment]
@lchrusciel Requires rebasing.

**Pull request merged**
