### PR TITLE
Use Null Coalesce Operator

### PR DESCRIPTION
**Pull request by carusogabriel**
| Q               | A
| --------------- | -----
| Branch?         | 1.0
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | -
| License         | MIT

### CODE REVIEW

**Comment by pamil** [comment]
It's a good idea, can you rebase to target 1.0 branch with this PR?

**Comment by pamil** [comment]
Just retriggering Travis build :)

**Comment by carusogabriel** [comment]
No problem. Should I change/rebase something?

**Comment by pamil** [comment]
Everything looks all right, the failing build is connected to Symfony 3.4 not being fully compatibile with Symfony 3.3, I'm on it! :)

**Comment by carusogabriel** [comment]
Gonna rebase and run tests again :sweat_smile:

**Comment by lchrusciel** [comment]
Thanks Gabriel! :)

**Pull request merged**
