### PR TITLE
Fix Jean 04 size

### PR DESCRIPTION
**Pull request by loic425**
| Q               | A                                                            
|-----------------|--------------------------------------------------------------
| Branch?         | 1.12
| Bug fix?        | yes  (for our planet)        
| New feature?    | no                                                       
| BC breaks?      | no                                                       
| Deprecations?   | no
| Related tickets | partially #14583    
| License         | MIT                                                          

Capture d’écran du 2022-12-08 14-21-38

### CODE REVIEW

**Review by Ferror — APPROVED** [review]

**Comment by vvasiloi** [comment]
They're no longer black though... maybe just optimize the original image?

**Review by lchrusciel — APPROVED** [review]

**Review by Zales0123 — COMMENTED** [review]
👌 although not black jeans with "black" in their name make me sick 😅 Do you think we can do something with it, @loic425? :dancer: Also, I believe it could be opened to 1.11 🖖

**Comment by loic425** [comment]
@Zales0123 Yep, but I dont know how to reduce the svg current file.

**Comment by jakubtobiasz** [comment]
Is there any good reason why we use SVG for the non-vector image? I see we use everywhere jpg (so we don't test the ability to use different extensions) 🤔.

**Comment by loic425** [comment]
> Is there any good reason why we use SVG for the non-vector image? I see we use everywhere jpg (so we don't test the ability to use different extensions) thinking.

@jakubtobiasz From my memory (maybe you should look at the PR where it was introduced), there was an issue with SVG files at some point.

**Pull request closed without merging**
