### PR TITLE
CRITICAL Symfony2.8 Debug Toolbar Fix

### PR DESCRIPTION
**Pull request by peteward**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| License         | MIT

screen shot 2016-02-29 at 13 23 27

To:

screen shot 2016-02-29 at 13 22 41

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
@peteward Something must be wrong with my life when I literally got scared by this "CRITICAL" PR headline until I realized what is going on here. Thank you Peter!

**Comment by pamil** [comment]
:+1: It's blocking me from releasing another batch of weird Behat extensions.

**Comment by peteward** [comment]
Sorry, I'm feeling mischievous today...

**Comment by pjedrzejewski** [comment]
@pamil MultiContextContainerPageObjectDecoratorMinkDebugPluginExtension must be open sourced soon.

**Comment by okwinza** [comment]
i'm not sure about this PR.
i think we need to open RFC to discuss such a change.

**Comment by lchrusciel** [comment]
:+1: for RFC

**Comment by pjedrzejewski** [comment]
Thanks Peter! :+1:

**Pull request merged**
