### PR TITLE
[API] Fix admin's side can't create new taxonomy

### PR DESCRIPTION
**Pull request by dawkaa**
I fixed the admin's side can't create new taxon.

| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.13                 |
| Bug fix?        | yes                                                       |
| New feature?    | no                                                       |
| BC breaks?      | no                                                       |
| Deprecations?   | no|
| Related tickets |
| License         | MIT                                                          |

### CODE REVIEW

**Comment by jakubtobiasz** [comment]
Hi @dawkaa!
Thanks for your contribution!

Would you like to write a test covering this case (the PHPUnit API test case should be enough)? I know there's none currently, but it should protect us in the future. Thanks in advance. If you need any help, just let me know :).

**Comment by dawkaa** [comment]
> Hi @dawkaa! Thanks for your contribution!
> 
> Would you like to write a test covering this case (the PHPUnit API test case should be enough)? I know there's none currently, but it should protect us in the future. Thanks in advance. If you need any help, just let me know :).

Hi @jakubtobiasz Sure, I see.
Thanks for your reply. If there is something I don't know, I will ask.
I added the PHPUnit API test case for a new taxon, so again review, please.

**Comment by dawkaa** [comment]
@jakubtobiasz

**Comment by jakubtobiasz** [comment]
@dawkaa I see after your force push the test disappeared.

**Comment by dawkaa** [comment]
> @dawkaa I see after your force push the test disappeared.

Sorry, I pushed the PHPUnit API test case from my laptop and did a force push from my work laptop 6 hours ago, so I would re-push after returning home. :smile:

**Comment by jakubtobiasz** [comment]
@dawkaa cool, ping me when done. I'll ping the rest of team to review it :).

**Review by jakubtobiasz — APPROVED** [review]

**Review by NoResponseMate — APPROVED** [review]

**Comment by jakubtobiasz** [comment]
Thank you, @dawkaa!

**Comment by dawkaa** [comment]
> Thank you, @dawkaa!

:smile:

**Review by GSadee — APPROVED** [review]

**Pull request merged**
