### PR TITLE
[Resource] Lazy resource repositories

### PR DESCRIPTION
**Pull request by pamil**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

It will save a lot of our time when we inject a repository to a service that does not use it, but is used while there is no database, eg. repositories injected to Twig extensions or cache warmers.

### CODE REVIEW

**Comment by gonzalovilaseca** [comment]
Why can't final classes be lazy?

**Comment by pamil** [comment]
@gonzalovilaseca lazy classes are made by extending the base class by some kind of proxy class.

**Comment by gonzalovilaseca** [comment]
:+1: thanks

**Comment by michalmarcinkowski** [comment]
:+1:

**Comment by pjedrzejewski** [comment]
Thanks Kamil!

**Pull request merged**
