### PR TITLE
Added pull request template

### PR DESCRIPTION
**Pull request by pamil**
Recently added Github feature: https://github.com/blog/2111-issue-and-pull-request-templates

### CODE REVIEW

**Comment by peteward** [comment]
:+1:  No issue template?

**Comment by pamil** [comment]
I don't have any good idea for issue template :)

**Comment by lchrusciel** [comment]
:+1:

**Comment by Zales0123** [comment]
:+1:

**Comment by pjedrzejewski** [comment]
Epic, thanks!

**Pull request merged**
