### PR TITLE
[WIP][API] Use codes instead of IDs in the REST API for complex objects

### PR DESCRIPTION
**Pull request by jjanvier**
To follow what I started on https://github.com/Sylius/Sylius/pull/6560

| Q               | A
| --------------- | ---
| Bug fix?        | no/yes |
| New feature?    | no/yes |
| BC breaks?      | no/yes |
| Related tickets | fixes #X, partially #Y, mentioned in #Z |
| License         | MIT |

### CODE REVIEW

**Comment by jjanvier** [comment]
@michalmarcinkowski @pjedrzejewski 

Hello guys,

I'm having some trouble in using codes instead of IDs for objects that are linked to other objects.
For example, a `Channel` is linked to several locales via the `locales` property. That's why I created the `Sylius\Bundle\ResourceBundle\Form\DataTransformer\ResourcesToIdentifiersTransformer` but that doesn't seem to work so far. Locales are still directly transformed via their IDs.

Do you have any idea of what I'm doing wrong?

**Comment by jjanvier** [comment]
@michalmarcinkowski @pjedrzejewski any hint?

**Comment by michalmarcinkowski** [comment]
We're reworking most of the forms to make it compatible with Symfony 3.0, maybe after that it will work well.

**Comment by pjedrzejewski** [comment]
Implemented! :)

**Pull request closed without merging**
