### PR TITLE
Use getRoot on taxons (replacing the remove getTaxonomy)

### PR DESCRIPTION
**Pull request by coudenysj**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Related tickets | relates to #3773
| License         | MIT

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
Good catch, but I think we should use ``code`` here and not the name, wdyt?

**Comment by coudenysj** [comment]
Makes sense. Updated the code.

**Comment by pjedrzejewski** [comment]
Thanks Jachim! 👍

**Comment by michalmarcinkowski** [comment]
There was already a fix for that in https://github.com/Sylius/Sylius/pull/5170. @coudenysj could you write spec for this method to prevent from regression in the future?

**Comment by coudenysj** [comment]
Sorry @michalmarcinkowski & @h-sn, I wasn't aware of that. If @h-sn is willing to rebase then the test would still be his code. If not, I'm happy to supply the test for this.

**Pull request merged**
