### PR TITLE
Move hardcoded declaration of controllers into configuration

### PR DESCRIPTION
**Pull request by stloyd**

### CODE REVIEW

**Comment by stloyd** [comment]
@pjedrzejewski ping...

**Comment by pjedrzejewski** [comment]
I do not like the mismatch between service name and class parameter... Can we fix it? Maybe we could introduce hierarchical config for controllers.

**Comment by aRn0D** [comment]
@stloyd can you update this PR ?

**Comment by pjedrzejewski** [comment]
Frontend controllers will be reworked soon with new theme. These will be most likely removed.

**Pull request closed without merging**
