### PR TITLE
Update methods to match symfony generated class

### PR DESCRIPTION
**Pull request by cdtweb**
Q | A
-- | --
Branch? | 1.0
Bug fix? | yes
New feature? | no
BC breaks? | no
Deprecations? | no
Related tickets | replace #8757
License | MIT

Removes the return types from `getCacheDir()` and `getLogDir()` to match what is being generated by `vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php` to resolve declaration mismatch.

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
@cdtweb thanks for your PR, could you rebase against 1.0, please? :)

**Comment by cdtweb** [comment]
I have rebased on the 1.0 branch. Let me know if you need anything else.

**Comment by GSadee** [comment]
@cdtweb it seems like you didn't do rebase or sth went wrong, please try again 😃

**Comment by adamelso** [comment]
When this PR is merged, it could be followed up by adding PHP 7.2 to Travis which is currently RC3.

**Comment by cdtweb** [comment]
I won't be back to work until the week of the Oct 23 -- so if someone else wants to take care of this for me, that would be great. Otherwise, I'll try and figure this out around then.

**Comment by stefandoorn** [comment]
In this PR I've added 7.2 to Travis, but running into some issues still: https://github.com/Sylius/Sylius/pull/8771.

**Comment by GSadee** [comment]
Closing in favour of #8797

**Pull request closed without merging**
