### PR TITLE
[WIP] Generic resource builder

### PR DESCRIPTION
**Pull request by aRn0D**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

@Sylius/core-team It is not finished yet but what do you think about it ?

### CODE REVIEW

**Comment by aRn0D** [comment]
@pjedrzejewski pong !

**Comment by aRn0D** [comment]
@pjedrzejewski ping

**Comment by aRn0D** [comment]
@pjedrzejewski pong

**Comment by stloyd** [comment]
@aRn0D TBH. I don't think we should have those builders at all, as they are kinda duplication of approach we (me & Paweł) suggest in other PRs: advanced managers or plain managers + factories.

So IMO it would better do deprecate them after we got one of approaches mentioned above merged.

**Pull request closed without merging**
