### PR TITLE
PhpSpec config has been added with ps4 support

### PR DESCRIPTION
**Pull request by aRn0D**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
@aRn0D Kill me but we need one last time rebase. :) I will wait for you!

**Comment by aRn0D** [comment]
@pjedrzejewski done !

**Comment by aRn0D** [comment]
@pjedrzejewski I fixed some stuff it should be good

**Comment by aRn0D** [comment]
@pjedrzejewski all the specs are green !

**Comment by pjedrzejewski** [comment]
Thank you Arnaud! :+1:

**Comment by aRn0D** [comment]
:v:

**Pull request merged**
