### PR TITLE
[Promotion] Remove add product action

### PR DESCRIPTION
**Pull request by lchrusciel**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | yes
| Related tickets | 
| License         | MIT

Probably not tested at all. Lets see if test would pass.

### CODE REVIEW

**Comment by michalmarcinkowski** [comment]
Thanks Łukasz!

**Comment by gabiudrescu** [comment]
omg, no more promotions that could add zero-priced products to cart if certain actions are met? :(

**Comment by gabiudrescu** [comment]
Can I help?

**Comment by lchrusciel** [comment]
If you are willing to open PR with them + test we would be more then happy to add them. It should not be more work then #6451.

**Pull request merged**
