### PR TITLE
[BuildFix] Fix AbstractMigration use statement

### PR DESCRIPTION
**Pull request by Zales0123**
| Q               | A
| --------------- | -----
| Branch?         | master
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| License         | MIT

😱

### CODE REVIEW

**Comment by lchrusciel** [comment]
Thank you, Mateusz! :tada:

**Comment by stefandoorn** [comment]
May be a good one to have tests to check migrations.. :-) I copy pasted the uses etc. from another migration, but that was on 1.2 I think.

**Comment by Zales0123** [comment]
Well, in fact, there is a test - using them to build a database on Travis https://github.com/Sylius/Sylius/blob/master/etc/travis/suites/application/before_script.sh#L10 😄 and it was the reason why the build was failing

**Comment by stefandoorn** [comment]
Oeps, I didn't say anything :D

**Pull request merged**
