### PR TITLE
[BC Break][Core][Pricing] Remove unused Pricing bundle and component

### PR DESCRIPTION
**Pull request by Zales0123**
| Q               | A
| --------------- | ---
| Bug fix?        | no |
| New feature?    | no |
| BC breaks?      | yes |
| Related tickets | |
| License         | MIT |

Due to last changes in pricing, we no longer use pricing calculators or any interface from *Pricing* component or bundle. I'm 100% sure this functionality will be provided as extension to *Sylius* and it's of course still available as separate bundle/component for those who want to use it in theirs applications.

### CODE REVIEW

**Comment by michalmarcinkowski** [comment]
@Zales0123 please cherry pick this commit to master branch 😉

**Comment by pamil** [comment]
@Zales0123 you can change the target branch while editing the PR title 🌮

**Comment by Zales0123** [comment]
@pamil Unfortunately it results with billions of unneeded commits from ``currency-party``, it would probably be easier to open a new PR with cherry-picked commit ;)

**Comment by Zales0123** [comment]
Closing in favor of https://github.com/Sylius/Sylius/pull/6916

**Pull request closed without merging**
