### PR TITLE
Make LoadMetadataSubscriber easier to extend

### PR DESCRIPTION
**Pull request by umpirsky**

### CODE REVIEW

**Comment by aRn0D** [comment]
:+1:

**Comment by steffenbrem** [comment]
Also looking for something like this.

**Comment by bburnichon** [comment]
I think PR #2241 could also be useful to ease metadata loading process.

**Comment by steffenbrem** [comment]
This would be so good, currently I need to add cascade persist mapping to some entities. This PR would solve it.

**Comment by pjedrzejewski** [comment]
I'd not recommend manipulating this class... It is easy to break things by doing so. I'd say for attribute we should add this to core.

**Pull request closed without merging**
