### PR TITLE
Extract StateMachine abstraction into its own package

### PR DESCRIPTION
**Pull request by jakubtobiasz**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.13
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| License         | MIT

### CODE REVIEW

**Comment by esserj** [comment]
@jakubtobiasz you are aware this, in its current state, is breaking BC?

- all renamed service definitions need deprecated aliases
- all moved classes need deprecated aliases/extensions

**Comment by jakubtobiasz** [comment]
@esserj this abstraction hasn't been released yet. We're on 1.13 branch, and in the same branch I've created the abstraction I'm currently extracting :)

**Comment by esserj** [comment]
Ok :)  , I was just concerned because the Description mentioned

`BC Break? No`

As long as we don't merge this into 1.13 without the BC layer in place I'm all good 👍

**Review by Wojdylak — APPROVED** [review]

**Review by NoResponseMate — APPROVED** [review]

**Comment by NoResponseMate** [comment]
Thank you, @jakubtobiasz!

**Pull request merged**
