### PR TITLE
[Docs] Bundles turbo refactoring

### PR DESCRIPTION
**Pull request by CoderMaggie**
| Q               | A
| --------------- | -----
| Branch?         | 1.2
| Doc fix?        | yes
| Related tickets | fixes all issues regarding outdated bundle docs
| License         | MIT

Due to our bundle docs being highly outdated we have decided to remove them and approach leaving only technical, non-ecommerce bundle docs here. The useful articles from the removed bundle docs will come back in cookbooks as soon as possible.

We were wondering who and why is nowadays using Sylius ecommerce bundles standalone, and we thought that a much better place for bundle documentation is _each bundle's readme file._

### CODE REVIEW

**Comment by stefandoorn** [comment]
This thing is rather double. I can understand it's outdated and takes significant time to update. On the contrary, I think there's very useful information in there. Adoption of the framework is highly based on the quality of documentation in my opinion. 

Not sure what's the solution though, as I understand the core team cannot support such piece of documentation.

**Comment by CoderMaggie** [comment]
@stefandoorn That's true and we are sorry for this move. We are getting very few contributions to the docs, we are currently incapable of updating them, and it's better not to have them at all than to have them outdated. We are doing the same thing with components. 
As I wrote in the description, we will be recommending to put Bundle docs into bundles' readmes.

**Comment by 4c0n** [comment]
I also highly value the existing documentation. Although it's outdated, I still manage to find useful information in it all the time.

Maybe it is a good idea to require documentation updates as a condition to get pull requests merged. If that is not the case already. That way it should stay up to date, but does bring in a bit more overhead.

**Comment by stefandoorn** [comment]
Makes sense @CoderMaggie. Alternative: is there a method to mark doc pages as 'outdated' asking community to support in updates? Then anyone can see it might be outdated, but still have access to the information. Not sure it's possible in the documentation tooling though.

**Comment by Konafets** [comment]
I proposed the idea to do an documentation hackathon (#9999) but so far now answer. The problem with contributing to the doc are in my case that I have no idea what the intended is. This makes it hard to describe anything. At a hackathon the ways are short and ppls can discuss things. 

I consider removing them now completely is not the right direction to go. Instead you should go through the doc and remove only those parts which are obviously outdated.

**Comment by CoderMaggie** [comment]
Closing in favor of #10100

**Pull request closed without merging**
