### PR TITLE
docblock fixes

### PR DESCRIPTION
**Pull request by ojhaujjwal**

### CODE REVIEW

**Comment by aRn0D** [comment]
Thank you Hrevert. I saw you are from Nepal, I hope you are fine.

**Comment by ojhaujjwal** [comment]
@aRn0D Thank you very much for your concern. I am fine but thousands of people died here. :( :'(

**Comment by aRn0D** [comment]
Ohh, Sorry thank you **Ujjwal**. I know for the heath-quake, my friends from Télécoms sans Frontière (Telecommunications without borders) are in the the ground to provide telecommunications for population or other NGO. Be brave.

**Comment by pjedrzejewski** [comment]
Thank you Ujjwal and stay strong!

**Pull request merged**
