### PR TITLE
[OrderBundle] Adjustment resource

### PR DESCRIPTION
**Pull request by sjonkeesse**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
What's the point of adding it to the core?

**Comment by sjonkeesse** [comment]
@pjedrzejewski Sorry there was no point, I removed it.

**Comment by pjedrzejewski** [comment]
No worries, I was just wondering. :) Could you squash your commits, please? Thanks!

**Comment by pjedrzejewski** [comment]
Thanks Robin!

**Pull request merged**
