### PR TITLE
[Admin] Do not disable channel base currency when none set

### LINKED ISSUE #15668: Base_currency_id cannot be null when creating a new channel
**Sylius Version Affected: 1.12 dev (I believe)**

Hi, I'm a brand-new developer, so please bear with me if I lack the experience in explaining my issue, which is the same as: https://github.com/Sylius/Sylius/issues/12330

**Description**
Currently, I am unable to create a new channel. The 'base currency' field is disabled when submitting the form. The error 'base_currency_field cannot be null' prevents the creation of the channel.

I believe the ticket submitted earlier is correct:

If I am on the URL: https://mywebsite.com/admin, and a channel hostname has mywebsite.com as the host name, Sylius identifies the channel I am creating as one already set, since you are unable to edit a channel's base currency.

**Steps to Reproduce**

1. Have your environment set in HTTPS.
2. Have a channel hostname similar to your current admin hostname.
3. Create a new channel.
4. Try to select a base currency (though you should not be able to).
5. Submit.
6. An error in your log should display:

[2023-12-21T11:05:10.032347+01:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'base_currency_id' cannot be null" at /home/korak/release/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 114 {"exception":"[object] (Doctrine\DBAL\Exception\NotNullConstraintViolationException(code: 1048): An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'base_currency_id' cannot be null at /home/korak/release/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:114)\n[previous exception] [object] (Doctrine\DBAL\Driver\PDO\Exception(code: 1048): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'base_currency_id' cannot be null at /home/korak/release/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'base_currency_id' cannot be null at /home/korak/release/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:130)"} []

**Bonus**: Local and dev environments don't have the issue, likely because my local is not in HTTPS, and my dev is not really in HTTPS.

**Possible Solution**

I am a bit out of my depth on this. My only workaround currently is to set a channel using the database, but I might not foresee all the impacts this may cause in the long term.

Our default channel is our main host. So maybe enable an exception regarding this hostname when we want to configure new channels?

Thank you in advance,

Regards,
Arthur

### PR DESCRIPTION
**Pull request by NoResponseMate**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.12 |
| Bug fix?        | yes                                                       |
| New feature?    | no                                                       |
| BC breaks?      | no                                                       |
| Deprecations?   | no |
| Related tickets | fixes #15668, #12330                      |
| License         | MIT                                                          |

### CODE REVIEW

**Review by Wojdylak — APPROVED** [review]

**Review by diimpp — APPROVED** [review]

**Comment by diimpp** [comment]
Not sure though how do they get in situation where channel exists without base currency set? 

It's against validation rule

https://github.com/Sylius/Sylius/blob/a0ad0d1e4c61ed8ec30bbb39e36184cb910736b2/src/Sylius/Bundle/CoreBundle/Resources/config/validation/Channel.xml#L22-L26

No currency created in the shop? Maybe it happens via api?

Unless I'm mistaking current PR allows to resolve situation, which shouldn't have happened in the first place, so would be cool to understand how it happens for end-users.

**Review by oallain — APPROVED** [review]

**Comment by jakubtobiasz** [comment]
@diimpp check the related tickets, there's a described reproducer.

**Comment by jakubtobiasz** [comment]
Thank you, @NoResponseMate!

**Pull request merged**
