### PR TITLE
Product attribute creation must be typed

### PR DESCRIPTION
**Pull request by gruberro**
| Q               | A
| --------------- | ---
| Bug fix?        | yes |
| New feature?    | no |
| BC breaks?      | yes |
| Related tickets | #6117 |
| License         | MIT |

This PR aims to fix product attribute creation via api as the configured factory does not allows creating untyped attributes (https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Attribute/Factory/AttributeFactory.php#L48-L53).

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
I think in case of API we can simply send the type together with the configuration, etc. So "type" should be the part of the payload. Factory can be changed if needed. WDYT?

**Comment by gruberro** [comment]
That would be fine in my mind too. Didn't saw a better solution than adding the type this way as the factory can only be invoked containing the type...

**Comment by gruberro** [comment]
Did some tests with `$type` as simple payload param... works as expected too 👍

**Comment by michalmarcinkowski** [comment]
Thank you Robert! 👍

**Comment by pjedrzejewski** [comment]
The reason why I have not merged this is that we need tests... @gruberro Could you write them? It is really straightforward, you can have a look at our existing API tests in ``tests`` directory of this repo.

**Comment by michalmarcinkowski** [comment]
I decided to merge it since we don't have tests for it right now anyway, so it's better to have it fixed than broken, but @pjedrzejewski you're right, I should have asked for tests!

**Pull request merged**
