### PR TITLE
Affiliate system

### PR DESCRIPTION
**Pull request by stloyd**
I will write more details later what's the reason, what are goals etc.

Just quick todo what's missing:
- [ ] fix provision rule checkers,
- [x] rethink default actions,
- [x] fix code for cookies after changes in affliation <-> refferal,
- [x] adjust old specs for refactored code of rules in promos + shippings,
- [x] finish code for affiliate invitations,
- [x] adjust frontend + backend views/translations,
- [ ] finish code for multi-level affiliations,
- [x] clean-up code for old provision counting,
- [x] add backend features for uploading banners used by affiliates,
- [x] fix backend for managing affliates
- [ ] extend & adjust code after feedback ;)

**Work on this PR was sponsored by [Locastic - Web & Mobile development](http://www.locastic.com/)**.

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
:open_mouth:

**Comment by pborreli** [comment]
amazing work :clap:

**Comment by antonioperic** [comment]
:)

**Comment by Rvanlaak** [comment]
:+1: Great work!

We will probably implement this Bundle in our sf2-standard project, so in case you'll need people to test that let me know

**Comment by pjedrzejewski** [comment]
Ping @stloyd @antonioperic, we need some PR description. :)

**Comment by antonioperic** [comment]
@pjedrzejewski I will probably have more info in next few days.

**Comment by ruibinyang** [comment]
How long can release the affiliate bundle？

**Comment by antonioperic** [comment]
@ruibinyang unfortunately @stloyd stopped to respond on emails and now probably I will need to complete this. Regarding my time arrangements I cannot promise anything until the end of this month.

**Comment by pjedrzejewski** [comment]
@stloyd Any plans to finish that PR?

**Comment by ruibinyang** [comment]
How long can release the affiliate bundle？

**Comment by antonioperic** [comment]
@ruibinyang do ytou have time maybe for finishing it?

**Pull request closed without merging**
