### PR TITLE
Update Vagrantfile

### PR DESCRIPTION
**Pull request by MblKiTA**
not enough memory. composer throws errors.

### CODE REVIEW

**Comment by Symfomany** [comment]
Use Docker to emulate environements  :p

**Comment by Strontium-90** [comment]
Use swap file for `composer update` command.

**Comment by Strontium-90** [comment]
updatedeps.sh

``` sh
#!/bin/bash
# Enable swap, run composer update, disable swap. That's it.

if [ ! -f /swapfile ]; then
    sudo dd if=/dev/zero of=/swapfile bs=1048576 count=4096
    sudo mkswap /swapfile
fi

sudo swapon /swapfile
composer update
sudo swapoff /swapfile

```

**Comment by MblKiTA** [comment]
Thanks!
Possibly this should be documented somewhere here:
https://github.com/Sylius/Sylius/tree/master/vagrant
?

**Comment by michalmarcinkowski** [comment]
@MblKiTA is it still relevant?

**Comment by MblKiTA** [comment]
@michalmarcinkowski, this works now.

**Pull request closed without merging**
