### PR TITLE
Added hook to update root taxon when taxonomy translation added

### LINKED ISSUE #2734: Link to view products by taxon is throwing No route found Exception
- Fresh install of Sylius (commit: c38485c581007f8f29fd8ba9f02b6d55537d920c). 
- Ran sylius:install and sylius:install:setup but did not load the sample data
- Logged into admin area and created one taxonomy with one root taxon and one child taxon
- Created one product belonging to the child taxon

Expected:
- When I click on the product link from homepage I see the product
- When I click on the child taxon in homepage I see the product

Actual:
- When I click on the product link from homepage I see the product
- When I click on the child taxon in homepage I get the following error:
 No route found for "GET /t//flooring/wood" (from "http://127.0.0.1:8000/app_dev.php/")
404 Not Found - NotFoundHttpException
1 linked Exception:

    ResourceNotFoundException » 
[1/2] ResourceNotFoundException: None of the routers in the chain matched this request
GET /app_dev.php/t//flooring/wood HTTP/1.1

I'm not a Symfony expert but I can see the relevant routes defined in vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
It looks like it's finding the %sylius.model.product.class% route but not the %sylius.model.taxon.class% route.

Any ideas why? Happy to submit a PR if it is an issue and you can point me in the right direction.

### PR DESCRIPTION
**Pull request by liquorvicar**
Fixes #2734 

Alternative solution to PR https://github.com/Sylius/Sylius/pull/2740

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
@liquorvicar Could you have a look at the failing build?

**Comment by liquorvicar** [comment]
@pjedrzejewski Yes, more than happy to fix the build (pretty sure it's just some Behat scenarios that need adjusting due to the changes I made) if you think this is a better solution to the problem? Don't really want to spend time on it if it's not a good solution. It hooks into the translation system which is pretty new to me so not sure of any unforeseen implications.

**Comment by pjedrzejewski** [comment]
@liquorvicar I think is the best solution for now. :+1:

**Comment by liquorvicar** [comment]
@pjedrzejewski I have tried to look at this but I'm not getting very far. Can you give me a few pointers? It looks like the build is failing due to behat. All the failures seem to be the same Exception: No locale has been set and current locale is undefined. (RuntimeException)
I'm guessing that we need to set a default locale for any translations that are created in the scenarios but I'm struggling to see where/how we might do that. Any help would be appreciated!

**Comment by pjedrzejewski** [comment]
Requires rebasing. The failing build is probably because the current locale is not set on the context for some reason. I'd recommend rebasing the PR, because the underlying issue may be fixed already.

**Comment by pjedrzejewski** [comment]
Forget my last comment, I did not realize it is fixed already.

**Pull request closed without merging**
