### PR TITLE
[Content] fixed the __toString() exception for static content

### PR DESCRIPTION
**Pull request by coudenysj**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #2883
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by nicolasricci** [comment]
@coudenysj thanks for the fix but can you have a look at the failed travis build so it can be merged?

**Comment by coudenysj** [comment]
Not sure if this is a problem of my branch, because master suffers from the same problem.

Will have a look at it later.

**Comment by coudenysj** [comment]
Fixed by syncing with upstream.

**Comment by nicolasricci** [comment]
:+1: 
@pjedrzejewski good to be merged :)

**Comment by pjedrzejewski** [comment]
Thank you Jachim!

**Pull request merged**
