### PR TITLE
Update composer lock file

### PR DESCRIPTION
**Pull request by zyleee**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #2696, #2754 
| License       | MIT
| Doc PR        | -

Updates symfony/symfony to v2.3.28 and doctrine/phpcr-bundle to 1.2.4

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
Perfect, thank you @zyleee! :+1:

**Comment by jeffsacco** [comment]
I am sure I did something wrong but ran the update and no go on my side
screen shot 2015-05-23 at 3 03 10 pm

**Comment by kayue** [comment]
@jeffsacco Module `intl`? Seems to be a php configuration / extension setting problem.

**Comment by jeffsacco** [comment]
@kayue Yes, I needed the international version of php for another project.  I havent had any issues with it on the Sylius project. You can dismiss those

**Comment by kayue** [comment]
@jeffsacco What other problem are you having?

**Comment by jeffsacco** [comment]
It has to do with this issue #2696 

I have updated my code base and ran:

php app/console doctrine:phpcr:repository:init

as instructed by @psyray but nothing has worked

**Pull request merged**
