### PR TITLE
[HOTFIX] Fix core data collector

### PR DESCRIPTION
**Pull request by lchrusciel**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Related tickets | 
| License         | MIT

It fix following issue: 
zrzut ekranu 2016-05-27 o 12 35 05

### CODE REVIEW

**Comment by lchrusciel** [comment]
I am not sure, if it is a best solution, but for now it would be enough. Overriding const in AppKernel smells bad, but it is topic for separate RFC.

**Comment by michalmarcinkowski** [comment]
Thanks, that is a good fix! 👍

**Comment by pjedrzejewski** [comment]
We cannot assume there is an AppKernel class...

**Comment by michalmarcinkowski** [comment]
@pjedrzejewski good point, also the version should be taken from `Core` since I can have `0.18` in my `\AppKernel` and update the `Core` to `0.19`, but the version in the collector will remain `0.18` unless I change it manually...

**Comment by lchrusciel** [comment]
@pjedrzejewski @michalmarcinkowski I know, but it was the simplest and fastest solution. As I wrote before, we have a time now to figure out a better one.

**Pull request merged**
