### PR TITLE
Adding more properties to ShippingMethod fixture

### PR DESCRIPTION
**Pull request by mamazu**
| Q               | A
| --------------- | -----
| Branch?         | master
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | -
| License         | MIT

Adding a way in the fixtures to set the shipping method's position and category requirements.

### CODE REVIEW

**Review by lchrusciel — COMMENTED** [review]
Hey Max,

can you add usage of these new options to the current fixtures?

**Comment by mamazu** [comment]
Sure, what should I use as a default value for them? 
all?

**Comment by mamazu** [comment]
Does anybody know what this error is?

**Comment by mamazu** [comment]
Hm, now I it stays that I have a cyclic dependency. But that makes no sense since the `category_requirements` is a string.

**Pull request closed without merging**
