### PR TITLE
Finalize bundles, container extensions and bundles configurations

### PR DESCRIPTION
**Pull request by pamil**
| Q               | A
| --------------- | ---
| Bug fix?        | no |
| New feature?    | no |
| BC breaks?      | yes |
| Related tickets | - |
| License         | MIT |

### CODE REVIEW

**Comment by michalmarcinkowski** [comment]
Please update upgrade doc.

**Comment by pamil** [comment]
@michalmarcinkowski I don't know what can I say to developers extending these classes.

> `Bundle` was made final so... do not extend it? 🌮

**Comment by michalmarcinkowski** [comment]
How about a simple note:
> Bundles, container extensions and bundles configuration classes were made final and can't be extended anymore, /*the recommended way of extending here*/

"the recommended way of extending here" - can be replaced with e.g. "follow Symfony best practices". WDYT?

**Comment by pamil** [comment]
@michalmarcinkowski done! 🎉

**Comment by pjedrzejewski** [comment]
Thanks Kamil!

**Pull request merged**
