### PR TITLE
fix query select for order number

### PR DESCRIPTION
**Pull request by ojhaujjwal**
I tried to override the order number generator. But, I got an exception saying something like Parse error, unexpected * etc. I changed it to this and it worked.

### CODE REVIEW

**Comment by aRn0D** [comment]
@ojhaujjwal Can you show us the trace of the exception, plz ?

**Comment by stloyd** [comment]
@aRn0D Even in case of exception IMO this change is must have ;) Counting on all table is __evil__ :see_no_evil:

**Comment by cordoval** [comment]
:+1:

**Comment by aRn0D** [comment]
Thank you Ujjwal.

**Comment by geshan** [comment]
+1

**Comment by ojhaujjwal** [comment]
@aRn0D  It's my pleasure! :D

**Pull request merged**
