### PR TITLE
Allow newer "doctrine/doctrine-bundle" to match upcoming ResourceBundle reqs

### PR DESCRIPTION
**Pull request by stloyd**
| Q               | A
| --------------- | -----
| Branch?         | master 
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | related #10928 + https://github.com/Sylius/SyliusResourceBundle/pull/135
| License         | MIT

### CODE REVIEW

**Review by lchrusciel — COMMENTED** [review]
Hey Józef,

thanks for your proposal, however, we tend not to open versions, that we cannot guarantee that it will work. Probably either we should have another build or update it entirely to 2.0

**Comment by stloyd** [comment]
While I get your consideration, I would still vote for this change.

Reasons are:
- will allow to support upcoming release of `ResourceBundle` which, already supports this,
- version `2.0` of Doctrine bundle is for Sylius BC safe, it even will allow to remove outdated Doctrine cache bundle,
- along with above, it will allow smother update to Symfony 5

Cheers! :)

**Review by pamil — APPROVED** [review]

**Review by Zales0123 — APPROVED** [review]

**Comment by pamil** [comment]
The base of this pull-request was changed, you need fetch and reset your local branch 
if you want to add new commits to this pull request. **Reset before you pull, else commits
may become messed-up.**

Unless you added new commits (to this branch) locally that you did not push yet, 
execute `git fetch origin && git reset "patch-3"` to update your local branch.
 
Feel free to ask for assistance when you get stuck :+1:

**Comment by pamil** [comment]
Thank you, Joseph! :tada:

**Pull request merged**
