### PR TITLE
:arrow_up: Upgrade gaufrette version (PHP 8+ compat)

### PR DESCRIPTION
**Pull request by Nek-**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.11                   |
| Bug fix?        | no                                                      |
| New feature?    | yes                                                       |
| BC breaks?      | no/yes                                                       |
| Deprecations?   | no |
| Related tickets | none                      |
| License         | MIT                                                          |

Hello, I worked on Gaufrette for supporting PHP 8.0 and 8.1. It's only supported in newer versions of Gaufrette.

Please notice there are some BC breaks in Gaufrette (we're talking about major version upgrade here) but it's actually really limited:
- Classes are now typed (and it should not impact many people, it does not impact sylius)
- Google Adapter use the new major version of the google library (which is compatible with PHP 8+)

I know you did an effort to remove Gaufrette (and you did right because gaufrette is end of life and will not be compatible with new versions of PHP and new external libraries) but I think allowing people to have a version compatible with their own PHP version is great.

### CODE REVIEW

**Comment by coldic3** [comment]
The base of this pull-request was changed, you need fetch and reset your local branch 
if you want to add new commits to this pull request. **Reset before you pull, else commits
may become messed-up.**

Unless you added new commits (to this branch) locally that you did not push yet, 
execute `git fetch origin && git reset "feat/gaufrette-php-8"` to update your local branch.
 
Feel free to ask for assistance when you get stuck :+1:

**Review by jakubtobiasz — APPROVED** [review]

**Comment by Nek-** [comment]
@coldic3 it seems like everything is still ok and the merge can be done. I will rebase tomorrow if you absolutely want it.

**Comment by jakubtobiasz** [comment]
@Nek- you don't need to do anything. @coldic3 message is auto-generated by hubkit as you opened your PR against 1.10 which is unsupported. He just changed the base to 1.11.

**Review by NoResponseMate — APPROVED** [review]

**Review by Rafikooo — APPROVED** [review]

**Comment by Rafikooo** [comment]
Thanks, Maxime! :tada:

**Pull request merged**
