### PR TITLE
Add Sylius template event

### PR DESCRIPTION
**Pull request by tavy315**
| Q               | A
| --------------- | -----
| Branch?         | 1.7
| Bug fix?        | no/yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | #11151
| License         | MIT

I've seen the changes done in (https://github.com/Sylius/Sylius/commit/186c13c25009904d00e322a2fb2259065099340b), but I guess that this file was missed.

### CODE REVIEW

**Comment by tavy315** [comment]
Can this be merged?

**Comment by lchrusciel** [comment]
Hey @tavy315,

thanks a lot for your contribution and your patience. It can be merged to the master, however we have a red build there. Once it is fixed I will ping you back

**Comment by tavy315** [comment]
Ok, no problem. Not sure if I can help there.
By the way, targeted branch was 1.7 since all the changes were also merged into that branch, see https://github.com/Sylius/Sylius/commit/186c13c25009904d00e322a2fb2259065099340b

**Comment by lchrusciel** [comment]
My mistake should be merged to 1.7

**Comment by lchrusciel** [comment]
Hey Octav, could you rebase your work to branch 1.7?

**Comment by tavy315** [comment]
@lchrusciel, sorry, I think I merged it instead. I'm still not used to sync and rebase a fork.

**Comment by pamil** [comment]
Thank you, Octav! :1st_place_medal:

**Pull request merged**
