### PR TITLE
[Admin] Remove admin root path

### PR DESCRIPTION
**Pull request by lchrusciel**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | yes
| Related tickets | 
| License         | MIT

### CODE REVIEW

**Comment by emodric** [comment]
Won't this make `/admin/` to stop working?

#6252 fixes `/admin`, but I guess you'd still want `/admin/` to keep on working, right?

**Comment by lchrusciel** [comment]
No. Both `sylius_admin_root` and `sylius_admin_dashboard_redirect` redirects to the same action `sylius_admin_dashboard`. So #6252 needs only `sylius_admin_dashboard` to work.

**Comment by emodric** [comment]
Sure, I get that, but if you remove this route, wouldn't `/admin/` (with trailing slash) become 404, so no redirect at all to `sylius_admin_dashboard` would happen?

**Comment by emodric** [comment]
Forget it, I somehow missed the line where you renamed `/dashboard` to just `/` :)

**Comment by pjedrzejewski** [comment]
Thank you Łukasz!

**Pull request merged**
