### PR TITLE
[Maintenance] Add staging environment

### LINKED ISSUE #8455: Introduce "staging" environment
We add it almost to every project so I think it makes sense to have it in both Sylius & Sylius-Standard.

Staging is just like production but has e-mails redirected to a test address, etc.

* [x] Sylius
* [x] Sylius-Standard

### PR DESCRIPTION
**Pull request by lchrusciel**
| Q               | A
| --------------- | ---
| Bug fix?        | no |
| New feature?    | no |
| BC breaks?      | no |
| Related tickets | fixes #8455 |
| License         | MIT |

Not sure if should duplicate the prod config or import it

### CODE REVIEW

**Comment by pamil** [comment]
If we define staging environment as production one but without sending emails, then we should rather import the production configuration.

**Comment by pjedrzejewski** [comment]
@pamil We discussed it and it seems safer to configure them separately and have full control. If we import prod in staging, one can be unaware that changing the former updates the latter as well.

**Comment by pamil** [comment]
@pjedrzejewski that makes sense too, no solution seems ideal here.

**Comment by pjedrzejewski** [comment]
@lchrusciel We should add it to docs too. :)

**Comment by pjedrzejewski** [comment]
Thank you Łukasz!

**Pull request merged**
