### PR TITLE
Payum 013 upgrade

### PR DESCRIPTION
**Pull request by makasim**
Chanages:

* Payum: [changelog](https://github.com/Payum/Payum/blob/master/CHANGELOG.md), [upgrade](https://github.com/Payum/Payum/blob/master/UPGRADE.md)
* PayumBundle: [changelog](https://github.com/Payum/PayumBundle/blob/master/CHANGELOG.md), [upgrade](https://github.com/Payum/PayumBundle/blob/master/UPGRADE.md).

The most import change is added `getFirstModel` method. I added it to `Generic` request. Check that you use that method instead of getModel one before upgrading your apps.

### CODE REVIEW

**Comment by winzou** [comment]
@makasim What is the status of this PR? My new extension depends on version 0.13...

**Comment by makasim** [comment]
@winzou I had a problem with a template layout, Somehow it does not applied a Sylius checkout layout while asking for credit card details. All the rest must be good, I tested it.

**Comment by winzou** [comment]
Requires rebase btw.

**Comment by makasim** [comment]
closing in favor: https://github.com/Sylius/Sylius/pull/2384

**Pull request closed without merging**
