### PR TITLE
[Admin] removed duplicated id attribute

### LINKED ISSUE #11649: Same HTML id attribute in Admin view
The id "shipping-state" is set 2 times in the document (in div and h3 tag)

https://github.com/Sylius/Sylius/blob/6ec16374070e8f142947d713a34fbc52db45a155/src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_shipments.html.twig#L4

### PR DESCRIPTION
**Pull request by foxou33**
| Q               | A
| --------------- | -----
| Branch?         | 1.5
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #11649 
| License         | MIT

### CODE REVIEW

**Comment by foxou33** [comment]
I made the changes on the 1.5 branch, but it looks like the tests are running on master...
I changed the base branch afterwards.
How can I re-run the tests against the correct branch ?

**Comment by foxou33** [comment]
I made the changes on the 1.5 branch, but it looks like the tests are running on master...
I changed the base branch afterwards.
How can I re-run the tests against the correct branch ?

**Comment by foxou33** [comment]
I made the changes on the 1.5 branch, but it looks like the tests are running on master...
I changed the base branch afterwards.
How can I re-run the tests against the correct branch ?

**Comment by foxou33** [comment]
I made the changes on the 1.5 branch, but it looks like the tests are running on master...
I changed the base branch afterwards.
How can I re-run the tests against the correct branch ?

**Comment by foxou33** [comment]
I made the changes on the 1.5 branch, but it looks like the tests are running on master...
I changed the base branch afterwards.
How can I re-run the tests against the correct branch ?

**Comment by foxou33** [comment]
I made the changes on the 1.5 branch, but it looks like the tests are running on master...
I changed the base branch afterwards.
How can I re-run the tests against the correct branch ?

**Comment by foxou33** [comment]
I made the changes on the 1.5 branch, but it looks like the tests are running on master...
I changed the base branch afterwards.
How can I re-run the tests against the correct branch ?

**Comment by foxou33** [comment]
I made the changes on the 1.5 branch, but it looks like the tests are running on master...
I changed the base branch afterwards.
How can I re-run the tests against the correct branch ?

**Comment by lchrusciel** [comment]
Hey @foxou33,

thanks for your contribution. You could reopen the PR to trigger another build, or rebase and force push your commit. 

However, version 1.5 is not supported since [10th of January](https://docs.sylius.com/en/latest/book/organization/release-cycle.html?highlight=release#past-releases). It should be opened to the 1.7 branch.

**Comment by foxou33** [comment]
Hi @lchrusciel ,
Ok I didn't know that I could close and re-open by myself, thanks for the info :smile: 
Also, I made the changes on the 1.5 branch because the docs said so (here: https://docs.sylius.com/en/latest/book/contributing/code/patches.html#choose-the-right-base-branch), but it seemed weird, so maybe we should update this page ?

**Comment by lchrusciel** [comment]
That's a mistake as well. Could you open another PR with the fix? :) Anyway, thanks for this change.

**Comment by lchrusciel** [comment]
Thank you, @foxou33! :1st_place_medal:

**Pull request merged**
