### PR TITLE
use behat page object extension

### LINKED ISSUE #9886: Unused FriendsOfBehat Page Object Extension
**Sylius version affected**: at least 1.3.2 

**Description**  

This extension is on dev dependencies but it's not used. Page, PageInterface and UnexpectedPageExtension still be on sylius and same objects from the behat extension are not used yet.

**Steps to reproduce**  

**Possible Solution**  

Remove duplicated objects on sylius and use this behat extension objects :)

Moreover, on sylius, there's more "phpdoc" on these objects, I think it has to be improved on the extension objects.

### PR DESCRIPTION
**Pull request by loic425**
| Q               | A
| --------------- | -----
| Branch?         | 1.3
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no 
| Related tickets | fixes #9886 
| License         | MIT

### CODE REVIEW

**Comment by lchrusciel** [comment]
Can we point it to 1.2?

**Comment by loic425** [comment]
> Can we point it to 1.2?

We can, but @pamil will need to fix conficts cause this extension was added to sylius on 1.3 branch.
Ok with that?

**Comment by loic425** [comment]
@lchrusciel I rebase this pull request from 1.2 branch. I now need this [pull request](https://github.com/FriendsOfBehat/PageObjectExtension/pull/5t) to be merged on the friends of behat extension.

**Comment by pamil** [comment]
PageObjectExtension v0.2.1 has been released, let's see if the build passes now.

**Comment by loic425** [comment]
@pamil I think you have to clear cache of this build no ?

> Installing friends-of-behat/page-object-extension (0.2): Loading from cache

**Comment by loic425** [comment]
@pamil @lchrusciel 
The Symfony 3.4 build is now ok but not on symfony 4.1 build, could you clear travis cache for [this build](https://travis-ci.org/Sylius/Sylius/jobs/453995838), please?

**Comment by loic425** [comment]
@pamil @lchrusciel 
Victory!! thanks a lot ;)

**Comment by Zales0123** [comment]
Thanks, Loïc! :1st_place_medal:

**Pull request merged**
