### PR TITLE
[ChannelBundle] Fix channel context interface alias

### PR DESCRIPTION
**Pull request by vvasiloi**
| Q               | A
| --------------- | -----
| Branch?         | master
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| License         | MIT

Currently `Sylius\Component\Channel\Context\ChannelContextInterface` is aliased to `sylius.context.channel.composite`, instead of `sylius.contex.channel`, so the `sylius.context.channel.cached` is not used and it can result in a lot of extra database queries in applications that mainly use autowiring for service arguments.
It also doesn't make use of any custom application decorations of `sylius.context.channel`.

### CODE REVIEW

**Comment by lchrusciel** [comment]
Should be rebased once, master will be fixed

**Comment by vvasiloi** [comment]
@lchrusciel OK. Any ideas how to test this?

**Comment by lchrusciel** [comment]
Master should be fixed now. Can you rebase? 

Let's add this change to UPGRADE.md also.

**Comment by lchrusciel** [comment]
Thank you, Victor! :tada:

**Pull request merged**
