### PR TITLE
Change Symfony2 to Symfony

### PR DESCRIPTION
**Pull request by edamov**
| Q               | A
| --------------- | -----
| Branch?         | master
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | no
| License         | MIT

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
👍 , could you open this PR against 1.0 branch, please? Thanks!

**Comment by edamov** [comment]
Should I create one more PR but in branch 1.0 or change this PR ?

**Comment by GSadee** [comment]
@edamov you can rebase this PR with the `1.0` branch or if it will be simpler, create new branch from `1.0` with your change and open a new PR against correct branch.

**Comment by edamov** [comment]
I've created new PR #8879

**Comment by GSadee** [comment]
Closing in favour of #8879

**Pull request closed without merging**
