### PR TITLE
Remove StofDoctrineExtensionsBundle

### PR DESCRIPTION
**Pull request by pamil**
See https://github.com/stof/StofDoctrineExtensionsBundle/issues/422 and #12298.

### CODE REVIEW

**Comment by alexander-schranz** [comment]
@Pamil There is also a maintained fork of the stof extension bundle: https://github.com/antishov/StofDoctrineExtensionsBundle. Sadly there was never a response from @stof about the future maintenance [here](https://github.com/antishov/StofDoctrineExtensionsBundle/issues/22) that they could maybe work together. Just wanted to mention the fork for you if you didn't see it yet.

**Comment by pamil** [comment]
@alexander-schranz thanks for the information - I've decided to opt-out from using a bundle as I'm trying to minimise the number of dependencies we have in Sylius. This way it's easier to upgrade when we own the code and it's not in some external repository we have little or no control of.

**Comment by vvasiloi** [comment]
@pamil a member of Symfony core team was added as co-maintainer, a new version was released and Symfony decided to keep recommending the bundle, see https://github.com/symfony/symfony-docs/pull/14909

**Comment by pamil** [comment]
@vvasiloi that's perfect, thanks! I'll close this PR for now then, it's easier to keep it for now at least.

**Pull request closed without merging**
