### PR TITLE
[User] Removed unnecessary method due to PHP version bump

### PR DESCRIPTION
**Pull request by pamil**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| License       | MIT

Removed plain PHP duplication of `hash_pbkdf2()`.

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
:+1:

**Comment by elliot** [comment]
This should be refactored to use [```password_hash```](https://secure.php.net/manual/en/function.password-hash.php) instead of ```hash_pbkdf2```. 
Secure password storage mechanisms need to be slow, which the underlying bcrypt implementation in password_hash handles. 

Even with using the key stretching mechanism in PBKDF - using a system based on fast hashes (i.e anything in the SHA family) is a brute force security risk due to the advances in GPU/ASIC/FPGA tech.

**Comment by pjedrzejewski** [comment]
@elliot is right here! What is the implementation in Symfony 3?

**Comment by pamil** [comment]
We can aslo use some secure string comparison function to prevent [timing attacks](https://en.wikipedia.org/wiki/Timing_attack).

**Comment by pjedrzejewski** [comment]
@pamil Let's apply @elliot's idea in a separate PR. Thanks!

**Comment by michalmarcinkowski** [comment]
This encoder is used as a default User component encoder. No need to implement something more there, because we use Symfony Security component encoders (https://github.com/symfony/symfony/tree/2.7/src/Symfony/Component/Security/Core/Encoder) anyway and if anyone is willing to use component and not use Symfony security can implement encoder on it's own.

**Pull request merged**
