### PR TITLE
[WebBundle] Configurable templates for frontend and backend controllers

### PR DESCRIPTION
**Pull request by aramalipoor**
Q  | A
------------- | -------------
Bug fix?  | no
New feature?  | yes
BC breaks? | no
Deprecations? | no
Fixed tickets | -
License | MIT
Doc PR | -

When you want to use Sylius `WebBundle` sometimes you want change only the templates. With this PR you do not need to override the whole controller instead easily put this configuration in `config.yml`:

```yml
sylius_web:
   templates:
      backend_dashboard: "SyliusWebBundle:Backend/Dashboard:main.html.twig"
      backend_login: "SyliusWebBundle:Backend/Security:login.html.twig"
      frontend_homepage: "SyliusWebBundle:Frontend/Homepage:main.html.twig"
      frontend_cart_summary: "SyliusWebBundle:Frontend/Cart:summary.html.twig"
      frontend_account: "SyliusWebBundle:Frontend/Account:show.html.twig"
      frontend_address_index: "SyliusWebBundle:Frontend/Account:Address/index.html.twig"
      frontend_address_create: "SyliusWebBundle:Frontend/Account:Address/create.html.twig"
      frontend_address_update: "SyliusWebBundle:Frontend/Account:Address/update.html.twig"
      frontend_order_index: "SyliusWebBundle:Frontend/Account:Order/index.html.twig"
      frontend_order_show: "SyliusWebBundle:Frontend/Account:Order/show.html.twig"
      frontend_order_invoice: "SyliusWebBundle:Frontend/Account:Order/invoice.html.twig"
```

\cc @stloyd

### CODE REVIEW

**Comment by ahmadrabie** [comment]
:+1:

**Comment by liverbool** [comment]
:+1:

**Comment by amenophis** [comment]
Why ? You can use the Symfony native template inheritance to achieve this.

**Comment by aramalipoor** [comment]
@amenophis In simple scenarios yeah you can do that. But in some complex applications (e.g. Theming Systems) you cannot use Symfony inheritance.

For example we have a `ThemingBundle` which is registering themes (and their hierarchies) under `@Theme` twig namespace. So we need to override all of the controllers inside `SyliusWebBundle` to achieve this. (e.g. To use `@Theme/Frontend/Homepage/main.html.twig`)

The other problem we're having is that Symfony inheritance does not support multi-level inheritance. Which in a theming system you're gonna need a lot. But twig namespaces does support multi-level!

There were also more reason but I cannot recall right now. If these reasons are not convincing enough I can ask my other teammates to remind me of them :)

**Comment by isometriks** [comment]
Been working on a bundle that does a similar thing, some of it might be useful: https://github.com/symedit/ThemeBundle

**Comment by steffenbrem** [comment]
I indeed think it is better to make a custom twig loader to achieve this. Since use cases can vary alot. Like @isometriks did is better IMO.

**Comment by pjedrzejewski** [comment]
Yes, I think this issue will be solved with theming, which is coming very soon.

**Pull request closed without merging**
