### PR TITLE
Remove loggable

### PR DESCRIPTION
**Pull request by GSadee**
| Q               | A
| --------------- | ---
| Bug fix?        | no |
| New feature?    | no |
| BC breaks?      | no |
| Related tickets |  |
| License         | MIT |

### CODE REVIEW

**Comment by Shine-neko** [comment]
Why ?

**Comment by pjedrzejewski** [comment]
@Shine-neko Because we do not support this feature properly, you can easily add the same thing to your app. We will reimplement this for BETA2 release.

**Comment by mickaelandrieu** [comment]
@pjedrzejewski is it worth to make a BC break between beta 1 and beta 2, because it's not perfect ?

**Comment by pjedrzejewski** [comment]
@mickaelandrieu Introducing it back won't cause any major BC break. We do not display these in the admin anywhere.

**Comment by michalmarcinkowski** [comment]
@mickaelandrieu it's better to put a tag on features that are fully working and add new features later when they will be implemented well and working without any issues. This feature is not well thought out, so if we leave it as it is now we will have to do BC breaks after beta anyway to fix it. If you use it now, you can easily add it back in your application.

**Comment by pjedrzejewski** [comment]
Thank you Grzesiu!

**Pull request merged**
