### PR TITLE
Translation bundle enhancements

### PR DESCRIPTION
**Pull request by aRn0D**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by aRn0D** [comment]
@pjedrzejewski Translation bundle and component are not registered to packagist

**Comment by stloyd** [comment]
@pjedrzejewski ping

**Comment by aRn0D** [comment]
@pjedrzejewski pong.

**Comment by stloyd** [comment]
@pjedrzejewski Can you merge this & publish Translation bundle & component on Packagist?

**Comment by stloyd** [comment]
@pjedrzejewski ping...

**Comment by stloyd** [comment]
@pjedrzejewski pong...

**Comment by aRn0D** [comment]
@pjedrzejewski ping

**Comment by aRn0D** [comment]
@pjedrzejewski pong

**Comment by aRn0D** [comment]
@pjedrzejewski : I rebased it if it is green you should merge it.

**Comment by pjedrzejewski** [comment]
Thank you Arnaud! :+1:

**Pull request merged**
