### PR TITLE
chore: Replace NBSP by Space in doc

### PR DESCRIPTION
**Pull request by sad270**
| Q               | A
| --------------- | -----
| Branch?         | 1.10
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | no
| License         | MIT

Replace NBSP by space and remove trailing space
Screenshot 2022-04-06 at 16 53 20

### CODE REVIEW

**Review by Roshyo — APPROVED** [review]

**Comment by sad270** [comment]
Any update about this PR ?

**Comment by sad270** [comment]
The NBSP are not removed.

**Review by Roshyo — APPROVED** [review]

**Review by jakubtobiasz — APPROVED** [review]

**Comment by jakubtobiasz** [comment]
Sorry for long waiting time @sad270. Thanks for your contribution 🤝🏼!

**Comment by sad270** [comment]
@jakubtobiasz no problem that was not a real big critical fix. I understand 😁
But it can avoid some issue if someone copy/past the code. That is why I made this PR.

**Comment by GSadee** [comment]
The base of this pull-request was changed, you need fetch and reset your local branch 
if you want to add new commits to this pull request. **Reset before you pull, else commits
may become messed-up.**

Unless you added new commits (to this branch) locally that you did not push yet, 
execute `git fetch origin && git reset "patch-1"` to update your local branch.
 
Feel free to ask for assistance when you get stuck :+1:

**Comment by GSadee** [comment]
Thanks, Sadetdin! :1st_place_medal:

**Pull request merged**
