### PR TITLE
[ResourceBundle] fix repository definition for odm driver

### PR DESCRIPTION
**Pull request by tonicospinelli**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #3859 
| License       | MIT
| Doc PR        | -

* fix argument to create Class Metada Definition
* add repository service definition in container

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
I restarted the builds, thanks! :+1:

**Comment by michalmarcinkowski** [comment]
Thank you Antonio! :+1:

**Comment by tonicospinelli** [comment]
@pjedrzejewski @michalmarcinkowski is a pleasure to help! I will expend more time to create integration tests to cover bugs like this.

**Comment by tonicospinelli** [comment]
@pjedrzejewski is possible to bump a new tag 0.16.1 for sylius/resource-bundle? :grin:

**Comment by pjedrzejewski** [comment]
@tonicospinelli I could do that easily for whole Sylius package, but for standalone bundle that can be a bit more problematic as they are subtree splits, not "real" repositories. I will see what I can do and get back to you. :) Quite unfortunate that we have not tested this properly...

**Comment by tonicospinelli** [comment]
ok @pjedrzejewski thanks for your feedback. So, for now, I made some changes at my application for it working. I will waiting 0.17 tag

**Pull request merged**
