### PR TITLE
Resource movement sort persistance

### PR DESCRIPTION
**Pull request by nakashu**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| License       | MIT

ResourceController was missing update event and flush for move actions. Consequently resources order/sorting wasn't changed. (promotions priority)

### CODE REVIEW

**Comment by nakashu** [comment]
travis errors seems unrelated - some CRUD connection errors.

**Comment by pjedrzejewski** [comment]
@nakashu I have restarted the build. :+1:

**Comment by nakashu** [comment]
hmm. its 3rd time it failed with the same errors. that's weird. any ideas ?

**Comment by nakashu** [comment]
yay test have passed .. bump

**Comment by pjedrzejewski** [comment]
Thanks @nakashu! :+1:

**Pull request merged**
