### PR TITLE
Replace abandoned libs

### PR DESCRIPTION
**Pull request by loevgaard**
| Q               | A
| --------------- | -----
| Branch?         | master 
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| License         | MIT

Related to #11049.

### CODE REVIEW

**Comment by pamil** [comment]
We only use these components internally, so it shouldn't be too difficult to change, but first, we need to take care of the following Sylius libraries:
 - Registry
 - ThemeBundle
 - FixturesBundle
Which all use one of those Zend libraries.

**Comment by tavy315** [comment]
Maybe their migration tools might help? https://docs.laminas.dev/migration/

**Comment by pamil** [comment]
@tavy315 sounds good, thanks!

@loevgaard I'll close this PR for now and mention steps that we need to take in #11049.

**Comment by loevgaard** [comment]
Thank you, Kamil :)

**Pull request closed without merging**
