### PR TITLE
Update fixtures.rst

### PR DESCRIPTION
**Pull request by gabiudrescu**
based on this gist: https://gist.githubusercontent.com/igormukhingmailcom/39edfb74d45d57f97bafadc3bc7d9af6/raw/bdb48156d8cc454d8e7624dc09feae13822fdaa1/sylius-tips.md

I think it will be better to have in Google SERPS the official documentation rather than a random gist on the internet that might be removed.

| Q               | A
| --------------- | -----
| Branch?         | master
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| License         | MIT

### CODE REVIEW

**Comment by gabiudrescu** [comment]
can this be merged to master? cc @lchrusciel

**Review by lchrusciel — APPROVED** [review]
For now, it is fine. In the long term, we should probably replace old service definition with FQCN

**Comment by lchrusciel** [comment]
Oh, and sorry Gabi, that this PR didn't count to hacktober fest.

**Comment by lchrusciel** [comment]
Thank you, Gabi! :1st_place_medal:

**Pull request merged**
