### PR TITLE
[DOCS] Update Sylius components - Addressing

### PR DESCRIPTION
**Pull request by arti0090**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.12                   |
| License         | MIT                                                          |

### CODE REVIEW

**Comment by arti0090** [comment]
@lchrusciel 
Missing components that I found in composer packagist are:
Calendar / Core / Grid / Resource / Registry
Should I add all of them also?

@CoderMaggie in https://docs.sylius.com/en/latest/components_and_bundles/components/Addressing/basic_usage.html
there is Caution block about "Throws InvalidArgumentException" - I have never meet anything like this in the docs codebase (or maybe missed it), but should we leave it or remove it ?

More of components will come soon 😉

**Comment by lchrusciel** [comment]
Calendar - could be added with one/two sentences about why we created it: "Simple component, that abstracts date object creation, which the main purpose is to ease testing of date depended features" + simple installation and usage guide? 
Core - this is the whole Sylius, so I would skip it. Unless, we would like to make it easier to use Sylus as eCommerce engine ;)  Something for the future
Grid - its docs were consciously moved to https://github.com/Sylius/SyliusGridBundle/tree/1.12/docs. I wouldn't add anything there other then just a link to other documentation
Resource - same as above
Registry - same as above

**Comment by vvasiloi** [comment]
Is this still relevant?

**Comment by jakubtobiasz** [comment]
Let's close it for now. We have more important things to do, and it'll be (or even it is already) covered in the new docs.

**Pull request closed without merging**
