### PR TITLE
Support for attaching all types of files to products, taxon and other entities.

### LINKED ISSUE #9111: Attach audio and video media types to product and not only image
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Sylius version   | 1.x.y

Currently, I can attach and override image upload behavior using events.
I want to upload audio and video types as well. I want to show audio and video players in the backend.
I am using Image model for uploading audio and video types, 
I went through the documentation and repo seems like there's only Image upload feature.
I would think a generic Media model would be preferable to handle and attach all types of media rather than just image.

Currently, I am working on the music store. I want admin to upload audio and want some pre-processing done to audio to generate waveforms etc.

Need some guidance on how I can achieve this.

### PR DESCRIPTION
**Pull request by smtlab**
This is a big update which replaces all image models to generic file
models.
Added FilesAwareTrait
Updated tests, validations, Models, Mapping Files.
Tested

| Q               | A
| --------------- | -----
| Branch?         | master 
| Bug fix?        | n
| New feature?    |yes
| BC breaks?      | no/yes
| Deprecations?   | no 
| Related tickets | fixes #9111 
| License         | MIT

### CODE REVIEW

**Comment by smtlab** [comment]
Hello,
I have done deep refactoring of code to support generic file types which can be easily attached to entities.
Let me know if this update makes sense so that I will keep on working out the fixes related to it otherwise.

What do you guys think?

**Comment by sweoggy** [comment]
Looks great so far, lacking non image files tests and frontend from what I can see.

**Comment by smtlab** [comment]
Ahh yes, wanted to get some input from the community first :)
We will probably need to implement admin form field type preview on the basis of mime-type, rest all remains same.
Frontend I have kept all the image related getters and setters intact. So everything should work as expected.

**Comment by pamil** [comment]
Thanks for your effort! Though I haven't reviewed it line-by-line, I can tell by a quick look that I won't be able to merge it, because of our [Backwards Compatibility Promise](http://docs.sylius.com/en/1.1/contributing/code/bc.html) - there are class names changes, API changes etc. The easiest way to include such changes would be making a plugin that allows you to add attachments to the product (but does not remove images).

**Comment by sweoggy** [comment]
@pamil Why not Sylius 2.0?

**Comment by pamil** [comment]
@sweoggy Sylius 2.0 isn't even planned yet, we're focusing on making Sylius 1.x the best eCommerce framework and growing the ecosystem now :)

**Comment by artggd** [comment]
@smtlab did you not eventually make a plugin out of your devs? Definitely need this feature 🙂

**Comment by Snowbaha** [comment]
I found this one: https://github.com/Mezcalito/SyliusFileUploadPlugin

**Pull request closed without merging**
