### PR TITLE
[Behat] Annihilate Łuksaz Zalewski

### PR DESCRIPTION
**Pull request by Zales0123**
| Q               | A
| --------------- | ---
| Bug fix?        | yes |
| New feature?    | no |
| BC breaks?      | no |
| Related tickets | |
| License         | MIT |

I'm 100% sure such a contributor does not exist 😕  🚀

### CODE REVIEW

**Comment by lchrusciel** [comment]
VETO!

**Comment by lchrusciel** [comment]
Travis don't like this change also!

**Comment by Zales0123** [comment]
Seems like it was a significant docblock 😕

**Comment by pjedrzejewski** [comment]
@Zales0123 Sorry Mateusz, even the build is red. This has to stay... FOREVER...

**Comment by Zales0123** [comment]
The build is red because you made it red, you bastards! :( 😕  🔥

**Pull request closed without merging**
