### PR TITLE
[Critical] Change Zales0123 mail

### PR DESCRIPTION
**Pull request by Zales0123**
| Q               | A
| --------------- | ---
| Bug fix?        | yes |
| New feature?    | no |
| BC breaks?      | no |
| Related tickets | |
| License         | MIT |

To allow world to communicate with me easier 🌎  📫

### CODE REVIEW

**Comment by alcaeus** [comment]
Just a general thought: how about moving these to `composer.json` and be done with it? If we want to know who did something in a specific file there's always `git log` and `git blame`. This would avoid huge PRs like this one or #8071.

**Comment by pamil** [comment]
@alcaeus that's why I don't add those author docblocks anymore :)

**Comment by alcaeus** [comment]
@pamil then that would be an idea how to deal with this once and for all: remove all `@author` docblocks and be done with it? :)

**Comment by pamil** [comment]
@alcaeus I'm OK with removing mine, although I'm not sure how other contributors will respond to their author docblocks being removed, it can be a sensitive matter for some

**Comment by alcaeus** [comment]
@pamil Here's a list:

```
$ grep -irho "* @author .*" . | sed -e 's/* @author //g' | sort | uniq -c | sort -grb
 546 Paweł Jędrzejewski <pawel@sylius.org>
 446 Kamil Kokot <kamil@kokot.me>
 348 Mateusz Zalewski <mateusz.zalewski@lakion.com>
 237 Grzegorz Sadowski <grzegorz.sadowski@lakion.com>
 233 Łukasz Chruściel <lukasz.chrusciel@lakion.com>
 213 Arkadiusz Krakowiak <arkadiusz.krakowiak@lakion.com>
 154 Anna Walasek <anna.walasek@lakion.com>
 149 Jan Góralski <jan.goralski@lakion.com>
  89 Saša Stamenković <umpirsky@gmail.com>
  88 Gonzalo Vilaseca <gvilaseca@reiss.co.uk>
  68 Michał Marcinkowski <michal.marcinkowski@lakion.com>
  44 Magdalena Banasiak <magdalena.banasiak@gmail.com>
  20 Mark McKelvie <mark.mckelvie@reiss.com>
  17 Arnaud Langlade <arn0d.dev@gmail.com>
  15 Gorka Laucirica <gorka.lauzirika@gmail.com>
  14 Magdalena Banasiak <magdalena.banasiak@lakion.com>
  13 Jérémy Leherpeur <jeremy@leherpeur.net>
  13 Gustavo Perdomo <gperdomor@gmail.com>
  11 Joseph Bielawski <stloyd@gmail.com>
  10 Arnaud Langlade <aRn0D.dev@gmail.com>
  10 Alexandre Bacco <alexandre.bacco@gmail.com>
   9 Daniel Leech <daniel@dantleech.com>
   7 Leszek Prabucki <leszek.prabucki@gmail.com>
   6 Daniel Richter <nexyz9@gmail.com>
   5 Ben Davies <ben.davies@gmail.com>
   5 Arnaud Langade <arn0d.dev@gmail.com>
   4 Tobias Schultze <http://tobion.de>
   4 Stefan Doorn <stefan@efectos.nl>
   4 Laurent Paganin-Gioanni <l.paganin@algo-factory.com>
   4 Kristian Loevstroem <kristian@loevstroem.dk>
   4 Gabi Udrescu <gabriel.udr@gmail.com>
   4 Fabien Potencier <fabien@symfony.com>
   4 Axel Vankrunkelsven <axel@digilabs.be>
   3 Łukasz Chruściel <lchrusciel@gmail.com>
   3 Viorel Craescu <viorel@craescu.com>
   3 Vincenzo Provenza <vincenzo.provenza89@gmail.com>
   3 Paweł Jędrzejewski <pawel@svaluelius.org>
   3 Loïc Frémont <loic@mobizel.com>
   3 Bartosz Siejka <bartosz.siejka@lakion.com>
   3 Adam Elsodaney <adam.elso@gmail.com>
   2 Łukasz Chruściel<lukasz.chrusciel@lakion.com>
   2 Łukasz Chruściel <lukasz.chrusciel@lakion.org>
   2 Łukasz Chrusciel <lukasz.chrusciel@lakion.com>
   2 Steffen Brem <steffenbrem@gmail.com>
   2 Sergio Marchesini
   2 Saidul Islam <saidul.04@gmail.com>
   2 Prezent Internet B.V. <info@prezent.nl>
   2 Myke Hines <myke@webhines.com>
   2 Ka Yue Yeung <kayuey@gmail.com>
   2 Julien Janvier <j.janvier@gmail.com>
   2 Jeroen Thora <jeroen.thora@intracto.com>
   2 Ivannis Suárez Jérez <ivannis.suarez@gmail.com>
   2 Hussein Jafferjee <hussein@jafferjee.ca>
   2 Dosena Ishmael <nukboon@gmail.com>
   1 Łuksaz Zalewski <mateusz.zalewski@lakion.com>
   1 Łukasz CHruściel <lukasz.chrusciel@lakion.com>
   1 Sebastiaan Stok <s.stok@rollerscapes.net>
   1 Romain Monceau <romain@akeneo.com>
   1 Piotr Walków <walkow.piotr@gmail.com>
   1 Patrik Karisch <patrik.karisch@abimus.com>
   1 Manuel Gonzalez <mgonyan@gmail.com>
   1 Maksim Kotlyar
   1 Joeri Timmermans <joeri.timmermans@intracto.com>
   1 Ivan Molchanov <ivan.molchanov@opensoftdev.ru>
   1 Fabian Kiss <fabian.kiss@ymc.ch>
   1 Dmitrijs Balabka <dmitry.balabka@gmail.com>
   1 David Buchmann <mail@davidbu.ch>
   1 Arnaud Langlade <arn0d.dev@gmali.com>
   1 Arkadiusz Krakowiak <arkadiusz.krakowiake@lakion.com>
   1 Aram Alipoor <aram.alipoor@gmail.com>
   1 Antonio Peric <antonio@locastic.com>
   1 Andrew Johnson
   1 Ahmed Kooli <kooliahmd@gmail.com>
```

Most should be easy to track down. Personally, I'd refer to the contributor list and the git log for attribution. You could always add "Community Contributors" to the composer authors to account for that.

**Comment by pjedrzejewski** [comment]
For me personally, my e-mail can be removed. Although I know for some it may be important indeed and it is nice to get this credit. We have 400+ contributors, moving to Composer.json is not an option imo. We should bring back contributor list to Sylius.org perhaps. As for removing the author blocks from code, I will try to get some advice.

**Comment by alcaeus** [comment]
@pjedrzejewski a contributor list is a good idea, one could link to that in `composer.json`. Symfony for example, [does exactly that](https://github.com/symfony/symfony/blob/master/composer.json#L13..L16).

**Comment by mbabker** [comment]
Using GitHub's API to get a contributor list to show on the Sylius website is honestly a better solution long term.  Plus, that lets you pick up contributors in other areas (i.e. docs and UI work).  And there are people who have contributed various things who won't have an author tag anywhere.

**Pull request closed without merging**
