### PR TITLE
Add extension point to add template data

### PR DESCRIPTION
**Pull request by winzou**
Q | A
------------- | -------------
Bug fix? | no
New feature? | no
BC breaks? | no
Deprecations? | no
Fixed tickets | -
License | MIT
Doc PR | -

Update FOSRestBundle to have the setTemplateData method, and add an extension point to add template data without overriding the whole action in ResourceController.

Side modification: in create/update action, do not set the form template data as it is automatically added by the ViewHandler cf [ViewHandler.php#L384-385](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/View/ViewHandler.php#L384-385)

### CODE REVIEW

**Comment by winzou** [comment]
OK, I removed my side modification and build is green. Ready to merge.

Not sure what you want to do, but it seems that we don't use FOSRestBundle the right way:
  * When using a form, we should not pass data this way: [ResourceController.php#L209-L212](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php#L209-L212)
  * Instead, we should just pass the form as the data, the VewHandler does the rest: [ViewHandler.php#L384-L385](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/View/ViewHandler.php#L384-L385)
  * When submitted form is invalid, the http code is 400 by default cf [ViewHandler.php#L200-L201](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/View/ViewHandler.php#L200-L201) but in our behat scenario we expect 200 (hence the failing build with my modification)

**Comment by winzou** [comment]
Ready to merge :)

**Comment by winzou** [comment]
ping @pjedrzejewski PR waiting for more than a month

**Comment by pjedrzejewski** [comment]
@winzou I love the use case and would like to have something for that, but it is a bit hacky don't you think? Overriding protected method just to add some data to template sounds a bit too much. I will think about something for this case! Thanks!

**Pull request closed without merging**
