### PR TITLE
Play with Travis-CI containers

### PR DESCRIPTION
**Pull request by stloyd**

### CODE REVIEW

**Comment by stloyd** [comment]
@pjedrzejewski @aRn0D ping ;) 

This should reduce quite a lot waiting queues for Sylius builds according to this tweet about capacity of builds: https://twitter.com/spacemanLubick/status/582919260076412928

**Comment by pjedrzejewski** [comment]
Nice! Could you just explain me briefly what is the difference technically? :P

**Comment by stloyd** [comment]
@pjedrzejewski I think best would be to check Travis-CI docs about container-based infrastructure: http://docs.travis-ci.com/user/workers/container-based-infrastructure/

**Comment by pjedrzejewski** [comment]
@stloyd Wow, this is actually really cool. Thanks! Next step would be to cache vendors? (according to the docs, container-based envs allow that)

**Comment by stloyd** [comment]
@pjedrzejewski vendors can be cached only in case we don't call low/high deps changes, but I guess we can easily cache `web/` assets changes etc.

**Pull request merged**
