### PR TITLE
[Hot-Fix] Add conflict to symfonyą/form 4.11 and nikic/php-parser 4.7

### PR DESCRIPTION
**Pull request by Tomanhez**
| Q               | A
| --------------- | -----
| Branch?         | 1.7
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| License         | MIT

### CODE REVIEW

**Comment by pamil** [comment]
Thanks, Tomasz! :tada:

**Comment by loevgaard** [comment]
Why was the `nikic/php-parser` added as a conflict and why was it added like `nikic/php-parser: ^4.7` instead of a specific version?

**Comment by lchrusciel** [comment]
Hey @loevgaard, I don't remember, but we can always try to remove the conflict and run build again.

**Comment by loevgaard** [comment]
Just tried to do that :)

**Pull request merged**
