### PR TITLE
Update UserController.php

### LINKED ISSUE #5859: Route 'sylius_user_security_login' does not exist anymore
In **UserBundle\Controller\UserController**, line  [217](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/UserBundle/Controller/UserController.php#L217), there is still a reference to a deleted route : 

```
$redirectRouteName = $request->attributes->get('_sylius[redirect]', 'sylius_user_security_login', true);
```

should be : 

```
$redirectRouteName = $request->attributes->get('_sylius[redirect]', 'sylius_shop_login', true);
```

There are some other occurences throughout the file too.

### PR DESCRIPTION
**Pull request by ibasaw**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Related tickets | fixes #5859 |
| License | MIT |

fix incorrect route

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
UserBundle does not know about ShopBundle, so this does not seem right, what is the problem with current default values?

**Comment by ibasaw** [comment]
ping @tchapi

**Comment by tchapi** [comment]
Well the current default routes does not exist, so it redirects and :boom: 500 with : 

    None of the chained routers were able to generate route: Route 'sylius_user_security_login' not found

Or is there something we missed ?

**Comment by tchapi** [comment]
Is there any update on the merging of this PR ? The forgotten password feature is currently broken because of this ...

**Comment by michalmarcinkowski** [comment]
Fixed in https://github.com/Sylius/Sylius/pull/6782

**Pull request closed without merging**
