### PR TITLE
[Documentation] Fix typo

### PR DESCRIPTION
**Pull request by willy-ahva**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Related tickets |  |
| License | MIT |

Hey Sylius Team !

I am an Akeneo Core Team member from and this week we use as model your documentation about contributing with a patch for our own documentation.
So we wanted to thank you for the great work, and let you know that we found some typos in the documentation. We would be pleased to share our fixes with you.

Regards,
Akeneo Team

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
Hi Willy! That's great, thank you! Our Contributing Guide is based on Symfony's documentation. :)

**Comment by Zales0123** [comment]
@CoderMaggie is it something we would like to merge? It's a long time and still seems valid 😄  🐃

**Comment by lchrusciel** [comment]
@willy-ahva would you like to rebase and resolve conflicts?

**Comment by Zales0123** [comment]
@CoderMaggie are we willing to merge this changes? If yes, then would you @willy-ahva be able to rebase it? And it should probably be made basing on 1.0 branch ;)

**Comment by CoderMaggie** [comment]
Yes, we are willing to merge this one.

But
* it has to be against `1.0` branch
* it has to be rebased :)

**Comment by pamil** [comment]
Rebased in #9137.

**Pull request closed without merging**
