### PR TITLE
Quote usage of !!int  to remove deprecation warning

### PR DESCRIPTION
**Pull request by stefandoorn**
| Q               | A
| --------------- | -----
| Branch?         | 1.0
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| License         | MIT

Removes some Symfony deprecation warnings.

### CODE REVIEW

**Comment by teohhanhui** [comment]
May I know what is the Symfony issue / PR? This seems wrong from a YAML perspective?

**Comment by stefandoorn** [comment]
Not sure @teohhanhui what is the related Symfony change. If you run a project locally, I found it in the deprecations in the profiler.

**Comment by teohhanhui** [comment]
The correct syntax should be `!!php/int`, but I'm not sure if that's implemented in Symfony.

**Comment by stefandoorn** [comment]
`vendor/symfony/symfony/src/Symfony/Component/Yaml/Inline.php` at line 727 is where the exception is. Symfony 3.4.2.

**Comment by pamil** [comment]
Thank you, Stefan! 🥇

**Pull request merged**
