### PR TITLE
[Payum][PayPal] Use full price instead of discounted one

### PR DESCRIPTION
**Pull request by Prometee**
| Q               | A
| --------------- | -----
| Branch?         | 1.4 to master
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | unknown
| License         | MIT

I was having trouble with many PayPal errors during the black friday and the error was :
`"The totals of the cart item amounts do not match order amounts."`

It was caused by the line I edit in this PR.

See discussion for more details : https://sylius-devs.slack.com/archives/C3EGDG9LY/p1575983221275500 (This link could be down one day)

### CODE REVIEW

**Comment by Prometee** [comment]
This is a critical issue for those who use PayPal, is this PR could be merge quickly ?

**Comment by lchrusciel** [comment]
What happened @Prometee? Did you want to reopen this issue?

**Comment by Zales0123** [comment]
It's already opened :) https://github.com/Sylius/Sylius/pull/10938

**Comment by Prometee** [comment]
I just blew up my cloned repository... So I rebase it to the master branch to avoid this long commit list coming from branch 1.3... Just delete this one and #10917  if you could do it. Sorry for making this mess ...

**Pull request closed without merging**
