### PR TITLE
Remove unused dependency

### PR DESCRIPTION
**Pull request by gonzalovilaseca**

### CODE REVIEW

**Comment by aRn0D** [comment]
it is used in comment ;)

**Comment by pjedrzejewski** [comment]
Agree with @aRn0D!

**Comment by gonzalovilaseca** [comment]
@aRn0D  Where's the comment you refer to? Sorry but I don't see it.

**Comment by pjedrzejewski** [comment]
Thanks Gonzalo! :+1: We are blind. :P

**Comment by aRn0D** [comment]
yes I thought we open the wrong file :)

**Comment by gonzalovilaseca** [comment]
:-) I started to think it was me....jeje

**Pull request merged**
