### PR TITLE
Fix missing colon

### PR DESCRIPTION
**Pull request by reyostallenberg**
| Q               | A
| --------------- | -----
| Branch?         | 1.4
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | n.a.
| License         | MIT

### CODE REVIEW

**Comment by lchrusciel** [comment]
The base of this pull-request was changed, you need fetch and reset your local branch 
if you want to add new commits to this pull request. **Reset before you pull, else commits
may become messed-up.**

Unless you added new commits (to this branch) locally that you did not push yet, 
execute `git fetch origin && git reset "patch-2"` to update your local branch.
 
Feel free to ask for assistance when you get stuck :+1:

**Comment by reyostallenberg** [comment]
I think this is a rebased version. (Would be nice if there was a PR template which stated to which branch to point proposed changes)

**Comment by lchrusciel** [comment]
Updated: #10923 10923

**Comment by pamil** [comment]
Thanks, Reyo! :1st_place_medal:

**Pull request merged**
