### PR TITLE
[Core][Checkout] fixed #13201

### LINKED ISSUE #13201: Insert duplicate Customer on checkout for repeating guest customers.
**Sylius version affected**: 1.7 | 1.8 | 1.9 | 1.10

**Description**  
At checkout, repeat guest customers who enter their email address with a different spelling results in a 500 error due to attempting to insert duplicate record (email)

**Steps to reproduce**  
- Checkout as guest entering the email address with a single capital letter.
- Checkout as guest again with the same email, this time all lowercase.

**Possible Solution**  
Modify the Form Event Listeners on CustomerCheckoutGuestType and CustomerGuestType to look up customer by emailCanonical instead of email

### PR DESCRIPTION
**Pull request by acornforth**
use canonicalized email for customer lookup on CustomerGuestFormTypes

Caused insert duplicate errors on customer table for repeat guest customers

| Q               | A
| --------------- | -----
| Branch?         | 1.11
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no?
| Deprecations?   | no
| Related tickets | fixes #13201
| License         | MIT

### CODE REVIEW

**Review by Roshyo — APPROVED** [review]

**Comment by acornforth** [comment]
Would this be more likely to attract the attention of the core team and be reviewed/merged is if was properly labelled as a Bug Fix ? I am unable to do it.

**Comment by stloyd** [comment]
I can confirm this issue, was doing similar adjustment to email to prevent duplication of users with same email.

**Comment by Roshyo** [comment]
Could you come up with some test about this scenario please ?

**Comment by acornforth** [comment]
While I can justify submitting this fix i already made during my work hours, my workload is quite heavy at the moment, and any tests i write would have to be done on my own time, and i don't have much at the moment, which means i can't get to it for a while. If anyone else can add the required tests and get this merged i'm sure it will be appreciated. Unfortunately i cannot right now.

**Comment by SirDomin** [comment]
The base of this pull-request was changed, you need fetch and reset your local branch 
if you want to add new commits to this pull request. **Reset before you pull, else commits
may become messed-up.**

Unless you added new commits (to this branch) locally that you did not push yet, 
execute `git fetch origin && git reset "issue_13201"` to update your local branch.
 
Feel free to ask for assistance when you get stuck :+1:

**Comment by SirDomin** [comment]
The problem occurs on PostgreSQL only, all mysql builds seems to be working correctly, /cc @Ferror

**Comment by lchrusciel** [comment]
Can be continued after #13786

**Review by GSadee — APPROVED** [review]

**Comment by GSadee** [comment]
Thank you, Andrew! :tada:

**Pull request merged**
