### PR TITLE
Add github templates

### PR DESCRIPTION
**Pull request by letanure**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | none
| License       | MIT
| Doc PR        | none

Just adding the [PR and Issue templates](https://github.com/blog/2111-issue-and-pull-request-templates) as files inside `/.github` folders

### CODE REVIEW

**Comment by gorkalaucirica** [comment]
[PR template](https://github.com/Sylius/Sylius/blob/master/PULL_REQUEST_TEMPLATE.md) already exists in project root

**Comment by letanure** [comment]
just using the github proposed structure, with `.github` folder, and template for **pull request** and for **issues** to avoid too many files in the root.

**Comment by pamil** [comment]
I don't think that we **do** need a template for issues - too much formalization isn't good too. The current PR template does its job too (and we don't need columns like docs PR or deprecations now).

**Comment by letanure** [comment]
ok!

**Pull request closed without merging**
