### PR TITLE
Update gulp-livereload

### PR DESCRIPTION
**Pull request by kulczy**
| Q               | A
| --------------- | -----
| Branch?         | 1.2
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| License         | MIT

"gulp-livereload" package update due to malicious code issues. More info [here](https://github.com/vohof/gulp-livereload/issues/139)

### CODE REVIEW

**Comment by 11mb** [comment]
Looking good!

**Comment by stefandoorn** [comment]
LGTM.

**Comment by stefandoorn** [comment]
Should this also be backported to v1.1? I think it still supports security fixes, isn't it?

**Comment by Zales0123** [comment]
@stefandoorn Agreed 👍

**Pull request closed without merging**
