### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by vvasiloi**
| Q               | A
| --------------- | -----
| Branch?         | 1.4
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| License         | MIT

### CODE REVIEW

**Comment by Zales0123** [comment]
This is a duplicate of #9661... and unfortunately, as mentioned [there](https://github.com/Sylius/Sylius/pull/9661#discussion_r212303537) it's not possible to merge it because of BC policy :/

**Comment by lchrusciel** [comment]
But what about adding an alias + depreciation about the usage of the old one?

**Comment by vvasiloi** [comment]
My bad, didn't see the other one.
I was thinking it may be a BC break.
I was hopping that adding the `payum.action` tag with alias `sylius.offline.status` will replace the action, but unfortunately the service has to be overriden or aliased.
So, alias + deprecation will work.
I can do that if you reopen this PR and close the other one.

**Comment by vvasiloi** [comment]
The question is, do I
1. deprecate the old service and alias the new one to it;
2. add the new service and alias the old one to it?

**Comment by lchrusciel** [comment]
I would go for 2 with alias deprecation: https://symfony.com/blog/new-in-symfony-4-3-deprecating-service-aliases

**Pull request closed without merging**
