### PR TITLE
[Channel] Revert Doctrine ORM 2.5 dependency to 2.4

### PR DESCRIPTION
**Pull request by axelvnk**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #3655
| License       | MIT

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
Thanks Axel!

**Comment by brendas-jomedia** [comment]
Hi there,
Is there a reason why the Sylius has a dependency on 2.4?  We are working with the promotion and promotion-bundle and both have doctrine-orm dependencies of ^2.4.8,<2.5.  We need to make the jump to Doctrine 2.5 and above (specifically, 2.5.1), because of the known issues with version 2.4.8.  Is this something you are working on?  Is there code available for the promotion and promotion-bundle?

Thanks!

**Comment by pamil** [comment]
@brendas-jomedia see #3836

**Comment by brendas-jomedia** [comment]
Thanks for your help!  In our case, we are only using the promotion and promotion-bundles, and these are still locked to ^2.4.8,<2.5.  This causes issues with the rest of our project, notably because of Doctrine bugs DDC-3699: Fix bug in EntityManager#merge: Skipping properties if they are listed after a not loaded relation and DDC-3667: PersistentCollection: Fix BC break when creating empty Array/PersistentCollections which were fixed in version 2.5.1.  Are you looking to update those bundles to Doctrine 2.5?

**Comment by michalmarcinkowski** [comment]
@brendas-jomedia we plan to resolve this issue and update to Doctrine 2.5 ASAP :)

**Comment by rvanlaak** [comment]
Seems `2.5.1` Doctrine bugs related to this revert action are fixed? [DDC-3699](https://github.com/doctrine/doctrine2/issues/4532) & [DDC-3667](https://github.com/doctrine/doctrine2/issues/4498)

@pjedrzejewski any plans to update `ORM` to `2.5` again? We are also only using `promotion` and `promotion-bundle`.

**Comment by pjedrzejewski** [comment]
@rvanlaak We will be looking at upgrading to Symfony 2.8 and Doctrine 2.5 very soon.

**Comment by rvanlaak** [comment]
Thanks @pjedrzejewski ! Hope this can be fixed soon. We use the `PromotionsBundle` in our Symfony application and are eager to upgrade to Symfony 3.1 at the moment its first patch version is released. 

Can you maybe provide some info on the Symfony upgrade path? What would it take for Sylius to bump all Symfony-related dependencies to `^2.8|^3.0` ?

**Comment by pjedrzejewski** [comment]
@rvanlaak I guess fixing all depracation warnings (we are on Symfony 2.8 already) and integrating this - https://github.com/isometriks/LegacyFormBundle. We heavily use aliases in forms and Symfony 3.0 unfortunately removed this functionality... Any help appreciated! 👍

**Comment by rvanlaak** [comment]
I'll try to put deprecation fixing of the `PromotionBundle` on my planning, would it be an idea to separately allow bundles to start supporting `Sf ^3.0` and `ORM ^2.5`?

**Pull request merged**
