### PR TITLE
[Admin] Change homepage path variable to use snake case

### PR DESCRIPTION
**Pull request by GSadee**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.12|
| Bug fix?        | no                                                      |
| New feature?    | no                                                      |
| BC breaks?      | no                                                      |
| Deprecations?   | no|
| Related tickets | fixes https://github.com/Sylius/Sylius/pull/14556#pullrequestreview-1277137601|
| License         | MIT                                                          |

### CODE REVIEW

**Comment by diimpp** [comment]
Is it necessary? I've checked AdminBundle variables declarations before selecting camelCase, for example order summary

https://github.com/Sylius/Sylius/blob/c88cdeaeda0229d4579ead93b12df8e8856d3a7e/src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/Summary/_item.html.twig#L3-L15

**Comment by diimpp** [comment]
Ah, I've seen mention of https://docs.sylius.com/en/1.12/book/contributing/code/conventions.html

Unless there is way to enforce this, I would go with most popular way to define variables in current codebase (camelCase) and leave convention change to sylius2.0, though I do not support this convention, most of the calls are entities like `customer.firstName` and having both `{% set first_name = customer.firstName %}` is most strange

**Comment by GSadee** [comment]
For me, we should follow this convention for all newly added variables. And probably in Sylius 2.0 we will make it consistent. Now, looking at the code, there is not really a rule, we used "snake_case" once and "camelCase" once.

**Review by Roshyo — APPROVED** [review]

**Review by TheMilek — APPROVED** [review]

**Review by jakubtobiasz — APPROVED** [review]

**Comment by jakubtobiasz** [comment]
Thank you, @GSadee!

**Pull request merged**
