### PR TITLE
Add some explanations about the stocks issue

### PR DESCRIPTION
**Pull request by jacquesbh**
| Q               | A
| --------------- | -----
| Branch?         | master
| Bug fix?        | kind of
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets |
| License         | MIT

I really didn't know how to write such thing. It's really difficult to understand actually.

cc @Zales0123

### CODE REVIEW

**Review by lchrusciel — APPROVED** [review]
However, I'm not sure about placing all this into upgrade file.

**Comment by jacquesbh** [comment]
@lchrusciel Ok, not here, but where then?

How to warn developers that something bad will happen? I discussed it with @Zales0123 when it happened. It's shit.

Let me know!

**Review by Zales0123 — APPROVED** [review]
It does not seem, it's an ideal place to write it... But I see no better one 😄 I would go with it, as the information could be important and if we find a better place to explain such an issue, we will just move it :)

**Comment by Zales0123** [comment]
The base of this pull-request was changed, you need fetch and reset your local branch 
if you want to add new commits to this pull request. **Reset before you pull, else commits
may become messed-up.**

Unless you added new commits (to this branch) locally that you did not push yet, 
execute `git fetch origin && git reset "patch-8"` to update your local branch.
 
Feel free to ask for assistance when you get stuck :+1:

**Comment by lchrusciel** [comment]
Thank you, Jacques! :tada:

**Pull request merged**
