### PR TITLE
[Addressing] Use UniqueWithinCollectionConstraint instead UniqueEntity for members validation

### LINKED ISSUE #3886: [Addressing] Can create a Zone of type country with duplicated zone members
Steps to reproduce:
1. Go to zones in admin;
2. Hit the "create" button with "country" selected;
3. Fill name and code with random values;
4. Add 2 zone members with the same country;
5. Submit the form

### PR DESCRIPTION
**Pull request by twojtylak**
| Q               | A
| --------------- | ---
| Bug fix?        | yes |
| New feature?    | no |
| BC breaks?      | no |
| Related tickets | fixes #3886 |
| License         | MIT |

Fixes Mysql Error Integrity constraint violation: 1062 when creating a new zone with duplicate zone members

### CODE REVIEW

**Comment by lchrusciel** [comment]
Can you rebase to the master? Failing build should be fixed.

**Comment by pjedrzejewski** [comment]
@twojtylak Hi! If you manage to rebase it today, it has a chance to get into beta.3 :)

**Comment by twojtylak** [comment]
@pjedrzejewski Hi. I rebased the branch a minute ago.

**Comment by lchrusciel** [comment]
Thanks @twojtylak :)

**Pull request merged**
