### PR TITLE
[RFC] [Behat] [DX] Split behat services to different files

### PR DESCRIPTION
**Pull request by lchrusciel**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | yes
| Deprecations?   | no
| Related tickets | 
| License         | MIT
| Doc PR          |

### CODE REVIEW

**Comment by TheMadeleine** [comment]
:+1:

**Comment by pjedrzejewski** [comment]
What's the point of having 1 folder with 1 file?

**Comment by lchrusciel** [comment]
Based on #4444

**Comment by michalmarcinkowski** [comment]
Thanks Łukasz! :+1:

**Pull request merged**
