### PR TITLE
Fix testing migrations

### PR DESCRIPTION
**Pull request by loic425**
| Q               | A
| --------------- | -----
| Branch?         | master (1.7)
| Bug fix?        | yes (CI only)
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets |
| License         | MIT

### CODE REVIEW

**Comment by Zales0123** [comment]
👍 but the build failed, so probably there is something wrong with the migrations... can you take a look at it @loic425?

**Comment by loic425** [comment]
@Zales0123 it proves the changes work :smile: 
I'll have a look soon.

**Comment by Zales0123** [comment]
Indeed 😄 Thank you!

**Comment by loic425** [comment]
@Zales0123 I check it out. This is not really a migration problem cause database cannot be reverted until first version due to data unique on sylius product translation unique index (slug, locale).

I think we have to empty database before or add this test before testing fixtures or behat features.

**Comment by loic425** [comment]
Empty database could hide some problems... But the only other solution is to remove duplicated to match the old unique key and this is not acceptable too...

**Comment by pamil** [comment]
Thanks, Loïc! :tada:

**Pull request merged**
