### PR TITLE
[API] fix prefix url on locale api path

### PR DESCRIPTION
**Pull request by oallain**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.12          |
| Bug fix?        | yes                                                       |
| New feature?    | no                                                       |
| BC breaks?      | no                                                       |
| Deprecations?   | no  |
| Related tickets |                        |
| License         | MIT                                                          |

### CODE REVIEW

**Comment by jakubtobiasz** [comment]
Were these missing `/` causing any troubles or that's only a cosmetic change?

**Comment by oallain** [comment]
> Were these missing `/` causing any troubles or that's only a cosmetic change?

After a few checks, ApiPlatform automatically adds the `/`, so it's just cosmetic.

**Review by jakubtobiasz — DISMISSED** [review]

**Review by diimpp — COMMENTED** [review]
There is one more at `Order.xml`
https://github.com/Sylius/Sylius/blob/104bc12d1bc8c7960d67ce1ec87b004eda574c3b/src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Order.xml#L24

**Review by diimpp — APPROVED** [review]

**Review by jakubtobiasz — APPROVED** [review]

**Review by Roshyo — APPROVED** [review]

**Comment by jakubtobiasz** [comment]
Thank you, @oallain!

**Pull request merged**
