### PR TITLE
[CoreBundle] Use more specific names for settings namespaces

### PR DESCRIPTION
**Pull request by aramalipoor**
Q  | A
------------- | -------------
Bug fix?  | no
New feature?  | no
BC breaks? | yes
Deprecations? | no
Fixed tickets | -
License | MIT
Doc PR | -

### CODE REVIEW

**Comment by aramalipoor** [comment]
@pjedrzejewski @aRn0D ping!

**Comment by stloyd** [comment]
This is BC break but IMO it's ok.

**Comment by aramalipoor** [comment]
@pjedrzejewski @aRn0D ping!

**Comment by aramalipoor** [comment]
@pjedrzejewski What do you think about this?

**Comment by aRn0D** [comment]
Personnlly Personalty, I prefer that approach #2691

**Comment by pjedrzejewski** [comment]
@aRn0D We will add this as well. @aramalipoor Thank you Aram! :+1:

**Pull request merged**
