### PR TITLE
Fix Typo fixtures.rst

### PR DESCRIPTION
**Pull request by zairigimad**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.12 or 1.13                   |
| Bug fix?        | no/yes                                                       |
| New feature?    | no/yes                                                       |
| BC breaks?      | no/yes                                                       |
| Deprecations?   | no/yes  |
| Related tickets | fixes #X, partially #Y, mentioned in #Z                      |
| License         | MIT                                                          |

### CODE REVIEW

**Review by diimpp — APPROVED** [review]

**Review by jakubtobiasz — DISMISSED** [review]

**Review by jakubtobiasz — COMMENTED** [review]
Why do you think it's a typo 🤔?

**Comment by zairigimad** [comment]
> Why do you think it's a typo 🤔?

For me the Entity folder should contains only entities, and we shoud have another folder for Fixtures

**Comment by jakubtobiasz** [comment]
Ah, you're right. Idk why, I read the diff inversly 😂.I thought you put it in the `Entity` directory 😂.

**Review by jakubtobiasz — APPROVED** [review]

**Comment by jakubtobiasz** [comment]
Thank you, @zairigimad!

**Pull request merged**
