### PR TITLE
Fix return typehint for TaxonTranslation

### PR DESCRIPTION
**Pull request by diimpp**
| Q               | A
| --------------- | -----
| Branch?         | 1.0, 1.1
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| License         | MIT

Untested

### CODE REVIEW

**Comment by pamil** [comment]
Looks fine, could you rebase it to 1.0 branch?

**Comment by pamil** [comment]
Rebased and pushed in #9133, thanks @diimpp! :)

**Comment by diimpp** [comment]
I was in the middle of rebasing, but thanks :)

**Comment by pamil** [comment]
Sorry, just thought it would be more convenient for you if I would do that

**Pull request closed without merging**
