### PR TITLE
Some form type templates have been created or moved to the ResourceBundle

### PR DESCRIPTION
**Pull request by aRn0D**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by aRn0D** [comment]
@pjedrzejewski do I rebase it ?

**Comment by aRn0D** [comment]
ping @pjedrzejewski

**Comment by aRn0D** [comment]
@pjedrzejewski pong

**Comment by aRn0D** [comment]
@pjedrzejewski plz merge or close it !

**Comment by pjedrzejewski** [comment]
The thing is I want to put these in UiBundle, to avoid making Resource a mess...

**Comment by aRn0D** [comment]
ok good !

**Pull request closed without merging**
