### PR TITLE
[Shop] Break infinite loop

### PR DESCRIPTION
**Pull request by Arminek**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| License         | MIT

### CODE REVIEW

**Comment by CarwynNelson** [comment]
What causes this infinite loop to occur? Is there a github issue which provides more details about this bug?

**Comment by Arminek** [comment]
Rendering partial on main shop layout. ``{% render(url('sylius_shop_partial_taxon_index_by_code', {'code': 'category', 'template': '@SyliusShop/Taxon/_horizontalMenu.html.twig'})) %}``

**Comment by CarwynNelson** [comment]
Are there any tests that could be written to prove that an infinite loop does indeed occur under these circumstances? It sounds like it would be quite a tricky one to test, but it would definitely be worth it. I can imagine somebody else later on down the line changing this bit of config and not realising that it causes an infinite loop.

**Comment by pjedrzejewski** [comment]
@CarwynNelson The reason is our RBAC system, which checks for permissions and roles of users. And in our current test environment, it is enabled for tests which cover RBAC, but disabled for rest, for performance reasons. That being said, we should definitely enable it for all scenarios, which would reveal such issues early.

Also, ``permission: false`` should be a default. Because it is more annoying to set it on all unsecured routes than configure it for entire admin.

**Comment by pjedrzejewski** [comment]
Thank you Arek!

**Pull request merged**
