### PR TITLE
Require ^3.3.8 for Symfony - when in 3.3.x

### PR DESCRIPTION
**Pull request by stefandoorn**
| Q               | A
| --------------- | ---
| Bug fix?        | no|
| New feature?    | no|
| BC breaks?      | no |
| Related tickets | mentioned in #8565 |
| License         | MIT |

We are already at 3.3.6 if > 3.2, so think that 3.3.8 might also make perfect sense.

### CODE REVIEW

**Comment by lchrusciel** [comment]
As far as I know, the current version allows to all patches from 3.2 or all versions above 3.3.6. So if we want to force using 3.3.8 we need to remove the part before the pipeline.

**Comment by stefandoorn** [comment]
Your comment (https://github.com/Sylius/Sylius/pull/8565#issuecomment-328375063) is exactly the reason why I submitted this PR, to at least have it correct within the 3.3.x tree.

I don't know why 3.2 is allowed. I have the impression - if I recall correctly - it was something temporary due to compatibility issues. But not sure about that. As most tests are ran on recent versions, the question is also whether all thing still work on 3.2..

**Comment by lchrusciel** [comment]
I'm voting for removing 3.2 from allowed versions. We are aiming to cover 3.4 and 4.0 as soon as possible anyway /cc @Sylius/core-team

**Comment by lchrusciel** [comment]
Closing in favour of #8576

**Comment by lchrusciel** [comment]
Now I hit a proper one 🏹  🎯

**Pull request closed without merging**
