### PR TITLE
[Product] Unique contraint on slug

### LINKED ISSUE #7245: [Admin][Product] Integrity constraint violation while adding a new product
1. In system there is a product  name:Vodka, code:vodka, slug:vodka
2. When we create a new product name:Vodka, code:122_vodka, slug:vodka then we get constraint violation

screen shot 2017-01-12 at 11 19 49

### PR DESCRIPTION
**Pull request by lchrusciel**
| Q               | A
| --------------- | ---
| Bug fix?        | yes |
| New feature?    | no |
| BC breaks?      | no |
| Related tickets | fixes #7245 |
| License         | MIT |

### CODE REVIEW

**Comment by michalmarcinkowski** [comment]
Have you checked we also have this validation on `Taxon`?

**Comment by lchrusciel** [comment]
@michalmarcinkowski nope. On it.

**Comment by lchrusciel** [comment]
@michalmarcinkowski it is tested already [here](https://github.com/Sylius/Sylius/blob/master/features/taxonomy/managing_taxons/taxon_validation.feature#L38)

**Comment by michalmarcinkowski** [comment]
Thanks Łukasz!

**Pull request merged**
