### PR TITLE
Bug #9738 Fix nested form collections

### LINKED ISSUE #9738: Form collection nested, wrong prototype replace on add button
**Sylius version affected**: 1.*

**Description**  
If you have an admin form that embed two nested collection form, the add button from the 2nd collection form will have his prototype replaced, but the two \_\_name\_\_ occurrences will be replaced by the count of the first collection form.
It will prevent the user from adding multiple items after clicking on the first collection form add button.
Because the inputs form from the 2nd collection have the same names.

It should replace only the first \_\_name\_\_.
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-form-collection.js#L48

**Possible Solution**  
Here how sonata fixed the problem:
https://github.com/sonata-project/SonataAdminBundle/commit/0d3c6ea55623e059e71a4838c43017da1daaf3ae

### PR DESCRIPTION
**Pull request by vic-blt**
If there are nested form collections, the value `__name__` of the sub
collection is being replaced by the parent collection index.
Which makes every new sub collection items having the same index.

| Q               | A
| --------------- | -----
| Branch?         | 1.7
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #9738
| License         | MIT

### CODE REVIEW

**Comment by vic-blt** [comment]
Hi Lukasz,

> Welcome to our community! :)

Thank you :)

**Comment by lchrusciel** [comment]
Btw. @vic-blt can you share some screenshots of the change done by this solution? Or an example code?

**Comment by vic-blt** [comment]
Without the fix :
without_fix

With the fix :
with_fix

You can see that without the fix, `data-form-collection-index` in `data-prototype` attribute, is already set to 0, which makes collection items having the same index because when `data-prototype` attribute of parent collection is modified by `prototype = prototype.replace(/__name__/g, this.count);`, `data-form-collection-index` value of sub collection is also replaced by `this.count` which is the index of parent collection.

**Comment by lchrusciel** [comment]
The base of this pull-request was changed, you need fetch and reset your local branch 
if you want to add new commits to this pull request. **Reset before you pull, else commits
may become messed-up.**

Unless you added new commits (to this branch) locally that you did not push yet, 
execute `git fetch origin && git reset "issue-9738-fix-nested-form-collections"` to update your local branch.
 
Feel free to ask for assistance when you get stuck :+1:

**Comment by lchrusciel** [comment]
The base of this pull-request was changed, you need fetch and reset your local branch 
if you want to add new commits to this pull request. **Reset before you pull, else commits
may become messed-up.**

Unless you added new commits (to this branch) locally that you did not push yet, 
execute `git fetch origin && git reset "issue-9738-fix-nested-form-collections"` to update your local branch.
 
Feel free to ask for assistance when you get stuck :+1:

**Comment by lchrusciel** [comment]
The base of this pull-request was changed, you need fetch and reset your local branch 
if you want to add new commits to this pull request. **Reset before you pull, else commits
may become messed-up.**

Unless you added new commits (to this branch) locally that you did not push yet, 
execute `git fetch origin && git reset "issue-9738-fix-nested-form-collections"` to update your local branch.
 
Feel free to ask for assistance when you get stuck :+1:

**Comment by lchrusciel** [comment]
Thank you, Victorien! :tada:

**Pull request merged**
