### PR TITLE
[Web][Form] - fixed unclickable upload buttons issue 3263

### PR DESCRIPTION
**Pull request by nakashu**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| Enhancement? | yes
| New feature? | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #3263
| License       | MIT

### css/ hmtl changes
Styled upload button area is now fully clickable
Changes where also made in product image prototype html, for it to be consistent/working
Will also fix bugs with translated messages for upload button, as there is no need for the fixed width, that was present before

### javascript - enhancement
Filename of file that would be uploaded is shown, next to upload button.
Works with multiple file upload fields also if browser supports [HTML5 File API](http://caniuse.com/#feat=fileapi)

### CODE REVIEW

**Comment by nakashu** [comment]
can anyone explain why is the test failing? 
I cannot find how it is related to the changes made in the commits.

**Comment by pamil** [comment]
@nakashu no fear, I'll take care of it today :)

**Comment by nakashu** [comment]
bump for merge ?

**Comment by pjedrzejewski** [comment]
Thank you @nakashu! Great work!

**Pull request merged**
