### PR TITLE
Add accept criteria configuration for grid.

### PR DESCRIPTION
**Pull request by liverbool**
| Q               | A
| --------------- | -----
| Branch?         | 1.0
| Bug fix?        | maybe yes
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | ~
| License         | MIT

Now we can config `criteria` for grid.

```yaml
web_search_user:
    path: /search/users
    defaults:
        _format: json
        _controller: sylius.controller.shop_user:indexAction
        _sylius:
            grid: some_grid
            criteria:
                enabled: 'true'

```

### CODE REVIEW

**Comment by liverbool** [comment]
no

**Comment by pamil** [comment]
Rebased with `master`, let's see if it passes. Anyway, it needs some docs (and probably some integration tests, but we don't have them in GridBundle, as I just searched for them 😨).

**Comment by pamil** [comment]
It breaks some tests, but seems like a good idea to have it implemented.

**Comment by Zales0123** [comment]
Hello @liverbool, again it took us some time to process that :/ and in the meantime, we extracted https://github.com/Sylius/SyliusResourceBundle/ and https://github.com/Sylius/SyliusGridBundle/. Can you please propose these changes to these repositories? I'm sure they will be merged sooner than later, as will be more visible on the new repos :) Thank you for your contribution! 🖖

**Pull request closed without merging**
