### PR TITLE
Cleanup various CS issues

### PR DESCRIPTION
**Pull request by stloyd**

### CODE REVIEW

**Comment by aRn0D** [comment]
@stloyd Did you ran a php-cs-fixer on the project?

**Comment by stloyd** [comment]
No ;) Half is manual, the rest is from PHPStorm features.

**Comment by stloyd** [comment]
@pjedrzejewski Feedback?

**Comment by pjedrzejewski** [comment]
Could you take a look at the filing build?

**Comment by stloyd** [comment]
@pjedrzejewski Yes, but anyway it's strange that current master is marked as pass where it fails... https://travis-ci.org/Sylius/Sylius/jobs/52124558#L991

**Comment by pjedrzejewski** [comment]
Ping @stloyd, could you update this PR or close if you miss the time? Thanks!

**Pull request closed without merging**
