### PR TITLE
Enable API by default in dev environment

### PR DESCRIPTION
**Pull request by Zales0123**
| Q               | A
| --------------- | -----
| Branch?         | 1.9
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets |
| License         | MIT

I believe it would be useful for the development 🖖 Without it if I want to change something in the API I need to change the parameter and pray to not forget to remove it before committing 🙏 🎉

### CODE REVIEW

**Review by GSadee — APPROVED** [review]

**Comment by GSadee** [comment]
The base of this pull-request was changed, you need fetch and reset your local branch 
if you want to add new commits to this pull request. **Reset before you pull, else commits
may become messed-up.**

Unless you added new commits (to this branch) locally that you did not push yet, 
execute `git fetch origin && git reset "enable-api-in-dev-by-default"` to update your local branch.
 
Feel free to ask for assistance when you get stuck :+1:

**Comment by stloyd** [comment]
In overall this is **huge** BC break to disabled in minor version something that was enabled before by default... cause as developer you don't expect to do update, have code working in dev env go to production & get fatal errors or 404s...

**Comment by GSadee** [comment]
Thank you, Mateusz! :1st_place_medal:

**Comment by Zales0123** [comment]
@stloyd in general, you're totally right 🖖 but because this new API is still in an experimental phase, a much bigger threat is to make it enabled by default and potentially introduce some security problems to the Sylius applications code 🚀

**Pull request merged**
