### PR TITLE
[Translation][composer] added resource bundle.

### PR DESCRIPTION
**Pull request by aitboudad**

### CODE REVIEW

**Comment by aRn0D** [comment]
@pjedrzejewski What do you plan for resource and translation bundle dependency ?

**Comment by pjedrzejewski** [comment]
@aRn0D Working on this as we speak, figuring out last little issues with some crazy Doctrine erros. (we manipulate it a lot :P)

**Comment by aRn0D** [comment]
@pjedrzejewski ok, I am working a resource extension (dependency injection), I will send a PR.

**Comment by aitboudad** [comment]
close in favor of #2519

**Pull request closed without merging**
