### PR TITLE
[Theme] fix bc break in templates loading, add real template existence check

### PR DESCRIPTION
**Pull request by ahilles107**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Related tickets | #5958, #6067 
| License         | MIT

### CODE REVIEW

**Comment by ahilles107** [comment]
@pamil - can take a look here?

**Comment by pamil** [comment]
Looks good to me! :+1:

**Comment by michalmarcinkowski** [comment]
Thanks Paweł! 👍

**Comment by tchapi** [comment]
:tada:

**Pull request merged**
