### PR TITLE
Add a missing orders prefix to routes in Admin Panel

### LINKED ISSUE #12225: Admin routing for orders misses /orders prefix for two routes
https://github.com/Sylius/Sylius/blob/e6c9cb6318bc806474427e0fca84c25515a4802d/src/Sylius/Bundle/AdminBundle/Resources/config/routing/order.yml#L123

```diff
    --- path: /{id}/resend-confirmation-email
    +++ path: /orders/{id}/resend-confirmation-email
```

https://github.com/Sylius/Sylius/blob/e6c9cb6318bc806474427e0fca84c25515a4802d/src/Sylius/Bundle/AdminBundle/Resources/config/routing/order.yml#L98

```diff
    --- path: /{id}/ship
    +++ path: /orders/{id}/ship
```

Otherwise you will get routes like this
image

### PR DESCRIPTION
**Pull request by jakubtobiasz**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.12                  |
| Bug fix?        | yes (as defined in the issue)                                |
| New feature?    | no                                                       |
| BC breaks?      | no                                                       |
| Deprecations?   | no |
| Related tickets | fixes #12225, successor of #13237                      |
| License         | MIT                                                          |

Previous PR had more changes than needed. I'm opening a new one as I couldn't push the changes 🤷🏼‍♂️.

### CODE REVIEW

**Review by NoResponseMate — APPROVED** [review]

**Review by diimpp — APPROVED** [review]

**Review by GSadee — COMMENTED** [review]
It is not a BC break according to our BC Promise, but I would be in favour of adding a note to the UPGRADE file about this fix

**Comment by jakubtobiasz** [comment]
@GSadee check now 🤔

**Review by coldic3 — APPROVED** [review]

**Comment by GSadee** [comment]
I know, that I commented several days ago with the suggestion of a note, but I still have doubts about this PR. As I wrote, this change is not a BC break according to our BC Promise, however, it can break end applications if someone does not use routing generation, but uses the path.
IMO, the best solution would be to create new routes and change the problematic ones to be deprecated aliases, ref.: https://symfony.com/doc/current/routing.html#deprecating-route-aliases
Wdyt?

**Comment by diimpp** [comment]
> I know, that I commented several days ago with the suggestion of a note, but I still have doubts about this PR. As I wrote, this change is not a BC break according to our BC Promise, however, it can break end applications if someone does not use routing generation, but uses the path. IMO, the best solution would be to create new routes and change the problematic ones to be deprecated aliases, ref.: https://symfony.com/doc/current/routing.html#deprecating-route-aliases Wdyt?

They only allow to deprecate `alias` (route name, not path) and not a real route, while we're changing route path without changing route name. There is no mechanic for proper route deprecation as far as I know.

If it's not covered by BC, then `upgrade` note is more than enough, imo. Both those buttons are covered with csrf, there shouldn't be random users of them.

**Comment by jakubtobiasz** [comment]
@GSadee we can't fix every case when somebody follows the bad practices. If somebody uses the path instead of generating it, then it's a problem on its side, not our 🤷🏼‍♂️.

**Review by GSadee — APPROVED** [review]

**Comment by GSadee** [comment]
Thank you, Jakub! :tada:

**Pull request merged**
