### PR TITLE
[Shop] Enable customization of body classes

### PR DESCRIPTION
**Pull request by loic425**
| Q               | A
|-----------------|-----
| Branch?         | 2.0
| Bug fix?        | no
| New feature?    | DX
| BC breaks?      | no
| Deprecations?   | no
| Related tickets |
| License         | MIT

I've tried with a "bg_primary" template
```yaml
sylius_twig_hooks:
    hooks:
        'sylius_shop.base#body_classes':
            bg_primary:
                template: '@SyliusShop/shared/layout/base/body_classes/bg_primary.html.twig'
                priority: 0          
```

Capture d’écran du 2024-11-05 15-40-53

### CODE REVIEW

**Review by GSadee — DISMISSED** [review]

**Comment by kulczy** [comment]
I don't see the point in breaking it down into twigs per class. Wouldn't it be better to make one 'classes' file?

**Comment by loic425** [comment]
> I don't see the point in breaking it down into twigs per class. Wouldn't it be better to make one 'classes' file?

Yeah, maybe with "default" and then you will be able to remove all the default classes, or adding ones.

**Comment by loic425** [comment]
@kulczy Do you prefer like this?

**Comment by kulczy** [comment]
yes, imo better, thanks!

**Review by kulczy — APPROVED** [review]

**Review by GSadee — APPROVED** [review]

**Pull request merged**
