### PR TITLE
[TaxonomyBundle] Form registration, missing specs and CS

### PR DESCRIPTION
**Pull request by aRn0D**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | refactoring 
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | no
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by aRn0D** [comment]
it needs #2824 (last variation fixes)

**Comment by aRn0D** [comment]
@pjedrzejewski rebased, let's see the build

**Comment by michalmarcinkowski** [comment]
@aRn0D Not passing, because of short array syntax :) PHP 5.4 is on it's way, just remember about that for a few more days :smile:

**Comment by aRn0D** [comment]
That syntax will kill me :'( !

**Comment by aRn0D** [comment]
@pjedrzejewski green !

**Comment by pjedrzejewski** [comment]
Thanks Arnaud! :+1:

**Pull request merged**
