### PR TITLE
Fix event deprecations

### PR DESCRIPTION
**Pull request by loic425**
| Q               | A
| --------------- | -----
| Branch?         | master
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | partially #10928 
| License         | MIT

### CODE REVIEW

**Comment by loic425** [comment]
@pamil I will add some event deprecations on UserController this week.

**Comment by loic425** [comment]
@pamil I made all the changes I wanted to do (on UserController). It's now ready to review.

**Review by pamil — APPROVED** [review]

**Comment by pamil** [comment]
Thank you, Loïc! :1st_place_medal:

**Comment by loic425** [comment]
@pamil I'm glad you approved without any changes cause it's in our Monofony fork of the UserBundle 😄 (in order to support Symfony 5)

**Pull request merged**
