### PR TITLE
leverage render_label option in taxonomy forms

### PR DESCRIPTION
**Pull request by MichaelKubovic**

### CODE REVIEW

**Comment by aRn0D** [comment]
ping @MichaelKubovic

**Comment by pjedrzejewski** [comment]
Ping @MichaelKubovic, requires a rebase.

**Comment by michalmarcinkowski** [comment]
@MichaelKubovic are you willing to rebase this?

**Comment by MichaelKubovic** [comment]
Sorry for the late reply, in master, the render_label is default to true, so I've rebased and resolved conflict so that label is displayed by default.

**Comment by pjedrzejewski** [comment]
@MichaelKubovic You need to update the specs. :) Thanks!

**Comment by michalmarcinkowski** [comment]
Depricated.

**Pull request closed without merging**
