### PR TITLE
[BEHAT] Injecting locale parameter instead of having it harcdoded

### LINKED ISSUE #11117: [Behat] Hardcoded en_US at product transformer
**Sylius version affected**: any

**Description**  
When someone try to create Behat tests for app that have non-US default locale,
and use product transformer - it failing as `en_US` hardcoded at context.

```
Fatal error: 0 products has been found with name "Socks". (Behat\Testwork\Call\Exception\FatalThrowableError)
```

**Steps to reproduce**  
Set non-US `%locale%` parameter.

**Possible Solution**  
Pass `%locale%` to Behat product transformer

Part of / related: #11092

### LINKED ISSUE #11701: [Behat] Hardcoded en_US at taxon transformer
**Sylius version affected**: any

**Description**  
When someone try to create Behat tests for app that have non-US default locale,
and use taxon transformer - it failing as `en_US` hardcoded at context.

```
Fatal error: 0 taxons has been found with name "Products". (Behat\Testwork\Call\Exception\FatalThrowableError)
```

**Steps to reproduce**  
Set non-US %locale% parameter.

**Possible Solution**  
Pass %locale% to Behat taxon transformer

Related to #11117

### PR DESCRIPTION
**Pull request by Roshyo**
| Q               | A
| --------------- | -----
| Branch?         | 1.7
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #11701 
| License         | MIT

### CODE REVIEW

**Comment by Roshyo** [comment]
I don't think that behat scenario are failing because of my change. Or are they ?

**Comment by Zales0123** [comment]
Should be fixed after https://github.com/Sylius/Sylius/pull/11710, just need to be rebased :)

**Comment by Roshyo** [comment]
@Zales0123 could you check it now ? :)

**Comment by lchrusciel** [comment]
Thanks, Stephane! :1st_place_medal:

**Pull request merged**
