### PR TITLE
Keep it consistent with simple quotes

### PR DESCRIPTION
**Pull request by jacquesbh**
| Q               | A
| --------------- | -----
| Branch?         | master
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets |
| License         | MIT

Nothing big… The whole file is using simple quotes, so I changed these 4 double quotes.

Code quality comes from small changes.

### CODE REVIEW

**Comment by jacquesbh** [comment]
Actually I didn't think of hacktoberfest. This PR can be marked as spam and merged anyway, I don't care :-).

**Comment by Zales0123** [comment]
Targeting consistency is never a spam @jacquesbh 😄 🖖

**Review by Zales0123 — APPROVED** [review]

**Comment by Zales0123** [comment]
Thanks, Jacques! :1st_place_medal:

**Comment by vvasiloi** [comment]
@Zales0123 what do you think about having a linter for it?
Symfony's `lint:yaml` command only checks if the syntax is valid.
Found these on the internet: https://github.com/adrienverge/yamllint and https://github.com/stoplightio/spectral
Also remembered https://github.com/sspooky13/yaml-standards from https://github.com/Sylius/Sylius/pull/10943.

**Comment by Zales0123** [comment]
@vvasiloi automatization is the thing I admire the most 🖖 I would totally consider it 🚀

**Pull request merged**
