### PR TITLE
[Storage] Added constuctor and removed setRequest method from CookieStorage

### PR DESCRIPTION
**Pull request by NeverResponse**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
@NeverResponse Could you elaborate on this change? I think I missed the discussion in the office. :) IIRC the reason we have the setter is that Request was set here via listener, not container. (because of container scopes)

**Comment by pjedrzejewski** [comment]
Of course, constructor injection > setter injection (evil), so I am in favor of this change, let's just clarify it for everyone and make sure it works. :)

**Comment by pamil** [comment]
IMHO we should use [`RequestStack`](http://symfony.com/blog/new-in-symfony-2-4-the-request-stack).

**Comment by stloyd** [comment]
This code was done for Symfony `2.3` which didn't have `RequestStack` & required to use "dirty hacks"... Yes it should use that `RequestStack` & still it will be broken probably, see PR.

**Comment by pjedrzejewski** [comment]
@stloyd Which PR? :+1: about using RequestStack.

**Comment by stloyd** [comment]
@pjedrzejewski #3437

**Comment by michalmarcinkowski** [comment]
@NeverResponse why closing this?

**Pull request closed without merging**
