### PR TITLE
Gitignore webserver pid files

### LINKED ISSUE #8681: Improve gitignore by ignoring webserver pid files
Since [Symfony 3.3, the built in server is creating some pid files in the current folder of the app](http://symfony.com/blog/new-in-symfony-3-3-webserverbundle). Imho, this file should be gitignored.

### PR DESCRIPTION
**Pull request by gabiudrescu**
| Q               | A
| --------------- | ---
| Bug fix?        | no |
| New feature?    | no |
| BC breaks?      | no |
| Related tickets | fixes #8681  |
| License         | MIT |

### CODE REVIEW

**Comment by lchrusciel** [comment]
Thanks Gabi! 👍

**Comment by pamil** [comment]
It should rather get merged to `1.0` branch :/

**Comment by gabiudrescu** [comment]
@pamil how do you plan to handle git flow, now that 1.0 was tagged?

**Comment by lchrusciel** [comment]
Sorry, my bad. Should I cherry-pick it to `1.0` or you want to do it?

**Comment by gabiudrescu** [comment]
@lchrusciel my git-fu goes only this far: https://github.com/Sylius/Sylius/pull/8686

**Comment by lchrusciel** [comment]
@gabiudrescu we will handle it. If we would merge your PR there could be some conflicts. I just forgot to change the branch.

**Pull request merged**
