### PR TITLE
Add support for guzzle 7

### PR DESCRIPTION
**Pull request by lruozzi9**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.12 |
| Bug fix?        | no                                                      |
| New feature?    | no                                                      |
| BC breaks?      | no                                                      |
| Deprecations?   | no |
| Related tickets |                       |
| License         | MIT                                                          |

### CODE REVIEW

**Comment by braisdesousa** [comment]
How far is this Support to happend? I have a project which is getting quite old and unmaintaned because cannot update to Guzzle7.

**Comment by kayue** [comment]
Would like to see this as well, since guzzle 6 aren't supported in PHP 8 any more

**Comment by jakubtobiasz** [comment]
Hi @lruozzi9!

It's a great idea! While discussing over this PR, we noticed there are changes in the services declarations.
```
        <service id="sylius.payum.guzzle_http.client" class="GuzzleHttp\Client" public="false" />

        <service id="sylius.payum.guzzle.http_client" class="Payum\Core\Bridge\Guzzle\HttpClient">
            <argument type="service" id="sylius.payum.guzzle_http.client"/>
        </service>

        <service id="sylius.payum.http_client" alias="sylius.payum.guzzle.http_client"/>
```

This is considered as breaking change, and we can't merge it in this form. If there's no way to preserve the old declarations, we can create a configuration like this:
```
<bundle_config_key>:
    use_legacy_guzzle: true
```

or something like that. Would you like to make the proper changes :)? If you require any further assistance, just let me know, I'll try my best to help you deliver this PR.

**Comment by lruozzi9** [comment]
Hi @jakubtobiasz! It has been a long time, so I don't remember much, but if I'm not wrong the `Payum\Core\Bridge\Guzzle\HttpClient` should implement `Payum\Core\HttpClientInterface`. So it should not be a BC, but I have to put the mind again on it 😄.

**Comment by UlrichHP** [comment]
Hey,
is there any news on this guzzle 7 update ?

**Comment by jakubtobiasz** [comment]
Hello guys,

Thank you for your patience, but we have a solution. @coldic3 introduces PSR-18 support in #14919. I talked to him, and it seems it'll be easy to add the version 7 support on top of his PR. So, once #14919 merged, we'll add Guzzle 7 support.

But the support for this version will be available starting with the version `1.13` as we bump dependencies only in major and minor releases.

I'll close this PR once the proper changes appear in `1.13` :).

**Comment by jakubtobiasz** [comment]
Hi everyone!
As I said, support for Guzzle 7 will be delivered with Sylius `1.13` (#14919) :).

**Pull request closed without merging**
