### PR TITLE
[Promotion] Basic gift card promotion support

### PR DESCRIPTION
**Pull request by stloyd**
Three screenshots:
screenshot
screenshot
screenshot

TODO:
- [x] add migration script,
- [x] add section in user account about used gift cards/coupons(?),
- [x] extend fixtures

### CODE REVIEW

**Comment by stloyd** [comment]
@pjedrzejewski @aRn0D Feedback?

**Comment by stloyd** [comment]
@pjedrzejewski @aRn0D Can we get review in close future? :)

**Comment by pjedrzejewski** [comment]
It's not a priority atm, but I will try to look at this as soon as we deal with other things. Thanks! :)

**Comment by ruibinyang** [comment]
how long can I use this bundle?

**Pull request closed without merging**
