### PR TITLE
Twig "sameas" replaced by "same as"

### PR DESCRIPTION
**Pull request by martijngastkemper**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | yes
| Related tickets | none
| License         | MIT
| Doc PR          | Sylius/Sylius-Docs#X

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
@martijngastkemper Could you squash your commits, please? Thanks! 1 will be enough for such small (but important) change. :)

**Comment by martijngastkemper** [comment]
@pjedrzejewski I tried to squash the commits, but I made a mistake.

**Comment by pjedrzejewski** [comment]
@martijngastkemper No worries, looks good now! Let's wait for the build.

**Comment by michalmarcinkowski** [comment]
Thanks Martijn! :+1:

**Pull request merged**
