### PR TITLE
Update locales.rst

### PR DESCRIPTION
**Pull request by davidangel**
| Q               | A
| --------------- | ---
| Bug fix?        | no |
| New feature?    | no|
| BC breaks?      | no|
| Related tickets | mentioned in #7069 |
| License         | MIT |

Clarify that multiple locales are assigned to channels.

### CODE REVIEW

**Comment by TheMadeleine** [comment]
Istead of what you have proposed here I would go for a note at the beginning of this file:
```
.. note:: 
    
    In order to add a new locale to your store you have to assign it to a channel.
```

**Comment by TheMadeleine** [comment]
Okay, great :) 

One more thing to do in this PR. It is just a one change in one file. Therefore it should be one commit instead of 4. Can you squash them into 1? :)

**Comment by pjedrzejewski** [comment]
@davidangel If you will have trouble with squashing, I can do it during the merge, but you definitely need to do a rebase because of conflicts, thank you! :)

**Comment by pjedrzejewski** [comment]
Thanks David! :)

**Pull request merged**
