### PR TITLE
[ResourceBundle] check translations are possible before configuration them

### PR DESCRIPTION
**Pull request by bendavies**
I am not using translations in my application, and an error is thrown here as I've not configured translations for my resources.
This was introduced by https://github.com/Sylius/Sylius/pull/3721.

Also, it seems it is not not possible to disable translations per resource, see [here](https://github.com/Sylius/Sylius/pull/3721/files#r48045552).

### CODE REVIEW

**Comment by bendavies** [comment]
just noticed this is related to https://github.com/Sylius/Sylius/issues/3748

**Comment by liverbool** [comment]
I thinks it's not comprehensive fix as you said 

> **"it seems it is not not possible to disable translations per resource"**

It still can't disable translation per resource.

**Comment by bendavies** [comment]
yes there are 2 issues here.
1. translations should not be mandatory (not fixed here)
2. don't try to configure translations at all if the Translation bundle is not available

**Comment by pjedrzejewski** [comment]
Sounds good until we figure out what to do with coupling. :) Thank you very much Ben! :+1:

**Comment by bendavies** [comment]
thanks @pjedrzejewski

**Comment by pjedrzejewski** [comment]
@bendavies Let me know what do you think in #3750.

**Pull request merged**
