### PR TITLE
correct payum version constraints for SyliusPayumBundle

### PR DESCRIPTION
**Pull request by videni**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| License         | MIT

### CODE REVIEW

**Comment by videni** [comment]
I checkout Travis report, the reason why it is failed,  it might be   it should execute `composer update` before `composer install`, for the version constraints is changed.

**Comment by michalmarcinkowski** [comment]
You should run `composer update payum/payum payum/payum-bundle` yourself. It will update the `composer.lock` file and the Travis will install proper versions.

**Comment by pamil** [comment]
@michalmarcinkowski we ignore `composer.lock` files from packages, so it won't have any effect.

@videni it looks like some package is missing, both `composer install` / `composer update` say so (btw. `composer install` without `composer.lock` file should work exactly as `composer update` - if not, that's an issue for Composer):

screen shot 2016-06-17 at 10 26 03

**Comment by pamil** [comment]
All right, it seems like `php-http/client-implementation` is a virtual package, we should add some package that implements it to `require`. For main `Sylius/Sylius` we use `"php-http/guzzle6-adapter": "^1.1"`.

**Comment by michalmarcinkowski** [comment]
@pamil I didn't notice it's a PayumBundle's composer.json :)

**Comment by videni** [comment]
Please merge this into master, or we can't update  dependencies, composer will complain this error
> [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]    
    Unrecognized option "factory" under "payum.gateways.offline"

**Comment by michalmarcinkowski** [comment]
@videni could you rebase?

**Comment by videni** [comment]
@michalmarcinkowski , this commit is  rebased  ,please check this branch again.

**Comment by michalmarcinkowski** [comment]
Thanks! 👍

**Pull request merged**
