### PR TITLE
Added LazyCustomerLoader for OrderType of SyliusAdminApiBundle

### LINKED ISSUE #8776: Creating cart via REST API takes long time
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.0

It occurs when you have a lot of customers in your database. 

The proble is due that the ```Sylius\Bundle\AdminApiBundle\Form\Type\OrderType``` uses for customer the ```Sylius\Bundle\CustomerBundle\Form\Type\CustomerChoiceType``` type and therefore it loads all customers leading to out of memory problem.

To clarify I'm speaking form the API call explained in the docs http://docs.sylius.org/en/latest/api/carts.html#creating-a-cart

```
curl http://demo.sylius.org/api/v1/carts/ \
    -H "Authorization: Bearer SampleToken" \
    -H "Content-Type: application/json" \
    -X POST \
    --data '
        {
            "customer": "shop@example.com",
            "channel": "US_WEB",
            "localeCode": "en_US"
        }
```

### PR DESCRIPTION
**Pull request by jdeveloper**
| Q               | A
| --------------- | -----
| Branch?         | 1.0.5
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #8776, mentioned in #8815 
| License         | MIT

### CODE REVIEW

**Comment by jdeveloper** [comment]
phpunit tests don't pass. I also tried in master and the even don't pass in this branch

**Comment by jdeveloper** [comment]
It was my fault. Just pushed before passing phpunit tests. Had just passed phpspec. Fixed an issue with the loader.

**Comment by Chrysweel** [comment]
@pamil @jdeveloper this pull request will accepted in some time ?

We have the same problem...

**Comment by pamil** [comment]
I'm on it, sorry for the delay!

**Comment by jdeveloper** [comment]
Hello, I am asking once again for the state of this PR since I think it's a clear improve when there are a lot of users in the database.

I have no problem to change implementation if you think it 's not a valid one.

Thanks in advance.

**Comment by jdeveloper** [comment]
@pamil Sorry for asking this one more time

Is this PR to be considered? I once again need to creat by REST a cart and it just creates a timeout with a large customer table.

I have no regards to take some time to adapt, improve the code

**Comment by jdeveloper** [comment]
Hi @pamil 

Sorry for asking once again but we have a database with more then 200 k customers and we want to use the sylius API without deppending on SyliusShopApiPlugin. It is imposible to create a cart without this PR.

It would be nice to review this PR, I think it is also a benefit for other developers. If we have to make changes on this PR just comment them and we will work on them.

**Comment by lchrusciel** [comment]
Hey @jdeveloper,

It took too long to provide you some feedback here. We all are humans, and sometimes we tend to forget or miss something. When you asked for a review, we (as a core team) had too much on our heads. 

I will ping @CoderMaggie to add this issue to our sprints. Therefore someone should take a look over it in the nearest sprint (if it only will fit into backlog). Please, ping me one more time if it won't be resolved during the next month.

Thank you for your patience.

**Comment by jdeveloper** [comment]
Hey @lchrusciel,

Thanks for replying. Don't worry, we understand that we are all humans and with such a huge project like Sylius, things can quickly go out of control. We appreciate your reply to an old issue.

As always, if we have to work in some issue around this PR, just ping me.

Thank you for your attention.

**Comment by jdeveloper** [comment]
Hi @lchrusciel 

I just wonder about the state of this PR. As you said to ping you if I got sign on this PR in a month here I am just pinging you to look if we can solve this together. I think it can benefit a lot of people and shops that have a lot of customers and want to integrate through REST API.

Have a nice time.

**Comment by lchrusciel** [comment]
As a part of the work over this PR, I've decided to make some profiling. @jdeveloper proposition reduced the time of execution by 62%, but this change may be much greater for a bigger set of data.
image

You can check the complete profile [here](https://blackfire.io/profiles/compare/3ba8ea6b-f181-4e2c-ba5d-3082ebec954d/graph). 
Data was collected on my local machine, with a set of 10k customers in DB.

The current solution assumes that customers are not loaded to choice type, which makes sense because it is used only in the Admin API Context. To make this choice type usable for the twig based templates, we should introduce Autocomplete Form Type. On the other hand, this form type wouldn't be used anywhere in current Sylius implementation. It is tested already with cart creation endpoint in Admin API. 

Therefore, it could be improved in the future, but I think that the current solution is good to go.

I'm also considering writing an ADR for this feature, not to lose track of it. (/cc @Sylius/core-team )

**Comment by pamil** [comment]
Thanks, @jdeveloper! :1st_place_medal:

**Comment by Chrysweel** [comment]
giphy

**Comment by Krleza** [comment]
señorordena

**Comment by jdeveloper** [comment]
WoW I'm so happy to see this merged. Thanks a lot. It's a great pleasure being able to contribute.

**Comment by pamil** [comment]
Hope things will go more smoothly in the future, thanks for your patience 💯

**Pull request merged**
