### PR TITLE
Fixed a typo in docs

### PR DESCRIPTION
**Pull request by dborsatto**
| Q               | A
| --------------- | -----
| Branch?         | 1.0
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | none
| License         | MIT

### CODE REVIEW

**Comment by CoderMaggie** [comment]
Hi @dborsatto, really nice to have you there as a contributor.
Unfortunately your PR should be opened to `1.0` instead of `master`, that is why I've changed your base branch, and you need to **do a rebase to** `1.0`. ;)

**Comment by dborsatto** [comment]
Will do, thanks!

**Comment by dborsatto** [comment]
Should be fine now 🙂

**Comment by CoderMaggie** [comment]
Thank you Davide, and welcome to Sylius contributors! 🎊

**Pull request merged**
