### PR TITLE
[RFC] Make `sylius_` table prefix configurable

### LINKED ISSUE #61: [Enhancement] Consider removing all `sylius_` database tables prefix
Once there is no way (at least a simple way) to override the DB's tables/repositories names, I think the `sylius_` prefix should be removed. If a prefix is desirable, it can be solved using a listener that can be disabled.

### PR DESCRIPTION
**Pull request by stloyd**
Fix #61.

### CODE REVIEW

**Comment by igorpan** [comment]
The problem with this is that even if you do extend Sylius Entities in your App, join table names are prefixed with `sylius_`

So if you have `Product extends SyliusProduct` and `Option extends SyliusOption` you will still have a join table named `syllabus_product_option`.

**Comment by steffenbrem** [comment]
I like this PR :+1:  Should be re-opened.

**Comment by Bonobomagno** [comment]
any news about table prefix?

**Comment by pamil** [comment]
This feature could include some side effects that wouldn't be caught in Sylius itself, but in projects relying on Sylius - see @igorpan comments. Also, it would make our migrations unusable after the prefix is changed.

**Comment by Bonobomagno** [comment]
i know, that's why a prefix indipendent update is needed. or at least a default prefix-removable variant.
say something like syliusprefix_ so we can easly refactor that word without sideeffect

**Comment by Bonobomagno** [comment]
What about using doctrine prefix?
https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/cookbook/sql-table-prefixes.html
do database would break mantaining the old prefix, but new one would use a free prefix. 

For the migration using parameter is enought. ofc "sylius_" would be still the default. 
No BC and everyone is happy.
 This becouse i don't think that someone will use a licenced name in own db, at least this simplify the work.

**Comment by pamil** [comment]
@Bonobomagno what's your use case?

**Pull request closed without merging**
