### PR TITLE
[Admin] Improve the variant generation form UI

### PR DESCRIPTION
**Pull request by pjedrzejewski**
| Q               | A
| --------------- | ---
| Bug fix?        | no |
| New feature?    | no |
| BC breaks?      | no |
| Related tickets | - |
| License         | MIT |

Before & after:

screen shot 2017-09-08 at 15 15 08
screen shot 2017-09-08 at 15 17 58

### CODE REVIEW

**Comment by stefandoorn** [comment]
Two screenshots weren't enough @Zales0123 ? 📦

**Comment by Zales0123** [comment]
I'm just blind, leave me alone 😄

**Comment by pjedrzejewski** [comment]
@Zales0123 I am very happy to help you fix your ecomerce script.

**Comment by pamil** [comment]
Thanks Paweł! 🥇

**Pull request merged**
