### PR TITLE
[Maintenance] Make all API Bundle services public and unify public notation

### PR DESCRIPTION
**Pull request by lchrusciel**
| Q               | A
| --------------- | -----
| Branch?         | master
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| License         | MIT

### CODE REVIEW

**Comment by stloyd** [comment]
Hmmmmmmm, will all the DI autowiring etc. why such change? It's against best practices of Symfony IIRC.

**Comment by Arminek** [comment]
@lchrusciel Could you give more background on why we want to have this?

**Comment by lchrusciel** [comment]
Hey @stloyd & @Arminek.

You are right, this PR is against Symfony Best practices. However, our internal rule is to make all services public, due to Sylius Resource Controller and testing with PHPUnit for example. In all these scenarios we are fetching services directly from the container. In the resource controller, the services are fetched to perform regular logic. In the case of PHPUnit, I just had a failing test at #12968. IIRC, Behat also requires us to have public services, but I'm not 100% sure about it. 

These changes should make us coherent with something, that we introduced in #9366. All our services should be public by default, unless we will write a new ADR

**Review by Arminek — APPROVED** [review]

**Review by GSadee — APPROVED** [review]

**Comment by GSadee** [comment]
Thank you, Łukasz! :tada:

**Pull request merged**
