### PR TITLE
Minor shipment factory update

### PR DESCRIPTION
**Pull request by umpirsky**
I just didn't like comparing like `if (!$shipment)`.

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| License       | MIT

### CODE REVIEW

**Comment by aRn0D** [comment]
:+1:

**Comment by pjedrzejewski** [comment]
Please update specs. :)

**Comment by umpirsky** [comment]
@pjedrzejewski Oh, done! :)

**Comment by aRn0D** [comment]
@umpirsky thanks !

**Pull request merged**
