### PR TITLE
Removed data transformer call in EntityHiddenType

### PR DESCRIPTION
**Pull request by rpg600**
The entity_hidden form type was broken due to PR #3406.

### CODE REVIEW

**Comment by rpg600** [comment]
Another thing came to my mind : i'm not 100% sure but i think that the `data_class` option should not be used in the EntityHiddenType : it need to stay null, otherwise the symfony Form class will compare the view data (which is a scalar due to the `ObjectToIdentifierTransformer`) and the data_class then will throw an exception because it expects the view data as an instance of data_class : https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Form/Form.php#L373

**Comment by pjedrzejewski** [comment]
@rpg600 Could you rebase this PR, please? Thanks! Or let us know if you miss the time to work on this.

**Comment by rpg600** [comment]
Rebased.

**Comment by michalmarcinkowski** [comment]
Should be fixed in #3831

**Comment by michalmarcinkowski** [comment]
There is no `Sylius/Bundle/ResourceBundle/Form/Type/EntityHiddenType` class anymore.

**Pull request closed without merging**
