### PR TITLE
Set default driver in bundle configuration

### PR DESCRIPTION
**Pull request by mtthb**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #2509 
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by aRn0D** [comment]
:+1:

**Comment by amenophis** [comment]
@mtthb Why not a protected method registerDefautConfiguration() in SyliusResourceBundle instead of duplicate it in each bundle ? For now, the config concern only one parameters, but maybe some configuration will come later.

**Comment by amenophis** [comment]
but :+1: for the unification of this !

**Comment by mtthb** [comment]
@amenophis You got me there, it's rather a quick and dirty patch. A registerDefaultConfiguration would definitely be a better option.

**Comment by aRn0D** [comment]
I am agree, A PR has been started #1921

**Comment by pjedrzejewski** [comment]
Thanks Matthieu!

**Pull request merged**
