### PR TITLE
[Resource] Remove layout.html.twig

### PR DESCRIPTION
**Pull request by lchrusciel**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | yes
| Related tickets | resolves #6519
| License         | MIT

Based on #6524

### CODE REVIEW

**Comment by lchrusciel** [comment]
@pamil I found it more appropriate to add this requirement, because we are using this bundle in several places. Just for consistency. 

Anyway, is there any reason, why we are still keeping templates in ResourceBundle?

**Comment by pamil** [comment]
@lchrusciel still, there's no need for downloading many more packages for someone using only ResourceBundle. I guess the whole `layout.html.twig` template can be deleted.

**Comment by lchrusciel** [comment]
@pamil I can agree with that. Removing layout.html.twig will be the best solution.

**Comment by pjedrzejewski** [comment]
Thank you Łukasz!

**Pull request merged**
