### PR TITLE
[Docs] Change the template path in customization

### LINKED ISSUE #13508: [Docs][Plugin] Overriding template path
As pointed out here: https://sylius-devs.slack.com/archives/C3E4EBKUZ/p1642570918002300

The path in the documentation about overriding a template is wrong.

It currently is `tests/Application/templates/SyliusAdminBundle/`
It should be `tests/Application/templates/bundles/SyliusAdminBundle/`

### PR DESCRIPTION
**Pull request by Roshyo**
| Q               | A
| --------------- | -----
| Branch?         | 1.11
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #13508 
| License         | MIT

### CODE REVIEW

**Review by CoderMaggie — APPROVED** [review]

**Comment by CoderMaggie** [comment]
Doesn't the issue also occur in lower versions (1.10)?

**Comment by Roshyo** [comment]
Yes it does. Should this branch target 1.10 ? I'm never sure about what is the target branch :D

**Comment by lchrusciel** [comment]
The base of this pull-request was changed, you need fetch and reset your local branch 
if you want to add new commits to this pull request. **Reset before you pull, else commits
may become messed-up.**

Unless you added new commits (to this branch) locally that you did not push yet, 
execute `git fetch origin && git reset "fix-customization-documentation-templat-path"` to update your local branch.
 
Feel free to ask for assistance when you get stuck :+1:

**Comment by lchrusciel** [comment]
Thank you, Stephane! :tada:

**Pull request merged**
