### PR TITLE
Prepare release v0.18.0

### PR DESCRIPTION
**Pull request by pjedrzejewski**

### CODE REVIEW

**Comment by peteward** [comment]
Please say you're going to merge https://github.com/Sylius/Sylius/pull/4768 before you remove the old admin?

**Comment by nakashu** [comment]
Couple suggestion what should be merged:
https://github.com/Sylius/Sylius/pull/5019
https://github.com/Sylius/Sylius/pull/4618

**Comment by pjedrzejewski** [comment]
@peteward Yes and I will also create 0.18 branch that will get most critical fixes when requested. The distribution is quite significant change, so there maybe some fixes coming.

@nakashu Thank you! Both merged. 👍

**Comment by loic425** [comment]
@pjedrzejewski  please merge #5075 :)

**Comment by pjedrzejewski** [comment]
@loic425 Done! ;)

**Comment by michalmarcinkowski** [comment]
We should also add info about the changes in promotions (#4768) in `UPGRADE.md`. /cc @Zales0123

**Comment by Zales0123** [comment]
@michalmarcinkowski 👍  https://github.com/Sylius/Sylius/pull/5078

**Comment by pamil** [comment]
Will #5080, #5081 and #5082 be included in 0.18? :tada:

**Comment by Zales0123** [comment]
#5083 Is also pretty important! 🌵

**Comment by lchrusciel** [comment]
Can't wait to have this crucial changes in a core!

**Comment by michalmarcinkowski** [comment]
Finally v0.18 💃

**Comment by pamil** [comment]
Let's drop the bass and PHP 5.5 :tada:

**Comment by okwinza** [comment]
Much congrats guys, keep up the awesome work!
Sylius FTW :+1:

**Pull request merged**
