### PR TITLE
[Core] Dropped support for Doctrine ORM 2.5

### PR DESCRIPTION
**Pull request by pamil**
See #3775 for reasoning behind this change.
Reverts #3726.

### CODE REVIEW

**Comment by peteward** [comment]
Hi @pamil, what's actual problem with OutputWalkers and 2.5?

**Comment by pamil** [comment]
Hello Peter, I've just made an issue about that - #3836.

**Comment by pjedrzejewski** [comment]
Thank Kamil! :+1:

**Comment by bendavies** [comment]
`doctrine/orm` is referenced in many other `composer.json` files in sylius. Should you not make them consistent?

**Pull request merged**
