### PR TITLE
Add "akeneo/phpspec-skip-example-extension" dependency & fix broken specs

### PR DESCRIPTION
**Pull request by stloyd**
Before:
Before

After:
After

### CODE REVIEW

**Comment by michalmarcinkowski** [comment]
Already fixed in https://github.com/Sylius/Sylius/pull/3337

**Comment by stloyd** [comment]
@michalmarcinkowski Nope, this is not fully fixed, please compare PRs before closing...

**Comment by michalmarcinkowski** [comment]
Do not make irrelevant changes with relevant ones. Like:

* What is wrong with this line https://github.com/Sylius/Sylius/compare/master...stloyd:bugfix/phpspec#diff-e02e8f73786f6373e93576a3f80290e0R23?
* CS fixes - https://github.com/Sylius/Sylius/compare/master...stloyd:bugfix/phpspec#diff-2f2865b3defb8a22fd68469ed579a576R43

**Comment by stloyd** [comment]
@michalmarcinkowski First is totally correct as that phpspec extension __can't__ skip spec if PHP extension is __not__ loaded, and that spec will always fail if you don't have `intl` PHP extension loaded as default Symfony subs support __only__ english language!

Without that change you will get:
> Sylius/Bundle/MoneyBundle/Templating/Helper/MoneyHelper                              
  38  - it formats the integer amounts into string representation
      exception [exc:Symfony\Component\Intl\Exception\MethodArgumentValueNotImplementedException("The Symfony\Component\Intl\NumberFormatter\NumberFormatter::__construct() method's argument $locale value 'de_DE' behavior is not implemented. Only the locale "en" is supported.  Please install the "intl" extension for full localization capabilities.")] has been thrown.

> Sylius/Bundle/MoneyBundle/Templating/Helper/MoneyHelper                         
  46  - it allows to format money in different currencies
      exception [exc:Symfony\Component\Intl\Exception\MethodArgumentValueNotImplementedException("The Symfony\Component\Intl\NumberFormatter\NumberFormatter::__construct() method's argument $locale value 'de_DE' behavior is not implemented. Only the locale "en" is supported.  Please install the "intl" extension for full localization capabilities.")] has been thrown.

Second is just matter of approach, when I fix code, why should I not fix another issue that is in that file? With such approach you should "moan" in at least 50% of PRs being done :stuck_out_tongue_winking_eye:

**Comment by michalmarcinkowski** [comment]
You're right with the `intl`, I didn't realize it can cause a problem.

The problem with second is that it makes code compare less readable and confuses what is a real fix and what is just a CS or esthetic. 

E.g. It is hard to see if you just reordered specs like here https://github.com/Sylius/Sylius/pull/3357/files#diff-bdc3b250d685513f2ff47620755d6405R8 or removed it totaly like here https://github.com/Sylius/Sylius/pull/3357/files#diff-bdc3b250d685513f2ff47620755d6405L24.

**Comment by stloyd** [comment]
@michalmarcinkowski Yes, I know it makes a bit harder to read first time, but some time ago we done some work to sort it, and I see some PRs ignored that change and broke sorting, that was the reason for this change.

While removing was done for purpose as there is __no__ such components like `Settings`, `Payum` or `Installer` and this caused to create empty folders by phpspec which is wrong IMO.

**Comment by michalmarcinkowski** [comment]
@stloyd I agree that both changes are correct, but it's worth to at least mention it in the PR description to make the review easier.

**Comment by stloyd** [comment]
@michalmarcinkowski My bad, will try to give more details what's done if the purpose is not so obvious.

Can you check the new PR that fixes problems mentioned above?

**Pull request closed without merging**
