### PR TITLE
[RFC] Bring back doctrine 2.5 support

### PR DESCRIPTION
**Pull request by lchrusciel**
| Q               | A
| --------------- | ---
| Bug fix?        | yes (kind of)
| New feature?    | no
| BC breaks?      | yes
| Related tickets | unfixes #3836 (in fact, it is not really fixed right now too)
| License         | MIT

I have spent some time in order to find the best solution and bring back doctrine 2.5 support and this is my proposal. 

The second parameter of DoctrineORMAdapter defines if `fetchJoinCollection` variable. By default it is value is equal to true. According to [doctrine documentation](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/tutorials/pagination.html) it should behave like this:
```
Paginating Doctrine queries is not as simple as you might think in the beginning. If you have complex fetch-join scenarios with one-to-many or many-to-many associations using the “default” LIMIT functionality of database vendors is not sufficient to get the correct results.

By default the pagination extension does the following steps to compute the correct result:

 * Perform a Count query using DISTINCT keyword.
 * Perform a Limit Subquery with DISTINCT to find all ids of the entity in from on the current page.
 * Perform a WHERE IN query to get all results for the current page.

This behavior is only necessary if you actually fetch join a to-many collection. You can disable this behavior by setting the $fetchJoinCollection flag to false; in that case only 2 instead of the 3 queries described are executed. We hope to automate the detection for this in the future.
```

As far as we are using only a default locale to list product in backend, fetch join is not required. But using this solution on a shop side, where we should add a fallback translation, for the resources without current one, we will end up with `Schrodinger-queries` as was mentioned in #3836. :cat: 

Another possible solution is to use DoctrineORMOutputWalker, but as was written in #3775, it has a major impact on performance. Maybe using both of this solution would something considerable(this for admin and output walkers in shop), but it won't as trivial as it looks like.

Some further readings:
 - [Doctrine pagination](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/tutorials/pagination.html)
 - [Probable problem with proposed solution](http://stackoverflow.com/questions/5620771/limiting-a-doctrine-query-with-a-fetch-joined-collection)
 - [Doctrine join explanation](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/dql-doctrine-query-language.html#joins)

 [Expected problem with output walker](https://github.com/doctrine/doctrine2/issues/5622).

### CODE REVIEW

**Comment by pamil** [comment]
Rebase needed 🌮

**Comment by pamil** [comment]
Rebase needed once again :taco:

**Comment by lchrusciel** [comment]
@pamil done

**Comment by pjedrzejewski** [comment]
Thank you Łukasz!

**Comment by Aniade** [comment]
Hello @lchrusciel. 
I am wondering why you set fetch join collection to false for pagination in this [commit](https://github.com/Sylius/Sylius/pull/6674/commits/36afcd67c1f77ef4a11b5fd87beabd4d33b69ae2) ? I am writing a custom query builder for an index page and my pagination is broken because of joined collections.
Thank you :)

**Comment by LaetitiaRiffaud** [comment]
Hello @lchrusciel. 
I am wondering why you set fetch join collection to false for pagination in this [commit](https://github.com/Sylius/Sylius/pull/6674/commits/36afcd67c1f77ef4a11b5fd87beabd4d33b69ae2) ? I am writing a custom query builder for an index page and my pagination is broken because of joined collections.
Thank you :)

**Comment by lchrusciel** [comment]
Hello @LaetitiaRiffaud,
I have tried to be as precise as possible when describing this solution. Turning off fetch joins allowed us to build a proper query to the database. Otherwise, we had not enough results on index pages. Turning off the fetch joins allows us to use lazy loading for other translations if needed, but at the same time use properly `setMaxResults` functions. When we were using fetch joins, it was possible to have only 5 results on the index page with limit 10, if each of item had 2 translations.

**Comment by peteward** [comment]
Hi @lchrusciel,

I agree with @LaetitiaRiffaud here. 

We've just upgraded to the latest ResourceBundle and this broke our pagination on various pages with 1-to-many join queries.

The result that we see is incomplete lists. The example in front of me is listing Orders and showing the OrderItems in them.  e.g. If the pagination is set to 10, the first order has 3 items, all other orders have only a single item, the list will only show 7 orders.

You can see this from the crude queries that doctrine creates as a result, doing a simple `COUNT` and then a `LIMIT, OFFSET` combination which just won't work for any 1-to-n selects: 

```
SELECT 
  count(DISTINCT r0_.id) AS sclr_0 
FROM 
  reiss_order r0_ 
  INNER JOIN sylius_order_item s2_ ON r0_.id = s2_.order_id 
  INNER JOIN reiss_product_variant r4_ ON s2_.variant_id = r4_.id 
  INNER JOIN reiss_product r5_ ON r4_.product_id = r5_.id 
WHERE 
  r0_.completed_at >= ?
```
```
SELECT *
FROM 
  reiss_order r0_ 
  INNER JOIN sylius_order_item s2_ ON r0_.id = s2_.order_id 
  INNER JOIN reiss_product_variant r4_ ON s2_.variant_id = r4_.id 
  INNER JOIN reiss_product r5_ ON r4_.product_id = r5_.id 
WHERE 
  r0_.completed_at >= ? 
ORDER BY 
  r0_.completed_at DESC, 
LIMIT 
  10 OFFSET 0
```

Doctrine is going to select 10 database rows and if 3 of those rows correspond to a single order you're only going to get 7 entities hydrated (potentially some of them get split between pages too which is really wrong).   

What does work is setting the fetch join collection to true. This creates the following 3 queries COUNT, DISTINCT, then explicit SELECT by ids (as described in the docs):

```
SELECT 
  count(DISTINCT r0_.id) AS sclr_0 
FROM 
  reiss_order r0_ 
  INNER JOIN sylius_order_item s2_ ON r0_.id = s2_.order_id 
  INNER JOIN reiss_product_variant r4_ ON s2_.variant_id = r4_.id 
  INNER JOIN reiss_product r5_ ON r4_.product_id = r5_.id 
WHERE 
  r0_.completed_at >= ?
```

```
SELECT 
  DISTINCT r0_.id AS id_0, 
  r0_.completed_at AS completed_at_1, 
  r0_.updated_at AS updated_at_2 
FROM 
  reiss_order r0_ 
  INNER JOIN sylius_order_item s2_ ON r0_.id = s2_.order_id 
  INNER JOIN reiss_product_variant r4_ ON s2_.variant_id = r4_.id 
  INNER JOIN reiss_product r5_ ON r4_.product_id = r5_.id 
WHERE 
  r0_.completed_at >= ? 
ORDER BY 
  r0_.completed_at DESC, 
  r0_.updated_at DESC 
LIMIT 
  10 OFFSET 0
```

```
SELECT *
FROM 
  reiss_order r0_ 
  INNER JOIN sylius_order_item s2_ ON r0_.id = s2_.order_id 
  INNER JOIN reiss_product_variant r4_ ON s2_.variant_id = r4_.id 
  INNER JOIN reiss_product r5_ ON r4_.product_id = r5_.id 
WHERE 
  r0_.completed_at >= ? 
  AND r0_.id IN (['5380988', '5380987', '5380983', '5380986', '5380985', '5380984', '5380963', '5380939', '5380891', '5380894', '5380825', '5380807', '5380786', '5380798', '5380750', '5380735', '5380726', '5380705', '5380648', '5380633']) 
ORDER BY 
  r0_.completed_at DESC, 
  r0_.updated_at DESC, 
  s2_.id ASC
```

I've read through this PR a couple of times and it's not clear to me which situation you were trying to solve. I remember that the problem is complicated and there might not be a perfect solution.

However, this change has broken pagination lists that involve selecting data from multiple tables with a 1-to-n resultset. Whilst this is not the most efficient way to write queries (we try to use `PARTIAL`s where necessary to mitigate this), it is probably still more efficient than hammering the database with lots of lazy-load single selects. As soon as you start using lazy-load in large lists of data you're asking for trouble in the number of queries called and can create strain on your DB.

We're going to revert this change in our project, but it would be interesting to know what the thinking was and if there's another approach that could be used.

**Comment by peteward** [comment]
ping

**Comment by lchrusciel** [comment]
Hello @peteward,

It was a while since I have made this change. But AFAIR, the problem was same as you described it but in a matter of locales. If resources had 2 translation on paginated pages we had only half of expected items. After this change, I have checked a web profiler but execution time and a number of queries actually have been reduced. Still, we are testing Sylius usually on a small amount of data, but @pamil has made some performance tests with Gatlling and it was fine. 

I'm open for any other solution, we can also just revert this change and see what will break(if anything). 
I have also discussed this problem briefly with Ocramius, and his recommendation was to create a custom paginator.

**Comment by peteward** [comment]
Hi @lchrusciel,

Reviewing the issues behind this, it does appear to come back to this one: https://github.com/Sylius/Sylius/issues/3836. I think this change inadvertently works around this issue but I don't think it's the correct solution and it has the adverse affect of breaking what I believe to be a more common use-case.

I'm not really sure how this solves the above issue though. It will run 1 less query, but it gets the wrong result with selected joins.

I think this issue needs to be revisited and consider various use-cases.

**Comment by lchrusciel** [comment]
@peteward I have reverted this change in #8038 PR and we can see what will be affected.

I don't have time to dig into it atm, but maybe somebody will be able to tackle it.

**Comment by peteward** [comment]
Thanks @lchrusciel.

Hopefully this is the last we'll hear of this but I suspect not! :)

**Pull request merged**
