### PR TITLE
Update 0.15 changelog

### PR DESCRIPTION
**Pull request by umpirsky**
I will be adding more updates to this PR if I find them during my update.

### CODE REVIEW

**Comment by michalmarcinkowski** [comment]
Great! Thanks Sasa :+1:

**Comment by pjedrzejewski** [comment]
Ping @umpirsky.

**Comment by umpirsky** [comment]
@pjedrzejewski Rebased, if that's what ping was for. :)

**Comment by pjedrzejewski** [comment]
Not perfect but generated changelog is easier to maintain and we should focus on the ``UPGRADE.md`` file.

**Pull request closed without merging**
