### PR TITLE
[Shop] Fix password request & contact pages with a mobile view.

### PR DESCRIPTION
**Pull request by versgui**
| Q               | A
| --------------- | -----
| Branch?         | 1.3
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| License         | MIT

Fix a small issue on the password request and contact pages, with a mobile view.

46560774-3f56dc80-c8f5-11e8-8322-b0c8197143f4

### CODE REVIEW

**Comment by versgui** [comment]
@Zales0123 Of course :)
I added a "stackable" CSS Class so the content is wide on mobile.

After the fix :
screenshot_2018-10-10 sylius

**Comment by Zales0123** [comment]
Could you please rebase to branch `1.2`? thanks :)

**Comment by pamil** [comment]
Rebased it so you don't have to :)

**Comment by pamil** [comment]
Thank you, Guillaume! 🥇

**Pull request merged**
