### PR TITLE
Make taxon comparable

### LINKED ISSUE #10797: Error: Nesting level too deep - recursive dependency For Taxon model
**Sylius version affected**: 1.6.1

**Description**  
We changed our taxon fixtures and now we are getting random `Error: Nesting level too deep - recursive dependency?" at /calida/shop/vendor/gedmo/doctrine-extensions/lib/Gedmo/Sortable/SortableListener.php line 471` errors. This happens when comparing two Taxon objects. 

**Steps to reproduce**  
This is the relevant fixture configuration we added
```yml
sylius_fixtures:
  suites:
    default:
      fixtures:
        taxon:
          options:
            custom:
              - name: root
                code: root
                translations:
                  en_US:
                    name: Root
                children:
                  - code: men
                    name: Men
                    slug: men
                    translations:
                      en_US:
                        name: Men
                    children:
                      - code: mens_jeans
                        name: Jeans
                        slug: men/jeans
                        translations:
                          en_us:
                            name: Jeans
                      - code: mens_tops
                        name: Tops
                        slug: men/tops
                        translations:
                          en_US:
                            name: Tops
                  - code: women
                    name: Women
                    slug: women
                    translations:
                      en_US:
                        name: Women
                    children:
                      - code: womens_jeans
                        name: Jeans
                        slug: women/jeans
                        translations:
                          en_US:
                            name: Jeans
                      - code: womens_tops
                        name: Tops
                        slug: women/tops
                        translations:
                          en_US:
                            name: Tops
                      - code: dresses
                        name: Dresses
                        slug: women/dresses
                        translations:
                          en_US:
                            name: Dresses
```

Obviously posting full reproducing example is hard, but this happens when hitting product edit endpoint and changing mainTaxon

**Possible Solution**  
Consider implementing `Doctrine\Common\Comparable` interface on your Taxon model to avoid weak comparison check.

### PR DESCRIPTION
**Pull request by oallain**
| Q               | A
| --------------- | -----
| Branch?         | 1.6
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #10797 
| License         | MIT

Is this good for you?
Do you think I should do the same for all resources (as said in the issue commands)?

### CODE REVIEW

**Comment by pamil** [comment]
The base of this pull-request was changed, you need fetch and reset your local branch 
if you want to add new commits to this pull request. **Reset before you pull, else commits
may become messed-up.**

Unless you added new commits (to this branch) locally that you did not push yet, 
execute `git fetch origin && git reset "doctrine-resources-comparable"` to update your local branch.
 
Feel free to ask for assistance when you get stuck :+1:

**Comment by pamil** [comment]
Thanks, @oallain! :tada:

**Comment by robgwin** [comment]
I've run into the same error when changing the position of existing variants. Pseudocode:

```
$product = productRepository->findOneBy(['code' => 'some_product']);
$variant = productVariantRepository->findOneBy(['code' => 'some_product_variant']);
$variant->setPosition(2);
$product->addVariant($variant);
productRepository->add($product);
```
This triggers fatal error "Nesting level too deep - recursive dependency?" in SortableListener.php line 471

**Comment by Loocos** [comment]
@Zales0123 I just got this on Product (Sylius v1.8.12). Using this [solution](https://github.com/Sylius/Sylius/issues/10797#issuecomment-602171800) helped me to fix it.
Should it be added too in core project ?

**Pull request merged**
