### PR TITLE
Add missing configuration for Sylius RBAC Security in backend

### PR DESCRIPTION
**Pull request by stloyd**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| License       | MIT

### CODE REVIEW

**Comment by stloyd** [comment]
@pjedrzejewski @aRn0D ping...

**Comment by pjedrzejewski** [comment]
I wanted to have it hidden for now, quite sensitive... What do you think?

**Comment by amenophis** [comment]
@pjedrzejewski why ?

**Comment by stloyd** [comment]
@pjedrzejewski Hidding feature that allows to manipulate that is wrong IMO as you added code that "uses" that feature. I can agree to add new roles for settings etc. and restrict them, but IMO it should not be hidden in any other way.

**Comment by stloyd** [comment]
@pjedrzejewski I have added new roles to lock setting changes only for admins.

**Comment by stloyd** [comment]
@pjedrzejewski I have added new roles for locking the settings update, only admin currently have them by default.

**Comment by stloyd** [comment]
@pjedrzejewski @aRn0D ping...

**Comment by pjedrzejewski** [comment]
Thanks Joseph! :+1:

**Pull request merged**
