### PR TITLE
fixes #10173, wrong regular expression for locale

### LINKED ISSUE #10173: The regular expression for locale in the URL is not correct
Current regular expression: 
https://github.com/Sylius/Sylius-Standard/blob/4de56cf9231ddb2d571cec31fb38e81d7d0f7ea0/config/routes/sylius_shop.yaml#L5
is not suitable for all locales.

For example `zh_Hans_CN` is not fit to this regular expression, which will cause an exception.

Below expression is copied from this post https://stackoverflow.com/a/48300605/2168459
```
^[A-Za-z]{2,4}([_-]([A-Za-z]{4}|[0-9]{3}))?([_-]([A-Za-z]{2}|[0-9]{3}))?$
```
I have tested it, everything works fine.

### PR DESCRIPTION
**Pull request by superbull**
| Q               | A
| --------------- | -----
| Branch?         | 1.3
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #10173 
| License         | MIT

### CODE REVIEW

**Comment by Zales0123** [comment]
It looks good, but I would add a scenario with extended locale in [this file](https://github.com/Sylius/Sylius/blob/master/features/locale/browsing_shop_in_different_than_default_locale.feature), to prevent us from possible issues. Would you be able to do it @superbull? Thanks! 🚀

**Comment by superbull** [comment]
OK, I can do it.

**Comment by kingkushk18789** [comment]
Imp confused

**Comment by Zales0123** [comment]
ping @superbull, any update on this one? :)

**Comment by Zales0123** [comment]
Thank you, Deng! :1st_place_medal:

**Comment by superbull** [comment]
@Zales0123 My pleasure! :blush:

**Pull request merged**
