### PR TITLE
Fix typo in shipping method fixture

### PR DESCRIPTION
**Pull request by ylastapis**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Related tickets | - |
| License | MIT |

### CODE REVIEW

**Comment by ylastapis** [comment]
Fixes the following error when trying to set a shipping_category on a shipping_method

[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  Unrecognized option "shipping_category" under "shipping_method.custom.normal"

**Comment by pamil** [comment]
Name's correct, `Sylius\Component\Shipping\Model\ShippingMethodInterface` has methods `getCategory()` and `setCategory()`.

**Comment by ylastapis** [comment]
You're right, but there is still a confusion between "category" from the fixture & "shipping_category" from the factory. I'm just discovering the brand new fixture system :)

With the fix, following code now works:
```
                shipping_method:
                    options:
                        custom:
                            normal:
                                description: normal
                                name: normal
                                code: normal
                                enabled: true
                                zone: EUROPE
                                category: regular
                                calculator:
                                    type: flat_rate
                                    configuration:
                                        amount: 500
                                        min_delay: 2
                                        max_delay: 4
```

**Comment by pjedrzejewski** [comment]
I was in favor of this change too, but I recall there was some reason to keep it that way - @pamil?

**Comment by pamil** [comment]
@pjedrzejewski I don't really know the reason - https://github.com/Sylius/Sylius/pull/5406#discussion_r69284245 :)

Can we do both the fixtures renaming and model renaming as described in #5384?

**Pull request closed without merging**
