### PR TITLE
Fluent interface for  calculateAdjustmentsTotal()

### PR DESCRIPTION
**Pull request by umpirsky**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| License       | MIT

### CODE REVIEW

**Comment by aRn0D** [comment]
Can you update the spec ($this->calculateAdjustmentsTotal()->shouldReturn($this);) plz :) ?

**Comment by umpirsky** [comment]
@aRn0D Added, thanks.

**Comment by stloyd** [comment]
@pjedrzejewski @aRn0D ping...

**Comment by aRn0D** [comment]
Thank you Sir @umpirsky  :D

**Comment by umpirsky** [comment]
:D

**Pull request merged**
