### PR TITLE
[Core][Taxon] Add missing createdAt/updatedAt mappings to Taxon.orm.xml

### PR DESCRIPTION
**Pull request by venyii**
| Q               | A
| --------------- | ---
| Bug fix?        | yes |
| New feature?    | no |
| BC breaks?      | no |
| Related tickets | - |
| License         | MIT |

So the Taxon API docs say [here](https://github.com/Sylius/Sylius/blob/master/docs/api/taxons.rst#definition-2) that `(optional) Field and direction of sorting, by default ‘desc’ and ‘createdAt’`. Which led me to the database where I couldn't find any dates for the `sylius_taxon` table.

Checking the [beta1 migration file](https://github.com/Sylius/Sylius/blob/master/app/migrations/Version20161202011555.php#L80) shows that those fields really didn't make it, but `Sylius\Component\Core\Model\Taxon` uses the `TimestampableTrait`.

First of all, is this a correct fix?

Additional questions:
* How about BC?
* Do I have to do anything else to make this work? Editing a taxon does not update the `updatedAt` for me?

**ToDo**
- [x] Migration file

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
@venyii Is it still a WIP? ;)

**Comment by venyii** [comment]
Well there was no feedback, I just added a migration file for the dates like it was done for `exchange_rates` - which errors out for me:

```
Migration 20170327135945 failed during Execution. Error An exception occurred while executing 'ALTER TABLE sylius_taxon ADD created_at DATETIME NOT NULL, ADD updated_at DATETIME DEFAULT NULL':

SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '0000-00-00 00:00:00' for column 'created_at' at row 1
```
```
$ mysql --version
mysql  Ver 14.14 Distrib 5.7.17, for osx10.12 (x86_64) using  EditLine wrapper
```

Not sure how this works on Travis. Using the following statements instead works:
```
$this->addSql('ALTER TABLE sylius_taxon ADD created_at DATETIME DEFAULT NULL, ADD updated_at DATETIME DEFAULT NULL');
$this->addSql('UPDATE sylius_taxon SET created_at = NOW()');
$this->addSql('ALTER TABLE sylius_taxon MODIFY created_at DATETIME NOT NULL');
```

Apart from that, it still doesn't update the `updated_at` for me when I change a Taxon's data. Creating a Taxon populates both dates, but they won't change. The dates of Exchange Rates work perfectly.

**Comment by NeverResponse** [comment]
@venyii 
My guess is the exchange rates' migration would also fail, but since there are no fixtures for it, there's no data actually being changed on the fly, so it passed only because the table's empty (which my guess will also need to be modified before beta2 gets released).

And as for taxons migration, You can shorten the three lines to a simple 
```
$this->addSql('ALTER TABLE sylius_taxon ADD created_at DATETIME NOT NULL DEFAULT NOW(), ADD updated_at DATETIME DEFAULT NULL');
```
Guess in theory the `updatedAt` field should be "initialized" along with `createdAt` on creation, but I'm not sure, so it's better to get some more feedback on this one.

And as for `updatedAt` not being updated. I don't seem to be able to reproduce it.
What fields exactly where you changing on the taxon?

**Comment by venyii** [comment]
Yeah, nevermind. The `updated_at` didn't change because I only changed the translations 😥 Changing the parent also updates the date 🥂 Thanks for pointing out which fields I'm exactly changing 👍 

I changed the migration file to use the three statements, so the only thing to decide is whether to initialize `updated_at`. Good to go from my point of view 🚀

**Comment by pjedrzejewski** [comment]
Thanks @venyii!

**Pull request merged**
