### PR TITLE
[RFC][Installer] Minor rework ui of Sylius installer

### PR DESCRIPTION
**Pull request by GSadee**
| Q               | A
| --------------- | ---
| Bug fix?        | no |
| New feature?    | no |
| BC breaks?      | no |
| Related tickets |  |
| License         | MIT |

Before:
zrzut ekranu 2017-03-01 o 14 03 43

[EDIT]
After:
zrzut ekranu 2017-03-02 o 08 34 51

Any feedback from you is of course more than appreciated 😃

### CODE REVIEW

**Comment by TheMadeleine** [comment]
1. Adding blank lines is cool. 
2. Changing the progress bars also.
_BUT_
3. 
```
Load sample data?
Warning! Your current environment is dev. 
<red-background>This action will erase your database! </red-background>
Continue? (y/N)
```
4. Should the progress bars have one space indentation?
4. I don't like the idea of adding Sylius logo into the installer. Our installer's log is long enough, no need to extend it even more. Plus: We cannot assure it will look fine in every console, on every OS. IMHO It may annoy some people.

**Comment by GSadee** [comment]
@TheMadeleine I have updated step 2

**Comment by pamil** [comment]
Btw. `<red-background>This action will erase your database! </red-background>` should be also applicable to the dialog with `Would you like to reset it?`. :)

**Comment by pjedrzejewski** [comment]
Thanks Grzesiu, looks good! :)

**Pull request merged**
