### PR TITLE
[Fix] Do not show cart id after saving

### LINKED ISSUE #15541: [Potential Issue] update cart lead to order id appears in url
**Sylius version affected**: 1.x.y

**Description**  

order id appears on url : https://demo.sylius.com/en_US/cart/?id=108642
no need to expose potential number of orders 

**Steps to reproduce**  
go to https://demo.sylius.com/ add an item in cart, next https://demo.sylius.com/en_US/cart/  click on "update cart" btn
REQUEST :  `POST https://demo.sylius.com/en_US/cart/`
RESPONSE Headers:  `Location: /en_US/cart/?id=108642` (part ?id=108642)

**Possible Solution**

### PR DESCRIPTION
**Pull request by NoResponseMate**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.12 |
| Bug fix?        | yes                                                       |
| New feature?    | no                                                       |
| BC breaks?      | no                                                       |
| Deprecations?   | no |
| Related tickets | fixes #15541 |
| License         | MIT                                                          |

### CODE REVIEW

**Review by vvasiloi — APPROVED** [review]
@loic425 wasn't this issue fixed in the Resource Bundle?

**Comment by NoResponseMate** [comment]
@vvasiloi 
I couldn't find a PR regarding this (though there have been a lot, so I might've just missed it 💃), but I don't think it'd change anything since the route points to a custom action, I might be wrong though 🤷

**Comment by vvasiloi** [comment]
> @vvasiloi I couldn't find a PR regarding this (though there have been a lot, so I might've just missed it 💃), but I don't think it'd change anything since the route points to a custom action, I might be wrong though 🤷

The issue was in how the resource controller resolves the redirect router arguments. I'll try to find it.

**Comment by vvasiloi** [comment]
I cannot find it, but I think this PR will fix it: https://github.com/Sylius/SyliusResourceBundle/pull/641 😄 
Anyway, this PR is a good fix until we get the new resource bundle.

**Review by jakubtobiasz — APPROVED** [review]

**Comment by jakubtobiasz** [comment]
Thank you, @NoResponseMate!

**Pull request merged**
