### PR TITLE
Add layout events for head & body

### PR DESCRIPTION
**Pull request by stefandoorn**
| Q               | A
| --------------- | ---
| Bug fix?        | no |
| New feature?    | yes |
| BC breaks?      | no |
| License         | MIT |

Makes it easier for plugin development to add things to head / end of body etc.

### CODE REVIEW

**Comment by stefandoorn** [comment]
I'm using this e.g. in https://github.com/stefandoorn/google-tag-manager-plugin to add the tracking codes to the appropriate locations.

**Comment by lchrusciel** [comment]
Thanks Stefan :)

**Comment by psren** [comment]
Is the block "sylius.shop.layout.before_head" dangerous?
IMO nothing should appear in the html-source before the ```charset```? In the definition of w3.org the charset should appear in die first 1024 chars of the content. If plugins add content to that block this limit could be reached.

**Comment by stefandoorn** [comment]
Basically it's inside the <head>. I tried to follow naming conventions used on several places, where `before` most often means at the beginning of something (before other things are rendered in the head in this case), while after means just after the content of it (after other things inside the head, so basically before `</head>`. 

Of course we can still adjust the naming of it, to make it more declarative.

**Comment by stefandoorn** [comment]
@pjedrzejewski @lchrusciel What are your thoughts on this naming thing?

**Comment by stefandoorn** [comment]
And now on topic, sorry @psren. Maybe we can put the charset higher, or this hook lower to prevent this issue you mentioned.

**Comment by lchrusciel** [comment]
Thanks @psren for pointing out, we should fix that of course. 

@stefandoorn after a while, I am thinking that only `sylius.admin.layout.head` should be placed just before `</head>`. Is there any particular to have to inject points there?

**Pull request merged**
