### PR TITLE
Add symfony/thanks Composer plugin

### PR DESCRIPTION
**Pull request by pamil**

### CODE REVIEW

**Comment by stefandoorn** [comment]
Does this actually work in the meanwhile? Previous time I tried it on my Sylius project the GitHub API failed due to the size of the dependencies graph it seems.. :-D

**Comment by pamil** [comment]
@stefandoorn it might be connected to token's permissions (see symfony/thanks#41).

**Comment by stefandoorn** [comment]
Hm I had another error but it's been a while so can't recall correctly. Tested again locally, seems better now.

**Comment by nicolas-grekas** [comment]
@stefandoorn please open an issue on symfony/thanks if you reproduce that error again

**Pull request merged**
