### PR TITLE
[Doc] Customizing admin routes prefix

### PR DESCRIPTION
**Pull request by oallain**
| Q               | A
| --------------- | -----
| Branch?         | 1.9
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | related #11664 and https://github.com/Sylius/Sylius-Standard/pull/530
| License         | MIT

### CODE REVIEW

**Comment by oallain** [comment]
Hello @Sylius/core-team 

Do you have any feedback on this PR?

**Comment by oallain** [comment]
Hello @CoderMaggie ,

Can you take a look at this PR and give me feedback ?

**Review by lchrusciel — APPROVED** [review]

**Comment by oallain** [comment]
Ping @Sylius/core-team 😄

**Comment by CoderMaggie** [comment]
The base of this pull-request was changed, you need fetch and reset your local branch 
if you want to add new commits to this pull request. **Reset before you pull, else commits
may become messed-up.**

Unless you added new commits (to this branch) locally that you did not push yet, 
execute `git fetch origin && git reset "doc-admin-routes-prefix"` to update your local branch.
 
Feel free to ask for assistance when you get stuck :+1:

**Review by arti0090 — APPROVED** [review]

**Comment by CoderMaggie** [comment]
Thank you, @oallain! :tada:

**Pull request merged**
