### PR TITLE
Fix translation for backend product undelete btn

### PR DESCRIPTION
**Pull request by diimpp**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| License       | MIT

Fixes actions undelete button
http://demo.sylius.org/administration/products/?deleted=1

Let me know, if I should rename translation string from `sylius.product.delete_revert` to `sylius.product.delete_restore`.

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
Actually, according to new translation key conventions (will be published soon when we finish migration script) it should be just ``sylius.restore``. Wdyt?

**Comment by diimpp** [comment]
Yes, this particular key should be move out of product namespace to general one for sure.

Looking forward to see new conventions.

**Comment by pjedrzejewski** [comment]
@diimpp This will take a few more days at least, so I will be happy to merge your change before that. Just tweak the key and we are good to go, thank you. :)

**Comment by diimpp** [comment]
@pjedrzejewski done

**Comment by pjedrzejewski** [comment]
Thank you @diimpp. We should not modify any other translation files than ``en``, cause they are overriden when syncing with Crowdin anyway. :+1:

**Comment by diimpp** [comment]
@pjedrzejewski sorry, I've missed another usage of this trans key. Here is hotfix https://github.com/Sylius/Sylius/pull/3516 It's last one for sure. :)

Will keep in mind about other translation files.

**Pull request merged**
