### PR TITLE
[User] Fix canonicalizer if mb_string extension isnt loaded

### PR DESCRIPTION
**Pull request by cdaguerre**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #3590 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by stloyd** [comment]
IMO better would be to use: https://packagist.org/packages/symfony/polyfill-mbstring

**Comment by cdaguerre** [comment]
@stloyd So you would add that package as a hard dependency? Installing it even if the `mb_string` extension is available? 
Or add suggest `ext-mbstring` and `symfony/polyfill-mbstring` in `composer.json` and check if the `mb_convert_case` function exists in the `Canonicalizer`, ie. `function_exists('mb_convert_case')` rather than `extension_loaded('mb_string')`?

**Comment by pjedrzejewski** [comment]
@carlowens :+1: for your second proposition. I think it is best solution right now.

**Comment by stloyd** [comment]
IMO this should be done same as it's done for Symfony. Add `polyfill` to required & done, all checks (`function_exists()` etc.) will be handled already by this component.

**Comment by pjedrzejewski** [comment]
@stloyd @cdaguerre Well, I am in favor of sticking to what Symfony follows, so I think we could actually add this one to deps.

@carlowens Sorry, I picked wrong mention autocomplete. :/

**Comment by stloyd** [comment]
With `polyfill` we can also add usage of `intl` etc.

**Comment by cdaguerre** [comment]
:+1:

**Pull request closed without merging**
