### PR TITLE
[ResourceBundle] Automatic form registration

### PR DESCRIPTION
**Pull request by Strontium-90**
| Q             | A
| ------------- | ---
| Bug fix?      | [no]
| New feature?  | [yes]
| BC breaks?    | [no]
| Deprecations? | [no]
| Tests pass?   | [yes]
| Fixed tickets | [ #1384 ]
| License       | MIT
| Doc PR        | []

Register resource form types as services.
Its possible register many form for resourse, i.e:
```yml
classes:
    controller: MyControllerClass
    form:
        default:             MyBundle\Form\Type\AnyResourceType
        short:                MyBundle\Form\Type\AnyResourceShortType
    choice_form:        MyBundle\Form\Type\AnyResourceChoiceType
```

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
Thank you so much Aleksey! This is a really cool thing, I will remove other forms. :) :+1:

**Comment by Strontium-90** [comment]
> I will remove other forms. :)

I think this will more easy, if we finish this PR #1921.

**Comment by adamelso** [comment]
This change is nice, I like it. However there's something slightly counter-intuitive in having to manipulate the service definitions just to pass in dependencies:

```php
$container
    ->getDefinition('my.form.type.blog')
    ->setArguments(array(
        new Reference('my.repository.blog')
    ))
;
```

Perhaps in another PR, this can be exposed to the config?

**Comment by isometriks** [comment]
I agree with @adamelso, I think it would be easier to have a check to see if the form's definition already exists and if it doesn't create it. That way any form that isn't standard you can create in your service definitions and any simple ones will just get created by themselves. It seems silly to mess with the definitions programmatically only. Kind of adds a big learning curve for newer users and is harder to read and trace out errors. Should be simple to change it to this:

```php
    protected function registerFormTypes(array $config, ContainerBuilder $container)
    {
        foreach ($config['classes'] as $model => $serviceClasses) {
            if (!isset($serviceClasses['form']) || !is_array($serviceClasses['form'])) {
                continue;
            }
            foreach ($serviceClasses['form'] as $name => $class) {
                $suffix = ($name === self::DEFAULT_KEY ? '' : sprintf('_%s', $name));
                $alias = sprintf('%s_%s%s', $this->applicationName, $model, $suffix);
                $definitionId = sprintf('%s.form.type.%s%s', $this->applicationName, $model, $suffix);

                // HERE
                if ($container->hasDefinition($definitionId)) {
                    continue;
                }

                $definition = new Definition($class);
                if ('choice' === $name) {
                    $definition->setArguments(array(
                        $serviceClasses['model'],
                        $config['driver'],
                        $alias
                    ));
                } else {
                    $definition->setArguments(array(
                        $serviceClasses['model'],
                        new Parameter(sprintf('%s.validation_group.%s%s', $this->applicationName, $model, $suffix))
                    ));
                }
                $definition->addTag('form.type',array('alias' => $alias));
                $container->setDefinition(
                    $definitionId,
                    $definition
                );
            }
        }
    }
```

**Comment by liverbool** [comment]
@isometriks I've use some your code snippet in my PR #2483 .

**Pull request merged**
