### PR TITLE
Move security.yml configuration file & made some params configurable

### PR DESCRIPTION
**Pull request by stloyd**

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
Is security node overridable in this scenario?

**Comment by stloyd** [comment]
@pjedrzejewski Don't really get what do you mean... It works same way it does for `app.yml` or `main.yml`...

**Comment by steffenbrem** [comment]
@stloyd Well what @pjedrzejewski says could be a concern, since you cannot override `firewalls` for example when you already have a `security` node defined. This might confuse people.

**Comment by pjedrzejewski** [comment]
@steffenbrem Exactly this, while I would love to move more default config into bundle, this does not allow us to easily modify. We do not want to ask user to copy everything over to change a single line... It should stay here.

**Pull request closed without merging**
