### PR TITLE
Adding strict typing for PHP classes in images doc

### PR DESCRIPTION
**Pull request by Roshyo**
This part of the doc was lacking strict PHP typing.

| Q               | A
| --------------- | -----
| Branch?         | 1.0, 1.1, 1.2
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| License         | MIT

Adding strict typing for the cookbook in images.

### CODE REVIEW

**Comment by CoderMaggie** [comment]
Hi there @Roshyo, nice to see you in our community as a contributor 👋 💪! 

One thing that we need to change here is the base branch of this PR. It should be opened to the `1.0` branch as it is a fix for an already existing doc, working since the 1.0 version (am I right @pamil ?).
**Could you please rebase with the 1.0 branch?**

**Comment by Roshyo** [comment]
@CoderMaggie Hi,

I'm ok with that, but since I'm definitely not familiar with GitHub (boooh shame on me) I'm not sure about how to do that. Can you help me ?

**Comment by pamil** [comment]
@CoderMaggie `1.0` is for security fixes only right now, `1.1` is for bug fixes and enhancements like this.

@Roshyo I'll do it for you :)

**Comment by pamil** [comment]
Thank you, Stephane! 🥇

**Pull request merged**
