### PR TITLE
[Admin][Order] Tweak the display of payment and shipping state on the order show

### PR DESCRIPTION
**Pull request by GSadee**
| Q               | A
| --------------- | ---
| Bug fix?        | no |
| New feature?    | no |
| BC breaks?      | no |
| Related tickets |  |
| License         | MIT |

Before:
zrzut ekranu 2017-02-27 o 09 59 44

After:
zrzut ekranu 2017-02-27 o 10 02 57

### CODE REVIEW

**Comment by TheMadeleine** [comment]
I like the second proposition much more :)

**Comment by Zales0123** [comment]
I'm also 👍  for the second option.

**Comment by NeverResponse** [comment]
+1 for the second, mainly 'cause the title doesn't jump around depending on the state.

**Comment by pjedrzejewski** [comment]
Thanks Grzesiu, looks nice! :)

**Pull request merged**
