### PR TITLE
Replace php-http/guzzle6-adapter with php-http/guzzle7-adapter

### PR DESCRIPTION
**Pull request by pamil**
See #12298.

### CODE REVIEW

**Comment by alexander-schranz** [comment]
Maybe it would make sense to use here the `symfony/http-client` instead of guzzle, maybe this is more future-proof as you build on top of symfony. See as example: https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/pull/561/files

**Comment by alexander-schranz** [comment]
Also the guzzle6 adapter was now merged with PHP 8 support. https://github.com/php-http/guzzle6-adapter/pull/86 and tagged as [2.0.2](https://github.com/php-http/guzzle6-adapter/releases/tag/v2.0.2). Still would go here with symfony/http-client :)

**Comment by pamil** [comment]
Thanks for the info, @alexander-schranz! Symfony's HTTP Client would be the next step, but this is good enough for now :)

**Comment by gomcodoctor** [comment]
Can we move to php-http/guzzle7-adapter instead of php-http/guzzle6-adapter till we waiting for Symfony's HTTP Client?

**Comment by Keimpy** [comment]
Any update on this? Is it possible to update to guzzle 7?

**Pull request closed without merging**
