### PR TITLE
[CoreBundle] Copied PHPCR initializer for CmfRoutingBundle to CoreBundle

### LINKED ISSUE #3139: Can't create pages/routes/blocks/menu in demo
Hi,

I didn't manage to create either routes, either pages, or blocks.
For example, when I try to create a simple block, I got an error message on a hidden field:

capture d ecran 2015-08-17 a 09 54 43

**edit**: It's the same when trying creating a menu

### PR DESCRIPTION
**Pull request by pamil**
See symfony-cmf/RoutingBundle#251. Fixes #3139.

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
:+1: I think this should be configurable under a separate config in CmfRoutingBundle. /cc @lsmith77 @dbu

**Comment by psyray** [comment]
This is already in a separate config file, here
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Resources/config/app/cmf.yml#L36

I 've done a test with Sylius install, without install fixtures, and I could reproduce the #3139  bug.

So why this config was not taken into account while doing `doctrine:phpcr:repository:init` ?

Other basepath are correcty taken into account
selection_223

Maybe it's too deeper (under dynamic) ?

**Comment by psyray** [comment]
I think this issue could help us to understand
https://github.com/symfony-cmf/SimpleCmsBundle/issues/129

**Comment by pamil** [comment]
@psyray it's been already explained in symfony-cmf/RoutingBundle#251, it requires `cmf_routing.dynamic.persistence.phpcr.use_sonata_admin` and `cmf_routing.dynamic.persistence.phpcr.enable_initializer` to be true in order to add initializer that creates `/cms/routes` each time `doctrine:phpcr:repository:init` is run.

**Comment by psyray** [comment]
Shame on me, I have not read your link in the first post :-1: 
Your fix is working fine :+1:

**Comment by dbu** [comment]
since a while, CmfRoutingBundle can support multiple basepaths. the route_basepath parameter is only the first one of those. i think what we should have is an initializer that can initialize all these base paths and can be activated regardless of whether sonata is used or not.

i just be so bold: could you do a pull request on CmfRoutingBundle to build that? i guess just creating one initializer per base path would be fine, as otherwise we would need a custom initializer class. the routing bundle 1.4 will be released soonish, to enable symfony 2.8 / 3.0 support.

**Comment by pamil** [comment]
@dbu awesome, working on it right now! :+1:

**Comment by pamil** [comment]
@dbu got it, symfony-cmf/RoutingBundle#318.

**Comment by pamil** [comment]
Closing as it should be fixed after symfony-cmf/RoutingBundle#318 is merged.

**Comment by dbu** [comment]
https://github.com/symfony-cmf/RoutingBundle/pull/318 has been merged.

**Pull request closed without merging**
