### PR TITLE
[PHP 5.5] Refactored \DateTime to \DateTimeInterface in typehints, docblocks and specs

### PR DESCRIPTION
**Pull request by pamil**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| License       | MIT

### CODE REVIEW

**Comment by stloyd** [comment]
:-1: as it gives no value and just makes any rebase/merge much more painful.

**Comment by lchrusciel** [comment]
:+1: As we should work on abstracts rather then on objects implementation.

**Comment by pamil** [comment]
It makes using `\DateTimeImmutable` possible in Sylius and improves overall code quality as we're not bound to specific implementation.

**Comment by Zales0123** [comment]
:+1: Agree with @lchrusciel, refactoring and improvements in code quality are always good.
(We've just create some kind of questionnaire here :smile:)

**Comment by pjedrzejewski** [comment]
:+1:, but after #2255. ;>

**Comment by aramalipoor** [comment]
Note that `\DateTimeInterface` does not guarantee existence of some methods such as `setTimezone` that can maybe cause some problems!

**Comment by stloyd** [comment]
@aramalipoor Yep, that's why we __shouldn't__ do this that way! If we want to use immutable dates, replace the code in proper places, doing grep replacing is always bad idea.

**Comment by pamil** [comment]
@aramalipoor @stloyd you're right, that change makes no sense :)

**Pull request closed without merging**
