### PR TITLE
Remove deprecations on Symfony Intl component

### PR DESCRIPTION
**Pull request by loic425**
| Q               | A
| --------------- | -----
| Branch?         | 1.4
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| License         | MIT

### CODE REVIEW

**Comment by loic425** [comment]
@pamil @lchrusciel 
Not compatible with Symfony 3... so You can keep it for later.

**Comment by vvasiloi** [comment]
Do not stale.

**Comment by Zales0123** [comment]
Hello @loic425! It's definitely a change we would like to make, but it has to be rebased with the `master` branch. As far as I know, you will have some fun with solving the conflicts in `LocaleSetup` and `CountryNameExtension` :) I hope you'll find some time to do it 🚀

**Comment by loic425** [comment]
> Hello @loic425! It's definitely a change we would like to make, but it has to be rebased with the `master` branch. As far as I know, you will have some fun with solving the conflicts in `LocaleSetup` and `CountryNameExtension` :) I hope you'll find some time to do it 🚀 Tests also need some polishing 🖖

I think I can work on it soon. :)

**Comment by pamil** [comment]
The master branch requires Symfony ^4.3 now, could be merged after being rebased and having conflicts fixed.

**Comment by loic425** [comment]
@pamil Done, let's wait for Travis build.

**Comment by loic425** [comment]
@pamil Do not stale 🙏

**Comment by lchrusciel** [comment]
Ref. #10928

**Comment by loic425** [comment]
@pamil @lchrusciel I just finished this old PR for Symfony 5 support and this time, all tests are OK 🎉

**Comment by pamil** [comment]
Thanks, Loïc! :tada:

**Comment by loic425** [comment]
@pamil just started 10 months ago :) I have more time for OSS now. So I can help again.

**Comment by jordisala1991** [comment]
Can this be backported to Sylius 1.7? It only requires Symfony >= 4.3

**Pull request merged**
