### PR TITLE
Catch event stop during create/update

### PR DESCRIPTION
**Pull request by amenophis**
My bad for the PR on splitted repo ...

Related to https://github.com/Sylius/Sylius/issues/2022 and https://github.com/Sylius/SyliusResourceBundle/pull/75

Is it OK ?

### CODE REVIEW

**Comment by Shine-neko** [comment]
:+1:

**Comment by amenophis** [comment]
@pjedrzejewski @stloyd is it OK for you ?

**Comment by stloyd** [comment]
As said before, looks good.

**Comment by amenophis** [comment]
wait for @pjedrzejewski feedback ?

**Comment by amenophis** [comment]
ping @pjedrzejewski

**Comment by Shine-neko** [comment]
Yah ping @pjedrzejewski

**Comment by stloyd** [comment]
@pjedrzejewski ping... again...

**Comment by pjedrzejewski** [comment]
Does not sound right to me, 500 when you stop the saving/deletion? It's not always case of an error, no?

**Comment by amenophis** [comment]
@pjedrzejewski ok, how can i manage it in a better way ? 
@stloyd @Shine-neko any suggestion ?

**Comment by amenophis** [comment]
@pjedrzejewski I made the errorCode configurable by setter and stop method on ResourceEvent object.
Is it better for you ?

**Comment by amenophis** [comment]
@pjedrzejewski Better or not ? Can be merge soon ?

**Comment by pjedrzejewski** [comment]
I'm not sure I like the fact that domain manager returns resource event ... It sounds a bit hacky to me. However, I have no idea how to make it better. What is your current usecase? (I see you need it fast J)

**Comment by amenophis** [comment]
I need it to check if customer has enough credit to do the operation during the creation process inside an event and stop event if not enough credit. All the operation are done with REST API process.

Do you understand the usecase ?

**Comment by amenophis** [comment]
@pjedrzejewski ?

**Comment by amenophis** [comment]
@pjedrzejewski what do you think ? we really need a functionallity this this !

**Comment by pjedrzejewski** [comment]
OK, I understand, but don't you think it is weird that in case of API call returing ResourceEvent means errors, while in case of normal call, it redirects to index?

**Comment by amenophis** [comment]
In API call, the fact we get a ResourceEvent will allow to throw the exception. In WEB call, if an error occur, the browser will be redirected to the index with a flash message. So in the two cases, we are informed that something went wrong. Maybe in WEB call we need to redirect to current page ?

Do you have a better solution ?

**Comment by pjedrzejewski** [comment]
Now I get it! :) Thanks Jeremy! This needs to be reworked, but I will include this behavior!

**Comment by amenophis** [comment]
OK thanks, take me in touch if you want some help

**Pull request merged**
