### PR TITLE
Added: TimestampableInterface to core TaxonInterface (fixes #10728)

### LINKED ISSUE #10728: [Bug] TaxonInterface should extend TimestampableInterface
**Sylius version affected**: master (1.7, 1.6, etc)

**Description**  
[TaxonInterface](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Core/Model/TaxonInterface.php) should extend `TimestampableInterface` as [Taxon](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Core/Model/Taxon.php) uses `TimestampableTrait` and have proper fields.

**Steps to reproduce**  
- When you define argument as `TaxonInterface $taxon`, your PHPStorm will not show `getUpdatedAt`/`setUpdatedAt` and `getCreatedAt`/`setCreatedAt` at autocomplete.

### PR DESCRIPTION
**Pull request by igormukhingmailcom**
| Q               | A
| --------------- | -----
| Branch?         | 1.3
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #10728
| License         | MIT

### CODE REVIEW

**Comment by pamil** [comment]
Could you add a line to `UPGRADE-1.7.md` about this change? It's very unlikely, but it can be a BC break for some.

**Comment by igormukhingmailcom** [comment]
> Could you add a line to `UPGRADE-1.7.md` about this change? It's very unlikely, but it can be a BC break for some.

I'm on 1.3, and there are no `UPGRADE-1.7.md`... How that usually handled?

**Comment by pamil** [comment]
@igormukhingmailcom it should appear after you rebase your PR with the `master` branch - we can't merge it into any previous version (BC reasons), and even if we could, currently only 1.5+ versions are supported.

**Comment by lchrusciel** [comment]
Hey Kamil. 

Do we really need to add a notice to the UPGRADE file? According to our [bc promise](https://docs.sylius.com/en/1.6/contributing/code/bc.html#models-model-interfaces) we are fine without it :) 

I would vote for merge ;)

**Comment by igormukhingmailcom** [comment]
> Models & model interfaces
> In order to fulfill the constant Sylius’ need to evolve, model interfaces are excluded from this BC promise.

Rebased to 1.5

**Comment by Zales0123** [comment]
Thank you, Igor! :tada:

**Pull request merged**
