### PR TITLE
Add a fixed parameter in WeightCalculator

### PR DESCRIPTION
**Pull request by winzou**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

Add the ability to use a linear function for the weight shipping charges (`a + b*x`, here the `a` is added).

### CODE REVIEW

**Comment by stloyd** [comment]
@winzou I would call that new part "base" or something like that as "variable" is quite confusing ;)

**Comment by michalmarcinkowski** [comment]
@winzou I agree that "base" will be a better name for the "fixed" part. As for the "variable" maybe we simply name it "rate"?

**Comment by winzou** [comment]
`fixed` and `variable` are taken from salary vocabulary, I find it quite explicit and the parallel helps to understand.

**Comment by pjedrzejewski** [comment]
Thank you Alexandre! :+1:

**Pull request merged**
