### PR TITLE
Update doctrine bundle to 1.4

### PR DESCRIPTION
**Pull request by gonzalovilaseca**
1.4 introduces some improvements, and it shouldn't break anything...let see if tests pass.

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
We should update that for other composer.json's as well, this does not affect the version used by Sylius.

**Comment by gonzalovilaseca** [comment]
ok, I will look again as I only saw this dependency on it

**Comment by Rvanlaak** [comment]
Only one extra right? https://github.com/Sylius/Sylius/search?utf8=%E2%9C%93&q=doctrine%2Fdoctrine-bundle

**Comment by aRn0D** [comment]
ping @gonzalovilaseca

**Comment by aRn0D** [comment]
ping @gonzalovilaseca

**Comment by Rvanlaak** [comment]
see #2747

**Pull request closed without merging**
