### PR TITLE
[ThemeBundle] allow symfony 3.x

### PR DESCRIPTION
**Pull request by ahilles107**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Related tickets | partialy #3564 |
| License | MIT |

### CODE REVIEW

**Comment by ahilles107** [comment]
@pjedrzejewski it works ok with SF3 in https://github.com/superdesk/web-publisher with this change. Can't run tests for bundle with 3.x as settings bundle require 2.x version of symfony/framework-bundle. But from what i can see in composer it's required for now only in dev.

**Comment by ahilles107** [comment]
@pamil can you take a look here?

**Comment by michalmarcinkowski** [comment]
Closing in favor of #6738

**Comment by ahilles107** [comment]
@pamil It's still not resolved (after merging #6896).

**Comment by rvanlaak** [comment]
@ahilles107 see https://github.com/Sylius/Sylius/pull/6896#issuecomment-263280862

**Pull request closed without merging**
