### PR TITLE
Fixed deprecated option usage on Email validator

### PR DESCRIPTION
**Pull request by stloyd**
| Q               | A
| --------------- | -----
| Branch?         | 1.8
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | related #10928 
| License         | MIT

### CODE REVIEW

**Review by lchrusciel — COMMENTED** [review]
Hey Józef, thanks for your fix. Shouldn't we, however, add https://packagist.org/packages/egulias/email-validator as a dependency, as described here: https://symfony.com/doc/4.4/reference/constraints/Email.html#strict

**Comment by stloyd** [comment]
@lchrusciel Hey, as in description, there is no more such option like `strict` in Symfony 5, it was replaced with added `mode` option:
https://symfony.com/doc/5.0/reference/constraints/Email.html#mode
https://github.com/symfony/symfony/blob/4.4/UPGRADE-5.0.md#validator
> The `Email::__construct()` 'strict' property has been removed. Use `'mode'=>"strict"` instead.

**Comment by lchrusciel** [comment]
What I meant was this line: `The egulias/email-validator component is now required for using the Email constraint in strict mode`. I wasn't sure if it is already in composer.json, but it is.

**Comment by lchrusciel** [comment]
Thanks, Joseph! :1st_place_medal:

**Pull request merged**
