### PR TITLE
[WIP] Fix javascript testing on Travis

### PR DESCRIPTION
**Pull request by WouterJ**
Let's see if this works :)

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
Would be great to get this working ... I failed, so thanks for your effort! :+1:

**Comment by WouterJ** [comment]
I'm already stuck on the current Yaml syntax error :(

**Comment by aRn0D** [comment]
:+1: IIRC @stloyd tries to do it !

**Comment by michalmarcinkowski** [comment]
Closing in favour of https://github.com/Sylius/Sylius/pull/3055

**Pull request closed without merging**
