### PR TITLE
form_theme is already configured in the config.yml

### PR DESCRIPTION
**Pull request by aRn0D**
| Q             | A
| ------------- | ---
| Bug fix?      | markup and config fixes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by aRn0D** [comment]
@pjedrzejewski what is your opinion about the last changes ?

**Comment by aRn0D** [comment]
@pjedrzejewski ping

**Comment by aRn0D** [comment]
@pjedrzejewski Is it enough for you? I remove some form_theme when I refactored the form type collection. So we need to merge it or merge the the different form theme into one form theme.

**Comment by aRn0D** [comment]
@pjedrzejewski ping

**Comment by aRn0D** [comment]
@pjedrzejewski pong

**Comment by pjedrzejewski** [comment]
:+1: Thank you Arnaud! :)

**Comment by aRn0D** [comment]
@pjedrzejewski :v:

**Pull request merged**
