### PR TITLE
[Admin] Fix attribute deletion when enter pressed on product edit

### PR DESCRIPTION
**Pull request by lchrusciel**
| Q               | A
| --------------- | -----
| Branch?         | 1.8
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | Replacement of #12150, fixes #11879 #11712
| License         | MIT

I've taken and rebased commits of @nils-m to the newest 1.8. Would be good to have it merged.

### CODE REVIEW

**Comment by zangra-dev** [comment]
Please can you do this merge ?

Our employees delete non stop attributes by pressing Enter in reflex to save the product. . . 

It's really important to have it in the basic code to don't fork the entire project just for this lines

**Comment by nils-m** [comment]
Hi,
Also it would be interesting to know why the check fails on Github and not on our local server ? (with the latest upstream branch upToDate).  Our server config PHP 7.3 Symfony 4.4.20 Sylius 1.8.9.

For the info ... On the online sylius demo the problem is still there in v.1.9

Thanks in advance,
nils

From: https://github.com/Sylius/Sylius/pull/12150#issuecomment-762868020

_behat --tags @managing_product_attributes:
36 scenarios (**36 passed**)
273 steps (**273 passed**)
2m4.66s (108.97Mb)_

_behat --tags @javascript:
260 scenarios (256 passed, 1 failed, 3 undefined)
2776 steps (**2762 passed**, 1 failed, 5 undefined, 8 skipped)
25m54.53s (117.56Mb)_

_Failed scenarios:
features/currency/managing_exchange_rates/deleting_multiple_exchange_rates.feature:15
But this has nothing to do with my modification._

**Comment by zangra-dev** [comment]
We are  on sylius 1.9
The problem still present since at least 8 months
Nobody is using the attribute or what ?

Sorry to tag you all, but can you verify this PR (or answer on the question above, why our behat is working without any problem but have fails on github ?)

Do a fork only for this lines is really messy  :/
@AdamKasp @Arminek @CoderMaggie @czechmarcin @GSadee @jacquesbh @kulczy @lchrusciel @mamazu @pamil @pjedrzejewski @Tomanhez @Zales0123

**Comment by vvasiloi** [comment]
@zangra-dev have you tried to rebase your branch onto the latest 1.8 branch?

**Comment by zangra-dev** [comment]
It's the same remark as the last 8 months to rebase on the latest branch but nothing change.
It's also what lchrusciel did before create the PR

If I search when the function is created in the js file, it's been done on 15 Jun 2018 and no update since

**Comment by vvasiloi** [comment]
@zangra-dev @nils-m @lchrusciel  I took a closer look at the solution now and I see that it's using a non-standard feature `Event.explicitOriginalTarget`:
https://developer.mozilla.org/en-US/docs/Web/API/Event/explicitOriginalTarget#Non-standard
https://caniuse.com/?search=explicitOriginalTarget
It will cover less than 1% of global users, which is bad.

**Comment by zangra-dev** [comment]
@vvasiloi Oh I see, the explicitOriginalTarget is specifc on Firefox.

Below you can see screenshots of what I get when I press Enter on an attribute or click on the button delete (for firefox and google chrome). What can I use to see the difference between the Enter and the Click ?
Chrome_Click
Chrome_Enter
Firefox_Click
Firefox_Enter

the event.originalEvent.pageX != 0 seems to be another solution, as I detailled here : https://github.com/Sylius/Sylius/issues/11712
ClientX/ClientY PageX/PageY ScreenX/ScreenY are at 0 for the Enter pressed but with number when Button clicked
and if I check https://caniuse.com/?search=pageX it's seems to be used on many browser (thank for this website, I didn't know it)

If a change the test from
```
if (!event.originalEvent.explicitOriginalTarget.id) {
  const attributeId = $(event.currentTarget).parents('.attribute').attr('data-id');

  $('div#attributeChoice > .ui.dropdown.search').dropdown('remove selected', attributeId);
  modifyAttributesListOnSelectorElementDelete(attributeId);
}
```
to
```
if (event.originalEvent.pageX != 0) {
  const attributeId = $(event.currentTarget).parents('.attribute').attr('data-id');

  $('div#attributeChoice > .ui.dropdown.search').dropdown('remove selected', attributeId);
  modifyAttributesListOnSelectorElementDelete(attributeId);
}
```

The result is the same => form validate if Enter and attribute delete if click on "delete"
Do you think it's a better solution ?

**Comment by vvasiloi** [comment]
@zangra-dev sorry for the incredibly late response, somehow I missed the notification for this.
I couldn't find a better way to distinguish the events than using the coordinates.
It's a good alternative, but it need some comments or a suggestive function name.

**Comment by zangra-dev** [comment]
hello @vvasiloi @lchrusciel @Zales0123 

With an update done by own side, my correction was removed. But I saw that the bug is still present, but now in a different file => sylius/src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-product-attributes.js  L29
```
const modifyAttributesListOnSelectorElementDelete = function modifyAttributesListOnSelectorElementDelete(removedValue) {
  $(`#attributesContainer .attributes-group[data-attribute-code="${removedValue}"]`).remove();
};
```
I redo my previous correction 2 years ago ... And the bug is again fixed =>

```
const modifyAttributesListOnSelectorElementDelete = function modifyAttributesListOnSelectorElementDelete(removedValue) {
  if (event.pageX != 0) {
    $(`#attributesContainer .attributes-group[data-attribute-code="${removedValue}"]`).remove();
  }
};
```
Can you **please** fix this problem to don't have the attributes deletion ?!

**Comment by jakubtobiasz** [comment]
Closing, as the bug has been fixed in #14971.

**Pull request closed without merging**
