### PR TITLE
Add support to configure the shop firewall context name

### PR DESCRIPTION
**Pull request by jdeveloper**
| Q                      | A
| ------------------- | --------
| Bug fix?            | no       |
| New feature?    | no       |
| BC breaks?       | no       |
| Related tickets  | #8151 |
| License             | MIT     |

### CODE REVIEW

**Comment by jdeveloper** [comment]
@pamil Your solution is clearly simpler. I was thinking to not force the user to configure a parameter and so, therefore, provide a default config to allow the user to change it. But you're right, after all it's just another parameter and that can be provided in ``src/Sylius/Bundle/CoreBundle/Resources/config/app/parameters.yml``

**Comment by pamil** [comment]
@jdeveloper what I meant is that DependencyInjection's Extension is defining that parameter taken from bundle configuration :)

**Comment by pamil** [comment]
Just like `sylius_locale.locale` parameter is set in LocaleBundle.

**Comment by jdeveloper** [comment]
I see that in travis, with php 5.6 not all behat scenarios pass. I just can't figure where the issue is. Some suggestion?

**Comment by lchrusciel** [comment]
@jdeveloper The 5.6 build is unstable. I have restarted it.

**Comment by jdeveloper** [comment]
@lchrusciel ok, when I get a little time, I'll do a PR to the docs

**Comment by pjedrzejewski** [comment]
Thanks @jdeveloper! :)

**Comment by jdeveloper** [comment]
@pjedrzejewski I wanted to add some doc but really don't know where to put it, since there is no doc for the ShopBundle.

**Comment by lchrusciel** [comment]
We could add a new section to our book with some tips and tricks about shop and admin. /cc @CoderMaggie

**Pull request merged**
