### PR TITLE
[Composer] Added webmozart/assert assertion library as a dependency

### LINKED ISSUE #3928: [RFC] Usage of assertion library
In Sylius there are many places when we're validating arguments and that logic is often duplicated. Agreeing on some assertion library will make our codebase cleaner.

My proposition: [beberlei/assert](https://github.com/beberlei/assert).

### PR DESCRIPTION
**Pull request by pamil**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #3928
| License         | MIT
| Doc PR          | -

### CODE REVIEW

**Comment by Zales0123** [comment]
:+1:

**Comment by gperdomor** [comment]
:+1:

**Comment by pjedrzejewski** [comment]
:fireworks:

**Comment by pamil** [comment]
Just remember to add the same library to dependencies in components / bundles where you will be using it :)

**Pull request merged**
