### PR TITLE
Avoid break of Metadata loading process.

### PR DESCRIPTION
**Pull request by bburnichon**
refs #1630 

In my case, I want to be able to override attribute of numbered entity for example.

Not sure all cases are handled this way but seems to be working on my local tests. (ODM part not tested as I currently don't have this requirement)

### CODE REVIEW

**Comment by bburnichon** [comment]
ping @stloyd @pjedrzejewski. I still need help for this PR.

**Comment by stloyd** [comment]
@bburnichon As you use that class you can easily overwrite that variable if needed:
```php
    function it_should_set_custom_repository_class_and_force_model_to_entity(
        LoadClassMetadataEventArgs $eventArgs,
        ClassMetadata $metadata
    ) {
        $metadata->isMappedSuperclass = true;
        $metadata->getName()
            ->willReturn('spec\Sylius\Bundle\ResourceBundle\Fixture\Entity\Foo');
        $metadata->setCustomRepositoryClass('spec\Sylius\Bundle\ResourceBundle\Fixture\Entity\FooRepository')
            ->shouldBeCalled();
        $eventArgs->getClassMetadata()->willReturn($metadata);

        $this->loadClassMetadata($eventArgs);
    }

**Comment by bburnichon** [comment]
I cannot check that `$metadata->isMappedSuperclass` is `false` after call to `$this->loadClassMetadata($eventArgs)`.

After some research, I found a way to do this, by using an extension of phpspec: bossa/phpspec2-expect.

With this extension, it would be possible to call `expect($metadata->isMappedSuperclass)->toBe(false);` but as stated in http://techportal.inviqa.com/2014/09/11/my-top-ten-favourite-phpspec-limitations/ Limitation # 9, using this extension is not recommended as it violate Law of Demeter.

**Comment by adamelso** [comment]
@bburnichon I've previously written specs for the LoadMetadataSubscribers classes in the [VariationBundle](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/VariationBundle/spec/EventListener/LoadMetadataSubscriberSpec.php) and [AttributeBundle](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AttributeBundle/EventListener/LoadMetadataSubscriber.php) if it helps :)

**Pull request closed without merging**
