### PR TITLE
Upgrade PHPStan to level 4

### PR DESCRIPTION
**Pull request by lruozzi9**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.12                  |
| Bug fix?        | no                                                      |
| New feature?    | no                                                      |
| BC breaks?      | no                                                      |
| Deprecations?   | no |
| Related tickets | partially #14019                      |
| License         | MIT                                                          |

### CODE REVIEW

**Review by NoResponseMate — DISMISSED** [review]

**Comment by jakubtobiasz** [comment]
Hi @lruozzi9 👋🏼!
Thanks for your work. I let myself provide some changes, removing the need of using `ignore` feature :).

I left 2 `ignore` lines in both the `PayumController` and the `DashboardController`, but they'll be removed in Sylius `1.13`.

**Review by jakubtobiasz — APPROVED** [review]

**Review by Rafikooo — APPROVED** [review]

**Comment by lruozzi9** [comment]
Hey @jakubtobiasz! 😃 
> I let myself provide some changes, removing the need of using `ignore` feature :).

Of course, no problem! We both run in the same direction! 😆 

I was not pretty sure about the change in NonChannelLocaleListener.php. I mean, the docblock of the method says that request attributes can not be null, but maybe it is not true!? The comment looks like that!

The change in UserCartRecalculationListener.php could not be considered a BC? You are restricting the type of public method's parameter!

**Comment by jakubtobiasz** [comment]
> I was not pretty sure about the change in NonChannelLocaleListener.php. I mean, the docblock of the method says that request attributes can not be null, but maybe it is not true!? The comment looks like that!

We checked this, and it's never `null`.

> The change in UserCartRecalculationListener.php could not be considered a BC? You are restricting the type of public method's parameter!

This class has no interface and is marked as final. Also, it was throwing an exception once any other type passed. Basically it does the same thing, and nobody can be hurt by this change :).

**Comment by lruozzi9** [comment]
> We checked this, and it's never `null`.

Good! 👍🏻 

> This class has no interface and is marked as final. Also, it was throwing an exception once any other type passed. Basically it does the same thing, and nobody can be hurt by this change :).

This is also true! ✅

**Review by TheMilek — APPROVED** [review]

**Comment by Rafikooo** [comment]
Thank you, @lruozzi9!

**Comment by lruozzi9** [comment]
I have quite ready also lev 5 😎

**Pull request merged**
