### PR TITLE
[Admin][Customer]Issue 8008: Fix inappropriate statistic message

### LINKED ISSUE #8008: irritating order count message if customer has cancelled orders
If a customer cancels an order the backend (sylius_admin_customer_show) says: "This customer has not placed any orders yet" which is not exactly true: the customer placed an order but it's cancelled :) #xberghackathon

### PR DESCRIPTION
**Pull request by bricelalu**
| Q               | A
| --------------- | ---
| Bug fix?        | yes |
| New feature?    | no |
| BC breaks?      | no |
| Related tickets | fixes #8008 |
| License         | MIT |

@TODO: I just updated translations for French and English labels, need help for translating other languages.

### CODE REVIEW

**Comment by Zales0123** [comment]
@bricelalu thank you for this fix - however in the main repo we only fix translations keys and English translations. All other languages should be translated in [our Crowdin](https://crowdin.com/project/sylius).

**Comment by pjedrzejewski** [comment]
@pamil Will Crowdin notice that this key is changed or will we lose translation?

**Comment by mbabker** [comment]
Crowdin will treat it as the key (and old translation) were removed and a new key (and translation) added.

**Comment by bricelalu** [comment]
@Zales0123 ok, sorry I didn't know that. What should I do then? Should I only let the English key and translation in messages.en.yml and revert the other files?

**Comment by pamil** [comment]
I guess we have done a similar renaming back in a day and it worked out well. No risk, no fun, let's see! :D

**Comment by pamil** [comment]
Thanks @bricelalu! :)

**Comment by bricelalu** [comment]
Thanks @pamil

**Pull request merged**
