### PR TITLE
fix verification email url

### LINKED ISSUE #8649: verification email url is not parsed on some email providers
verification email prints the `{{ url|raw }}` (raw url) in the email and some email providers (i.e hotmail) won't parse the URL in to a clickable link.

### PR DESCRIPTION
**Pull request by kochen**
| Q               | A
| --------------- | ---
| Bug fix?        | yes |
| New feature?    | no |
| BC breaks?      | no |
| Related tickets | fixes #8649, relates to #7985 |
| License         | MIT |
replace the Raw URL in the verification email to a link

### CODE REVIEW

**Comment by lchrusciel** [comment]
But is it the only email with the link?

**Comment by kochen** [comment]
@lchrusciel no, also `passwordReset` & `orderConfirmation`.
shall I fix those as well?

**Comment by kochen** [comment]
We should merge/combine it with: #7985

**Comment by lchrusciel** [comment]
They should be merged separately, as the tackle different problems

**Comment by lchrusciel** [comment]
Thanks Mati!

**Pull request merged**
