### PR TITLE
Add app assets processing

### LINKED ISSUE #10332: No default Gulp processor
In order to process assets in my local environment/theme, I need to create a new Gulp processor over and over again. I think it'd be nice if there's a default one provided.

### PR DESCRIPTION
**Pull request by bitbager**
| Q               | A
| --------------- | -----
| Branch?         | master 
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no 
| Related tickets | fixes #10332
| License         | MIT

### CODE REVIEW

**Comment by Zales0123** [comment]
cc @kulczy 🚀

**Comment by migmolrod** [comment]
Is this open to suggestions? I see a couple improvements that could be made to this to have a better out-of-the-box experience and following the other Sylius gulp files (Admin and Ui bundles). But may be a tad overkill for most use cases, I don't know.

**Comment by Zales0123** [comment]
@migmolrod I'd vote for merging this when it will be rebased (cc @bitbager) and accepted (cc @kulczy 😄) and then propose some improvements :) But you can also open a PR basing on this one, to have these changes already open for the discussion 🖖

**Comment by kulczy** [comment]
@bitbager thanks for that! I know that gulp's configuration is not simple, but I'm not a fan of adding more configurations. In addition, we plan to completely migrate to webpack very soon

**Pull request closed without merging**
