### PR TITLE
Fix user serializer

### PR DESCRIPTION
**Pull request by liverbool**
| Q	                       | A     |
|--------------------------|------ |
| Bug Fix?        	| y     |
| New Feature?	| n     |
| BC Breaks?	       | n     |
| Deprecations?	| n     |
| Tests Pass?	       | n     |
| Fixed Tickets	       |        |
| License	               | MIT |
| Doc PR                  |        |

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
@liverbool Nice, could you squash your commits please? 1 is enough for this small change. Thank you very much! :+1:

**Comment by liverbool** [comment]
ping @pjedrzejewski :)

**Comment by amenophis** [comment]
@liverbool You need to squash your 2 commits into onye one before merge

**Comment by liverbool** [comment]
@amenophis commit `#1` been merged from `master` (my bad) i'm not sure that we have too many changed files when i squash my commit `#2` into `#1`, how i can do?

**Comment by amenophis** [comment]
@liverbool you can follow the following docs: https://help.github.com/articles/configuring-a-remote-for-a-fork/ and https://help.github.com/articles/syncing-a-fork/

First is for configuring a remote pointing to the original repository, and the second explain how to update your fork.

**Comment by amenophis** [comment]
@liverbool now your branch is bad, you can recreate a new branch after update it from sylius repo and cherrypick the commit with your changes

**Comment by liverbool** [comment]
@amenophis OK :)

**Pull request closed without merging**
