### PR TITLE
[Translation][ORM][Repository] reduce number of executed queries.

### PR DESCRIPTION
**Pull request by aitboudad**

### CODE REVIEW

**Comment by aRn0D** [comment]
@pjedrzejewski sounds good.

**Comment by stloyd** [comment]
Specs should be adjusted too, other than that :+1:

**Comment by aRn0D** [comment]
Yes please update the specs :)

**Comment by aitboudad** [comment]
spec updated.

**Comment by aRn0D** [comment]
@aitboudad humm, the build is still red

**Comment by aitboudad** [comment]
@aRn0D I'll check it :)

**Comment by aitboudad** [comment]
The build is green now.

**Comment by aRn0D** [comment]
@aitboudad Thank you

**Pull request merged**
