### PR TITLE
[Bug] [Admin] fixed filter reset after changing grid page limits

### LINKED ISSUE #8412: [Grids] Per page has to keep filters informations
In fact, when you change pagination in grid, you loose your filters

Has to change 
```twig
{% set path = path(app.request.attributes.get('_route'), app.request.attributes.get('_route_params')|merge({'limit': limit})) %}
```
To
```twig
{% set path = path(app.request.attributes.get('_route'), app.request.attributes.get('_route_params')|merge(app.request.query)|merge({'limit': limit})) %}
```

Let me know if you want a PR, i could add that quickly

### PR DESCRIPTION
**Pull request by doctorx32**
| Q               | A
| --------------- | -----
| Branch?         | 1.0
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #8412 
| License         | MIT

### CODE REVIEW

**Comment by GSadee** [comment]
Hi @doctorx32! Thank you for your contribution, you chose a good branch in the table, but unfortunately you created a PR to the wrong base branch, I've changed that to 1.0, so please rebase with this branch.

**Comment by doctorx32** [comment]
Hi @GSadee , it looks like I rebased as you asked, please let me know if I should make something else for this PR

**Comment by GSadee** [comment]
It looks like something went wrong with the rebase. If you have problem with rebase, probably the simplest way to do that is to create a new branch from the base branch (`1.0`), cherry-pick only your commit and create a new PR.

**Comment by GSadee** [comment]
Closes in favour of #8857

**Pull request closed without merging**
