### PR TITLE
Using phparkitect github actions

### PR DESCRIPTION
**Pull request by AlessandroMinoccheri**
| Q               | A
| --------------- | -----
| Branch?         | 1.10
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| License         | MIT

### CODE REVIEW

**Review by lchrusciel — APPROVED** [review]
Hey Alessandro,

thanks a lot for your PR. Can you rebase your work to newest master? That should fix the build

**Comment by AlessandroMinoccheri** [comment]
Done @lchrusciel :)

**Review by Zales0123 — APPROVED** [review]

**Comment by Zales0123** [comment]
The base of this pull-request was changed, you need fetch and reset your local branch 
if you want to add new commits to this pull request. **Reset before you pull, else commits
may become messed-up.**

Unless you added new commits (to this branch) locally that you did not push yet, 
execute `git fetch origin && git reset "use-phparkitect-github-actions"` to update your local branch.
 
Feel free to ask for assistance when you get stuck :+1:

**Comment by Zales0123** [comment]
Hey @AlessandroMinoccheri, I've allowed myself to rebase your PR 🖖 it should be ready to merge after the build is green :) thanks!

**Comment by AlessandroMinoccheri** [comment]
Ok thanks @Zales0123

**Review by GSadee — APPROVED** [review]

**Comment by GSadee** [comment]
Thank you, Alessandro! :tada:

**Pull request merged**
