### PR TITLE
Experimental CHANGELOG generation

### PR DESCRIPTION
**Pull request by pjedrzejewski**
Hey folks!

Maintaining a good changelog manually is a pain, I'd rather have our energy and time focused on keeping UPGRADE.md file up-to-date. So I found this nice tool to generate. Only problem is that we have few thousand issues behind so fetching them all actually consumes my GitHub API limit, even with a token.

https://skywinder.github.io/github-changelog-generator/#installation

This CHANGELOG is generated from last 500 issues. I am figuring out the configuration of this tool right now.

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
Preview: https://github.com/pjedrzejewski/Sylius/blob/generate-changelog-automatically/CHANGELOG.md

**Comment by peteward** [comment]
Looks awesome, I love it! :+1:

**Comment by michalmarcinkowski** [comment]
Nice! Do we have control over the sections, so we can declare which labels corresponds to which sections?

**Comment by pjedrzejewski** [comment]
Yes, although configuration is not working so far. :D I will try again. https://skywinder.github.io/github-changelog-generator/#params

**Comment by pjedrzejewski** [comment]
Would be cool to exclude Support Request issues and maybe some more. Also adjust what is bug, what is enhancement (right now it takes only Enhancement label, we want New Feature too)

**Comment by peteward** [comment]
I'm trying it here and can't seem to get it to recognise milestones...

**Comment by michalmarcinkowski** [comment]
@peteward doesn't it work on `tags` only?

**Comment by peteward** [comment]
Yeah, I've worked it out now, thanks ;)

**Comment by gabiudrescu** [comment]
:+1:

**Comment by pjedrzejewski** [comment]
Alternative generator used in #3804 because this one does not support big repos. It stops at 3000 commits... :( Maybe it will be fixed in the future, for now I used https://github.com/lalitkapoor/github-changes#generate-changelog-via-pull-requests.

**Pull request closed without merging**
