### PR TITLE
jms/serializer-bundle is now 1.1

### PR DESCRIPTION
**Pull request by joshuataylor**
Currently sylius is on 0.13.

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
You need to run composer update and also update other composer.json's of individual bundles and components. (I think resource-bundle only)

**Comment by michalmarcinkowski** [comment]
It is not possible to make an update yet. We're waiting for Symfony CMF guys to release compatibile version. Related discussion https://github.com/Sylius/Sylius/issues/3389. 

/cc @dbu @lsmith77

**Comment by dbu** [comment]
sorry, we are working on it but might still take a bit of time.

**Comment by michalmarcinkowski** [comment]
Closing in favour of https://github.com/Sylius/Sylius/pull/3818

**Pull request closed without merging**
