### PR TITLE
Update summary.html.twig

### PR DESCRIPTION
**Pull request by gonzalovilaseca**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| License         | MIT
| Doc PR          |

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
Actually, I think this should be is defined? WDYT?

**Comment by gonzalovilaseca** [comment]
:+1:  I'll update the PR

**Comment by gonzalovilaseca** [comment]
updated!

**Comment by adamelso** [comment]
:+1: but please change the commit message and the PR title to be more descriptive.

**Comment by michalmarcinkowski** [comment]
Closing as WebBundle is already removed.

**Pull request closed without merging**
