### PR TITLE
[SettingsBundle] Removed from the main repository

### LINKED ISSUE #5054: [SettingsBundle] SettingsController references non-existent template
`SettingsController::updateAction` uses `SyliusSettingsBundle:Settings:update.html.twig` as a default template, but that file does not exist.

### LINKED ISSUE #5093: [SettingsBundle] Handle multiple settings form in controller
What do you think if we can path multiple schemas to controller so that we have only one route for many settings? For the sake of better UX.

``` yml
sample_route_settings:
    path: /settings
    defaults:
        _controller: sylius.controller.settings:updateAction
        schema: [sylius_general, sylius_taxation]
        template: AppBundle:Admin:settings.html.twig
```

### PR DESCRIPTION
**Pull request by NeverResponse**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | yes
| Related tickets | closes #5093, closes #5054
| License         | MIT

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
Requires rebasing.

**Comment by pamil** [comment]
Closes #5054.

**Comment by pjedrzejewski** [comment]
@steffenbrem We are no longer using this bundle in the core - are you willing to develop and maintain it? I know you and couple of other people are using it heavily. I can't promise we will invest enough time in its development - we have enough of bundles to worry about already. ;) Let me know!

**Comment by pjedrzejewski** [comment]
Thanks Jasiek!

**Comment by steffenbrem** [comment]
@pjedrzejewski Sure! I am willing to maintain the `SettingsBundle`. Do you want the developments to happen under the `Sylius` organisation or do you prefer that I put it under my own personal account?

**Comment by pjedrzejewski** [comment]
@steffenbrem I will give it some thought and let you know ASAP, we have several other bundles which may need to be moved from Sylius organization.

**Pull request merged**
