### PR TITLE
[Behat] Fix a typo on Paypal context

### PR DESCRIPTION
**Pull request by loic425**
| Q               | A
| --------------- | -----
| Branch?         | 1.4
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| License         | MIT

### CODE REVIEW

**Comment by pamil** [comment]
The base of this pull-request was changed, you need fetch and reset your local branch 
if you want to add new commits to this pull request. **Reset before you pull, else commits
may become messed-up.**

Unless you added new commits (to this branch) locally that you did not push yet, 
execute `git fetch origin && git reset "fix/paypal-context-typo"` to update your local branch.
 
Feel free to ask for assistance when you get stuck :+1:

**Comment by pamil** [comment]
Thanks, Loïc! :1st_place_medal:

**Comment by loic425** [comment]
@pamil Little question, 1.4 branch is not maintained anymore, right?

**Comment by lchrusciel** [comment]
Hey Loic,

unfortunately yes, it is not supported since Oct 4, 2019 (Ref. https://docs.sylius.com/en/1.5/contributing/organization/release-process.html#past-releases)

**Comment by loic425** [comment]
@lchrusciel Ok, thanks, I just asked for pull requests' base branch.

**Pull request merged**
