### PR TITLE
[Content Bundle] Fix #2962 - Update symfony-cmf to ~1.2 in composer.json

### LINKED ISSUE #2962: [ContentBundle] Can't use sylius/content-bundle as standalone.
Here's my basic config:
https://github.com/Joypricecorp/balltoro-com/commit/41cc4e8a3ef489007aee048e44fc4f9411ffd018

#### Problem
I'v followed http://symfony.com/doc/master/cmf/book/installation.html#set-up-the-database 
screen shot 2558-07-05 at 15 34 52

**I try to comment out on `LoadPagesData` file at `Line: 33`**

screen shot 2558-07-05 at 15 37 56

** And run again**:
screen shot 2558-07-05 at 15 40 46

Anyone can help :0

@sylius-team @pjedrzejewski

### PR DESCRIPTION
**Pull request by psyray**
Hi,

A fix for the https://github.com/Sylius/Sylius/issues/2962 bug

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
@psyray Awesome! Could you please squash these 3 commits into 1? Thanks!

**Comment by psyray** [comment]
Done !

**Comment by michalmarcinkowski** [comment]
Thank you Raynald! :+1:

**Comment by pjedrzejewski** [comment]
:+1:

**Pull request merged**
