### PR TITLE
[Fixtures] Fixture loading command asks for confirmation before purging database

### PR DESCRIPTION
**Pull request by NeverResponse**
| Q               | A
| --------------- | ---
| Bug fix?        | no |
| New feature?    | no |
| BC breaks?      | no |
| Related tickets | - |
| License         | MIT |

### CODE REVIEW

**Comment by venyii** [comment]
@pamil but then the command should provide an option to purge the DB in non-interactive mode IMO

**Comment by pamil** [comment]
@venyii yup, `--force` like with `doctrine:database:drop`?

**Comment by NeverResponse** [comment]
Well I see at least 4 ways to go about it:
* `-n` would just run the fixtures, no questions asked (in line with doctrine's fixtures)
* instead of asking, throw a warning until user provides `--force` option (like w/ database dropping)
* same as the first one, but only if user's not on `prod` env, in which case demand `-f`
* `-n` which does nothing unless there's also `-f` given

Whichever's less annoying to the end user's fine with me.

**Comment by michalmarcinkowski** [comment]
Thanks Janek! 👍

**Pull request merged**
