### PR TITLE
Don't render _token field if it's already rendered

### LINKED ISSUE #12438: Form problem with _token field on custom form
**Sylius version affected**: 1.9

**Description**  

When using a custom form template in admin, I have this error : 
```
An exception has been thrown during the rendering of a template ("Field "_token" has already been rendered, save the result of previous render call to a variable and output that instead.").
```

It is related to https://github.com/Sylius/Sylius/pull/12378 which fixed the issue only if a custom form is not defined.

**Steps to reproduce**  

Have a ressource form with custom form defined in controller.

**Possible Solution**  
Use : 
```twig
{% if not form._token.isRendered %}
    {{ form_row(form._token) }}
{% endif %}
```

### PR DESCRIPTION
**Pull request by maximehuran**
| Q               | A
| --------------- | -----
| Branch?         | 1.9
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #12438
| License         | MIT

### CODE REVIEW

**Review by pamil — APPROVED** [review]
Rebasing to 1.9 branch in a sec

**Comment by pamil** [comment]
The base of this pull-request was changed, you need fetch and reset your local branch 
if you want to add new commits to this pull request. **Reset before you pull, else commits
may become messed-up.**

Unless you added new commits (to this branch) locally that you did not push yet, 
execute `git fetch origin && git reset "feature/token-field-custom-form"` to update your local branch.
 
Feel free to ask for assistance when you get stuck :+1:

**Comment by pamil** [comment]
Triggering the new build, should be green now

**Review by Zales0123 — COMMENTED** [review]
👍 Shouldn't we do this fix also for `Crud/Update/_content.html.twig`?

**Comment by pamil** [comment]
Thank you, Maxime! :tada:

**Comment by pamil** [comment]
@Zales0123 fixed that in #12454.

**Comment by vvasiloi** [comment]
I think this block should be after it's parent block, i.e.:
```
    {% if configuration.vars.templates.form is defined %}
        {% include configuration.vars.templates.form %}
    {% else %}
        {{ form_widget(form) }}
    {% endif %}

    {% if not form._token.isRendered %}
        {{ form_row(form._token) }}
    {% endif %}
  ```
   Otherwise, default forms will be rendered without the token.

**Comment by pamil** [comment]
Wouldn't `form_widget(form)` render all the not rendered fields anyway?

**Comment by vvasiloi** [comment]
@pamil not if it's customized via form themes and the token is not rendered, which I personally did a lot in the past and upgrading created issues.
There's nothing to lose by moving that block anyway.

**Pull request merged**
