### PR TITLE
WIP Add Plugin Creator Command

### PR DESCRIPTION
**Pull request by tonicospinelli**
| Q               | A
| --------------- | -----
| Branch?         | master
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | -
| License         | MIT

It's just a lightweight proposal to automate the creation of the Sylius Plugin.
This work in progress is to onboard new developers to create their sylius plugins.

image

### CODE REVIEW

**Comment by tonicospinelli** [comment]
if you understand this command makes sense, please, give me a feedback and let's improve it 🤗

**Comment by loevgaard** [comment]
It shouldn't be in this repository. I have tried to something similar in this skeleton: https://github.com/Setono/SyliusPluginSkeleton with [init file](https://github.com/Setono/SyliusPluginSkeleton/blob/master/init).

**Comment by vvasiloi** [comment]
This should probably be in https://github.com/Sylius/PluginSkeleton.

**Comment by tonicospinelli** [comment]
@vvasiloi @loevgaard

Giving my rationale on the subject...

The core is responsible for the Sylius resources and ecosystem. Therefore, it is fair that you provide any tool to extend your capabilities.

In my point of view, the plugin is an alternative to extend or add any new resource to the Sylius platform. Therefore, this repo may be responsible for providing tools and instructions for extending them.

With that in mind, any tools used to extend or add resources, or command lines, or any instructions for creating or installing a new Sylius plugin or resources should be here.

For example, the symfony framework provides an empty [skeleton] (https://github.com/symfony/skeleton) to create a new project.

Also, it can be an opportunity to start an initiative to install or generate a new plugin based on existing or new features.

Does it make sense?

**Comment by vvasiloi** [comment]
@tonicospinelli 
It makes sense, however I have some counter arguments.
The Symfony Skeleton is the equivalent of Sylius Standard, not the plugins.
I see what you're trying to do more as an optional dev dependency like [Symfony Maker](https://symfony.com/doc/current/bundles/SymfonyMakerBundle/index.html)
Also, I think it's better to be avoid with adding more stuff to the core, when possible, otherwise it will be harder and harder to maintain.
What do you think?

**Comment by jakubtobiasz** [comment]
Closing as this functionality is covered in https://github.com/Sylius/PluginTemplate

**Pull request closed without merging**
