### PR TITLE
Register state machine configs in bundle extensions

### PR DESCRIPTION
**Pull request by Strontium-90**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | refactor |
| BC breaks? | no |
| Deprecations? | no |
| Fixed tickets | no |
| License | MIT |
| Doc PR | - |

Some questions:
1) Should `SyliusPaymentBundle`, `SyliusOrderBundle` etc work without StateMachineBundle?
2) Which bundle should have dependency in composer.json from `winzou/state-machine-bundle`: `ResourceBundle` or `SyliusPaymentBundle`, `SyliusOrderBundle`?..
3) I keep same structure of state-machine.yml files for BC, right?

### CODE REVIEW

**Comment by Strontium-90** [comment]
ping @pjedrzejewski. Lets simplify configs!

**Comment by okwinza** [comment]
Not sure 4 lines in a config file worth a bunch of copy-pasted code. Moreover, it definitely won't simplify anything for a sylius newcomer.

Although moving "sylius.callback.complete_order.class" parameter from core/services.xml seems like a good idea, IMO.

**Comment by Strontium-90** [comment]
@okwinza, you should copy-paste this lines every time you use these bundles standalone.

**Comment by pjedrzejewski** [comment]
I don't like the duplications as well, but let's have some discussion about this. I am definitely for simplifying things.

**Comment by Strontium-90** [comment]
Same issue with JMSSerializer configs:
```yml
jms_serializer:
    metadata:
        directories:
            sylius-user:
                namespace_prefix: "Sylius\\Component\\User"
                path: "@SyliusUserBundle/Resources/config/serializer"
            sylius-addressing:
                namespace_prefix: "Sylius\\Component\\Addressing"
                path: "@SyliusAddressingBundle/Resources/config/serializer"
```

**Pull request closed without merging**
