### PR TITLE
[ApiBundle] Change api client public id to be simply random id

### PR DESCRIPTION
**Pull request by michalmarcinkowski**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

Related discussion https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/issues/328

### CODE REVIEW

**Comment by aRn0D** [comment]
Specs are missing ;)

**Comment by michalmarcinkowski** [comment]
@aRn0D You got me! Forgot about to update :)

**Comment by michalmarcinkowski** [comment]
Done :wink:

**Comment by aRn0D** [comment]
you should generate yours empties classes with phpspec ;)

**Comment by pjedrzejewski** [comment]
Thank you Michal!

**Pull request merged**
