### PR TITLE
Removed ROLE_SYLIUS_ADMIN

### PR DESCRIPTION
**Pull request by cdaguerre**

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
:+1:

**Comment by pjedrzejewski** [comment]
These builds. That's just insane. :) Thank you Christian!

**Comment by cdaguerre** [comment]
Blazing fast ;) I think this closes #3453 @pjedrzejewski

**Comment by psyray** [comment]
Thanks for this but you forgot one :)
PR submitted above

**Comment by psyray** [comment]
I think also we should set up a migration script to remove the ROLE_SYLIUS_ADMIN from db, no ?

**Comment by michalmarcinkowski** [comment]
@psyray someone can use this role in his custom code, so I don't think we should remove it since this additional role doesn't break anything :)

**Comment by psyray** [comment]
ok, you're right

**Pull request merged**
