### PR TITLE
[API] Product filter no longer crashes when using multiple taxons

### PR DESCRIPTION
**Pull request by palttamas**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.13                   |
| Bug fix?        | yes                                                       |
| New feature?    | no                                                      |
| BC breaks?      | no                                                   |
| Deprecations?   | no  |
| Related tickets | [#15107](https://github.com/Sylius/Sylius/issues/15107)                      |
| License         | MIT                                                          |

### CODE REVIEW

**Comment by jakubtobiasz** [comment]
Hello @palttamas 👋🏼
Everything seems great, can you just target this change against `1.12` as it's a bug 🙏🏻?

**Comment by palttamas** [comment]
> Hello @palttamas 👋🏼 Everything seems great, can you just target this change against `1.12` as it's a bug 🙏🏻?

I made a separate PR for 1.12 https://github.com/Sylius/Sylius/pull/15161

1.12 is more simplistic in terms of the collection extension, also the a transformer is missing from 1.12

**Comment by jakubtobiasz** [comment]
We upmerge `1.12` into `1.13` every time, so I'll just this PR as a reference while upmerging, and close it after it :). Thank you, I'll review your PR today.

**Comment by jakubtobiasz** [comment]
Closing as #15161 containing these changes has been upmerged into `1.13` along with #15163.

**Pull request closed without merging**
