### PR TITLE
[ADMIN] layout modifications - crud container fluid, data_table r…

### PR DESCRIPTION
**Pull request by ars-creo**
…emoved text-nowrap class
[ AdminBundle Template ]

| Q               | A
|-----------------|-----
| Branch?         | 2.0
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #X, partially #Y, mentioned in #Z
| License         | MIT

Before
Screenshot from 2024-11-18 11-33-22
After
Screenshot from 2024-11-18 11-37-07

Small change in layout template for CRUD grid and data_table. Container now is fluid for 100% with and text is wrapping in the name cell.

### CODE REVIEW

**Comment by kulczy** [comment]
Hi, @ars-creo. We’re exploring ways to make better use of the panel space, but applying a generic fluid and wrap to the entire table won’t look good on all scenarios. Anyway, thanks for the suggestions!

**Comment by ars-creo** [comment]
Hi @kulczy
Thank you for your feedback. I understand the importance of maintaining a consistent design across various scenarios, but I believe this issue is more critical and should be treated as a bug rather than a feature.

Currently, with long product titles, the edit icons are not visible, and customers often report being unable to edit products. They don’t realize that they need to scroll horizontally far to the right to access these icons. This creates significant usability challenges, as users expect the essential actions to remain accessible without additional effort.

I’ve attached a screenshot to illustrate the issue clearly. I hope we can revisit this topic and find a solution that balances both usability and design consistency.
Screenshot from 2024-11-20 12-59-12
Screenshot from 2024-11-20 12-59-27

**Comment by ars-creo** [comment]
@kulczy Perhaps removing the text-nowrap class could be a solution that satisfies both sides, as it would improve usability without introducing excessive changes to the overall design?
Screenshot from 2024-11-20 13-04-03

**Comment by kulczy** [comment]
You’re right, the text-nowrap class should be removed. If you could, please prepare a PR with only the removal of text-nowrap, and we can merge it

**Pull request closed without merging**
