### PR TITLE
[Twig][UiBundle] fix value's label on string filter type

### PR DESCRIPTION
**Pull request by loic425**
| Q               | A
| --------------- | ---
| Bug fix?        | yes |
| New feature?    | no|
| BC breaks?      | no|
| Related tickets |  |
| License         | MIT |

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
Actually, this is on purpose for Shop. We should look at some better solution later.

**Comment by loic425** [comment]
@pjedrzejewski [](url)
are you really sure ?
I don't see any change on shop search box.
capture d ecran 2017-09-12 a 14 36 10

**Comment by lbaey** [comment]
👍

**Comment by pjedrzejewski** [comment]
@loic425 ha, you are right. Thank you! :)

**Pull request merged**
