### PR TITLE
Making coupon code length configurable.

### PR DESCRIPTION
**Pull request by Richtermeister**

### CODE REVIEW

**Comment by Richtermeister** [comment]
Wondering if this would be useful on a per-instruction level..

**Comment by stloyd** [comment]
Sounds reasonable, but I guess that this setting could be pushed to `Instruction` class so you can set it while generating coupons, yet having option to use global setting like this is good idea too IMO.

**Comment by pjedrzejewski** [comment]
Yeah! Let's make it configurable on Instruction as well, should be simple, hm?

**Comment by Richtermeister** [comment]
Agreed, will do.

**Comment by stloyd** [comment]
@Richtermeister ping ;)

**Comment by stloyd** [comment]
@Richtermeister Could you rebase?
@pjedrzejewski Feedback?

**Comment by pjedrzejewski** [comment]
Looks good to me, we just need a rebase. :)

**Comment by Richtermeister** [comment]
Sorry guys :) Will rebase & wrap this up this week.

**Comment by stloyd** [comment]
@Richtermeister ping ;)

**Comment by Rvanlaak** [comment]
@Richtermeister ping

**Comment by pjedrzejewski** [comment]
@Richtermeister ping! :)

**Comment by michalmarcinkowski** [comment]
@Richtermeister ping :)

**Comment by michalmarcinkowski** [comment]
https://github.com/Sylius/Sylius/pull/3339 will continue this. Thanks @Richtermeister!

**Pull request closed without merging**
