### PR TITLE
Orders index API endpoint

### PR DESCRIPTION
**Pull request by Zales0123**
| Q               | A
| --------------- | -----
| Branch?         | 1.3
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | replaces https://github.com/Sylius/Sylius/pull/10138
| License         | MIT

Order API is missing the `/orders` endpoint described in the docs
https://docs.sylius.com/en/1.2/api/orders.html. Thank you, @JaisDK, for your amazing work!

### CODE REVIEW

**Comment by loevgaard** [comment]
@Zales0123 will this be merged? :)

**Comment by pamil** [comment]
The base of this pull-request was changed, you need fetch and reset your local branch 
if you want to add new commits to this pull request. **Reset before you pull, else commits
may become messed-up.**

Unless you added new commits (to this branch) locally that you did not push yet, 
execute `git fetch origin && git reset "orders-index-api-endpoint"` to update your local branch.
 
Feel free to ask for assistance when you get stuck :+1:

**Comment by pamil** [comment]
Thank you, Mateusz! :tada:

**Comment by loevgaard** [comment]
Great! Thanks, Pamil! Will this be included in the next patch or minor release? (I really hope patch :))

**Comment by JaisDK** [comment]
Yay!

**Comment by pamil** [comment]
@loevgaard as much as I'd like to merge it as a bug, it's a feature nonetheless - the documentation was buggy in fact. I can't release it in a patch, because it's restricted strictly to bugfixes to the existing features.

It will be included in the next minor, but the good news is that it's coming one month earlier (#10171), in late April. You might find https://github.com/cweagans/composer-patches useful to have it fixed in your application until it's released in Sylius.

**Comment by loevgaard** [comment]
Thanks for mentioning `cweagans/composer-patches`. I didn't know about that. Do you know if the patch url I should use is just this PR's patch url, i.e. https://github.com/Sylius/Sylius/pull/10161.patch ?

**Comment by pamil** [comment]
Yeah, it should work that way! Thanks to @mmenozzi for showing me that before, it's quite a handy tool.

**Comment by mmenozzi** [comment]
You’re welcome @pamil! Happy to help you!

**Comment by lchrusciel** [comment]
I have to say `cweagans/composer-patches` is just a pure gold <3

**Pull request merged**
