### PR TITLE
Fix for #4098, applying #3978 again

### PR DESCRIPTION
**Pull request by pamil**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #4098
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by michalmarcinkowski** [comment]
Hah, well smuggled in :smile:

**Comment by michalmarcinkowski** [comment]
We should also get rid of [step definition]( https://github.com/michalmarcinkowski/Sylius/blob/4dad2b7e8423f544247a8ea21f8b0bbdf58535c6/src/Sylius/Bundle/WebBundle/Behat/WebContext.php#L649-L649).

**Comment by pamil** [comment]
@michalmarcinkowski roger that!

**Comment by michalmarcinkowski** [comment]
:+1:

**Pull request merged**
