### PR TITLE
[WIP] Add Subscription Bundle

### PR DESCRIPTION
**Pull request by Richtermeister**
This goal of this PR is to add subscription features to Sylius, to support recurring orders, club-memberships, etc.

sylius_subscriptions1

sylius_subscriptions2

sylius_subscriptions3

The model revolves around subscriptions and subscription items, which on the application level can be linked specific products/variants. The scheduling mechanism is decoupled so that complex scheduling scenarios can be supported. A simple interval-based scheduler is included. The bundle also comes with a command and a processor harness to process subscriptions that are due. Actual processing logic is delegated to the application layer.

I also added a new section to the customer panel to allow customers to manage their subscriptions.

Feedback pleez!
Thanks! :)

Todos:
- [ ] Make Interval Units a dropdown and configurable
- [ ] Add twig extension to format interval unit + frequency, i.e. "Every 10 days / Every Month"
- [ ] Add Behat Features
- [ ] Add ability to create new subscriptions (from cart / during checkout)
- [ ] Add ability to add items to existing subscription (how to select product variant?)
- [ ] Add admin capabilities
- [ ] Add log / retry / audit capabilities (optional, could be separate bundle)

### CODE REVIEW

**Comment by adremasu** [comment]
any news about this issue?

**Comment by drewmach** [comment]
I just want to give a shout out that this is functionality I am looking for in Sylius as well. I will give a shot at  trying to implement the repo's linked above and add the missing functionality, but would be awesome if this would be implemented in the core.

**Comment by kzap** [comment]
@pjedrzejewski 
so subscriptions were never merged in?

is there any core component for this even?

or is subscriptions considered an archetype or a special pricing calculator on a product?

whats the easiest way one would extend the core to have subscriptions?

**Comment by MichaelMackus** [comment]
@kzap development for this is being continued in the repos linked above.. the PR is on a hiatus until dev team is interested in merging

**Comment by michalmarcinkowski** [comment]
@MichaelMackus @kzap unfortunately this feature will not land on master in Sylius 1.0 release. We're in stabilization phase and as @pjedrzejewski comment [here](https://github.com/Sylius/Sylius/pull/385#issuecomment-61678130) we have other more important features to polish. We will be interested to resume this work later on ;)

**Comment by kzap** [comment]
Thanks for keeping a updated repo..ill use yours then

**Comment by xrow** [comment]
Hi, I have an requirement on this feature.  The last update is already long ago. I am wondering, if one can provide an update on the roadmap / timings. So far is looks like that this will never get merged since it is so old. Please don't mind asking. I am just curious. Thx.

**Comment by lchrusciel** [comment]
I'm not sure if there is any point in keeping this one open. Too many things have changed. Thus it is a good plugin proposal :)

**Comment by gadelkareem** [comment]
hmm, any plugin already available providing this feature?

**Pull request closed without merging**
