### PR TITLE
Made attribute bundle configuration methods protected

### PR DESCRIPTION
**Pull request by mihaichitic**
The goal is to override them in extended classes.

I want to implement AttributeValueTranslation and avoid code duplication (continue to use the validation from parent, and just append 'translation' under 'attribute_value' key)

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
Hey @mihaichitic! Having AttributeValues translatable is something we would be interested to have in core. Have you considered working on this? We generally do not recommend extending these methods (and configuration classes in general), that's why they are private. :) Let me know!

**Comment by Tetragramat** [comment]
I'm sorry, that referenced comits are my big mistake.

**Comment by pjedrzejewski** [comment]
@mihaichitic Please reopen if still interested in this issue. Translatable attribute values is a separate topic, but generally I don't think we will ever recommend extending these classes thus they should stay private. Thanks!

**Comment by a2xchip** [comment]
:open_mouth: Are not attribute values translatable? :scream: @pjedrzejewski

**Pull request closed without merging**
