### PR TITLE
[Documentation] Rework Cookbook organization

### PR DESCRIPTION
**Pull request by CoderMaggie**
| Q               | A
| --------------- | -----
| Branch?         | 1.0
| Doc fix?        | kinda
| New docs?    | no
| Related tickets | 
| License         | MIT

For quite a long time I've been struggling with the organization of our current Cookbook 📚 . 
It has grown amazingly, and it now has 28 articles in it. But on the other hand, with each new article it was becoming harder to look at. Even though I know this chapter very well I used to have problems in finding anything among this long list of articles.

I'm proposing to divide the Cookbook into chapters. At least for me it looks better now 🎉 .

**How it used to be:**
cookbook-old

**How it will be now:**
cookbook

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
Great idea!

**Comment by dukusz** [comment]
Far more better! ;)

**Comment by psihius** [comment]
Awesome

**Comment by pamil** [comment]
Can you rebase it to 1.0? No BC policy for docs as for now and it would make the maintenance easier.

**Comment by CoderMaggie** [comment]
If you wish so, sure @pamil :)

**Comment by CoderMaggie** [comment]
@pamil done!

**Comment by lchrusciel** [comment]
It looks awesome now! Thanks Magda 🍰

**Pull request merged**
