### PR TITLE
Speed up phpunit tests by using dama/doctrine-test-bundle

### PR DESCRIPTION
**Pull request by dmaicher**
| Q               | A
| --------------- | ---
| Bug fix?        | no |
| New feature?    | yes |
| BC breaks?      | no |
| Related tickets | - |
| License         | MIT |

I propose to use https://github.com/dmaicher/doctrine-test-bundle for speeding up phpunit tests involving doctrine.

Run on php 5.6.

Before:
```
PHPUnit 5.7.9 by Sebastian Bergmann and contributors.

...............................................................  63 / 231 ( 27%)
............................................................... 126 / 231 ( 54%)
............................................................... 189 / 231 ( 81%)
..........................................                      231 / 231 (100%)

Time: 1.35 minutes, Memory: 147.50MB

OK (231 tests, 466 assertions)
```

After:
```
PHPUnit 5.7.9 by Sebastian Bergmann and contributors.

...............................................................  63 / 231 ( 27%)
............................................................... 126 / 231 ( 54%)
............................................................... 189 / 231 ( 81%)
..........................................                      231 / 231 (100%)

Time: 44.17 seconds, Memory: 133.25MB

OK (231 tests, 466 assertions)
```

It also provides test isolation regarding database changes as all tests are running inside a transaction.

Let me know what you think :wink:

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
Nice, thanks David!

**Comment by dmaicher** [comment]
:+1:

**Comment by pjedrzejewski** [comment]
I believe it also affects Sylius-Standard? Can you have a quick look if phpunit still works there? :)

**Comment by dmaicher** [comment]
Will check it :wink:

**Comment by dmaicher** [comment]
Actually I don't think it impacts Sylius Standard? Anyway I think it also makes sense to use the bundle there and have some phpunit default config: https://github.com/Sylius/Sylius-Standard/pull/162

**Pull request merged**
