### PR TITLE
Run test against doctrine 2.15

### PR DESCRIPTION
**Pull request by alexander-schranz**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.12 or 1.13                   |
| Bug fix?        | yes                                                      |
| New feature?    | no                                                      |
| BC breaks?      | no                                                      |
| Deprecations?   | no |
| Related tickets | https://github.com/doctrine/orm/issues/10552                    |
| License         | MIT                                                          |

Just test if @sylius run into the same issues as @sulu with the current doctrine/orm `2.15@dev` version.

Testing: https://github.com/doctrine/orm/pull/10554

### CODE REVIEW

**Comment by alexander-schranz** [comment]
After testing Sylius seems to run into the same issue as @sulu:

```
 The target entity class Sylius\Component\Taxonomy\Model\TaxonInterface
 specified for Sylius\Component\Taxonomy\Model\Taxon::$root is not an entity class.     
```

https://github.com/Sylius/Sylius/actions/runs/4313426016/jobs/7525270130

Bildschirmfoto 2023-03-02 um 13 22 53

**Comment by jakubtobiasz** [comment]
Hi @alexander-schranz 🙋🏼‍♂️!
Thank you very much for sharing this issue with the upcoming `doctrine/orm` release. I've created a ticket in our internal issue tracking system, and we'll take care of it 🙏🏻.

I guess we can close this PR for now anyway :).

**Comment by alexander-schranz** [comment]
@jakubtobiasz it mostly just require some testing of @mpdude pull request here: https://github.com/doctrine/orm/pull/10554. But sadly your CI is not yet setup to test composer against fork (missing COMPOSER_TOKEN). I tried to add it but the `COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}` maybe is not allowed in the root level here and need to be set per Job which I was afraid to mess something else up.

**Comment by jakubtobiasz** [comment]
@alexander-schranz I guess it's org-level setting. Thanks for suggestion :D.

**Comment by alexander-schranz** [comment]
The Doctrine/orm pull request was merged. I did rerun thest tests here: https://github.com/Sylius/Sylius/pull/14889 And as seen in:

 - https://github.com/Sylius/Sylius/actions/runs/4525498213/jobs/7970058736?pr=14889 vs https://github.com/Sylius/Sylius/actions/runs/4313426016/jobs/7525270130

We see the error with the `UserBundle` and `ReviewBundle` is gone. So Sylius should now be again compatible with `doctrine/orm` `2.15`.

PS: I recommend Sylius that atleast one CI runs tests against `composer config minimum-stability dev` so errors in dependencies can be catched before they are released there. We are doing this @sulu and did already catch errors in @symfony this way before they hit a stable version release.

**Pull request closed without merging**
