### PR TITLE
[Composer] Clean up json format and remove translation-bundle required.

### PR DESCRIPTION
**Pull request by liverbool**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| License         | MIT
| Doc PR          | 

ping @pjedrzejewski `search-bundle` not update to `18.x-dev` in packagist.

### CODE REVIEW

**Comment by lchrusciel** [comment]
:+1:

**Comment by pjedrzejewski** [comment]
Will be fixed in https://github.com/Sylius/Sylius/pull/4415, I am pretty sure we will merge it first, but thanks @liverbool!

**Comment by liverbool** [comment]
:+1: Good news!! @pjedrzejewski

**Comment by pjedrzejewski** [comment]
Can be closed, fixed in #4415. :)

**Pull request closed without merging**
