### PR TITLE
[Maintenance] Added promotion form theme override in UPGRADE-1.9.md

### PR DESCRIPTION
**Pull request by SVillette**
| Q               | A
| --------------- | -----
| Branch?         | 1.12
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | -
| License         | MIT

This PR aims to add documentation in UPGRADE-1.9.md about changes made in c18f11e.

It has been a blocking issue to me and I think it has its place in the upgrade file

### CODE REVIEW

**Review by Arminek — APPROVED** [review]

**Comment by SVillette** [comment]
Hello, any news about when it going to be merge ?

**Comment by SVillette** [comment]
Friendly ping @GSadee and @Zales0123, should I close this PR ? (as this is opened since September and Sylius 1.11 is released now)

**Comment by SVillette** [comment]
Hi @lchrusciel, sorry for pinging you again. This PR is opened since a long time now. 1.9 is not supported anymore but do you think this change could be useful for anyone upgrading a Sylius project to newer versions ? 

Thank you.

**Comment by jakubtobiasz** [comment]
To avoid upmerging from non-maintained versions, we've decided to merge this change into 1.12. Thanks!

**Review by jakubtobiasz — APPROVED** [review]

**Comment by jakubtobiasz** [comment]
Thank you, @SVillette!

**Pull request merged**
