### PR TITLE
Fixed email template in API - SendOrderConfirmationHandler

### PR DESCRIPTION
**Pull request by antonioperic**
| Q               | A
| --------------- | -----
| Branch?         | 1.7, 1.8 or master 
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no 
| License         | MIT

Wrong settings and template are used in API email on order confiramtion

### CODE REVIEW

**Review by lchrusciel — APPROVED** [review]
I would like to merge it, but I think it would be good to add some functional test in ApiBundle, to ensure that this bundle and AdminBundle stays decoupled

**Comment by antonioperic** [comment]
@lchrusciel can you explain a little bit?

**Comment by lchrusciel** [comment]
I thought about some short PHPUnit test in ApiBundle, that would trigger sending an email. As each package PHPUnit tests are run in separation from others, we would have confidence, that it works without AdminBunle 
image

**Comment by NoResponseMate** [comment]
Hi @antonioperic,
The bug has been fixed in [1.9](https://github.com/Sylius/Sylius/pull/12668).
Sorry for the late response, thanks for raising this issue and the proposal 🍻

**Pull request closed without merging**
