### PR TITLE
Update version of sensio/distribution-bundle to 3.0

### PR DESCRIPTION
**Pull request by MblKiTA**
Facing this issue: https://github.com/sensiolabs/SensioDistributionBundle/pull/150 while using sensio/distribution-bundle v2.3.22.
3.0 branch should be compatible with symfony 2.3 and higher per http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/index.html

### CODE REVIEW

**Comment by michalmarcinkowski** [comment]
@MblKiTA could you rebase this PR?

**Comment by MblKiTA** [comment]
@michalmarcinkowski, rebased

**Comment by michalmarcinkowski** [comment]
@MblKiTA have you pushed your changes? I don't see any update.

**Comment by MblKiTA** [comment]
Seems I've done it.

**Comment by steffenbrem** [comment]
@MblKiTA I think he means you have to squash your commits I guess.

**Comment by michalmarcinkowski** [comment]
Something is wrong, cause I see 13 commits... I would suggest to switch on a clean master branch and apply this change once again, it will be probably faster than struggling with desynchronized rebase. Please remember to update the `composer.lock` file also. Thanks for your effort!

**Comment by MblKiTA** [comment]
@michalmarcinkowski is it ok now?

**Comment by michalmarcinkowski** [comment]
@MblKiTA please run `composer update sensio/distribution-bundle` in order to update `composer.lock` file, then it's ready to merge :wink:

**Comment by MblKiTA** [comment]
@michalmarcinkowski, I've created a new pull request for this:
https://github.com/Sylius/Sylius/pull/3826

**Pull request closed without merging**
