### PR TITLE
[WIP][API] Fixing user permissions

### PR DESCRIPTION
**Pull request by starspire**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #3815
| License       | MIT
| Doc PR        | 

I added correct permissions to access users via API but now instead of 403 denied I get 500 internal error without any message or anything else. Any suggestion how to go further?

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
@starspire What about logs?

**Comment by starspire** [comment]
@pjedrzejewski  There is nothing special I think. Probably the request is closing in unexpected way :/ There are logs from this particular request.
[dev.log.txt](https://github.com/Sylius/Sylius/files/91520/dev.log.txt)

**Comment by michalmarcinkowski** [comment]
@starspire are you able to add tests for the User API (like here https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Tests/Controller/ShippingCategoryApiTest.php)? You can find this blog post useful http://lakion.com/blog/tdd-your-api-with-symfony-and-phpunit.

**Comment by starspire** [comment]
I'll give it a shot, but not sooner than in the next week :-)
15 sty 2016 14:09 "Michał Marcinkowski" <notifications@github.com>
napisał(a):

**Comment by michalmarcinkowski** [comment]
That's fine, we can wait. Thanks!

**Comment by michalmarcinkowski** [comment]
Closing in favor of #4833.

**Pull request closed without merging**
