### PR TITLE
Make ResourceBundle routing working correctly again

### LINKED ISSUE #8165: On Symfony 3.3.2, problem parsing routing/cart.yml
```
[Symfony\Component\Config\Exception\FileLoaderLoadException]                                                                                                              
  The file "alias: sylius.order                                                                                                                                             
  path: '" does not exist in /var/www/vendor/sylius/sylius/src/Sylius/Bundle/AdminApiBundle/Resources/config/routing/cart.yml (which is being imported from "/var/www/vend  
  or/sylius/sylius/src/Sylius/Bundle/AdminApiBundle/Resources/config/routing/main.yml"). 
```
Am I the only one getting this error ?
If I remove this part, everything works.
```
sylius_admin_api_carts:
    resource: |
        alias: sylius.order
        path: '/'
        only: [index]
        grid: sylius_admin_api_cart
        section: admin_api
        serialization_version: $version
    type: sylius.resource_api
```

### PR DESCRIPTION
**Pull request by pamil**
| Q               | A
| --------------- | ---
| Bug fix?        | yes |
| New feature?    | no |
| BC breaks?      | no |
| Related tickets | kinda fixes #8165, helps #8120 |
| License         | MIT |

Makes it compatible with Symfony 3.3 🎉

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
👍

**Comment by pamil** [comment]
Issue at Symfony side: symfony/symfony#23412.

**Comment by loic425** [comment]
@pamil @pjedrzejewski 
Does that also fix that problem ?

`app_backend_address:
    resource: |
        alias: app.address
        section: backend
        templates: :backend/crud
        except: ['show']
        redirect: index
        grid: app_backend_address
        vars:
            all:
                subheader: app.ui.manage_addresses
                templates:
                    form: backend/address/_form.html.twig
            index:
                icon: map
    type: sylius.resource` 

which throw this error:
The file "alias: app.address
section: backend
templates: :backend" does not exist in /var/www/app_name/app/config/routing/backend/address.yml (which is being imported from "/var/www/app_name/app/config/routing/backend.yml").

**Comment by pamil** [comment]
@loic425 it's a workaround on our side, the issue I've posted in previous comment tries to address it at Symfony side.

**Comment by loic425** [comment]
@pamil 
Ok thx
So the bug is on symfony side and beta3 upgrade won't fix this problem ?

**Comment by pamil** [comment]
We will wait with beta.3 until all issues listed in #8120 are resolved.

**Comment by loic425** [comment]
@pamil 
Yes, great :)

**Pull request merged**
