### PR TITLE
[minor] SCA

### PR DESCRIPTION
**Pull request by kalessil**
| Q               | A
| --------------- | -----
| Branch?         | master
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | n/a
| License         | MIT

Php Inspections (EA Ultimate): new findings

### CODE REVIEW

**Comment by kalessil** [comment]
One of travis build envs has errored - not connected with the changes.

**Comment by pamil** [comment]
Travis build should be fine now 🎉

**Comment by kalessil** [comment]
@pamil : worked, huge thank you!

**Comment by pamil** [comment]
Thank you, Vladimir! 🎉

**Pull request merged**
