### PR TITLE
Fix perfomance issue by adding index for "enabled" field

### PR DESCRIPTION
**Pull request by dbalabka**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.13                   |
| Bug fix?        | yes                                                       |
| New feature?    | no                                                       |
| BC breaks?      | no                                                       |
| Deprecations?   | no |
| Related tickets | n/a                      |
| License         | MIT                                                          |

### CODE REVIEW

**Comment by jakubtobiasz** [comment]
Hi @dbalabka!
Did you run any performance tests before/after?

**Comment by dbalabka** [comment]
@jakubtobiasz, yes. Are you interested in particular numbers?

**Comment by jakubtobiasz** [comment]
@dbalabka it'd be great to have some insight 🙌🏼!

**Comment by dbalabka** [comment]
@jakubtobiasz , I would try to provide some benchmarks. However, using the index on column that contains a flag value, probably, is a common sense, especially, if the field included in most of the queries. Do you have any concerns about such change in database schema?

**Comment by jakubtobiasz** [comment]
@dbalabka once in my life we've dropped a “test” index (not in Sylius), and it caused terrible performance. Since then, I'm careful when I touch indexes 😂.

But it was just “good to know”, not requirements from my side :).

**Comment by dbalabka** [comment]
@jakubtobiasz , these changes add the index instead of removing it. Therefore, performance degradation is unlikely (in some cases, it is possible). Please give me some time to show the difference. It may not be possible to reproduce on small amounts of products. Does the Sylius team have any testing database for such cases?

**Comment by jakubtobiasz** [comment]
Hi @dbalabka!
After a meeting with a team – we decided we would rather not merge this PR. This is a project specific, and it might be a topic for a performance guide in our docs. Just in case, this decision has nothing with not providing any data. We just want (at least for now) to stay with a basic configuration, and allow project teams to decide how they want to optimize concrete places in Sylius.

Thanks for contribution!

**Comment by dbalabka** [comment]
@jakubtobiasz , please re-evaluate your decision because most used repositories rely on `enabled` columns which should lead to a full table scan (in case MySQL InnoDB database engine):
1. https://github.com/Sylius/Sylius/blob/7bdd9325f334266a2308a713644cc180bc2c7e62/src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php#L97
2. https://github.com/Sylius/Sylius/blob/7bdd9325f334266a2308a713644cc180bc2c7e62/src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php#L58

It is not a case only if you are fetching all data from Elasticsearch.

**Comment by jakubtobiasz** [comment]
I'll raise your concerns on the upcoming meeting. I'll let you know as soon as I have any additional information.

**Comment by vvasiloi** [comment]
I will make some performance tests next week and share the results here.

**Comment by coldic3** [comment]
After a bit of research, I'd lean towards it may not be a performance improvement. Let's see eg. https://www.percona.com/blog/2007/08/28/do-you-always-need-index-on-where-column/

**Pull request closed without merging**
