### PR TITLE
Move some common Twig macros from WebBundle to ResourceBundle.

### LINKED ISSUE #1841: move paginate twig macro to ResourceBundle?
atm there are only 2 macros in the misc macro. `paginate` and `shipment_state` . It's possible that shipment state needs a new home also.

### PR DESCRIPTION
**Pull request by stloyd**
Fixes #1841.

### CODE REVIEW

**Comment by aRn0D** [comment]
@stloyd Can you update it ?

**Comment by aRn0D** [comment]
ping @stloyd ;)

**Comment by aRn0D** [comment]
pong @stloyd

**Comment by pjedrzejewski** [comment]
These will go to SyliusUiBundle, when we work on new theme and backend upgrade.

**Comment by jrobeson** [comment]
SO how does that help folks who are using the ResourceBundle standalone?

**Pull request closed without merging**
