### PR TITLE
[Admin] Fix 500 when resending order confirmation email for a cart

### PR DESCRIPTION
**Pull request by NoResponseMate**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.11 |
| Bug fix?        | yes                                                       |
| New feature?    | no                                                       |
| BC breaks?      | no                                                       |
| Deprecations?   | no |
| Related tickets | continues #14174                      |
| License         | MIT                                                          |

### CODE REVIEW

**Review by jakubtobiasz — APPROVED** [review]

**Comment by jakubtobiasz** [comment]
Thank you, @NoResponseMate!

**Comment by coldic3** [comment]
Do we have a behat scenario for that?

**Comment by NoResponseMate** [comment]
The functionality of resending the order confirmation email is [tested](https://github.com/Sylius/Sylius/blob/1.11/features/order/managing_orders/resending_order_confirmation_email.feature), so we know it didn't break.
As for a scenario in which we cannot resend it for a cart, there's no way to do that ATM, the UI parts with the trigger are inaccessible and the API functionality is not covered.
If anything I'd be for Unit testing the action classes instead of using behat.

**Comment by coldic3** [comment]
Oh, I see, thx for the clarification :+1:

**Pull request merged**
