### PR TITLE
Added expression language support to template event system

### PR DESCRIPTION
**Pull request by 4c0n**
Added expression language support to template event system block contexts

| Q               | A
| --------------- | -----
| Branch?         | master
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no (Unless you count passing values that start with `@=` in the context values)
| Deprecations?   | no
| License         | MIT

See also: https://github.com/Sylius/Sylius/pull/11590

### CODE REVIEW

**Comment by 4c0n** [comment]
FYI:
It would allow you to do something like this in the template event config:
```
sylius_ui:
    events:
        nedac.shop.homepage.header:
            blocks:
                header:
                    template: 'Homepage/_header.html.twig'
                    priority: 20
                    context: '@=service("App\\SomeService").getData()'
```
Simlar to the YAML version of: https://symfony.com/doc/current/service_container/expression_language.html

**Review by lchrusciel — COMMENTED** [review]
We need to test this behavior, probably with some functional tests but seems like it would be a great addition to our template system

**Comment by 4c0n** [comment]
@lchrusciel Thank you :) I'll try to get around writing some tests soon and remove [WIP] from the title.

**Comment by lchrusciel** [comment]
Thank you for your contribution! ;)

**Comment by 4c0n** [comment]
@pamil @lchrusciel I don't know why the travis status is not being reported it passes: https://travis-ci.org/github/Sylius/Sylius/builds/706881110
Also the SymfonyInsight doesn't reach beyond pending. Maybe it needs to be triggered or something?

**Review by lchrusciel — APPROVED** [review]

**Comment by 4c0n** [comment]
@lchrusciel `SymfonyInsight` still hasn't ran for some reason, any clue why?

**Comment by lchrusciel** [comment]
Hey Youri,

SymfonyInsight is not a blocker for merge. However, right now we have some composer conflicts to resolve. Can you take a look into it?

**Comment by 4c0n** [comment]
@lchrusciel Hi Lukasz,

I resolved the conflict. All checks passed as well now :smiley:

**Comment by 4c0n** [comment]
Anyone interested in this feature? Otherwise we can close it. It has been sitting here for about a year now.

**Pull request closed without merging**
