### PR TITLE
[TaxationBundle] Form registration, missing specs and CS

### PR DESCRIPTION
**Pull request by aRn0D**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | refactoring 
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | no
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
@aRn0D Needs rebasing. :)

**Comment by aRn0D** [comment]
@pjedrzejewski this evening ;)

**Comment by aRn0D** [comment]
@pjedrzejewski done

**Comment by pjedrzejewski** [comment]
Restarted the build!

**Comment by aRn0D** [comment]
@pjedrzejewski green !

**Comment by pjedrzejewski** [comment]
Thank you Arnaud! :)

**Pull request merged**
