### PR TITLE
Make the User class compatible with Symfony 6 to use encoder_name

### LINKED ISSUE #15286: Impossible to login if the encoder_name is different from the hasher defined on UserInterface class
**Sylius version affected**: 1.13 and 1.12

**Description**  

The `Sylius\Component\User\Model\User` class is not compatible with Symfony 6 to retrieve the password encoder via `PasswordHasherFactory`.

Since version 6.0, only the `PasswordHasherAwareInterface` is used: [PasswordHasherFactory diff](https://github.com/symfony/password-hasher/compare/5.4..6.0#diff-f554f2e8aedb0dc6c25450b0ff91ef2c835033c31ccd8fc9024e24ae7a026000R42-R43)

So, the factory doesn't retrieve the `encoder_name` from entity and uses the encoder defined on the class. If the values are different, the customer cannot log in.

**Steps to reproduce**  

1. Install the Sylius fixtures with the customer `shop@example.com`
2. Change the password hasher in `config/packages/security.yaml`, example:

```diff
-        Sylius\Component\User\Model\UserInterface: argon2i
+        Sylius\Component\User\Model\UserInterface: sha256
``` 

3. Try to log in
4. We get the error "Invalid credentials."

**Possible Solution**  

Implement the `PasswordHasherAwareInterface` interface in the `Sylius\ComponentUser\Model\User` class and define the method:

```php
public function getPasswordHasherName(): ?string
{
    return $this->getEncoderName();
}
```

### PR DESCRIPTION
**Pull request by delyriand**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.12                  |
| Bug fix?        | yes                                                       |
| New feature?    | no                                                       |
| BC breaks?      | no                                                       |
| Deprecations?   | no |
| Related tickets | fixes #15286                      |
| License         | MIT                                                          |

### CODE REVIEW

**Comment by jakubtobiasz** [comment]
Hello @delyriand 👋🏼,
can you add a note about the changed model's interface to the `1.12`'s upgrade file, please?

**Review by lchrusciel — DISMISSED** [review]
Jacob ask should be added, but all in all, that's a good change 👍

**Review by Roshyo — DISMISSED** [review]

**Comment by delyriand** [comment]
Hi @jakubtobiasz!

I've just added a step to the update file for version 1.12.

**Comment by diimpp** [comment]
Sylius uses https://github.com/SyliusLabs/PolyfillSymfonySecurity which handles interface mismatch for [UserInterface](https://github.com/SyliusLabs/PolyfillSymfonySecurity/blob/main/src/Core/User/UserInterface.php) as well, should this fix be added over there, while SF5 is supported?

@loic425 Hi, what do you think?

**Comment by loic425** [comment]
> Sylius uses https://github.com/SyliusLabs/PolyfillSymfonySecurity which handles interface mismatch for [UserInterface](https://github.com/SyliusLabs/PolyfillSymfonySecurity/blob/main/src/Core/User/UserInterface.php) as well, should this fix be added over there, while SF5 is supported?
> 
> @loic425 Hi, what do you think?

That's a good question, the existing Pollyfill is to create a bc-layer to keep compatibility with legacy Symfony versions. 
It's for complex bc-layer, here it's simple cause it works with Symfony 5 and 6.

**Review by diimpp — DISMISSED** [review]

**Review by Prometee — DISMISSED** [review]

**Review by GSadee — APPROVED** [review]

**Comment by GSadee** [comment]
Thank you, Maxime! :1st_place_medal:

**Pull request merged**
