### PR TITLE
[Association] Fix table name and add migration

### PR DESCRIPTION
**Pull request by lchrusciel**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Fixed tickets | #4166

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
@lchrusciel No idea how it worked before, please add a migration. :)

**Comment by lchrusciel** [comment]
Doctrine loves [magic](https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php#L1704)...

**Comment by lchrusciel** [comment]
don't merge this PR yet. I have some troubles with migration

**Comment by lchrusciel** [comment]
ok, it is ready to merge

**Comment by pjedrzejewski** [comment]
Thanks Łukasz! :+1:

**Pull request merged**
