### PR TITLE
Add missing preposition in license docblock

### PR DESCRIPTION
**Pull request by GSadee**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Related tickets | 
| License         | MIT

### CODE REVIEW

**Comment by lchrusciel** [comment]
Why didn't you add a `[CRITICAL]` tag? It is must have

**Comment by pjedrzejewski** [comment]
I am not sure it is entirely correct and Symfony can live without it... Let's avoid unnecessary noise in the repo.

**Comment by GSadee** [comment]
👎

**Comment by pamil** [comment]
https://www.gnu.org/licenses/gpl-howto.en.html GNU GPL is also missing a preposition :)

**Pull request closed without merging**
