### PR TITLE
Fixed deprecated `Intl` component usage

### PR DESCRIPTION
**Pull request by stloyd**
| Q               | A
| --------------- | -----
| Branch?         | 1.8
| Bug fix?        | yes(?)
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | related #10928 
| License         | MIT

### CODE REVIEW

**Comment by stloyd** [comment]
@pamil @lchrusciel Friendly ping 😂

**Comment by stloyd** [comment]
This is still valid...

**Comment by stloyd** [comment]
@pamil @Tomanhez @lchrusciel Can we get this one merged?

**Review by Zales0123 — APPROVED** [review]

**Review by lchrusciel — APPROVED** [review]

**Comment by lchrusciel** [comment]
Thank you, Joseph! :tada:

**Pull request merged**
