### PR TITLE
BUGFIX: #13176 add missing serialization configuration for phone number, company name

### LINKED ISSUE #13176: [API] Phone number and company name can not be added to the address via the endpoint PATCH ​/api​/v2​/shop​/orders​/{tokenValue}​/address
**Sylius version affected**: 1.10.2

**Description**  
When adding an Adresse to an Order the values for phone number and company name are not added to the address when using the endpoint PATCH ​/api​/v2​/shop​/orders​/{tokenValue}​/address

**Steps to reproduce**  

1. Create a cart via the api
2. Add a product via the api
3. Add the billing address data with phone number and company name via the endpoint PATCH /api​/v2​/shop​/orders​/{tokenValue}​/address
4. Check the address data in the database -> phone number and company name are empty

**Possible Solution**  

https://github.com/Sylius/Sylius/pull/13177

### PR DESCRIPTION
**Pull request by andrehoffmann30**
| Q               | A
| --------------- | -----
| Branch?         | 1.10
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #13176
| License         | MIT

### CODE REVIEW

**Review by vvasiloi — CHANGES_REQUESTED** [review]
Hey @andrehoffmann30 , thank you for your contribution!
Please add the missing groups to the already defined attributes instead of duplicating those.

Edit: don't forget to rebase your branch first.
Second edit: note that some group names may have changed in the meantime.

**Comment by coldic3** [comment]
Hey @andrehoffmann30,
could you also provide unit tests like these https://github.com/Sylius/Sylius/blob/master/tests/Api/Shop/OrdersTest.php? :woman_dancing:

**Comment by andrehoffmann30** [comment]
Hallo @vvasiloi , hallo @coldic3 I tried to implement your suggestions. I fixed the code duplication and added an unit test for my changes. But it seems, that the api route for adjusting the address data was removed. Is this correct? In your documentation here https://docs.sylius.com/en/latest/getting-started-with-sylius/using-api.html the route is still mentioned. Can you give me some information, how we should proceed from here on? Thank you very much.

**Comment by vvasiloi** [comment]
Hi @andrehoffmann30, see https://github.com/Sylius/Sylius/pull/13329 for details. You can now update the address via `PUT /api/v2/shop/orders/{tokenValue}`.

**Comment by andrehoffmann30** [comment]
Hallo @coldic3 , hallo @vvasiloi I have further adjust my changes and in a manual test everything seems to work as intended, but the unit tests are still red. I don't really understand the problem and can't further debug the test, because I could not find a documentation an how to configure and run the tests locally. Cann you please take a look at my code and give me hint on would could be wrong. It would also help, if you could give me a clear documentation, on how to run the test locally. Thank you ver much.

**Comment by vvasiloi** [comment]
@andrehoffmann30 I will look at it, probably tomorrow.

**Comment by coldic3** [comment]
Hey @andrehoffmann30,

the problem you have is that you try to modify placed order.

Please try to replace
```php
$this->placeOrder($tokenValue, 'oliver@doe.com');
```
with eg.
```php
/** @var MessageBusInterface $commandBus */
$commandBus = $this->get('sylius.command_bus');

$pickupCartCommand = new PickupCart($tokenValue);
$pickupCartCommand->setChannelCode('WEB');
$commandBus->dispatch($pickupCartCommand);
$addItemToCartCommand = new AddItemToCart('MUG_BLUE', 3);
$addItemToCartCommand->setOrderTokenValue($tokenValue);
$commandBus->dispatch($addItemToCartCommand);
```
and it should work then :slightly_smiling_face:

**Comment by DufourVictor** [comment]
Hi, 

Is it possible to merge this pull request? 
I use version 1.12 and I had this problem which made me lose a lot of time...

Thanks in advance.

**Comment by coldic3** [comment]
@DufourVictor We are on it 💃

I'm closing this one in favor of https://github.com/Sylius/Sylius/pull/14574

**Pull request closed without merging**
