### PR TITLE
[Travis] New migrations policy

### PR DESCRIPTION
**Pull request by pamil**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #3303
| License       | MIT

Deleted all existing migrations and created one that builds Sylius v0.15.0 database structure from scratch.

### CODE REVIEW

**Comment by michalmarcinkowski** [comment]
:+1: Please update the changelog and we can get this merged! :wink:

**Comment by winzou** [comment]
Wow, you cannot just delete migrations and let us deal with it when upgrading our sylius!
Please keep these migrations and add a new one from scratch to the first already existing migration.

**Comment by michalmarcinkowski** [comment]
@winzou all migrations will be available in v0.15, so you can use whatever you need. Then in order to jump to v0.16 you would need to run just one migration. We plan to make one migration file per release to ease upgrades (all PRs will introduce their migrations and just before release we will merged them all into one file).

Does it sound good for you or you have some better idea? (related discussion https://github.com/Sylius/Sylius/issues/3303)

**Comment by pamil** [comment]
@michalmarcinkowski done! :)

**Comment by winzou** [comment]
What is the point of merging migrations?

For this PR, I would checkout Sylius just before the first migration, then do a `do:mi:di`, then add the generated file here. It would keep history and ease migrations (what if I want to update from 0.14 to dev-master?). I just hope that every schema change has its migration...

**Comment by pamil** [comment]
@winzou New migrations will allow to migrate 0.15 -> 0.16 in just one migration. Development branch `master` will contain unmerged migrations so migrating 0.15 -> master would be easy to. The only drawback I can see is that migrating master -> next stable version would not be easily available - @michalmarcinkowski?

**Pull request closed without merging**
