### PR TITLE
Make setting User listener more generic

### PR DESCRIPTION
**Pull request by stloyd**

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
:+1:

**Comment by stloyd** [comment]
@pjedrzejewski @aRn0D Failed build is unrelated (seems like lag on one of Travis-CI boxes).

**Comment by stloyd** [comment]
@pjedrzejewski Anything blocking this?

**Comment by pjedrzejewski** [comment]
Thanks Joseph! :+1:

**Pull request merged**
