### PR TITLE
Allow for JMSTranslationBundle 1.1 and above.

### PR DESCRIPTION
**Pull request by Nyholm**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | none
| License         | MIT

I've just tagged 1.2.2 of JmsTranslation. We follow Semver so it should not be a problem updating to future versions. 

It has been 135 commits from 1.1.0 to 1.2.2, it is mainly bugfixes, code cleanups and added tests. See the full list [here](https://github.com/schmittjoh/JMSTranslationBundle/compare/1.1.0...master).

### CODE REVIEW

**Comment by michalmarcinkowski** [comment]
Thanks Tobias! :+1: 

Can you update the `composer.lock` to the newest JmsTranslationBundle? We have a strict composer validation.

**Comment by Nyholm** [comment]
Sorry, I forgot about that. 
I've updated the PR now and travis says everything is green.

**Comment by pjedrzejewski** [comment]
Hey Tobias! Great to see that you will be taking care of JMS bundles, congrats! Could you rebase this PR? I merged another updated to composer.lock. Thanks!

**Comment by Nyholm** [comment]
Thank you. 

I've rebased the PR and calculated a new hash for composer.lock.

**Comment by pjedrzejewski** [comment]
Thank you Tobias!

**Comment by Nyholm** [comment]
Thank you for merging. Also, thank you for the Podcast. I will start to throw out my custom half-built webshop and start my first Sylius project in late April.

**Comment by pjedrzejewski** [comment]
@Nyholm Awesome! :)

**Pull request merged**
