### PR TITLE
Use DQL instead of repository to fetch product attributes

### LINKED ISSUE #11843: Unable to extend ProductAttribute with new properties after 1.8
**Sylius version affected**: 1.8

**Description**  
We are no longer able to extend `ProductAttribute` with new properties due to the new way doctrine migrations are now ordered.

Due to the way [this](https://github.com/pamil/Sylius/blob/1.8/src/Sylius/Bundle/CoreBundle/Migrations/Version20171003103916.php#L40) specific migration works (specifically how it uses the repository in line 40), it will fail if you have added any properties to `ProductAttribute` since these properties will not yet have been migrated to the table schema.

We used to solve this by backdating the migrations that altered the product attribute table back to some timestamp before the `20171003103916` migration. This no longer works.

```
 bin/console doc:data:drop --force && bin/console doc:data:create && bin/console doc:mig:migrate
Dropped database `sylius_18_dev` for connection named default
Created database `sylius_18_dev` for connection named default

 WARNING! You are about to execute a database migration that could result in schema changes and data loss. Are you sure you wish to continue? (yes/no) [yes]:
 > y

[notice] Migrating up to DoctrineMigrations\Version20171003100000
[warning] Migration Sylius\Bundle\CoreBundle\Migrations\Version20161209095131 was executed but did not result in any SQL statements.
[error] Migration Sylius\Bundle\CoreBundle\Migrations\Version20171003103916 failed during Execution. Error: "An exception occurred while executing 'SELECT t0.code AS code_1, t0.type AS type_2, t0.storage_type AS storage_type_3, t0.configuration AS configuration_4, t0.created_at AS created_at_5, t0.updated_at AS updated_at_6, t0.position AS position_7, t0.id AS id_8, t0.facetType AS facetType_9 FROM sylius_product_attribute t0 WHERE t0.type = ?' with params ["select"]:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.facetType' in 'field list'"

In AbstractMySQLDriver.php line 64:

  An exception occurred while executing 'SELECT t0.code AS code_1, t0.type AS type_2, t0.storage_type AS storage_type_3, t0.configuration AS configuration_4, t0.created_at AS created_at_5, t0.updated_at AS updated_at_6, t0.position AS position_7, t0.id AS id_8, t0.facetType AS facetTyp
  e_9 FROM sylius_product_attribute t0 WHERE t0.type = ?' with params ["select"]:

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.facetType' in 'field list'


In PDOStatement.php line 131:

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.facetType' in 'field list'


In PDOStatement.php line 129:

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.facetType' in 'field list'


doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--configuration CONFIGURATION] [--db-configuration DB-CONFIGURATION] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<version>]
```

**Steps to reproduce**  
I have provided a repository that reproduce the bug in question.

https://github.com/leflings/sylius-1.8-migration-issue/commits/master

**How will we solve this problem from now on, now that backdating no longer works? Can the `20171003103916` migration be rewritten to not use the the repository (which is what creates the failing select query)?**

### PR DESCRIPTION
**Pull request by loevgaard**
| Q               | A
| --------------- | -----
| Branch?         | 1.7
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #11843
| License         | MIT

### CODE REVIEW

**Comment by loevgaard** [comment]
I have no idea why the build fails, but since it doesn't fail on PHP7.3 I guess it doesn't have something to do with this PR?

**Review by lchrusciel — APPROVED** [review]
Hey Joachim, 

thanks for your contribution. Does it solve the issue with changes to entities mapping during migration? I was wondering if we shouldn't go even further and write plain SQL to fetch all the required attributes. What do you think? 

Also, I've restarted your build. The error seems to be not related with your changes.

**Comment by loevgaard** [comment]
I used https://patch-diff.githubusercontent.com/raw/Sylius/Sylius/pull/11882.patch as a patch for the issue mentioned and it fixes that issue, yes. I don't see why we would need to rewrite it to SQL.

**Comment by lchrusciel** [comment]
The base of this pull-request was changed, you need fetch and reset your local branch 
if you want to add new commits to this pull request. **Reset before you pull, else commits
may become messed-up.**

Unless you added new commits (to this branch) locally that you did not push yet, 
execute `git fetch origin && git reset "11843-fix-migration"` to update your local branch.
 
Feel free to ask for assistance when you get stuck :+1:

**Comment by lchrusciel** [comment]
The base of this pull-request was changed, you need fetch and reset your local branch 
if you want to add new commits to this pull request. **Reset before you pull, else commits
may become messed-up.**

Unless you added new commits (to this branch) locally that you did not push yet, 
execute `git fetch origin && git reset "11843-fix-migration"` to update your local branch.
 
Feel free to ask for assistance when you get stuck :+1:

**Review by lchrusciel — APPROVED** [review]

**Comment by lchrusciel** [comment]
Thanks, Joachim! :1st_place_medal:

**Pull request merged**
