### PR TITLE
Add failing test for showing correct shipping method fees after shipping discount applied

### PR DESCRIPTION
**Pull request by stefandoorn**
| Q               | A
| --------------- | -----
| Branch?         | 1.1
| Bug fix?        | not yet
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| License         | MIT

### CODE REVIEW

**Comment by pamil** [comment]
The scenario is now failing because of missing steps, are you willing to implement them or reuse the existing ones to make this PR include a really failing scenario?

**Comment by stefandoorn** [comment]
Done, @pamil.

**Comment by stefandoorn** [comment]
@pamil @Zales0123 I'm not sure what's the best fix here, could you have a look?

**Comment by Zales0123** [comment]
Hmmm, it's a good question 😄 Write now displayed shipping cost is calculated [in this file](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ShippingBundle/Form/Type/ShippingMethodChoiceType.php#L109). I think the best option would be to either to extend this form type in _Core_ and calculate costs one more time including discount or provide a new shipping calculator (also in _Core_) that would include these discounts as well... The easiest option I see here is just to display a message "These are full prices of shipping, go to the end of the checkout to see how much your shipping would actually cost" but it seems like a not so good customer experience ⚖️ 🏎

**Comment by lchrusciel** [comment]
Related to #10813

**Comment by lchrusciel** [comment]
Hello Stefan 👋 

I've checked this description, and the solution for this problem is a custom shipping calculator, which will allow for free delivery above some threshold. We are not able to recalculate the price of shipping with the promotion applied. This PR will go along with the #10813 request. Would you (or @loevgaard or @igormukhingmailcom) like to contribute to this new calculator? Behat tests are almost ready in this PR. We just need to change one step here.

**Pull request closed without merging**
