### PR TITLE
[GridBundle] Add multiple object managers support

### PR DESCRIPTION
**Pull request by RADiActive**
| Q               | A
| --------------- | ---
| Bug fix?        | yes |
| New feature?    | no |
| BC breaks?      | no |

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
@RADiActive Could you also update tests? Thank you!

**Comment by RADiActive** [comment]
Yes. I can, a little bit later

**Comment by RADiActive** [comment]
commits was squashed

**Comment by pjedrzejewski** [comment]
Nice, thank you very much @RADiActive! :)

**Pull request merged**
