### PR TITLE
[ShopBundle] Make HomepageController final

### PR DESCRIPTION
**Pull request by TheMadeleine**
| Q               | A
| --------------- | ---
| Bug fix?        | yes |
| New feature?    | no |
| BC breaks?      | yes |
| Related tickets | related to #7502 |
| License         | MIT |

### CODE REVIEW

**Comment by TheMadeleine** [comment]
Why @pamil? Many ppl extend it in order to add stuff to Homepage :)

**Comment by pamil** [comment]
Let's force them to make their own controller, so we won't introduce future BC breaks eg. by adding an extra argument to this controller.

If they are beginners it's even better for them to extend Symfony's `Controller` instead of fighting with injecting dependencies. At worst they would copy 20 lines of code from this one and customise it.

**Comment by pamil** [comment]
They still need to register their custom controller as a service with the same id as extended controller anyway (https://github.com/Sylius/Sylius/pull/7502#discussion_r101021992).

**Comment by TheMadeleine** [comment]
@pamil, done :)

**Comment by pamil** [comment]
Don't want to be annoying, but the commit message is quite outdated now :D

**Comment by TheMadeleine** [comment]
:+1: @pamil 🎉

**Comment by pjedrzejewski** [comment]
Thank you Magda!

**Pull request merged**
