### PR TITLE
bug fix #2504

### LINKED ISSUE #2504: [BUG][ResourceBundle] createYmlMappingDriver have no method in DoctrineOrmMappingsPass.
@aRn0D Just report the Bug.
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/AbstractResourceBundle.php#L138

for i was fixed by:

```php
// createYmlMappingDriver not exist!
if ($this->mappingFormat === ResourceBundleInterface::MAPPING_YAML) {
    $compilerPassMethod = 'createYamlMappingDriver';
} else {
    $compilerPassMethod = sprintf('create%sMappingDriver', ucfirst($this->mappingFormat));
}
```

### PR DESCRIPTION
**Pull request by aRn0D**
| Q             | A
| ------------- | ---
| Bug fix?      | #2504 
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by liverbool** [comment]
Oops! That so easy haha Why i missed.
@aRn0D :+1:

**Comment by aRn0D** [comment]
@liverbool :D

**Comment by pjedrzejewski** [comment]
Thanks guys! :+1:

**Comment by aRn0D** [comment]
:v:

**Pull request merged**
