### PR TITLE
Update PromotionEligibilityChecker to work with coupons

### PR DESCRIPTION
**Pull request by lbaey**
I think we need to keep the eligibility, so coupons can be combined with rules.

### CODE REVIEW

**Comment by tristanbes** [comment]
@lbaey 
So that means that we can create coupons,
And then only make them availble if only conditions are met inside rule's promotion with your PR, that's right ?

**Comment by lbaey** [comment]
Yes, exactly.
I had this case : with a COUPON, 10% off on first order delivered in store. I set up a coupon based promotion with 2 rules and 1 action. Even if the rules condition were not met, the coupon was OK, and the action was applied. I didn't want this behaviour, and I think when you set up a promotion with rules and coupon you want all the conditions to be met.

**Comment by PWalkow** [comment]
@lbaey Seems legit. Do you mind updating the tests for check this behaviour? You have changed the logic and no tests were changed. I wonder how the tests are passing now.

**Comment by tristanbes** [comment]
so that's a great idea, i'm :+1:

**Comment by AlucardleVash** [comment]
:+1:

**Comment by tristanbes** [comment]
@PWalkow I guess tests are passing because there are no fixtures that adds a coupon conditions on a promotion rules. :)

**Comment by pjedrzejewski** [comment]
Yes, let's add scenario for that. :+1:

**Comment by lbaey** [comment]
I'm working on it :)
will be added to this PR

**Comment by pjedrzejewski** [comment]
Ping @lbaey. :)

**Comment by pjedrzejewski** [comment]
Friendly ping @lbaey. :)

**Comment by michalmarcinkowski** [comment]
Fixed.

**Pull request closed without merging**
