### PR TITLE
[Composer] Update lock to use guzzlehttp/guzzle:6.2.1 that fixes HTTPoxy vulnerability

### PR DESCRIPTION
**Pull request by pamil**

### CODE REVIEW

**Comment by bendavies** [comment]
thin you should `composer require guzzlehttp/guzzle "^6.2.1"` as well if you want to enforce this

**Comment by pjedrzejewski** [comment]
Requires rebasing.

**Comment by pamil** [comment]
@bendavies good catch! 👍 
@pjedrzejewski done!

**Comment by bendavies** [comment]
closed?

**Comment by pamil** [comment]
@bendavies just don't want to spam Travis :)

**Pull request closed without merging**
