### PR TITLE
[BugFix] Use latest phpcr-odm (master), fixes #3752

### LINKED ISSUE #3752: [Bug] Changing content of second menu node gives "This value is not valid." error
I have made a video to show the issue: https://www.youtube.com/watch?v=F8DbT2ytAlg (tested on `demo.sylius.org` and my own sylius installation)

When you create a new menu, and create two menu nodes linking to the same content it will save fine. But if you have different content for one menu node, it fails and gives you "This value is not valid.".

I am not sure if this is a recent bug or one introduced in `0.16` only.

Symfony profiler:
Profiler

### PR DESCRIPTION
**Pull request by steffenbrem**
This PR fixes #3752

### CODE REVIEW

**Comment by nakashu** [comment]
@steffenbrem can you rebase? I bumped to this issue also and would be nice to have it merged.

**Comment by steffenbrem** [comment]
I am currently on vacation. I think Pawel wants to wait till phpcr-odm is tagged as 1.3.2.

**Comment by nakashu** [comment]
thank you

**Comment by steffenbrem** [comment]
Not necessary anymore since `1.3.1` has been released 🎉

**Pull request closed without merging**
