### PR TITLE
Bump version to 0.18.x

### PR DESCRIPTION
**Pull request by pjedrzejewski**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | -
| License         | MIT
| Doc PR          | -

### CODE REVIEW

**Comment by aRn0D** [comment]
@pjedrzejewski good news :+1: !

**Comment by okwinza** [comment]
:tada: :tada: :tada:

**Comment by gabiudrescu** [comment]
:beers:

**Comment by aramalipoor** [comment]
:beers: :beers:

**Comment by pamil** [comment]
Need to update the lock file :tada:

**Comment by kasrakhosravi** [comment]
:beers:

**Comment by michalmarcinkowski** [comment]
:+1:

**Comment by tonicospinelli** [comment]
:beers: :heart_eyes:

**Comment by pjedrzejewski** [comment]
Cheers! :beer:

**Pull request merged**
