### PR TITLE
fix default repository for variant and association type resources

### PR DESCRIPTION
**Pull request by loic425**
| Q               | A
| --------------- | -----
| Branch?         | 1.3
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| License         | MIT

### CODE REVIEW

**Comment by Zales0123** [comment]
Thanks, Loïc! :1st_place_medal:

**Comment by lchrusciel** [comment]
Was there any discussion behind this bug? Loic, can you explain briefly, where did you encounter a problem?

I'm not saying, that it is a bad solution, I don't know why we want to change this configuration. The problem is that the same configuration is true for 55 other repositories
image
and all repositories where configured dynamically in:
https://github.com/Sylius/SyliusResourceBundle/blob/92c8e365a7c15aa436429b07dd14e7b2f8965f2f/src/Bundle/DependencyInjection/Driver/Doctrine/DoctrineORMDriver.php#L38-L69
or if overridden in YAML:
https://github.com/Sylius/Sylius/blob/c56d62eae80638f961073eaaeb477afc50cbc7ca/src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius/sylius_order.yml#L10

If I recall correctly, the main idea was to decouple bundles from ORM by default. I don't know if it is still a case, but I would vote for a little discussion here. /cc @Sylius/core-team

**Comment by loic425** [comment]
> I'm assuming, that you are working with `doctrine/orm` driver, am I correct?
> Can you check if this line works properly:https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ProductBundle/DependencyInjection/SyliusProductExtension.php#L43 ?
> 
> It should load this file: https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ProductBundle/Resources/config/services/integrations/doctrine/orm.xml and extend basic configuration.

Yes, this load this file. This is indeed ok with product variant repository but not ok for association type repository:

**sylius.repository.product_variant**
Sylius\Bundle\ProductBundle\Doctrine\ORM\ProductVariantRepository

**sylius.repository.product_association_type**                                                                   Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository

Normal, cause this second repository is not defined in https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ProductBundle/Resources/config/services/integrations/doctrine/orm.xml

**Comment by lchrusciel** [comment]
At least we found a source of 🐛 Would you like to open a PR with a fix? :D

**Comment by loic425** [comment]
Yes I will open a pull request next week :)

**Pull request merged**
