### PR TITLE
Revert "[Behat] Remove js requirement for bulk delete scenarios"

### PR DESCRIPTION
**Pull request by GalloisLuca**
This reverts commit 4013e51dfdd3ff7d5bd00f2751308eac2bb3149a.

| Q               | A
| --------------- | -----
| Branch?         | 1.7
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets |
| License         | MIT

Related to this issue https://github.com/Sylius/Sylius/issues/11324
Custom bulk action can't work cause of the id #bulk-delete wich has been had in the reverted commit.

### CODE REVIEW

**Comment by lchrusciel** [comment]
Hey Luca! 

thank a lot for this revert. I would like to merge it and publish it with the nearest release. However, the build is red and it seems to not be a random one. What I think you could do, is to rebase your PR with the newest master and check if the build is still red. I assume it may still be red due to missing part of your revert https://github.com/Sylius/Sylius/commit/4013e51dfdd3ff7d5bd00f2751308eac2bb3149a#diff-a3ee22317b316e28312b526441fee27fR140-R142. 

Nonetheless, let me welcome you to our community. Even if you are reverting part of work :)

**Comment by GalloisLuca** [comment]
@lchrusciel Hey i updated the PR on the new master and add the missing modification (don't know why it didn't there before) but it still red ... i think you made some test on this specific case, so if we wants the custom bulkAction works again, we maybe have to dev something for it ? What do you think about that ?

**Comment by lchrusciel** [comment]
Ok, I know what is wrong with your PR. You should add two `@javascript` tags to `features/addressing/managing_zones/deleting_multiple_zones.feature` and `features/product/managing_product_association_types/deleting_multiple_product_association_types.feature`. I hope that will make build green again.

**Comment by GalloisLuca** [comment]
@lchrusciel The build is now green, you were right ! :smile:

**Comment by lchrusciel** [comment]
Great! I had to mess a little bit with your commits, as it should be opened from 1.7 branch(so you will not have to wait for 1.8 to take benefit from this fix ;)). If you would like to add something on a top of it, please remember to fetch data from the remote first.

**Comment by lchrusciel** [comment]
Thank you, Luca! :1st_place_medal:

**Comment by GalloisLuca** [comment]
@lchrusciel You are welcome ! Even if i made a revert ! Sorry about how i updated my fork repo, that's my first "contribution" overall, i didn't know how to update the fork properly :confused: . Anyway, thanks for the merge and your time !

**Pull request merged**
