### PR TITLE
Remove wrong trailing space in test attribute

### PR DESCRIPTION
**Pull request by mmenozzi**
| Q               | A
| --------------- | -----
| Branch?         | 1.8
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | none
| License         | MIT

Remove wrong trailing space in address full name test attribute.

### CODE REVIEW

**Review by vvasiloi — APPROVED** [review]
Hey @mmenozzi , thank you for your contribution!
Some checks failed for unrelated reasons, can you rebase your branch?

**Comment by mmenozzi** [comment]
Hi @vvasiloi, there are no more commits on the 1.8 branch. I think that someone with write access should try to run workflows again.

**Comment by vvasiloi** [comment]
I didn't even notice the target branch is 1.8.
I changed it to 1.10, but now there's an extra commit in the diff.
I guess it's easier to just opened another PR on 1.10.

**Comment by vvasiloi** [comment]
I cherry-picked you commit here: https://github.com/Sylius/Sylius/pull/13448

**Comment by mmenozzi** [comment]
Thank you @vvasiloi!

**Pull request closed without merging**
