### PR TITLE
fix sylius_backend_product_delete_restore path

### PR DESCRIPTION
**Pull request by nicolasricci**

### CODE REVIEW

**Comment by michalmarcinkowski** [comment]
Could you also correct the translation key?

**Comment by nicolasricci** [comment]
Not sure what is wrong with the translation key as it looks properly set 
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/WebBundle/Resources/translations/messages.en.yml#L761

**Comment by michalmarcinkowski** [comment]
With translation key I meant ``` sylius.product.delete_revert ``` to be changed to ``` sylius.product.delete_restore ```.

**Comment by nicolasricci** [comment]
done

**Comment by pjedrzejewski** [comment]
Thank you Nicolas! :+1:

**Pull request merged**
