### PR TITLE
[TaxonomyBundle] Remove serialization relation to the obsolete taxonomy entity.

### PR DESCRIPTION
**Pull request by liverbool**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| License         | MIT
| Doc PR          |

### CODE REVIEW

**Comment by lchrusciel** [comment]
If you change serialization of Taxon, will you be able to add some test for api?

**Comment by liverbool** [comment]
@lchrusciel How? I can't see any test case for that.

**Comment by lchrusciel** [comment]
Here you have example of [test for customer endpoint](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Tests/Controller/CustomerApiTest.php). TestCase is not a part of Sylius because we are using ApiTestCase library

**Comment by liverbool** [comment]
TaxonApiTest not yet exist, my hotfix now green i think it can be merged. :)

**Comment by TheMadeleine** [comment]
Your PR title and the commit name tell absolutely nothing about its purpose. Please take a look at this to become inspired ;)  :  http://docs.sylius.org/en/latest/contributing/code/index.html

**Comment by liverbool** [comment]
Ah! I know about my lack of `PR title`, It's contains 3 bundles and i can't naming ;), feel free to close this, just flags that we have some bugs.

**Comment by aramalipoor** [comment]
Suggested title ;) "[TaxonomyBundle] Remove serialization relation to the obsolete taxonomy entity"

**Comment by liverbool** [comment]
Thanks @aramalipoor i found other PR sent to fix Fixture Bug, i should separate PR.

**Comment by aramalipoor** [comment]
:+1: Yes, always do separate PRs/commits as much as you can ;)

**Comment by pjedrzejewski** [comment]
Thanks @liverbool, good catch!

**Pull request merged**
