### PR TITLE
[Deploy] Handle deploy with capistrano 3 and symfony plugin

### PR DESCRIPTION
**Pull request by gperdomor**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | yes
| Fixed tickets | #2966
| License       | MIT
| Doc PR        | -

This PR is for handle the deploy using capistrano 3 and symfony plugin.

The main configuration is in the <code>deploy.rb</code> file but you need modify some parameters in the <code>develop.rb</code> file to deploy in develop mode or <code>production.rb</code> file to deploy in production mode.

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
Nice, but why moving it to separate folder? I think ``app/config/deploy`` is good spot. :)

**Comment by gperdomor** [comment]
@pjedrzejewski app/config normally contains configurations files needed by the application. But this files aren't not needed by the app. This files are related to deploy and i think is better if they live in another place for not mix things. But i can put them back to <code>app/config/deploy</code> if you like.

**Comment by pjedrzejewski** [comment]
@gperdomor Fair point, but maybe we can keep it shorter and name the directory ``deploy``? :)

**Comment by gperdomor** [comment]
@pjedrzejewski dirdirectory name updated!

**Comment by pjedrzejewski** [comment]
Thank you @gperdomor! Could you also update Sylius-Standard with these scripts?

**Comment by kayue** [comment]
@gperdomor May I know command do you use to install Ruby / Capistrano dependency? (ie: Symfony plugin)

**Comment by gperdomor** [comment]
@pjedrzejewski sure, no problem :+1:

**Comment by gperdomor** [comment]
@kayue you can install capistrano runing <code>gem install capistrano</code> and the symfony pluging runing <code>gem install capistrano/symfony</code>. For more details you can view the official docs [here](http://capistranorb.com) and [here](https://github.com/capistrano/symfony/)

**Pull request merged**
