### PR TITLE
[Template] Variant name instead of product name

### PR DESCRIPTION
**Pull request by ernestWarwas**
| Q               | A
| --------------- | -----
| Branch?         | 1.10
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| License         | MIT

Show variant name instead of the product name.

### CODE REVIEW

**Review by Ferror — APPROVED** [review]
Nice catch!

**Review by Ferror — COMMENTED** [review]
Btw. We have tons of tests and we don't have a scenario to check if the variant name is actually the variant name?

Maybe we could provide a scenario like this in the next iteration? Even in sprint :)

**Comment by ernestWarwas** [comment]
> Btw. We have tons of tests and we don't have a scenario to check if the variant name is actually the variant name?

We have tests for that 😄 I didn't check it. Fixed.

**Review by lchrusciel — APPROVED** [review]

**Review by GSadee — APPROVED** [review]

**Comment by lchrusciel** [comment]
Thank you, Ernest! :1st_place_medal:

**Pull request merged**
