### PR TITLE
Remove inline css

### PR DESCRIPTION
**Pull request by Prometee**
This avoid table overflow in some languages like : for exemple in French.

| Q               | A
| --------------- | -----
| Branch?         | 1.2
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | unknow
| License         | MIT

### CODE REVIEW

**Comment by Zales0123** [comment]
The base of this pull-request was changed, you need fetch and reset your local branch 
if you want to add new commits to this pull request. **Reset before you pull, else commits
may become messed-up.**

Unless you added new commits (to this branch) locally that you did not push yet, 
execute `git fetch origin && git reset "patch-4"` to update your local branch.
 
Feel free to ask for assistance when you get stuck :+1:

**Comment by Zales0123** [comment]
It was also an issue on `1.2` so I've rebased your PR :) Could you also provide some screenshot to be 100% sure that nothing changed in UI in a wrong way? :)

**Comment by Prometee** [comment]
**Before locale en_US**
capture d ecran 2018-11-26 a 11 51 29
**After locale en_US**
capture d ecran 2018-11-26 a 11 51 44
**Before locale fr_FR**
capture d ecran 2018-11-26 a 11 53 30
**After locale fr_FR**
capture d ecran 2018-11-26 a 11 53 51

**Comment by Zales0123** [comment]
Thanks, Francis! :1st_place_medal:

**Pull request merged**
