### PR TITLE
[Behat] [DX] Extract legacy tag

### LINKED ISSUE #4436: [Behat] [Taxonomy] Legacy taxonomy suit has broken tag
Ref:
* [suite](https://github.com/Sylius/Sylius/blob/master/etc/behat/suites/legacy/taxonomy.yml#L17)
* [feature](https://github.com/Sylius/Sylius/blob/master/features/legacy/backend/taxonomy.feature#L1)

### PR DESCRIPTION
**Pull request by lchrusciel**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | yes
| Related tickets | partially #4410, fix #4436
| License         | MIT
| Doc PR          | 

As @pamil said it would be better to extract legacy from tags. I know, that we are going to rid of this behats, but until that it can be really useful.

### CODE REVIEW

**Comment by pamil** [comment]
:+1:, but it would be nice to rename legacy tags from the plural form to the singular one, as we got `@legacy @channels` and `@ui @channel` now :)

**Comment by lchrusciel** [comment]
@pamil good catch. The whole point of this PR it to enable running behats with tags

**Comment by lchrusciel** [comment]
Based on #4444

**Comment by pjedrzejewski** [comment]
Thanks @lchrusciel!

**Pull request merged**
