### PR TITLE
feature: simplified docker config

### PR DESCRIPTION
**Pull request by Ferror**
Simplified docker stack with frontend and backend service. Without php-fpm. Just the internal PHP server without any external dependencies.

Also got rid of testing stack, as there will be no more running tests in docker container in CI.

### CODE REVIEW

**Comment by vvasiloi** [comment]
This is just for development, right?

**Comment by Ferror** [comment]
> This is just for development, right?

Actually we could also use it for Sylius "production"

**Comment by vvasiloi** [comment]
> > This is just for development, right?
> 
> Actually we could also use it for Sylius "production"

Which one is that?

**Comment by Ferror** [comment]
> > > This is just for development, right?
> > 
> > 
> > Actually we could also use it for Sylius "production"
> 
> Which one is that?

The sylius demo & local/dev environment

**Pull request closed without merging**
