### PR TITLE
php-http/guzzle6-adapter dependency upgraded

### LINKED ISSUE #11035: Upgrade php-http/guzzle6-adapter version
Sylius depends on `"php-http/guzzle6-adapter": "^1.1"` but last release is `v2.0.1`. Some other libraries relies on `"php-http/guzzle6-adapter": "^2"` it so it is important to upgrade this dependency in order to support v2 as well.

### PR DESCRIPTION
**Pull request by pfazzi**
| Q               | A
| --------------- | -----
| Branch?         | 1.5
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #11035 
| License         | MIT

### CODE REVIEW

**Comment by pfazzi** [comment]
I see 1 failing scenario but the error seems to be unrelated whit this change

**Comment by pamil** [comment]
What I mean is that because 1.1.1 is still installed, we can't verify whether 2.0 is working correctly.

It is blocked by `hwi/oauth-bundle` currently, which is required in dev cause it's an optional integration.

**Comment by pfazzi** [comment]
`hwi/oauth-bundle` has just released version `1.0` which now depends on `"php-http/guzzle6-adapter":     "^2.0"`

**Comment by pamil** [comment]
Thank you, Patrick! :1st_place_medal:

**Pull request merged**
