### PR TITLE
Fix for shipping calculators to return integers

### PR DESCRIPTION
**Pull request by Dukecz**
Fix for shipping calculators to return integers because of error thrown during checkout caused by #2427

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
Amount should be integer already, that's strange.

**Comment by Dukecz** [comment]
Its string. I have just updated to from 0.12 to 0.13 and run into that problem. Other shipping calculators has int casting already.

**Comment by pjedrzejewski** [comment]
Thanks @Dukecz!

**Comment by michalmarcinkowski** [comment]
@Dukecz can you describe the issue? All scenarios passed, so we definitely should also cover the one you encountered to prevent future bugs.

**Comment by Dukecz** [comment]
@michalmarcinkowski Updated to sylius 0.13 and made testing order selecting flat rate shipping method, that was created before update.
After that the error has been thrown because price returned by shipping was "0" (string) instead of 0 (int).

**Comment by michalmarcinkowski** [comment]
Ok, I understand. You had strings saved in the database, what is wrong and will not happen from v0.13, but after your fix we will be backward compatible. @Dukecz thanks for making the point!

**Pull request merged**
