### PR TITLE
[UI] Remove flags near to locale name

### PR DESCRIPTION
**Pull request by GSadee**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Related tickets | 
| License         | MIT

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
Why?

**Comment by GSadee** [comment]
Because locales are not always linked with the countries. For example, we have an issue that there was no flag for locale `Africaans`, so we decided that locales shouldn't  have flags.

**Comment by michalmarcinkowski** [comment]
Right now I have second thoughts about that, because we display flags on translation forms and it prettify our UI and is a good UX. Maybe we could leave current logic, so display flags of locales that are connected with country and don't display for locales like `Africaans`. @GSadee @pjedrzejewski WDYT?

**Comment by GSadee** [comment]
So.. we should leave it as it is now 😃

**Pull request closed without merging**
