### PR TITLE
[PricingBundle] CS fixes and missing specs

### PR DESCRIPTION
**Pull request by aRn0D**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | refactoring 
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | no
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
@aRn0D We still support 5.3. Only few days more, but still. :)

**Comment by aRn0D** [comment]
@pjedrzejewski ok I will push the fix this evening, I use the new syntax by force of habit :)

**Comment by aRn0D** [comment]
@pjedrzejewski should be green now!

**Comment by pjedrzejewski** [comment]
Thank you Arnaud! :+1:

**Pull request merged**
