### PR TITLE
[Security] Admin redirection fix

### LINKED ISSUE #6168: When not "admin-logged", /admin redirects to /login
... I guess it should rather redirect to `/admin/login`, no ?

It's the case on the demo site, too.

### PR DESCRIPTION
**Pull request by lchrusciel**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Related tickets | fixes #6168 
| License         | MIT

working without a slash
working with a slash

### CODE REVIEW

**Comment by michalmarcinkowski** [comment]
Can we also remove exiting redirect root now?
```
sylius_admin_root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sylius_admin_dashboard
        permanent: true
```

**Comment by lchrusciel** [comment]
@michalmarcinkowski is it connected to this PR? I have only adjust a firewall changes.

**Comment by pamil** [comment]
@michalmarcinkowski shouldn't we put dashboard at `/` now?

**Comment by michalmarcinkowski** [comment]
Thanks Łukasz! 👍 

The admin root can be adjusted in a separate PR. Not sure why it was under `/dashboard` at a first place. Let's wait with this change for @pjedrzejewski.

**Pull request merged**
