### PR TITLE
Bump minimal requirements to Symfony 2.8

### PR DESCRIPTION
**Pull request by pamil**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Related tickets | includes #4978
| License         | MIT

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
Thanks Kamil! Now we need to fix all deprecation warning. :)

**Comment by pamil** [comment]
And work out how to deal with scope removal in service container of Symfony 3.0 :camel:

**Comment by pjedrzejewski** [comment]
@pamil LegacyFormBundle supports form type names in ``getParent()`` already? We need that too.

**Comment by rvanlaak** [comment]
Also see https://github.com/Sylius/Sylius/pull/3571

**Pull request merged**
