### PR TITLE
Revert "Move "polishsymfonycommunity/symfony-mocker-container" into dev dependencies" due to the BC break

### PR DESCRIPTION
**Pull request by lchrusciel**
This reverts commit 673bc6662c3934f3e5c1e8cfa0a3fc8710a437b1.

| Q               | A
| --------------- | -----
| Branch?         | 1.10
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| License         | MIT

In the https://github.com/Sylius/Sylius/pull/13118 we've introduced a small BC-Break. This commit breaks updated applications if they don't add ` && class_exists(MockerContainer::class)` part of conditions to theirs kernel. Therefore, I'm proposing reverting this change, as it was part of patch release - which should be stable and easily accessible.

### CODE REVIEW

**Comment by stloyd** [comment]
Fun fact I was not proposing this change to 1.10 but to next major.

**Comment by lchrusciel** [comment]
Yup, thats my fault.

**Comment by lchrusciel** [comment]
Thank you, Łukasz! :tada:

**Comment by lchrusciel** [comment]
Should be merged to 1.10. I've downported commited to proper branch

**Pull request merged**
