### PR TITLE
[ApiBundle] Form registration, missing specs and CS

### PR DESCRIPTION
**Pull request by aRn0D**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | refactoring 
| BC breaks?    | yes
| Deprecations? | no
| Fixed tickets | no
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by aRn0D** [comment]
@pjedrzejewski rebased !

**Comment by michalmarcinkowski** [comment]
:+1:

**Comment by aRn0D** [comment]
ping @pjedrzejewski

**Comment by pjedrzejewski** [comment]
Thanks Arnaud! ;)

**Pull request merged**
