### PR TITLE
[CoreBundle] Adding OrderPricingListener spec and fixing CS

### PR DESCRIPTION
**Pull request by mgonyan**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | enhancement
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | no
| License       | MIT
| Doc PR        | no

- Adding specs for OrderPricingListener class
- Fixing CS

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
@mgonyan I have restarted the failing builds.

**Comment by mgonyan** [comment]
:+1: @pjedrzejewski

**Comment by pjedrzejewski** [comment]
The build is still failing, could you have a look?

**Comment by mgonyan** [comment]
@pjedrzejewski fixed

**Comment by pjedrzejewski** [comment]
Thank you Manuel! :+1:

**Pull request merged**
