### PR TITLE
Replace EntityManager type-hints in the constructors with EntityManagerInterface

### PR DESCRIPTION
**Pull request by Wojdylak**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 2.0
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | yes
| Deprecations?   | no
| Related tickets | #13549
| License         | MIT

### CODE REVIEW

**Review by diimpp — DISMISSED** [review]
There is one more at

https://github.com/Sylius/Sylius/blob/7f14e4b5f53185fdba8e14207ac6c8097ee5b7a0/src/Sylius/Bundle/CoreBundle/CatalogPromotion/CommandHandler/RemoveInactiveCatalogPromotionHandler.php#L16

**Comment by jakubtobiasz** [comment]
We talked only about repositories, but we might expand that task about all other places where `EntityManager` is used instead of the interface 🤔. From what I see it's about 2-3 more classes.

**Review by Rafikooo — COMMENTED** [review]
Shouldn't we mention such a change in the upgrade file? (1.13 -> 2.0)

**Comment by jakubtobiasz** [comment]
@Rafikooo previously it was requiring `EntityManager` type which is more specific, so it won't require any additional work :p. We can add such a note, but it won't change anything. I'm for skipping that information as we'll have a bunch of steps for upgrading, there's no need to add minor (and at the end of day nothing changing) changes.

**Review by loic425 — DISMISSED** [review]

**Review by Rafikooo — DISMISSED** [review]

**Review by jakubtobiasz — DISMISSED** [review]

**Review by Rafikooo — DISMISSED** [review]
Not a big deal, but there are some specs, that use `EntityManager` instead of `EntityManagerInterface`

**Comment by jakubtobiasz** [comment]
So, let's change them before merging @Wojdylak 👆🏻

**Comment by Wojdylak** [comment]
@jakubtobiasz I've changed these files.

**Review by jakubtobiasz — APPROVED** [review]

**Review by Rafikooo — APPROVED** [review]

**Review by diimpp — APPROVED** [review]

**Pull request merged**
