### PR TITLE
WIP - implement shift multiple select for bulk actions

### PR DESCRIPTION
**Pull request by gabiudrescu**
| Q               | A
| --------------- | -----
| Branch?         | 
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | partially #8917 
| License         | MIT

Not ready yet. if you like the idea, I'll have to modify each yml file from Sylius/Bundle/AdminBundle/Resources/config/grids/* to ensure all grids have this feature.

So far, I've implemented it for Products.

### CODE REVIEW

**Comment by gabiudrescu** [comment]
I have no clue why Travis failed.
also, wdyt about incl. this in a 1.0.x release?

**Comment by gabiudrescu** [comment]
Based on the feedback from @stefandoorn I implemented a simpler solution:

image

**Comment by gabiudrescu** [comment]
build keeps failing for unrelated issues :(

**Comment by wapcrazut** [comment]
I know it's closed, but this should be implemented. 
In grids with many records this would be handy.

**Comment by tophsic** [comment]
Don't worry, @odautriche try to resolve this use case :wink:

**Pull request closed without merging**
