### PR TITLE
[Promotion] Introduce code for Promotion

### PR DESCRIPTION
**Pull request by tuka217**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | yes
| Deprecations? | no
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by peteward** [comment]
Doesn't code become confusing with coupon codes? I assumed that's why there weren't already there.

**Comment by pjedrzejewski** [comment]
@tuka217 Nice work, please add a database migration and add a PR to the docs.

@peteward Can be a bit confusing, but I think it is essential for all imports/exports to identify a promotion with a unique code. Also, helps if you have some custom logic in your code specific to a promotion (should not be done, although gives you a lot of flexibility if you have to do something like this in a short timeframe)

Unfortunately I do not see way for avoiding confusion other than documenting fields well in the docs. Saying that this code is a "machine name" for promotion and should not be confused with codes on the promotion coupon entity.

**Comment by stloyd** [comment]
@pjedrzejewski Personally I get `code` quite confusing, IMO those all PRs were adding `identifiers` or `internal identifiers/codes`.

**Comment by pjedrzejewski** [comment]
I don't see how ``code`` is confusing except for the Promotion example. I'd say if we document it well, there will be no problem. Identifier would be confused with the id and redundant.

**Comment by peteward** [comment]
There is now a consistency with the term `code` within Sylius, with the recent PR's I think it's clear enough from a code architecture. Some though might need to be given to avoiding confusion to the admin user though so that they know what to expect.

**Comment by pjedrzejewski** [comment]
@tuka217 Could you take a look at the failing build?

**Comment by pjedrzejewski** [comment]
Thank you Ania! :+1:

**Pull request merged**
