### PR TITLE
Split Sylius packages in Github Actions

### PR DESCRIPTION
**Pull request by Zales0123**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.11         |
| Bug fix?        | no                                                       |
| New feature?    | no                                                       |
| BC breaks?      | no                                                       |
| Deprecations?   | no |
| Related tickets |                       |
| License         | MIT                                                          |

Currently, we're doing packages split manually (I mean, with a script 😄 but by ourselves) after each merge. I suppose it's the highest time to automatize it. I checked this configuration on my fork and it worked :dancer: I'm not sure do `user_name` and `user_email` should be mine (or anywhere else)... maybe we should use Sylius and hello@sylius.com? But it can be also fixed later 🖖

### CODE REVIEW

**Review by loic425 — APPROVED** [review]

**Comment by loic425** [comment]
@Zales0123 Is something possible to do after tagging?

**Comment by mbabker** [comment]
> @Zales0123 Is there something possible to do after tagging?

Yep, that part's absolutely needed (and the action's docs cover that).

> I'm not sure do `user_name` and `user_email` should be mine (or anywhere else)... maybe we should use Sylius and [hello@sylius.com](mailto:hello@sylius.com)?

If the Symplify tool works similarly to `splitsh-lite`, the author here should really only matter for tags and mostly just affects the releases page on the read-only repo (just look at the tags in https://github.com/symfony/console/tags or https://github.com/Pagerfanta/twig/tags, both are read-only split repos).

**Comment by Zales0123** [comment]
@loic425 @mbabker aggreed, I just wanted to start simple and then extend the action (maybe I'm too cautious 😄 but I still have 5% of uncertainty would it work well :dancer:)

**Comment by loic425** [comment]
@Zales0123 Yes, let's start simple, you're right, I prefer tiny PRs

**Review by loic425 — APPROVED** [review]

**Comment by Ferror** [comment]
Yea I would go with ex github@sylius.com or any other email/user. We could even make it a little more fun and make Swan Bot <3 🦢

**Comment by Zales0123** [comment]
I guess I could generate a token for @SyliusBot account 🤔 It seems as the best option for now 🖖

**Review by GSadee — APPROVED** [review]

**Comment by GSadee** [comment]
Thanks, Mateusz! :tada:

**Pull request merged**
