### PR TITLE
Add migration to change column types from JSON to TEXT, as it is on MySQL database

### LINKED ISSUE #15390: Bug on removing product attribute value (postgres only)
**Sylius version affected**: 1.x.y

**Description**  
The PostgreSQL database schema contains JSON typed property on table sylius_product_attribute_value (the json_value field). The JSON type breaks the functionality of removing select-typed attribute value from the attribute, when it's used in the product.

**Steps to reproduce**  
1. Create a "Select" typed product attribute with 3 options.
2. Assign different options if the attribute to the product.
3. Try to remove one option form the attribute, which is used in the product.

**Possible Solution**  
I've did some research on PostgreSQL documentation, which says the JSON type is stored as clean text value, so it's possible just to write the migration to convert that column type into TEXT.

Reflinks:

- https://www.postgresql.org/docs/current/datatype-json.html
- https://www.postgresql.org/docs/current/datatype-character.html

### PR DESCRIPTION
**Pull request by senghe**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.13 (1.12 has no postgresql migrations)                  |
| Bug fix?        | yes                                                       |
| New feature?    | no                                                       |
| BC breaks?      | no                                                       |
| Deprecations?   | no |
| Related tickets | fixes #15390                      |
| License         | MIT                                                          |

### CODE REVIEW

**Comment by senghe** [comment]
I see one check is broken, but it's not related to my fix.

**Comment by senghe** [comment]
Hi @diimpp, could I ask you for a review? :pray:

**Comment by diimpp** [comment]
@senghe Hi, I've seen PR, but I'm not experienced with PostgreSQL, so I cannot say much. If nobody will do a review, I will try to reproduce over weekend.

@Rafikooo Hi, could you please take a look as you've done two PostgreSQL PRs recently.

**Comment by Rafikooo** [comment]
> @senghe Hi, I've seen PR, but I'm not experienced with PostgreSQL, so I cannot say much. If nobody will do a review, I will try to reproduce over weekend.
> 
> @Rafikooo Hi, could you please take a look as you've done two PostgreSQL PRs recently.

Hey Fellows, I'll have a look at it later

**Comment by senghe** [comment]
@Rafikooo I would kindly ask you, would you review this PR? :)

**Comment by NoResponseMate** [comment]
IMO this will create more problems than fix, since if anyone was already using it as an actual json column this will basically break their app. How about instead of migrating it to text we'd do something like [this](https://github.com/ScientaNL/DoctrineJsonFunctions)?

**Comment by senghe** [comment]
@NoResponseMate I can't agree with you. By extending Sylius, everyone can use anything in any way. But the Sylius logic uses that fields in database like a text fields, so they should be text. Migrating from JSON to TEXT won't change anything in the Sylius behaviour. I think the developers who use Sylius should review every database migration query and react if changed anything they customized.

**Comment by vvasiloi** [comment]
Hey @senghe, it would be nice to see a test that reproduces the issue. It will also prevent regression in the future, especially since, for Sylius projects, PostgreSQL is not as popular of a choice as MySQL. We test on PostreSQL, so adding another scenario, such as the one you described in the issue, to our E2E test suite with Behat would be great!
You can find the existing scenarios covering the product attributes management here: https://github.com/Sylius/Sylius/tree/1.13/features/product/managing_product_attributes

**Comment by diimpp** [comment]
@senghe Hi, does this solves your issue? https://github.com/Sylius/Sylius/pull/16012

**Comment by jakubtobiasz** [comment]
Yes, it does @diimpp. My PR is a fix exactly for that issue. I just forgot to close it.

**Pull request closed without merging**
