### PR TITLE
Bump version and branch alias for 1.0.0-alpha

### PR DESCRIPTION
**Pull request by pjedrzejewski**

### CODE REVIEW

**Comment by pamil** [comment]
It's happening! :tada:

**Comment by inssein** [comment]
Are there any bug fixes that 0.19 is waiting for? There are still a few that are important, like https://github.com/Sylius/Sylius/issues/5008

**Comment by pjedrzejewski** [comment]
@inssein Unfortunately, these will be fixed in the new shop, so not part of v0.19.0.

**Comment by inssein** [comment]
Ah okay. Is there an updated road map somewhere, with some estimates for release? Also, am I correct in assuming that 0.19 won't release with a WebBundle?

**Comment by pamil** [comment]
`composer.lock` needs to be updated

**Comment by michalmarcinkowski** [comment]
🎉

**Comment by theyoux** [comment]
I did not see this one, SO-GREAT!!!

**Pull request merged**
