### PR TITLE
Minor fixtures fixes

### PR DESCRIPTION
**Pull request by AdamKasp**
| Q               | A
| --------------- | -----
| Branch?         | 
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | n
| License         | MIT

### CODE REVIEW

**Comment by AdamKasp** [comment]
> Will it solve some of order fixtures problems like #10719?

No, it fixed the only problem with missing fixture data :(

**Comment by lchrusciel** [comment]
As it is bugfix, we should add it to 1.6

**Comment by lchrusciel** [comment]
The base of this pull-request was changed, you need fetch and reset your local branch 
if you want to add new commits to this pull request. **Reset before you pull, else commits
may become messed-up.**

Unless you added new commits (to this branch) locally that you did not push yet, 
execute `git fetch origin && git reset "minor-fixture-fixes"` to update your local branch.
 
Feel free to ask for assistance when you get stuck :+1:

**Comment by GSadee** [comment]
Thank you, Adam! :tada:

**Pull request merged**
