### PR TITLE
Fix for #9942

### LINKED ISSUE #9942: AbstractResourceFixture: Node `prototype` not defined at `options` node
**Sylius version affected**: 1.3.3

**Description**  
I would like to use `prototype` option during random fixtures creation for my custom resource as far as my resource have some mandatory options which can't be generated by faker and should be provided at `prototype` to populate to every random fixture (this option is designed for this as I noticed reading code).

But as far as this option never used by Sylius itself, it was not tested and actually not working as far as node `prototype` not defined at `options` node.

**Steps to reproduce**  
```
# config/packages/_sylius.yaml
sylius_fixtures:
    suites:
        default:
            fixtures:
                any_resource_fixture:
                    options:
                        random: 3
                        prototype: # <------- This one is not defined at AbstractResourceFixture::getConfigTreeBuilder, but used at AbstractResourceFixture::__construct to produce random fixtures
                            mandatory_option_name: 'bla1'
                        custom:
                            resource_fixture_1:
                                mandatory_option_name: 'bla2'
```

**Possible Solution**  
I will prepare PR now with next change:
```php
<?php
# AbstractResourceFixture.php

abstract class AbstractResourceFixture implements FixtureInterface
{
    // ...
    final public function getConfigTreeBuilder(): TreeBuilder
    {
        // ...
        $optionsNode->children()
            ->integerNode('random')->min(0)->defaultValue(0)->end()
            ->variableNode('prototype')->end() // <------ This line was added
        ;
        // ...
        return $treeBuilder;
    }
    // ...
}
```

### PR DESCRIPTION
**Pull request by igormukhingmailcom**
| Q               | A
| --------------- | -----
| Branch?         | master
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #9942
| License         | MIT

### CODE REVIEW

**Comment by igormukhingmailcom** [comment]
Sorry, I've committed to `master` before noticed this should be on `1.2`.

**Comment by igormukhingmailcom** [comment]
@lchrusciel 

> create a prototyped resource in fixtures

I guess `prototype` could be used here:

```
# fixtures.yml
# ...
                address:
                    options:
                        random: 10
                        prototype:
                            country_code: US
```

**Comment by lchrusciel** [comment]
@igormukhingmailcom can you add it to your PR? 

Also, for me, it is totally ok, how the current implementation works. I would even say, that it was desired. But, of course, feel free to open an issue, or even better fix it :) Maybe the rest of community will say something about it :)

**Comment by igormukhingmailcom** [comment]
> @igormukhingmailcom can you add it to your PR?

Added

**Comment by lchrusciel** [comment]
The base of this pull-request was changed, you need fetch and reset your local branch 
if you want to add new commits to this pull request. **Reset before you pull, else commits
may become messed-up.**

Unless you added new commits (to this branch) locally that you did not push yet, 
execute `git fetch origin && git reset "patch-3"` to update your local branch.
 
Feel free to ask for assistance when you get stuck :+1:

**Comment by lchrusciel** [comment]
Thanks, Igor! :tada:

**Pull request merged**
