### PR TITLE
[ProductReview] Changed classes to interfaces in ProductReviewAdminType

### PR DESCRIPTION
**Pull request by GSadee**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | #4381 
| License         | MIT
| Doc PR          |

### CODE REVIEW

**Comment by peteward** [comment]
:+1:  :smile:

**Comment by GSadee** [comment]
I guess that this PR was not a good idea, we could not use interfaces instead of classes, because it have to be an entity mapped by doctrine. @michalmarcinkowski WDYT? Is there any other option to solve problem from #4381 ?

**Comment by pjedrzejewski** [comment]
@GSadee Yes, removing this feature. I don't think we want adding reviews in backend. For editing: We can generate ``sylius_customer_choice`` type. Just add ``choice`` configuration node under ``customer -> node``. And I think we should remove the ability to select products, it does not make sense. Still not sure if it makes sense to edit them in admin.

**Comment by nakashu** [comment]
Edit in admin for review is viable but only for certain stuff, like title and comment. So the admin can fix typos in the review post by customer. Rating and review subject should not be editable imho.

**Pull request closed without merging**
