### PR TITLE
Add coupon channel eligibility checker

### LINKED ISSUE #14087: Promotions channels are not validated then Promotion Coupon is applied
**Sylius version affected**: All versions

**Description**  
Promotions channels are not validated then Promotion Coupon is applied

**Steps to reproduce**  
1. Create a Promotion with coupons
2. Disable all channels
3. Enter a promotion coupon code in cart
4. Promotion coupon code is applied to order (which is incorrect), but promotions are not distributed on items (which is correct)

Screenshot 2022-06-15 at 10 36 57

Screenshot 2022-06-15 at 10 38 02

**Possible Solution**  
Implement new PromotionEligibilityChecker, which will check for current channel.

### PR DESCRIPTION
**Pull request by PILLOWPET**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.10, 1.11 or master           |
| Bug fix?        | yes                                                       |
| New feature?    | no                                                     |
| BC breaks?      | no                                                       |
| Deprecations?   | no  |
| Related tickets | fixes #14087                     |
| License         | MIT                                                          |

### CODE REVIEW

**Comment by Roshyo** [comment]
Hey, thanks for your contribution. But it would be great if you could add some tests to cover that. First to make sure it is an issue in the first place (I did not try reproducing). And second to make sure it never fails again.

**Comment by Roshyo** [comment]
Also, I think that by default, it can not happen since the resolution takes first all applicable promotions by channel, then tries to apply them one by one. So I guess this issue is more due to a custom dev that took a promotion that was not assigned to that channel. Could I right?

**Comment by PILLOWPET** [comment]
I think the issue here is that there are 2 behaviors when a promotion coupon is applied to the order.

Scenario 1:
1. I create a promotion coupon associated to a promotion that will begin in 20 days.
2. I try to use the promotion coupon on my cart that matches the rules
3. I get an error "Coupon code is invalid" because the Eligibility Checker determines that the promotion cannot be applied

Scenario 2:
1. I create a promotion coupon associated to a promotion that will begin in 20 days.
2. I don't enable the coupon on channel US
3. I try to use the promotion coupon on my US cart that matches the rules
4. I don't get an error

These scenarios are reproducible on demo.sylius.com.

I think the behaviors should be consistent and we should show an error in both scenarios.

**Comment by TheMilek** [comment]
Hi @PILLOWPET 💃🏽 
I'm closing this PR as Your commits with tests added have been merged here: https://github.com/Sylius/Sylius/pull/14237
Kudos to You for solving this issue 🍻

**Pull request closed without merging**
