### PR TITLE
[WIP] Switch to FriendsOfBehat/SymfonyExtension ^2.0

### PR DESCRIPTION
**Pull request by pamil**
Proof of the concept.

The current Behat infrastructure, despite being powerful, is also overcomplicated. We use 5 different DI containers and glue them with three Behat extensions. SymfonyExtension v2.0 tries to solve that issue, being the only extension needed and providing autowiring and autoconfiguration support out of the box, while using only two containers (with Behat one being transparent for end-users).

Things to consider:
 - [ ] Deprecate the current services configuration instead of replacing it in order not to break plugins using Sylius context services
 - [x] Perform performance testing
 - [x] Publish stable release of SymfonyExtension
 - [x] Publish stable release of PageObjectExtension

| Q               | A
| --------------- | -----
| Branch?         | 1.2
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | -
| License         | MIT

### CODE REVIEW

**Comment by pamil** [comment]
Performance looks roughly the same as the previous generation.

**Comment by loic425** [comment]
@pamil Why this pull-request has been closed?

**Comment by pamil** [comment]
I've started to work on a new PR locally, it's tough to make it BC-break-free way, but I'll open a new one this week.

**Comment by loic425** [comment]
@pamil Thx, good work anyway.
I'm gonna follow your new PR when you'll submit it.

**Comment by pamil** [comment]
@loic425 there's #10102 🎉

**Pull request closed without merging**
