### PR TITLE
fix my email

### PR DESCRIPTION
**Pull request by bendavies**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Related tickets | 
| License         | MIT

this is my best PR to date.

### CODE REVIEW

**Comment by okwinza** [comment]
I'm pretty much sure you forgot to mark this with "[CRITICAL]" tag. :laughing:

**Comment by Zales0123** [comment]
Happy to see you inspired so many people to perform some crucial actions on this awesome project! 🏇 💃 
zrzut ekranu 2016-05-20 o 15 58 07

**Comment by bendavies** [comment]
oh boy

**Comment by pamil** [comment]
Looks good to me, ready to go! :)

**Comment by Zales0123** [comment]
Agreed and happy to say that! 👍

**Comment by pjedrzejewski** [comment]
👍

**Pull request merged**
