### PR TITLE
[Mailer] add reply-to on contact request email

### PR DESCRIPTION
**Pull request by loic425**
| Q               | A
| --------------- | ---
| Bug fix?        | no |
| New feature?    | yes |
| BC breaks?      | yes |
| Related tickets | mentioned in #8371  |
| License         | MIT |

### CODE REVIEW

**Comment by stefandoorn** [comment]
I think this is a BC break, as it's changing the interface. I'm using it also in a custom implementation, which won't like that.

But, +1 for this. What about BCC / CC? This is a great win already for SPF / email spam etc., but BCC / CC could also be helpful now and then.

**Comment by loic425** [comment]
@stefandoorn Yes, i've changed bc break to true.

**Comment by pjedrzejewski** [comment]
@loic425 Looks good, could you just add a note to UPGRADE file about the interface change? :)

**Comment by loic425** [comment]
@pjedrzejewski done :)

**Comment by loic425** [comment]
@pjedrzejewski @lchrusciel 
The linked issue is tagged as 1.0.0, so this one could me imho :)

**Comment by pjedrzejewski** [comment]
Thank you @loic425! Nice work. :)

**Pull request merged**
