### PR TITLE
[Content] Clean up a little bit

### PR DESCRIPTION
**Pull request by pamil**

### CODE REVIEW

**Comment by pamil** [comment]
Don't want to spam Travis, temporarily closed :)

**Comment by gabiudrescu** [comment]
from what you've seen so far, is this kind of clean up speeding up the build or an installed Sylius instance?

**Comment by pamil** [comment]
Actually the #6365 was opened as I couldn't reopen this one.

The goal of cleanups we're doing now is to unify the code to make it use the same conventions, finalise as many classes as possible, decouple it and remove unused code. It probably won't make Sylius noticably faster (this is the next phase), but more stable and more prepared for alpha & beta releases. The less code to maintain the better :)

**Comment by gabiudrescu** [comment]
I see. well, keep up the good work.

**Pull request closed without merging**
