### PR TITLE
Fix error templates path

### PR DESCRIPTION
**Pull request by pamil**
Reported in #9778.

### CODE REVIEW

**Comment by Zales0123** [comment]
As far as I understand, it only resolves a problem with error template override? Overriding another Sylius templates is still bugged?

**Comment by pamil** [comment]
@Zales0123 it fixes some of that error templates (404, 500), but not others (401) - but overall the path was wrong - `templates/bundle/` instead of `templates/bundles/`.

**Comment by Zales0123** [comment]
Thank you, Kamil! ⭐️

**Comment by emodric** [comment]
@Zales0123 You're right, yes, overriding Sylius templates is still bugged. For example, I tried overriding the main layout template with `templates/bundles/SyliusShopBundle/layout.html.twig` path, and it doesn't work.

**Comment by pamil** [comment]
@emodric I'm on it! :)

**Comment by nechocandia** [comment]
I just tried to do the same path from the tutorial: https://docs.sylius.com/en/1.3/customization/template.html  

`\templates\bundle\SyliusShopBundle\login.html.twig` and it's not working for me, I already did the `cache:clear` and I can't see anything.

I'm using the latest version.

**Comment by Zales0123** [comment]
There is a bug in documentation, should be `\templates\bundles` not `\templates\bundle` :)

**Comment by pamil** [comment]
@nechocandia docs should be fixed already (#9841).

**Comment by Gerardlc** [comment]
> @Zales0123 You're right, yes, overriding Sylius templates is still bugged. For example, I tried overriding the main layout template with `templates/bundles/SyliusShopBundle/layout.html.twig` path, and it doesn't work.

Is there any solution? Im stuck on this

**Pull request merged**
