### PR TITLE
[Core] Do not remove onFlush listeners in OrderItemInventoryListener

### LINKED ISSUE #5270: [Core] OrderItemInventoryListener removes all onFlush listeners
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/EventListener/OrderItemInventoryListener.php#L62-L64

```php
/**
 * @param OnFlushEventArgs $args
 */
public function onFlush(OnFlushEventArgs $args)
{
    $em = $args->getEntityManager();
    $eventManager = $em->getEventManager();
    $uow = $em->getUnitOfWork();

    foreach ($listeners = $eventManager->getListeners('onFlush') as $listener) {
        $eventManager->removeEventListener('onFlush', $listener);
    }

    foreach ($uow->getScheduledEntityUpdates() as $entity) {
        if ($this->supports($entity)) {
            $this->eventDispatcher->dispatch('sylius.order_item.pre_update', new GenericEvent($entity));
            $uow->commit($entity);
        }
    }

    foreach ($listeners as $listener) {
        $eventManager->addEventListener('onFlush', $listener);
    }
}
```

### PR DESCRIPTION
**Pull request by pamil**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | yes (listeners do execute on that flush now)
| Related tickets | fixes #5270 (and failing build on master)
| License         | MIT

### CODE REVIEW

**Comment by lchrusciel** [comment]
Why didn't you add a `[CRITICAL]` label to title? It is a must-have.

**Comment by pamil** [comment]
`[CRITICAL]` is reserved for changing emails and adding funny themes :tada:

**Comment by peteward** [comment]
`wtf/cancer-removal` 😄

**Comment by pjedrzejewski** [comment]
Thanks Kamil!

**Pull request merged**
