### PR TITLE
Add missing translation-bundle dependency

### PR DESCRIPTION
**Pull request by amenophis**

### CODE REVIEW

**Comment by amenophis** [comment]
@pjedrzejewski without this, it make resource-bundle unusable standalone.

**Comment by amenophis** [comment]
used here: https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/DependencyInjection/SyliusResourceExtension.php#L27

and here:
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/DependencyInjection/AbstractResourceExtension.php#L35

**Comment by amenophis** [comment]
@pjedrzejewski rebased

**Comment by pjedrzejewski** [comment]
Thanks, I need to update Lionframe. :)

**Comment by amenophis** [comment]
@pjedrzejewski you're welcome !

**Pull request merged**
