### PR TITLE
Adding default outgoing ip address for dev (default vm outgoing network)

### PR DESCRIPTION
**Pull request by vihuvac**

### CODE REVIEW

**Comment by elliot** [comment]
-1
Each developers setup/local network will be different - we can't expect everyone to be on a 10.0.0.0/8 network with the first IP

**Comment by cordoval** [comment]
@elliot is right, you can do these customizations in your own project.

**Comment by vihuvac** [comment]
Yeah I am agree but I added that ip address according to the **project's default ip** (**10.0.0.200**). I got several projects running under **vagrant** and **puppet**, and I usually preserve the ip range in order to have the same **ip for the outgoing network**, it means you can have a different ip for each project but if you preserve the range for each one, the outgoing will the always the same. In this case it is really obvious, and in fact I do not use the same range **10.0.0.something_else** because this is commonly used. if you go to the **vagrant directory** and run `vagrant up` you will have **10.0.0.1** as **outgoing network** (the same than mine), so that's because _**the vm ip address is 10.0.0.200**_ (used in this case), _I did not added that ip_ (10.0.0.200), it was already added in the project itself, but the ip that was not added or registered it was the outgoing network, that ip should be right there if you want to use the default project settings. Curious! None of you noticed such small detail.

**Comment by pborreli** [comment]
:+1: for DX sake
> 10.0.0.0/8 - This block is set aside for use in private networks.
   Its intended use is documented in [RFC1918].  Addresses within this
   block should not appear on the public Internet.

**Comment by jrobeson** [comment]
If you want something like this to work for more people, then you should use something like this: https://github.com/symfony/symfony-standard/pull/773  . The main problem being though.. that these defaults would leave app_dev.php open on many company intranets.

**Comment by jimbocoder** [comment]
Have to agree with the other :-1: comments, because a "private" (as in RFC1918) address is not the necessarily the same as a "trusted" address.  The only responsible exception would be localhost addresses, which is how things stand now -- everyone's still free to customize their own project to add other trusted networks, so there's little upside in my opinion.

Suggesting to close this one, so it doesn't repeatedly get discussed in the future.

**Comment by elliot** [comment]
Sylius needs to ship with safe defaults, so I'm with @jimbocoder in saying private != trusted.

**Comment by pjedrzejewski** [comment]
I agree with :-1:, private is not trusted. Thanks for the discussion guys.

**Pull request closed without merging**
