### PR TITLE
[Shop] Preselect only available country on addressing form

### PR DESCRIPTION
**Pull request by Zales0123**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Related tickets |
| License         | MIT

### CODE REVIEW

**Comment by michalmarcinkowski** [comment]
👍

**Comment by pjedrzejewski** [comment]
This is a required field, so we should not allow "empty" option, this looks like a bit of workaround for a simple thing.

**Comment by michalmarcinkowski** [comment]
Do you know a better solution than one `if` statement?

**Comment by pjedrzejewski** [comment]
Yes, using the built-in HTML feature... 😆  https://jsfiddle.net/u7La63ph/

The rendered select is invalid, because it allows empty value, which is incorrect, as this field must be selected. It will work even if there are no countries configured. So the solution is to fix Symfony form to render properly, not this if and "forcing" a value on the field.

**Comment by michalmarcinkowski** [comment]
Welcome back our frontend master! 🎉  😆

**Comment by pjedrzejewski** [comment]
XD

**Pull request merged**
