### PR TITLE
Update Github PR template

### PR DESCRIPTION
**Pull request by Zales0123**
| Q               | A
| --------------- | -----
| Branch?         | 1.7
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| License         | MIT

### CODE REVIEW

**Review by jacquesbh — APPROVED** [review]

**Review by arti0090 — APPROVED** [review]

**Review by oallain — APPROVED** [review]

**Comment by jacquesbh** [comment]
@Zales0123 Are you sure you want to merge this on 1.7 branch? And not on 1.8 or master?

**Comment by oallain** [comment]
This is already on master by #11930 :wink:

**Comment by Zales0123** [comment]
I think the developer should be informed about all supported branches, no matter where the PR is opened :) 🖖

**Review by lchrusciel — APPROVED** [review]

**Comment by lchrusciel** [comment]
Thanks, Mateusz! :tada:

**Pull request merged**
