### PR TITLE
Fix having error using alias for postgresql in SalesDataProvider

### PR DESCRIPTION
**Pull request by apeliberty**
Hello,

having clause error using alias for postgresql.

| Q               | A
| --------------- | -----
| Branch?         | 1.7, 1.8 or master 
| Bug fix?        | no/yes
| New feature?    | no/yes
| BC breaks?      | no/yes
| Deprecations?   | no/yes 
| Related tickets | fixes #X, partially #Y, mentioned in #Z
| License         | MIT

### CODE REVIEW

**Comment by lchrusciel** [comment]
Hey Alexis,

thanks for your first contribution to Sylius. However, the build is failing (due to SQL structure I suppose). Also, can you rebase to the newest version of master?

**Comment by apeliberty** [comment]
> Hey Alexis,
> 
> thanks for your first contribution to Sylius. However, the build is failing (due to SQL structure I suppose). Also, can you rebase to the newest version of master?

I just rebase on the latest version of master.

**Comment by lchrusciel** [comment]
Hey Alexis,

I'm afraid we cannot merge it, as your changes are breaking current behavior :(

**Comment by vvasiloi** [comment]
For reference, there's another PR with the same proposal: #13432

**Comment by jakubtobiasz** [comment]
As @vvasiloi mentioned, the problem was fixed in another PR. Thanks for your contribution anyway :).

**Pull request closed without merging**
