### PR TITLE
[Resource] Repository interface fix

### PR DESCRIPTION
**Pull request by TheMadeleine**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Related tickets |
| License         | MIT

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
@TheMadeleine Why removing the constants?

**Comment by TheMadeleine** [comment]
@pjedrzejewski - Since they are used just in one place and that in my opinion makes them a bit redundant.

**Comment by michalmarcinkowski** [comment]
We should use them in all new development and when refactoring the existing repository methods. I would leave them :)

**Comment by TheMadeleine** [comment]
Corrected :)

**Comment by michalmarcinkowski** [comment]
This PR should fix [this bug](https://github.com/michalmarcinkowski/Sylius/blob/90f267c8edfc0d6ce48813b2adc619017ce50682/src/Sylius/Component/Resource/Repository/InMemoryRepository.php#L170-L170), but know it doesn't.

**Comment by TheMadeleine** [comment]
now, it does @michalmarcinkowski

**Comment by pjedrzejewski** [comment]
Thanks Magda!

**Pull request merged**
