### PR TITLE
fixes #2036 define config keys to allow override

### LINKED ISSUE #2036: Overriding setting for showing taxons is not working
I am trying to override in separate file configuration for showing products by taxon like this:

sylius_core:
    routing:
        %sylius.model.taxon.class%:
            field: permalink
            prefix: /t
            defaults:
                controller: sylius.controller.product:indexByTaxonAction
                sylius:
                    template: SyliusWebBundle:Frontend/Product:indexByTaxon.html.twig
                    paginate: 12

but it seems that anything under defaults is not getting overriden in this way

### PR DESCRIPTION
**Pull request by MichaelKubovic**
Looks like 'controller' and 'sylius' keys have to be explicitly declared, otherwise the merged config would look like:

```
{
  "defaults": {
    "1": {
      "template": "AcmeBundle:Product:indexByCategorySlug.html.twig"
    },
    "0": "AcmeBundle:Product:indexByCategorySlug",
    "sylius": {
      "template": "SyliusWebBundle:Frontend\\/Product:indexByTaxon.html.twig"
    },
    "controller": "sylius.controller.product:indexByTaxonAction"
  },
  "prefix": "\\/t",
  "field": "permalink"
}
```

### CODE REVIEW

**Comment by aRn0D** [comment]
@MichaelKubovic can you have a look on it, can you give us feedback ?

**Comment by pjedrzejewski** [comment]
Ping @MichaelKubovic.

**Comment by michalmarcinkowski** [comment]
Ping @MichaelKubovic.

**Comment by MichaelKubovic** [comment]
I've just tried to reproduce the problem on current master and it seems that the issue no longer exists. Feel free to close. and #2036

**Comment by pjedrzejewski** [comment]
@MichaelKubovic Awesome, thanks for letting us know!

**Pull request closed without merging**
