### PR TITLE
[WebBundle] Remove default icon for enable and disable buttons

### PR DESCRIPTION
**Pull request by michalmarcinkowski**
IMO this icons are unnecessary and we should remove them at default.

### CODE REVIEW

**Comment by aRn0D** [comment]
:+1: I think we should keep them :dancer:

**Comment by pamil** [comment]
Every button has its own icon, why do we want to make an exception? It will save some space on small screens too. Anyway, I think that we need enable and disable buttons to have the same width, it will look nice while rendering them in column.

**Comment by pjedrzejewski** [comment]
Let's keep them for now, otherwise on small screen you won't see anything.

**Comment by michalmarcinkowski** [comment]
I don't think that current icons are the most approriate, but agree with you guys :+1:

**Pull request closed without merging**
