### PR TITLE
Psalm

### PR DESCRIPTION
**Pull request by loic425**
| Q               | A
| --------------- | -----
| Branch?         | 1.3
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| License         | MIT

### CODE REVIEW

**Comment by loic425** [comment]
@pamil @lchrusciel @Zales0123 
There is an interesting error triggered by Psalm on Symfony 3 build.
StaticPrefixCollection doesn't have **populateCollection** method on symfony/routing 3.3
https://github.com/symfony/routing/blob/3.4/Matcher/Dumper/StaticPrefixCollection.php

**Comment by pamil** [comment]
@loic425 thanks for your patience, #10468 should fix that error.

**Comment by loic425** [comment]
@pamil Something was wrong with rebase. It requires phpstan/phpstan (and not phpstan-shim) to get rid of nikic/php-parser error.

**Comment by loic425** [comment]
@pamil I fixed this pull-request. CI builds are now ok

**Comment by pamil** [comment]
Thank you, Loïc! :tada:

**Pull request merged**
