### PR TITLE
Include correct Paweł's email

### PR DESCRIPTION
**Pull request by pamil**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | yes
| Related tickets | -
| License         | MIT

Inspired by #5080 and #5081, I think it is crucial for Sylius to have correct, unified Paweł's email address.

### CODE REVIEW

**Comment by Zales0123** [comment]
I see some big changes being done on *Sylius*, bigger than ever!
zrzut ekranu 2016-05-20 o 15 54 01

**Comment by pamil** [comment]
@Zales0123 preparing for alpha release! 📆

**Comment by okwinza** [comment]
@Zales0123 That's one small step for Sylius, one giant leap for Pawel' email address :laughing:

**Comment by pjedrzejewski** [comment]
Thanks Kamil! :)

**Pull request merged**
