### PR TITLE
Use semantic ui view instead of deprecated semantic_ui_translated

### LINKED ISSUE #12462: [UiBundle] Pagination macro uses deprecated PagerfantaBundle view
With the introduction of Twig support into Pagerfanta and PagerfantaBundle, I deprecated all of the PHP templates from the bundle that essentially were decorators around the base classes and used Symfony's translator to override the messages in favor of Twig templates.  The pagination macro in the UiBundle is still using the deprecated PHP view class and should be updated to remove the use of this deprecated API (note, this is a blocker to allowing Pagerfanta and PagerfantaBundle 3.0 in the main Sylius app).

From an end-user perspective, it becomes a little easier to customize pagination templates with Twig as they have full control of the various blocks that are rendered and it's easier to introduce new Twig templates, whereas with the PHP templates the options really only give control over some CSS classes and deeper markup adjustments would require new PHP classes and a compiler pass registering them to the view factory.

```twig
{{ pagerfanta(paginator, 'twig', options|default({'template': '@BabDevPagerfanta/semantic_ui.html.twig'})) }}
```

I *think* that should be the right change needed in the macro, but there are minor markup differences between the PHP template and the Twig template so it may be slightly more involved to make the change.  Personally, I'd also recommend updating the Sylius-Standard with the below config snippet and changing the macro call to `{{ pagerfanta(paginator, options) }}` as at that point you can control the default pagination view and Twig template through the Symfony configuration instead of needing to overload a macro which uses a hardcoded view name:

```yaml
babdev_pagerfanta:
    default_view: 'twig'
    default_twig_template: '@BabDevPagerfanta/semantic_ui.html.twig'
```

### PR DESCRIPTION
**Pull request by loic425**
| Q               | A
| --------------- | -----
| Branch?         | 1.11
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #12462
| License         | MIT

### CODE REVIEW

**Comment by Zales0123** [comment]
cc @kulczy but seems good for me 😄

**Comment by mbabker** [comment]
You need to use the “twig” view with the `@BabDevPagerfanta/semantic_ui.html.twig` template to keep translation support.  The “semantic_ui” view is PHP generated without translation support.

This’ll also close https://github.com/Sylius/Sylius/issues/12462 😉

**Comment by loic425** [comment]
@mbabker Thx a lot, I will follow your issue details to update this PR.

**Comment by loic425** [comment]
@mbabker I updated this PR, is that ok for you?

For the package configuration, I think it's needed into the sylius/sylius-standard repository.

**Review by mbabker — APPROVED** [review]

**Review by lchrusciel — APPROVED** [review]

**Comment by lchrusciel** [comment]
Thank you, Loïc! :tada:

**Pull request merged**
