### PR TITLE
[OrderBundle] Bug fix - add flush after cancel expired order/cart.

### PR DESCRIPTION
**Pull request by liverbool**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Related tickets | #6321 #6291
| License         | MIT

### CODE REVIEW

**Comment by michalmarcinkowski** [comment]
Thanks Ishmael! 👍

**Comment by pjedrzejewski** [comment]
Actually, the service should call the flush. @Zales0123 How is the scenario passing?

**Comment by michalmarcinkowski** [comment]
@pjedrzejewski not sure about that, now there is no service that does that, if all services would call `flush` we would have too many flushes during single request.

The scenario is passing because the entity is loaded into unity of work and there is no "refresh from database" between service call and assertion. Can we enforce that?

**Comment by pjedrzejewski** [comment]
I am of course against calling flush from inside most of services, but in this case, the service without flush does not make any sense. And you only call this service if you want to *really* cancel/delete these orders.

**Comment by liverbool** [comment]
😶 hard to say.

`flush` inside service make sense if this service doesn't use together with others.

**Comment by pjedrzejewski** [comment]
@liverbool I think in case of services like this, it makes sense. They are meant to be run separately. I just want to avoid situation when someone is surprised that carts are not cleared / cancelled when this is called.

**Comment by Zales0123** [comment]
I think the reason it works now, is because we're calling repository [``remove`` method](https://github.com/Sylius/Sylius/blob/6cb794ef5bbf43d7cea6bb7a9229a60d3e0926a9/src/Sylius/Component/Order/Remover/ExpiredCartsRemover.php#L45) inside each of this services. It implies ``flush`` [after each removal](https://github.com/Sylius/Sylius/blob/4bf30cee02d6d066dd3aff568b54c03c98791475/src/Sylius/Bundle/ResourceBundle/Doctrine/ORM/EntityRepository.php#L43), which also not good, as manager is flushed multiple times :/

**Comment by pjedrzejewski** [comment]
Oh, that's bad - let's add ``remove`` on the manager and do a late flush.

**Comment by Zales0123** [comment]
Good for me 👍  This requires of course injecting a manager, but it's lesser evil, I suppose ;)

**Comment by liverbool** [comment]
i dose't look in https://github.com/Sylius/Sylius/blob/4bf30cee02d6d066dd3aff568b54c03c98791475/src/Sylius/Bundle/ResourceBundle/Doctrine/ORM/EntityRepository.php#L43 that surprised me, why we need `manager.flush()` again !! (in my PR)

**Pull request merged**
