### PR TITLE
Fix sprintf parameters order

### PR DESCRIPTION
**Pull request by Creeperface01**
| Q               | A
| --------------- | -----
| Branch?         | 1.11 
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no 
| License         | MIT

### CODE REVIEW

**Review by Zales0123 — APPROVED** [review]
Nice catch 👍

**Comment by Zales0123** [comment]
@Creeperface01 we need a small fix in `AvailableProductOptionValuesResolverSpec` 🖖

**Comment by Creeperface01** [comment]
> @Creeperface01 we need a small fix in `AvailableProductOptionValuesResolverSpec` 🖖

Is it ok now?

**Review by NoResponseMate — APPROVED** [review]

**Review by jakubtobiasz — APPROVED** [review]

**Review by Rafikooo — APPROVED** [review]

**Review by everwhatever — APPROVED** [review]

**Review by TheMilek — APPROVED** [review]

**Review by coldic3 — APPROVED** [review]

**Comment by jakubtobiasz** [comment]
For future readers:
We are aware of the problem with one of builds configuration, and we are sure it is not related to this PR, so I merge it :).

**Comment by jakubtobiasz** [comment]
Thank you, @Creeperface01! :tada:

**Pull request merged**
