### PR TITLE
[Documentation] Syntax typo fix

### PR DESCRIPTION
**Pull request by kate-kate**
| Q               | A
| --------------- | ---
| Bug fix?        | no |
| New feature?    | no |
| BC breaks?      | no |
| Related tickets | - |
| License         | MIT |

Just a little fix for a valid example code

### CODE REVIEW

**Comment by lchrusciel** [comment]
@kate-kate thanks for your first-time contribution! We really appreciate your help. However your PR should be open to 1.0 branch, and because of our recent activities, we are not able to merge things that come from the master(it is 6 commits ahead 1.0). Would you like to rebase your PR to the 1.0 branch or do you prefer to wait until we will resolve our problems?

**Comment by kate-kate** [comment]
Ok, I will try

**Comment by lchrusciel** [comment]
If you would have any troubles, please find me on our slack and I try to help you

**Comment by GSadee** [comment]
@kate-kate Thank you for your first contribution! 😃

**Pull request merged**
