### PR TITLE
Cascade persist translatables

### PR DESCRIPTION
**Pull request by umpirsky**
In our app (where we override a lot of Sylius stuff) I was getting this error during CLI install:

```
$ ./app/console sylius:install
Installing Sylius...

Step 1 of 4. Checking system requirements.
+--------------------+----------------+
| Issue              | Recommendation |
+--------------------+----------------+
| short_open_tag     |                |
| session.auto_start |                |
+--------------------+----------------+
Success! Your system can run Sylius properly.

Step 2 of 4. Setting up the database.
Creating Sylius database for environment dev.
It appears that your database already exists. Would you like to reset it? (y/N) y
 7/7 [||||||||||||||||||||||||||||] 100%
Warning! This will erase your database. Your current environment is dev.
Load sample data? (y/N) y
Loading sample data...
 3/4 [||||||||||||||||||||||      ]  75%PHP Fatal error:  Uncaught exception 'Doctrine\ORM\ORMInvalidArgumentException' with message 'A new entity was found through the relationship 'Sylius\Component\Core\Model\ProductTranslation#translatable' that was not configured to cascade persist operations for entity: Hypebeast\Bundle\CoreBundle\Entity\Product@000000003d7399dd0000000049429139. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'Hypebeast\Bundle\CoreBundle\Entity\Product#__toString()' to get a clue.' in vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:91
Stack trace:
#0 vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(797): Doctrine\ORM\ORMInvalidArgumentException::newEntityFoundThroughRelationship(Array, Object(Hypebeast\Bundle\CoreBundle\Entity\Produ in vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php on line 91
```

After submitted fix, the error is gone.

May it be we are missing something? Or this cascade is really missing? Any idea @gonzalovilaseca?

### CODE REVIEW

**Comment by gonzalovilaseca** [comment]
The cascade is set on the Translatable mapping, as it's the owner of the relationship, you shouldn't need this on Translation to cascade persist.
Did you map ``Hypebeast\Bundle\CoreBundle\Entity\Product`` correctly as a Sylius resource?

**Comment by umpirsky** [comment]
@gonzalovilaseca Yes, here is my config:

```yml
sylius_product:
    driver: doctrine/orm
    classes:
        product:
            model: Umpirsky\Bundle\CoreBundle\Entity\Product
            controller: Umpirsky\Bundle\CoreBundle\Controller\ProductController
            repository: Umpirsky\Bundle\CoreBundle\Repository\ProductRepository
            form:
                default: Umpirsky\Bundle\CoreBundle\Form\Type\ProductType
            translation:
                model: Sylius\Component\Core\Model\ProductTranslation
                form:
                    default: Sylius\Bundle\CoreBundle\Form\Type\ProductTranslationType
```

Thanks.

**Comment by gonzalovilaseca** [comment]
Did you override getTranslationClass in your product model?

**Comment by umpirsky** [comment]
@gonzalovilaseca Nope. Thanks.

**Comment by gonzalovilaseca** [comment]
Can you remove ``model: Sylius\Component\Core\Model\ProductTranslation`` from your config and try again?
It would be ideal if you could pack your app in a vagrant box so I can have a deep look.

**Comment by umpirsky** [comment]
@gonzalovilaseca I will debug it more to see if I can figure it out. Thanks a lot! :+1:

**Pull request closed without merging**
