### PR TITLE
Random CS fixes

### PR DESCRIPTION
**Pull request by aRn0D**
| Q             | A
| ------------- | ---
| Bug fix?      | cs
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by aRn0D** [comment]
@pjedrzejewski you should add the label "CS fixes"

**Comment by pjedrzejewski** [comment]
Could you rebase? Thanks.

**Comment by aRn0D** [comment]
@pjedrzejewski done

**Comment by pjedrzejewski** [comment]
Thank you Arnaud! :+1:

**Comment by aRn0D** [comment]
:v:

**Pull request merged**
