### PR TITLE
[Admin][Taxon] Fix slug generation to work based on the parent field

### LINKED ISSUE #13749: [Admin][UI] Taxon slug generation broken
**Sylius version affected**: 1.10

**Description**  
Taxon slug field does not handle taxon parent field to generate slug.

**Steps to reproduce**  
You can try on Sylius demo : https://demo.sylius.com/admin/taxons/65190/edit

- Slug of `Jeans > Men` category is `jeans/men`
- Parent of `Men` category is `Category / Jean`
- But if you unlock slug field and change taxon name by `Test`
- Slug field is `test` instead of `jeans/test`

**Possible Solution**  
Remove `&& $('#sylius_taxon_parent').is(':visible')` condition on `sylius-taxon-slug.js`. 
The condition ` $('#sylius_taxon_parent').val() != ''` should be enough.

And update `TaxonSlugController` to find parent by `code` instead of `id`.

### PR DESCRIPTION
**Pull request by NoResponseMate**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.12 |
| Bug fix?        | yes                                                       |
| New feature?    | no                                 |
| BC breaks?      | no                                                       |
| Deprecations?   | no |
| Related tickets | fixes #13749, replaces #13889                      |
| License         | MIT                                                          |

### CODE REVIEW

**Review by jakubtobiasz — DISMISSED** [review]

**Review by TheMilek — APPROVED** [review]

**Review by jakubtobiasz — APPROVED** [review]

**Review by SzymonFilipek — APPROVED** [review]
Changes passed QA check

**Comment by jakubtobiasz** [comment]
Thank you, @NoResponseMate!

**Pull request merged**
