### PR TITLE
Feat: Add breadcrumb var in CRUD template for AdminBundle

### PR DESCRIPTION
**Pull request by toofff**
| Q               | A
| --------------- | -----
| Branch?         | master
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | no
| License         | MIT

### CODE REVIEW

**Comment by Zales0123** [comment]
Hi @toofff! I believe such a customization option is already introduced a level higher [in this file](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Index/_header.html.twig#L4). It, of course, is a little bit different - but the proposed solution seems as duplicated behaviour.

**Comment by toofff** [comment]
@Zales0123 I'm not thinking duplicating an existing solution.

Currently we can directly change the `header` and the `subheader` with a translation key that we want to put.
I just wanted to make the code homogeneous for the breadcrumb.

```
app_admin_page:
    resource: |
        alias: app.page
        section: admin
        path: /pages
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        grid: app_admin_page
        permission: true
        vars:
            all:
                breadcrumb: app.ui.page.breadcrumb
                header: app.ui.page.header
                subheader: app.ui.page.subheader
    type: sylius.resource
    prefix: admin
```

However for the `subheader` variable [we can define it with the `subheader` key](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Index/_headerTitle.html.twig#L3) or [change the template with `header_title` key](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AdminBundle/Resources/views/Crud/Index/_header.html.twig#L3).

**Comment by toofff** [comment]
@Zales0123 do I have to keep the branch up to date or do I just delete my pull request?

**Comment by Zales0123** [comment]
Hello, sorry for processing it long 🖖 Please, update to the master branch and I would like to see the opinion of other @Sylius/core-team members :)

**Comment by toofff** [comment]
@Zales0123 ;)

**Review by lchrusciel — APPROVED** [review]
A small improvement, but I would vote for adding it.

A small problem that I have, is that we don't know how to test it and ensure, that it is working in the future. Probably it is true for the rest of these dynamic fields.

**Comment by lchrusciel** [comment]
Thanks, @toofff! :tada:

**Comment by lchrusciel** [comment]
I was a long-lived PR, but lets put it to the master :) If I'm correct, we do not have any docs about this feature. May you propose something and contribute to docs?

**Comment by toofff** [comment]
@lchrusciel As soon as I have some time I will add this in the documentation

**Pull request merged**
