### PR TITLE
Update illdurand/hateoas dependency

### PR DESCRIPTION
**Pull request by pierre-H**
| Q               | A
| --------------- | -----
| Branch?         | master
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| License         | MIT

### CODE REVIEW

**Comment by jmontoyaa** [comment]
I have the same issue this is blocking an update of vichuploadbundle.
Any news about this?

**Comment by pamil** [comment]
For details let's move to Sylius/SyliusResourceBundle#108.

**Comment by alexsegura** [comment]
+1, I can't update `vich/uploader-bundle` above `~1.8`

**Comment by pierre-H** [comment]
Linked to #10928

**Comment by pamil** [comment]
Some work is being made in #11301.

**Pull request closed without merging**
