### PR TITLE
[User] Added missing unique indexes on customer.email and emailCanonical

### PR DESCRIPTION
**Pull request by peteward**
Import a million users to your database and you'll really need this index...

user.username and usernameCanonical seem to be nullable? so I haven't added any to this, although customer.email will be where db queries are mainly run against anyway.

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
@peteward Could you generate a database migration for that change? Thanks!

**Comment by peteward** [comment]
updated

**Comment by pjedrzejewski** [comment]
Thank you very much Peter! :+1:

**Comment by okwinza** [comment]
@awerffeli this will be fixed in #4009

_At least here i was faster than @pamil :D_

**Pull request merged**
