### PR TITLE
[PayumBundle] Make offline payum capture action to be public

### PR DESCRIPTION
**Pull request by aramalipoor**

### CODE REVIEW

**Comment by makasim** [comment]
What is the reason to have it public? FYI: The payum's action is not designed to be used outside of Gateway.

**Comment by aramalipoor** [comment]
Maybe I'm missing something, this is my `config.yml`:
```yml
payum:
    storages:
        Sylius\Component\Core\Model\Order: { doctrine: orm }
        Sylius\Component\Core\Model\Payment: { doctrine: orm }

    security:
        token_storage:
            Sylius\Bundle\PayumBundle\Model\PaymentSecurityToken: { doctrine: orm }

    dynamic_payments:
        config_storage:
            Sylius\Bundle\PayumBundle\Model\PaymentConfig: { doctrine: orm }

    payments:
        offline:
            offline:
                actions:
                    - sylius.payum.offline.action.capture_payment
```

I'm using sylius core in my project and with this configuration I get a "service not found" error for this action.

What do you think I'm missing?!

**Comment by makasim** [comment]
Yes, you are right. The gateways are created in runtime so the actions has to be public. 

@pjedrzejewski good to merge

**Comment by pjedrzejewski** [comment]
Thank you Aram and Maksim! :+1:

**Comment by aramalipoor** [comment]
:+1:  Thank you Makasim and Paweł ;)

**Pull request merged**
