### PR TITLE
Updated twig/intl-extra to allow v3

### PR DESCRIPTION
**Pull request by UlrichHP**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.12                   |
| Bug fix?        | no                                                     |
| New feature?    | no                                                       |
| BC breaks?      | no                                                       |
| Deprecations?   | no  |
| Related tickets | mentioned in #14628                       |
| License         | MIT                                                          |

### CODE REVIEW

**Comment by jakubtobiasz** [comment]
Hi @UlrichHP!
Thanks for your contribution 🎉 . Can you fix the build? You need to adjust the package's version also in subpackages.
CleanShot 2022-12-14 at 13 44 07@2x

**Comment by UlrichHP** [comment]
Hi @jakubtobiasz,

Sorry about that, i fixed it.

**Review by jakubtobiasz — APPROVED** [review]
Seems ok for me 👍🏼.

**Review by GSadee — APPROVED** [review]

**Review by coldic3 — APPROVED** [review]

**Review by NoResponseMate — APPROVED** [review]

**Comment by GSadee** [comment]
Thank you, Ulrich! :1st_place_medal:

**Pull request merged**
