### PR TITLE
[Behat] Restructure behat features

### PR DESCRIPTION
**Pull request by michalmarcinkowski**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

Moving features out of "shop" folder and renaming folders to singular `channels` -> `channel`

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
@michalmarcinkowski Build is failing because of missing ``ui_channels.yml`` file, should be ``ui_channel.yml``.

**Comment by michalmarcinkowski** [comment]
Fixed, waiting for build

**Comment by pjedrzejewski** [comment]
@michalmarcinkowski Requires rebasing.

**Comment by pjedrzejewski** [comment]
:+1:

**Pull request merged**
