### PR TITLE
[MailerBundle] CS fixes and missing specs

### PR DESCRIPTION
**Pull request by aRn0D**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | refactoring 
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | no
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
@aRn0D Array syntax again... :)

**Comment by aRn0D** [comment]
@pjedrzejewski done :'(

**Comment by aRn0D** [comment]
@pjedrzejewski green ;)

**Comment by pjedrzejewski** [comment]
Thank you Arnaud! :+1:

**Pull request merged**
