### PR TITLE
Use underscores for tag attribute names

### PR DESCRIPTION
**Pull request by mvar**
| Q               | A
| --------------- | ---
| Bug fix?        | no |
| New feature?    | no |
| BC breaks?      | yes |
| Related tickets | mentioned in #7838 |
| License         | MIT |

### CODE REVIEW

**Comment by lchrusciel** [comment]
Please, add also a note in UPGRADE.md

**Comment by mvar** [comment]
Updated README.md. Added info to the main block as it effect 3 or 4 bundles.

**Comment by mvar** [comment]
@lchrusciel it's OK to use dashes in XML (and looks more XML'ish). Then you use dashes you get both versions in the compiler pass. `form-type` and `form_type` will be set as attribute with the same value.

**Comment by lchrusciel** [comment]
What kind of sorcery is that :D I'm not sure about it either. Simple example: newcomer would like to check where this definition is parsed and will look for `form-type` but he will not find anything, cuz compiler pass operates on `form_type`. Anyway, I'm ok with that if others will agree. /cc @pamil @Zales0123 @Arminek

**Comment by pamil** [comment]
Thanks @mvar! 🎉

**Comment by pjedrzejewski** [comment]
👍 👍 👍

**Pull request merged**
