### PR TITLE
[Maintenance] Migrate GatewayConfig config column type to json

### PR DESCRIPTION
**Pull request by lchrusciel**
| Q               | A
| --------------- | -----
| Branch?         | 1.10
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes red build
| License         | MIT

Consequences of https://github.com/Payum/Payum/pull/924, released at: https://github.com/Payum/Payum/releases/tag/1.7.0

### CODE REVIEW

**Comment by vvasiloi** [comment]
@lchrusciel https://github.com/Sylius/Sylius/pull/13214 😄

**Comment by lchrusciel** [comment]
Yup, we will have to do the same. But in this PR I just want to unblock us from red build

**Comment by vvasiloi** [comment]
The same changes are in the other PR, which is ready to be merged.

**Comment by lchrusciel** [comment]
Closing in favour of #13214

**Pull request closed without merging**
