### PR TITLE
[ADR][API] Update ADR for providing locales after changing the approach

### PR DESCRIPTION
**Pull request by GSadee**
| Q               | A
| --------------- | -----
| Branch?         | 1.11
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | https://github.com/Sylius/Sylius/pull/12766 and https://github.com/Sylius/Sylius/pull/13333
| License         | MIT

### CODE REVIEW

**Review by Rafikooo — APPROVED** [review]

**Comment by Ferror** [comment]
I don't think we should update the ADRs when we change our decision, especially after a year. In that case, I think we should create another ADR with relation to the first one that explains why the previous approach appeared to be wrong.

The decision was made, people died, this cannot be undone :)

**Comment by GSadee** [comment]
> I don't think we should update the ADRs when we change our decision, especially after a year. In that case, I think we should create another ADR with relation to the first one that explains why the previous approach appeared to be wrong.
> 
> The decision was made, people died, this cannot be undone :)

I wonder about doing it in this way, but I wanted to simplify our ADRs, especially that the changed ADR was in `proposed` state. However, I agree with your arguments and I've added the new ADR with reference to the old one.

**Comment by lchrusciel** [comment]
as a contr-argument for changing ADRs with time - we have git in place. Therefore, we could replace them and base our current decisions only on existing ADRs at the moment. Of course, there is one more case - when we are transitioning from one approach to another, while two ADRs may exist: legacy and new one

**Review by AdamKasp — APPROVED** [review]

**Comment by AdamKasp** [comment]
Thank you, Grzegorz! :1st_place_medal:

**Pull request merged**
