### PR TITLE
Allow nullable product variants

### LINKED ISSUE #8993: Product variant resolver must allow nullable result
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.4

```
Given the content management team adds a configurable product
And they don't add any variants to it
When I go to the product list with this product
Then I should see 500 error with `Sylius\\Bundle\\CoreBundle\\Templating\\Helper\\VariantResolverHelper::resolveVariant() must implement interface Sylius\\Component\\Product\\Model\\ProductVariantInterface, null returned at /home/anqans/www/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Templating/Helper/VariantResolverHelper.php:43` message
```

### PR DESCRIPTION
**Pull request by bitbager**
| Q               | A
| --------------- | -----
| Branch?         | 1.0
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #8993
| License         | MIT

### CODE REVIEW

**Comment by pamil** [comment]
Can you add an entry to `UPGRADE-1.0.md` about this return typehint declaration change?

**Comment by pamil** [comment]
Rebased & UPGRADE.md entry added in #9143.

**Comment by bitbager** [comment]
Ough, thank you for the effort of upgrading the UPGRADE.md file. I don't know if I'd be able to do it 😄

**Comment by pamil** [comment]
It's my pleasure to help! :D

**Pull request closed without merging**
