### PR TITLE
Optimise Travis builds

### PR DESCRIPTION
**Pull request by pamil**
| Q               | A
| --------------- | -----
| Branch?         | 1.0
| Bug fix?        | kinda
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | -
| License         | MIT

### CODE REVIEW

**Comment by CoderMaggie** [comment]
@pamil can we also turn off this annoying, not working links checking for docs builds? 😄

**Comment by pamil** [comment]
@CoderMaggie here you are: #8855

**Comment by GSadee** [comment]
Thanks Kamil 🐗

**Comment by stefandoorn** [comment]
Not sure all went well:

```
fatal: ambiguous argument 'origin/1.0': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
grep: ^CHANGELOG-[\d\.]+.md: No such file or directory
grep: ^UPGRADE-[\d\.]+.md: No such file or directory
/home/travis/build/Sylius/Sylius/etc/travis/suites/application/is_suitable.sh: line 9: [: -eq: unary operator expected
```

**Comment by pamil** [comment]
Ouch, hate that Travis stuff sometime

**Pull request merged**
