### PR TITLE
[CustomerGroup] CRUD

### LINKED ISSUE #6307: [Customer] Rename Group to CustomerGroup
See #5384 for further reference.

### PR DESCRIPTION
**Pull request by GSadee**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | yes
| Related tickets | Fixes #6307
| License         | MIT

### CODE REVIEW

**Comment by pamil** [comment]
Missing "Fixes #6307" in "Related tickets" section :tada:

**Comment by pjedrzejewski** [comment]
@GSadee Sorry, but we need a rebase after validation split. :(

**Comment by pjedrzejewski** [comment]
Thank you Grzesiu! :)

**Comment by tchapi** [comment]
hi,
What is the rationale for only allowing a single group linked to a customer ?

**Comment by pjedrzejewski** [comment]
@tchapi Having a customer in multiple groups adds complexity for pricing, promotions, etc. So by having a simpler version in core, we can actually provide more functionality.

**Pull request merged**
