### PR TITLE
Don't load class cache and bootstrap file on php7. Remove app/autoloa…

### PR DESCRIPTION
**Pull request by dannyvw**
…d.php

| Q               | A
| --------------- | ---
| Bug fix?        | no |
| New feature?    | no |
| BC breaks?      | no |
| Related tickets |  |
| License         | MIT |

Improve autoloading for php7, see also symfony-standard.

### CODE REVIEW

**Comment by dannyvw** [comment]
@pamil Done

**Comment by pamil** [comment]
Thanks @dannyvw! 🎉

**Comment by pjedrzejewski** [comment]
👍 👍 👍

**Comment by pamil** [comment]
Btw. we should replicate it in Sylius-Standard and PluginSkeleton.

**Comment by pjedrzejewski** [comment]
@pamil Good point, opened issues on appropriate repos.

**Pull request merged**
