### PR TITLE
[Product] Removed 'originalPrice' field from ProductVariant

### PR DESCRIPTION
**Pull request by NeverResponse**
| Q               | A
| --------------- | ---
| Bug fix?        | no |
| New feature?    | no |
| BC breaks?      | yes |
| Related tickets | - |
| License         | MIT |

### CODE REVIEW

**Comment by michalmarcinkowski** [comment]
👍

**Comment by tchapi** [comment]
and ... there goes another useful feature that was used by a lot of us ... + another BC break in the alpha.

@pjedrzejewski I remember a time when you were supposed to stabilize the release and avoid BC breaks — now we have like 10 BC breaks _per day_, what is the rationale ?

**Comment by pjedrzejewski** [comment]
@tchapi The BC breaks we are doing right now are not "just for fun". Based on the feedback from alpha, we are using **last days of development** to do the "worst" bc breaks before the BETA release. This functionality will most likely be back just in time before the tag. 

We have detected a serious limitation with our current implementation of exchange rates handling and we need to rework that - thus removing this small extra feature to make space for the appropriate development. After the tag, every BC break that happens during the BETA will be done only when really necessary and well documented - you can trust me on that. I understand the frustration - it is not cool, but needs to be done.

**Comment by inssein** [comment]
@pjedrzejewski understandable, but I don't follow the reasoning for this change, could I get a better explanation? Perhaps I can put some of my time into bringing this back properly as I have been using this feature.

**Pull request merged**
