### PR TITLE
[Behat] Generic login user type

### PR DESCRIPTION
**Pull request by majidgolshadi**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Related tickets | -
| License         | MIT

### CODE REVIEW

**Comment by majidgolshadi** [comment]
@pamil 
All Sylius tests passed but Travic return `The command "etc/travis/run-suite script "${SYLIUS_SUITE}"" exited with 255.` error. WDYT?

**Comment by michalmarcinkowski** [comment]
@majidgolshadi the build fails because of:
```
PHP Fatal error:  Declaration of Sylius\Behat\Service\SecurityService::performActionAs(Sylius\Component\User\Model\UserInterface $user, callable $action) must be compatible with Sylius\Behat\Service\SecurityServiceInterface::performActionAs(Sylius\Component\Core\Model\UserInterface $user, callable $action) in /home/travis/build/Sylius/Sylius/src/Sylius/Behat/Service/SecurityService.php on line 24
```

You should update this interface also.

**Comment by aramalipoor** [comment]
:+1: Ping @michalmarcinkowski ;)

**Comment by michalmarcinkowski** [comment]
Thank you Majid!

**Pull request merged**
