### PR TITLE
[Taxation] - reset pointer for orderUnits collection before each call

### PR DESCRIPTION
**Pull request by nakashu**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #4202
| License       | MIT

### CODE REVIEW

**Comment by nakashu** [comment]
all well now. I must have been really tired yesterday

**Comment by nakashu** [comment]
bump

**Comment by pjedrzejewski** [comment]
@michalmarcinkowski WDYT?

**Comment by michalmarcinkowski** [comment]
This is a proper fix. Thanks @nakashu! :+1:

**Pull request merged**
