### PR TITLE
Fix SyliusFlowBundle readme bug with completing step

### PR DESCRIPTION
**Pull request by pjedrzejewski**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #3587 
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
Ping @umpirsky @michalmarcinkowski. :)

**Comment by michalmarcinkowski** [comment]
@pjedrzejewski I know that the builds are fast now, but you don't have to ping us an hour after the PR has been opened :smile: Thanks for the fix! :+1:

**Comment by pjedrzejewski** [comment]
@michalmarcinkowski Everyone is always pinging me, so I wanted to feel different for this one time. :D

**Comment by michalmarcinkowski** [comment]
No problem, ping me whenever you feel it's needed :smile:

**Comment by umpirsky** [comment]
I like to be pinged! :)

@pjedrzejewski @michalmarcinkowski Did you see https://github.com/facebook/mention-bot?

**Pull request merged**
