### PR TITLE
[LocaleBundle] Add traditional calendar systems support and related twig functions

### PR DESCRIPTION
**Pull request by aramalipoor**
Q  | A
------------- | -------------
Bug fix?  | no
New feature?  | yes
BC breaks? | no
Deprecations? | no
Fixed tickets | -
License | MIT
Doc PR | -

This is a proposal to add support for traditional calendar systems into Sylius. I'm so new to Symfony2 so please forgive me if you see some bad practices ;)

Your comments are really appreciated ;)

Here is a list of twig filters/functions I've added:
* `sylius_localized_date([date], [format], [timezone])` Twig date filter with calendar-aware conversion, based on current locale.
* `sylius_language([code])` Returns localized language name of current (or provided) locale code.
* `sylius_rtl()` Returns true if current locale code is of an RTL-type language. e.g  If current locale is RTL so that we can load RTL stylesheets and whatnot.
* `sylius_direction()` Returns current locale language direction. (`rtl`, `ltr`)
* `sylius_calendar()` Returns current locale calendar system. (`gregorian`, `persian`, `hebrew`, `islamic`, etc)

* I've created a TypeExtension for Symfony's `date` FormType to support calendar-aware dates.

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
@aramalipoor Sounds really cool, but it is hard to review right now, could you rebase it? Thank you! Cool stuff! :+1:

**Comment by aramalipoor** [comment]
@pjedrzejewski Thanks Pawel, it's my pleasure to bring any help. I'll do a rebase ASAP ;)

**Comment by aramalipoor** [comment]
@pjedrzejewski Now you can take a look. For now we don't have localized `datepicker`s, IMO that can be another PR.

**Comment by aramalipoor** [comment]
@pjedrzejewski @aRn0D @stloyd ping!

**Comment by aramalipoor** [comment]
@pjedrzejewski pong! :D

**Comment by aramalipoor** [comment]
@aRn0D @pjedrzejewski Review please :D

**Pull request closed without merging**
