### PR TITLE
[ResourceBundle] The date type has been improved

### PR DESCRIPTION
**Pull request by aRn0D**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by aRn0D** [comment]
@pjedrzejewski pong :) what do we do?

**Comment by stloyd** [comment]
@pjedrzejewski Feedback?

**Comment by aRn0D** [comment]
ping @pjedrzejewski

**Comment by aRn0D** [comment]
@pjedrzejewski  pong

**Comment by aRn0D** [comment]
@pjedrzejewski ping

**Comment by aRn0D** [comment]
@pjedrzejewski rebase :)

**Comment by aRn0D** [comment]
@pjedrzejewski I need it for a personal projet, do you want something like that?

**Comment by saidul** [comment]
@pjedrzejewski  ping

**Comment by aRn0D** [comment]
@pjedrzejewski ping

**Comment by aRn0D** [comment]
@pjedrzejewski pong!

**Comment by aRn0D** [comment]
ping @pjedrzejewski

**Comment by pjedrzejewski** [comment]
Thanks Arnaud! Sorry it took so long. :dancer:

**Comment by aRn0D** [comment]
:v: no problem!

**Pull request merged**
