### PR TITLE
[ProductBundle] Add validation for product meta keywords & description

### PR DESCRIPTION
**Pull request by DieterHolvoet**
| Q               | A
| --------------- | -----
| Branch?         | 1.12
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| License         | MIT

### CODE REVIEW

**Comment by Rafikooo** [comment]
Hello Dieter Holvoet, thank you for your contribution, and sorry for the long response time. If you still want to contribute please change the base branch to Sylius 1.11 as Sylius 1.7 is no longer supported. We need to provide a behat test for this case, if you fill up to do it, let us know, if not, we will finish it in the near future. Wish you all the best 🚀

**Review by SzymonFilipek — APPROVED** [review]
Changes passed QA check

**Review by GSadee — APPROVED** [review]

**Comment by GSadee** [comment]
Thank you, Dieter! :tada:

**Pull request merged**
