### PR TITLE
Move punctuation inside translations

### LINKED ISSUE #6513: Question and exclamation marks in translations for spanish language
Some translations don't have the question or exclamation marks included and those are placed directly in the template. This is the case for `sylius.ui.need_assistance`, `sylius.ui.call_us` or `sylius.ui.forgot_password` for example, but there are probably more.

``` twig
{{ 'sylius.ui.need_assistance'|trans }}? {{ 'sylius.ui.call_us'|trans }}!
```

``` yaml
sylius:
    ui:
        need_assistance: 'Need assistance'
        call_us: 'Call us'
        forgot_password: 'Forgot password'
```

This is OK for english but not for spanish where we use both opening and closing marks. This is how it should look like:

``` twig
{{ 'sylius.ui.need_assistance'|trans }} {{ 'sylius.ui.call_us'|trans }}
```

``` yaml
sylius:
    ui:
        need_assistance: 'Need assistance?'
        call_us: 'Call us!'
        forgot_password: 'Forgot password?'
```

And for spanish translations would be:

``` yaml
sylius:
    ui:
        need_assistance: '¿Necesitas ayuda?'
        call_us: '¡Llámanos!'
        forgot_password: '¿Contraseña olvidada?'
```

May be there are more scenarios like this one.

### PR DESCRIPTION
**Pull request by patrick-mcdougle**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | yes (technically) |
| Related tickets | fixes #6513 |
| License | MIT |

I only modified translation files in which I knew the language sufficiently well. Translators for this software will have to do whatever is required of the other languages to denote questions and exclamations.

I used the following case insensitive regex to search for the occurrences:

```
\|trans.*?\}\}.*?(\?|\!)
```

I also added quotes to all the strings in the english file. Figured I'd enforce consistency while I was in there.

NOTE: There was a tricky place in the code that I didn't replace which was where the translation was in the database. I wasn't sure what to do so I left it. REF: https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ShopBundle/Resources/views/Homepage/Menu/_security.html.twig#L3

Perhaps these need to be translation blocks instead?

### CODE REVIEW

**Comment by patrick-mcdougle** [comment]
@pjedrzejewski

**Comment by pjedrzejewski** [comment]
Spanish translations should not be modified here as they will not be synced.

/cc @pamil WDYT?

**Comment by pamil** [comment]
They need to be changed on CrowdIn.

**Comment by patrick-mcdougle** [comment]
Updated.

**Comment by michalmarcinkowski** [comment]
@patrick-mcdougle please rebase

**Comment by patrick-mcdougle** [comment]
@michalmarcinkowski merge quick before someone adds another translation! Also, I have the maintainer box checked, so you can merge master into this branch to resolve the merge conflicts. (I only work on open source on the weekends, and I know that that can slow things down).

**Comment by michalmarcinkowski** [comment]
Thanks Patrick! 👍

**Pull request merged**
