### PR TITLE
2.7 Defintion deprecation fix

### PR DESCRIPTION
**Pull request by rvanlaak**
` ->setFactory('sylius.controller.configuration_factory::createConfiguration') ` would also work.

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
We will merge this when we bump to 2.7. :)

**Comment by michalmarcinkowski** [comment]
Thanks @rvanlaak! Could you rebase?

**Comment by rvanlaak** [comment]
It does not seem to conflict against `master`, or do you want me to rebase against another branch?

**Comment by michalmarcinkowski** [comment]
@rvanlaak, but a lot has changed since this PR. E.g. the builds have been heavily reworked that's why they are red now. Please rebase with master and let's see the green build here :) Thanks!

**Comment by rvanlaak** [comment]
Ok, give me a sec :+1:  a "restart checks" button would be the thing you'd like to have right? ;)

**Comment by rvanlaak** [comment]
I've fixed the typo and rebased this one against master (see commit parent), but travis still throws errors @michalmarcinkowski

**Comment by pjedrzejewski** [comment]
@rvanlaak I think you shouldn't use array keys, just regular callable ``array(service, method)``.

**Comment by rvanlaak** [comment]
@pjedrzejewski done :+1:

**Comment by pjedrzejewski** [comment]
Thanks Richard! :+1:

**Pull request merged**
