### PR TITLE
[WIP] Attribute value translation

### PR DESCRIPTION
**Pull request by xantrix**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | mentioned in #4341
| License         | MIT
| Doc PR          | -

### CODE REVIEW

**Comment by steffenbrem** [comment]
I think extending `AbstractTranslatable` is deprecated and you should now use the `TranslatableTrait` instead (see https://github.com/Sylius/Sylius/pull/4260). This PR was merged very recently.

**Comment by xantrix** [comment]
@steffenbrem Thanks for pointing that out :+1:

**Comment by peteward** [comment]
Good work on the idea of this feature :+1: 

It could make performance interesting in some cases, but it's important.

**Comment by pjedrzejewski** [comment]
Hey @xantrix! Sorry for lack of feedback, why closing? This is something really interesting, although not sure how soon we can include it.

**Comment by xantrix** [comment]
Sorry @pjedrzejewski, I forgot to report here the new PR #4512 (with correct history). My fault! looking forward to feedbacks in the new one!
Thanks

**Pull request closed without merging**
