### PR TITLE
[Composer][Locale] Add SonataIntlBundle and localized date in templates

### PR DESCRIPTION
**Pull request by Niiko**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Related tickets | mentioned in #3232
| License         | MIT

As suggested by @pjedrzejewski, i add sonataIntlBundle to localized dates.

A big warning on format date, that is no more from php format but from [ICU format](http://userguide.icu-project.org/formatparse/datetime)

### CODE REVIEW

**Comment by Niiko** [comment]
Ok, i have a problem on one test, it works locally and i think it's a date format configuration problem on server.

Could i have the log of my test ?
features/product/viewing_products/viewing_product_attributes.feature:43

I expect that value "Dec 12, 2015, 12:34:00" but that's not found

**Comment by pamil** [comment]
You can find links to logs after clicking on `$ etc/travis/run-suite after_failure "${SYLIUS_SUITE}"` in Travis log.

```
$ etc/travis/run-suite after_failure "${SYLIUS_SUITE}"
Uploading logs: Sylius
> vendor/lakion/mink-debug-extension/travis/tools/upload-textfiles "etc/build/*.log"
Uploading logs...
etc/build/behat-20160629104930.log - http://termbin.com/y4mw
etc/build/behat-20160629105103.log - http://termbin.com/gjzn
etc/build/selenium.log - 
etc/build/webserver.log - http://termbin.com/x9tq
```

**Comment by Niiko** [comment]
Thanks @pamil

**Comment by pjedrzejewski** [comment]
@pamil How is travis not failing without SonataIntlBundle in Core's composer.json?

**Comment by pamil** [comment]
@pjedrzejewski It looks like neither `phpspec` or `phpunit` CoreBundle's tests does not involve `Kernel` class.

**Comment by pjedrzejewski** [comment]
@Niiko Could you add this bundle to Core's kernel? Thanks!

**Comment by Niiko** [comment]
Done @pjedrzejewski

**Comment by pjedrzejewski** [comment]
Thanks Nicolas! Nice work. 👍

**Pull request merged**
