### PR TITLE
[Core][Channel] Make hard coded channel resolver class a configurable parameter

### PR DESCRIPTION
**Pull request by cdaguerre**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by cdaguerre** [comment]
@pjedrzejewski Hi Pawel, this is actually a real easy pick, no idea why the second test suite failed for PHP5.5 with the following error:
`Warning: constant(): Couldn't find constant Monolog\Logger::DEBUG in [...]`
I guess restarting the build would probably work but don't think it's even necessary...

**Comment by michalmarcinkowski** [comment]
@cdaguerre restarted the build, probably some travis issue :wink:

**Comment by cdaguerre** [comment]
:+1: thanks @michalmarcinkowski

**Comment by michalmarcinkowski** [comment]
Thanks Christian! :+1:

**Comment by pjedrzejewski** [comment]
:+1:

**Pull request merged**
