### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by jakubtobiasz**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.12
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| License         | MIT

### CODE REVIEW

**Review by TheMilek — DISMISSED** [review]

**Review by Zales0123 — DISMISSED** [review]

**Review by Rafikooo — DISMISSED** [review]

**Comment by Zales0123** [comment]
@jakubtobiasz one scenario i one build configuration is constantly failing and, surprisingly, multiple reruns did not help :/ can you take a look at it? 🖖

**Comment by jakubtobiasz** [comment]
@Zales0123 what the ... :|! how :|? Do you need it today?

**Comment by Zales0123** [comment]
> @Zales0123 what the ... :|! how :|? Do you need it today?

don't worry, it can wait 😄

**Review by GSadee — APPROVED** [review]

**Comment by GSadee** [comment]
Thank you, Jacob! :tada:

**Pull request merged**
