### PR TITLE
Decrement length constraint on postcode

### PR DESCRIPTION
**Pull request by loevgaard**
In Oslo, Norway there is a postal code `1`. See https://worldpostalcode.com/norway/hordaland/oslo

| Q               | A
| --------------- | -----
| Branch?         | All
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| License         | MIT

### CODE REVIEW

**Comment by CoderMaggie** [comment]
After a quick research, although there is this postal code you referred, but it is written as `0001` not just `1`
ref: 
1. http://www.fedex.com/be/shippingguide/postalcodeformat.html 
2. http://www.dhl.com.tw/content/dam/downloads/tw/express/forms/postcode_formats.pdf

**Comment by loevgaard** [comment]
Yes, that is correct, but does users adhere for standards? No :) The same in Denmark. We also have 4 digit postal codes, but there postal codes like 0983. When people order, they write 983 obviously.

**Comment by lchrusciel** [comment]
Thanks, Joachim! :1st_place_medal:

**Comment by loevgaard** [comment]
Great, thank you!

**Pull request merged**
