### PR TITLE
Remove flashHelper dependency from domainManager

### PR DESCRIPTION
**Pull request by winzou**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | yes, DomainManager now throws DomainException
| Deprecations? | no
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

Remove the ugly flashHelper dependency from DomainManager. Make it return a resource everytime (instead of a mix resource/event).
If there are flashes to define, it must be done from the controller.
Solve the cases where multiple flashes were defined (UserController for example).
Improve usability of ResourceBundle standalone.

### CODE REVIEW

**Comment by amenophis** [comment]
:+1:

**Comment by winzou** [comment]
ping @pjedrzejewski ?

**Comment by winzou** [comment]
ping @pjedrzejewski PR waiting for more than a month

**Comment by pjedrzejewski** [comment]
This is fixed in #2255. Closing this as it will only complicate my rebase. :P

**Comment by pjedrzejewski** [comment]
Thanks for the idea Alexandre!

**Pull request closed without merging**
