### PR TITLE
Added controller configuration for OrderItemUnit

### PR DESCRIPTION
**Pull request by sjonkeesse**

### CODE REVIEW

**Comment by steffenbrem** [comment]
This is needed because you want to expose order items units for a partial shipments.

**Comment by peteward** [comment]
:+1: just needed this myself...

**Comment by pjedrzejewski** [comment]
Nice, thank you Robin! :+1:

**Comment by pjedrzejewski** [comment]
@sjonkeesse Congrats on your first PR! (according to some Twitter bot haha)

**Comment by sjonkeesse** [comment]
Haha thats correct. I'm very proud!

**Pull request merged**
