### PR TITLE
[LocaleBundle] Fixed sylius_locale() function

### PR DESCRIPTION
**Pull request by cdaguerre**

### CODE REVIEW

**Comment by cdaguerre** [comment]
@pjedrzejewski It seems the build failed because of composer dependency resolution for PHP 5.3 but don't think this is related to this PR. Any clues?

**Comment by pamil** [comment]
@cdaguerre rebase your PR branch with latest Sylius version, we don't use neither 5.3 nor 5.4 since v0.16

**Comment by cdaguerre** [comment]
@pjedrzejewski @pamil Rebased, build green. Thanks!

**Comment by pjedrzejewski** [comment]
Thanks Christian! :+1:

**Pull request merged**
