### PR TITLE
Fix service definition at custom-payment-gateway

### LINKED ISSUE #13915: [Docs][Cookbook][Payments] In "How to integrate a Payment Gateway as a Plugin" tutorial yaml example for plugin action service registration is missing a parameter
**Sylius docs version**: 1.x / latest

**Description**

https://docs.sylius.com/en/1.11/cookbook/payments/custom-payment-gateway.html

```yaml
//src/Resources/config/services.yaml
Acme\SyliusExamplePlugin\Payum\Action\CaptureAction:
    arguments:
        - '@sylius.http_client'
    tags:
        - { name: payum.action, factory: sylius_payment, alias: payum.action.capture }
```

It should be declared as `public` otherwise it won't work. I will submit PR later

### PR DESCRIPTION
**Pull request by diimpp**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.11                 |
| Bug fix?        | yes                                                       |
| New feature?    | no                                                       |
| BC breaks?      | no                                                       |
| Deprecations?   | no  |
| Related tickets | fixes #13915                       |
| License         | MIT                                                          |

### CODE REVIEW

**Comment by jakubtobiasz** [comment]
Hi @diimpp!
Why do you think this service should be marked as public?

**Comment by diimpp** [comment]
Hello @jakubtobiasz,

I cannot tell you exact reason why custom payum actions should be registered as public, but that's the way with SyliusPayumBundle custom actions https://github.com/Sylius/Sylius/blob/23dc8d6915b2540f88ffceb7b9ea9a3214543837/src/Sylius/Bundle/PayumBundle/Resources/config/services/action.xml#L8
 as well in my personal experience I was forced to do the same for my custom actions.

There are two service definitions in this doc, xml and yaml. Xml contains correct `public` definition, while yaml misses it. (See related ticket)

**Review by jakubtobiasz — APPROVED** [review]

**Comment by diimpp** [comment]
@jakubtobiasz hi, what can be done to merge it early? Do you need second review for core team?

**Comment by jakubtobiasz** [comment]
@diimpp yep, more votes needed, I pinged the team.

**Review by Zales0123 — APPROVED** [review]
🖖

**Comment by Zales0123** [comment]
Thank you, Dmitri! :tada:

**Pull request merged**
