### PR TITLE
[WIP] Support for Symfony 3

### LINKED ISSUE #3018: YamlPersister Yaml::parse compatible with Symfony 3.0
To keep compatibility with 3.0, in your class YamlPersister:

line 28 when your parse file, use

$data = Yaml::parse(file_get_contents($his->file));

instead of:

$data = Yaml::parse($this->file);

### LINKED ISSUE #3564: [RFC] Symfony 3.0 Compatibility
Do you plan to make [sylius/resource-bundle](https://packagist.org/packages/sylius/resource-bundle) symfony 3.0 compatible?

What about these changes in composer 

```
{
    //
    "require": {
        //
        "symfony/framework-bundle": "~2.3|3.0",
        //
    }
}

```

According to the good example in [Symfony 3.0 support in FOSUserBundle](https://github.com/1ed/FOSUserBundle/blob/symfony-3-support/composer.json)

### LINKED ISSUE #5590: [ResourceBundle] ResourceFormFactory is not compatible with Symfony 2.8+
I don't know if this can be considered a bug, a feature request or neither of the two, but let me explain the problem first: I'm using the `ResourceBundle` with Symfony 2.8. From that version of Symfony, how a form is declared (and istantiated) was changed. Instead of using an alias name for each form type, the FCQN of the type class is used ([#15079](https://github.com/symfony/symfony/pull/15079)). If a FCQN is used as the form type in the resource config, the default `ResourceFormFactory` tries to instantiate the form type by doing a simple `new $className()`, and then pass the instance to the underlying form factory. This causes two problems: the first is a deprecation message triggered by the `createNamedBuilder` method that doesn't accept anymore an instance of the form type, and the second is that not using an alias there is no way to have a form that takes arguments in the constructor (e.g. injected services). My suggestion is to remove the check for the FCQN in the Sylius form factory, and always let the underyling Symfony form factory to instantiate the form by using the specified type, whatsever it is.

### PR DESCRIPTION
**Pull request by pamil**
| Q               | A
| --------------- | ---
| Bug fix?        | no |
| New feature?    | no |
| BC breaks?      | yes |
| Related tickets | closes #6269, closes #5590, closes #3571, closes #3564, closes #3018 |
| License         | MIT |

### CODE REVIEW

**Comment by rvanlaak** [comment]
@pamil great! Will this be a "big bang" merge PR? What about first making the app bootable and tests runnable with this PR, and make all bundles / components compatible afterwards? I'd love to help with the `PromotionBundle` if you'd like.

**Comment by rvanlaak** [comment]
I'd might be able to help you by adding commits to your `pamil/symfony3` branch?

**Comment by rvanlaak** [comment]
If I can push commits to `pamil:symfony3` then that would allow me to help you ;) Or maybe it would work if I send PRs for your branch?

**Comment by pamil** [comment]
@rvanlaak I'm open for PRs incoming to my fork :)

**Comment by liverbool** [comment]
😱 Please taged Sylius to some version before merge this PR.

💝  Cheer!

**Comment by pamil** [comment]
Massive amount of jobs are created on Travis, closing temporarily.

**Comment by bigfoot90** [comment]
Sylius stable version `1.0.0` will be fylly compatible with Symfony 3?

**Comment by pamil** [comment]
@bigfoot90 we aim for Beta release to be compatibile :tada:

**Comment by pamil** [comment]
For all interested in this PR - it's actually happening in #6896.

**Pull request closed without merging**
