### PR TITLE
[ContentBundle] Fix cascade validation of collection form (issue #2895)

### PR DESCRIPTION
**Pull request by psyray**
Hi,

Fix for this issue https://github.com/Sylius/Sylius/issues/2895

Tested and approved ;)

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
@psyray Thank you for the patch Raynald! Could you please have a look at the failing build? Thanks!

**Comment by psyray** [comment]
Validation complains about the id that I removed from the form generation on this line
https://github.com/Sylius/Sylius/pull/3172/files#diff-db52331bf73c6ccbca0722ad103e1738L33

The purpose of this remove was this error
selection_072

That occurs when a user update an existing static content, click the add route button, and save without filling the route fields.
Like this
selection_073

I remove the id field from the form generation and validation works fine
selection_074

But while doing some tests, I've seen that the embedded route form need more validation, I explain :
- While you create a static content, the parent must be filled (don't know why but the embedded form does not use the read-only field like in the classic route form)
selection_075

- While you create a static content and specifying a route, the dropdown list with the static content is displayed. This is not good because the static content linked to this route must be the current one and not another one, which cause conflict while saving form

So we need to decide, 
- Keeping the embedded form ?
- Exclusively set route in the route section ?
- Polish route validation in the static content form ?

It's up to you @pjedrzejewski ;)

**Comment by pjedrzejewski** [comment]
@psyray I'd go with the first option and remove the embedded form. At least we will make it work again and then we will try to come up with something more user friendly. Sounds like a plan?

**Comment by psyray** [comment]
Done.
Embedded form removed
selection_077

I took the opportunity to **correct some bugs** and **add some more informations to the user** to make it more friendly and prevent mistakes.
I don't create a PR for each, that's good for you ?

**Corrected bugs:**
- Prevent static content element to display in frontend home page if route is not set (should fix #1708 and don't break demo website anymore with exception *"None of the chained routers were able to generate route: Route 'Route aware content ...."*)
- Display title in form content choice instead of ugly id (menu and route)
selection_078

**Informations to user:**
- Display routes attached to a page in Pages list
selection_076

**Question about content choice list !**
Do you know how to sort the content choice list ?
I don't know how to do with ResourceBundle (as choice list is generated by it)
Should I use a classic 'query_builder' parameter with anonymous function or is there an easier way ?
Maybe @aRn0D could help ?

Enjoy ;)

**Comment by psyray** [comment]
up !

**Comment by pjedrzejewski** [comment]
Thank you Raynald! :+1: Great work. Could you drop me an e-mail to pawel@sylius.org. I wanted to discuss something real quick, thanks!

**Comment by psyray** [comment]
email dropped yesterday, did you receive it ?

**Comment by pjedrzejewski** [comment]
@psyray Yes, I will get back to you soon. :) Thank you!

**Pull request merged**
