### PR TITLE
[CurrencyBundle] Form registration, missing specs and CS Fixes.

### PR DESCRIPTION
**Pull request by aRn0D**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | refactoring 
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | no
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by aRn0D** [comment]
@pjedrzejewski I don't know why the build has failed ...

**Comment by aRn0D** [comment]
ping @pjedrzejewski @michalmarcinkowski

**Comment by aRn0D** [comment]
@pjedrzejewski green !

**Comment by michalmarcinkowski** [comment]
:+1:

**Comment by pjedrzejewski** [comment]
Thank you Arnaud! :+1:

**Pull request merged**
