### PR TITLE
[WIP][SHIPPING] fixed methods' positions in the resolver

### PR DESCRIPTION
**Pull request by EmilMassey**
| Q               | A
| --------------- | -----
| Branch?         | 1.6
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | -
| License         | MIT

### CODE REVIEW

**Comment by lchrusciel** [comment]
Hey Emil,

thanks a lot for the contribution! Would you like to give a try to our behat and write acceptance tests for this change? Also, I'm considering if the same change should not be applied to `DefaultShippingMethodResolver`

**Comment by EmilMassey** [comment]
Hi Łukasz,

I've never dealt with behat, but I will try. I'm marking this PR as WIP and will write acceptance tests asap. 

I don't know about `DefaultShippingMethodResolver`. Does the position matter in this case?

**Comment by Zales0123** [comment]
`DefaultShippingMethodResolver` is a very simple and default implementation, returning "the first shipping method available for channel" - I wonder does it matter if "the first" means "first by position" or "first by id" 🤔 💃 
👍 for Behat tests, I hope you'll enjoy them ;)

**Comment by EmilMassey** [comment]
I think that for me as a shop user it doesn't really matter. I'm choosing delivery method in the checkout anyway.

**Comment by lchrusciel** [comment]
You can check `features/checkout/shipping_order` for inspiration ;)

**Comment by dbalabka** [comment]
@lchrusciel I guess it should not be stale

**Comment by dbalabka** [comment]
@lchrusciel please make not stale.

This PR should include also changes in the following line:
https://github.com/Sylius/Sylius/blob/34ab79289fa127714d2443dd78bde9be27b19d78/src/Sylius/Bundle/ShippingBundle/Form/Type/ShippingMethodChoiceType.php#L69

Correct logic
```php
return $this->repository->findBy(['enabled' => true], ['position' => 'ASC']);
```

**Comment by EmilMassey** [comment]
Hi, Dmitry!
Can you help me with the PR and commit the change you proposed?

I will try to find some time to write acceptance tests.

**Comment by dbalabka** [comment]
@EmilMassey, yes. I'll try to find spare time for this.

**Comment by dbalabka** [comment]
Probably, sorting should be changed in `findEnabledForChannel` because `findEnabledForZonesAndChannel` already has correct `->addOrderBy('o.position', 'ASC')` sorting.

**Pull request closed without merging**
