### PR TITLE
Check if customer is set before get/set email

### PR DESCRIPTION
**Pull request by teohhanhui**
| Q               | A
| --------------- | -----
| Branch?         | 1.0
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | N/A
| License         | MIT

### CODE REVIEW

**Comment by Zales0123** [comment]
@teohhanhui ping :) it would be nice to have it merged, but we need some tests

**Comment by teohhanhui** [comment]
Haven't got the time for the tests yet. Sorry...

**Comment by Zales0123** [comment]
No problem at all, just provide them when you'll be able to do that :)

**Comment by pamil** [comment]
Thanks, Teoh! 🥇

**Comment by teohhanhui** [comment]
Thanks @pamil for taking care of the tests! :)

**Pull request merged**
