### PR TITLE
WIP [OrderBundle] Totals in Sylius tables column causes 500 internal error

### LINKED ISSUE #9639: items_total in sylius_order table column causes 500 internal error
**Sylius version affected**: 1.1

**Description**  

the items_total field has limited size int(11) , thus cause 500 internal error with high values
**Steps to reproduce**  

add 70 unit of some item to cart  with unit price 15000000 through sylius resftul api

**Possible Solution**  

items_total field type or value should be changed or if you have restrictions, there should be validation rather than internal error.

### PR DESCRIPTION
**Pull request by kayneth**
| Q               | A
| --------------- | -----
| Branch?         | master
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #9639 
| License         | MIT

### CODE REVIEW

**Comment by pamil** [comment]
It looks more tricky than at first, since we need to deal with strings instead of integers now :/

**Comment by lchrusciel** [comment]
Just reminding about old issue: https://github.com/Sylius/Sylius/issues/3163. 

If we want to do something about it, maybe we should consider Money VO.

**Comment by kayneth** [comment]
Hi ! 
I forgot about Doctrine handling bigint with strings ! 
I'll give it a look to some Money VO and try it into Sylius.

**Comment by pamil** [comment]
I'll close this PR as we can't merge this in 1.x, but I'll keep the issue open.

**Pull request closed without merging**
