### PR TITLE
Move DotEnv on prod requirements

### LINKED ISSUE #10158: Failure during prod installation
**Sylius version affected**: 1.4.0

**Description**  

Failure on cache:clear on prod due to DotEnv requirement.
```
Script symfony-cmd handling the auto-scripts event returned with error code 127
Script @auto-scripts was called via post-update-cmd
```

**Steps to reproduce**  

composer install --no-dev

**Possible Solution**  

Due to config/bootstrap.php, DotEnv is required on prod. Symfony/Skeleton has DotEnv on prod requirements.
https://github.com/symfony/skeleton/blob/master/composer.json

Maybe this is a bug on symfony...

### PR DESCRIPTION
**Pull request by loic425**
| Q               | A
| --------------- | -----
| Branch?         | 1.4
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #10158 
| License         | MIT

### CODE REVIEW

**Comment by loic425** [comment]
@pamil @lchrusciel 
This pull request failed because of application/before_script.sh
`run_command "chmod -R 555 app bin config docs features src templates tests translations vendor"`

Maybe I could add `run_command "rm -rf vendor"` on my "test-prod-requirements" ?

**Comment by pamil** [comment]
I discussed it a bit on Symfony's Slack and it looks like the best solution. However, I think it should go to Sylius-Standard, so that we don't force users to have `symfony/dotenv` installed when they don't want to.

**Comment by loic425** [comment]
> I discussed it a bit on Symfony's Slack and it looks like the best solution. However, I think it should go to Sylius-Standard, so that we don't force users to have `symfony/dotenv` installed when they don't want to.

Ok so I will move that on Sylius Standard

**Comment by loic425** [comment]
@pamil https://github.com/Sylius/Sylius-Standard/pull/333

**Comment by pamil** [comment]
Let's continue on Sylius-Standard repository then! :)

**Pull request closed without merging**
