### PR TITLE
Improve filters UI

### PR DESCRIPTION
**Pull request by kulczy**
| Q               | A
| --------------- | -----
| Branch?         | master
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| License         | MIT

### CODE REVIEW

**Comment by Roshyo** [comment]
IMO, filters should be set in the <th> of each attribute if possible, and in a separate block if they deal with multiple/no specific attribute.

That's what any other CMS do and it feels very intuitive.

The matching can be done by name (replacing '.' by '_') or with a specific configuration line.

And for the filter block itself. The global width of number inputs is way too large.

**Comment by vvasiloi** [comment]
In the first screenshot the number value field has an icon, what's that? Should it be for the customer input?

**Comment by kulczy** [comment]
@vcraescu my bad, it's just a chrome addon :D

**Comment by gabiudrescu** [comment]
poor @vcraescu... @kulczy I thought you meant @vvasiloi 

they are both Moldavians, but there's a river separating them.

**Comment by vcraescu** [comment]
@kulczy it's ok! 😁

**Comment by GSadee** [comment]
Thanks, Szymon! :tada:

**Pull request merged**
