### PR TITLE
Upgrade packages to Symfony 3

### PR DESCRIPTION
**Pull request by pamil**
| Q               | A
| --------------- | ---
| Bug fix?        | no |
| New feature?    | yes |
| BC breaks?      | yes |
| Related tickets | related to #6738 and #6896 |
| License         | MIT |

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
Thanks Kamil!

**Comment by bendavies** [comment]
amazing effort @pamil

**Comment by bendavies** [comment]
@pamil symfony 3.2 is tagged

**Comment by pjedrzejewski** [comment]
See #6948. :)

**Comment by bendavies** [comment]
@pamil so are non core bundles (settings bundle) remaining on symfony 2.8? abandoned?
What did you replace settings bundle functionality with in sylius?

**Comment by michalmarcinkowski** [comment]
We didn't use settings in core and this bundle is a generic Symfony bundle not even related to eCommerce, so we excluded it from main repository. We're still trying to figure out the best approach to these not eCommerce bundles and extensions, so stay tuned.

**Pull request merged**
