### PR TITLE
[Promotion] Don't lock Doctrine to version 2.4.x only

### PR DESCRIPTION
**Pull request by stloyd**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| License         | MIT

Without this change I cannot use newest versions of this standalone component.

### CODE REVIEW

**Comment by stloyd** [comment]
@pjedrzejewski @michalmarcinkowski ping

**Comment by pjedrzejewski** [comment]
See https://github.com/Sylius/Sylius/issues/3268, we cannot use 2.5 until this is resolved. :/

**Comment by stloyd** [comment]
@pjedrzejewski But this has __nothing__ to do with __standalone__ usage as this component __don't__ depend on this functionality! Even bundle don't depend on this IIRC...

**Comment by pamil** [comment]
IMO the component itself can be used with 2.5, it does not use any sorting on translatable fields. The only references to ORM are in `CouponGenerator`.

**Pull request closed without merging**
