### PR TITLE
[AUTO] Updated translations from Crowdin

### PR DESCRIPTION
**Pull request by SyliusBot**

### CODE REVIEW

**Comment by pamil** [comment]
Awesome work @SyliusBot :tada:

**Comment by Zales0123** [comment]
Yes @SyliusBot, you're doing great job with translations, keep it that way!

**Comment by lchrusciel** [comment]
We are proud of you, @SyliusBot. Great job, great! :tada: :+1: :100: :8ball:

**Comment by michalmarcinkowski** [comment]
Awesome @SyliusBot! :+1:

**Pull request merged**
