### PR TITLE
Corrected import for money Twig macro.

### PR DESCRIPTION
**Pull request by kkevindev**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.12  |
| Bug fix?        | no                                                       |
| New feature?    | no                                                       |
| BC breaks?      | no                                                       |
| Deprecations?   | no |
| Related tickets | |
| License         | MIT                                                          |

### CODE REVIEW

**Review by Roshyo — COMMENTED** [review]
Both are correct, there is even one in the CoreBundle. It all depends on what/where you want to display, and what bundles you have enabled.

**Comment by kkevindev** [comment]
@Roshyo 

> Both are correct, there is even one in the CoreBundle. It all depends on what/where you want to display, and what bundles you have enabled.

Than I would rather see the one from the CoreBundle instead of the one in the ShopBundle or AdminBundle. So the documentation is always right, wether you have the ShopBundle or AdminBundle installed or not.

**Comment by kkevindev** [comment]
Do you agree? @Roshyo

**Review by CoderMaggie — APPROVED** [review]

**Comment by kkevindev** [comment]
@CoderMaggie @Roshyo PR still open?

*< Surprised Pikachu.png >*

**Comment by kkevindev** [comment]
@jakubtobiasz 👀

**Comment by jakubtobiasz** [comment]
We have this file (`money.html.twig`) in `CoreBundle`, `AdminBundle` and `ShopBundle`. If you look inside each of them you can find there is a different set of macros. The presence of this file in `CoreBundle` is a solve to some use-case. In Admin Panel you should use the one from `AdminBundle`, and in the shop you should use the one from `ShopBundle`.

If you want you can change your PR to include this information, otherwise we will close this PR soon. Thanks for your contribution!

**Pull request closed without merging**
