### PR TITLE
Update messenger table if table exist

### LINKED ISSUE #13838: Database isn't sync with mapping for Sylius 1.11
**Sylius version affected**: 1.11

**Description**  

After a new installation of Sylius 1.11, the database schema isn't in sync with the current mapping file. Because the length of column queue_name [has changed from 255 to 190](https://github.com/symfony/doctrine-messenger/blob/5.4/Transport/Connection.php#L437) and missing two indexes on queue_name and available_at columns. 
The [Sylius migration file](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Migrations/Version20220203115813.php) creates the table with the old length.

**Steps to reproduce**  

- Install a Sylius 1.11
- Run the command: `bin/console doctrine:schema:validate`

**Possible Solution**  
Create a new migration file with the new length and indexes, like:

```php
    public function up(Schema $schema): void
    {
        if ($schema->hasTable('messenger_messages')) {
            $this->addSql('ALTER TABLE messenger_messages CHANGE queue_name queue_name VARCHAR(190) NOT NULL');
            $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
            $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        }
    }
```

### PR DESCRIPTION
**Pull request by delyriand**
| Q               | A
| --------------- | -----
| Branch?         | master 
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #13838
| License         | MIT

### CODE REVIEW

**Comment by lchrusciel** [comment]
Hey Maxime, 

thanks a lot for your contribution. Do you know, why we didn't catch it up with our workflow? Can we improve our tests to avoid regression in the future?

**Comment by delyriand** [comment]
I don't know why your workflow don't catch this error. Because in your `workflow/application.yml` file, i saw 2 tests with the validation command: `test-application-without-frontend-postgres` and `test-application-without-frontend-mariadb`…

**Comment by lchrusciel** [comment]
Ok, PostgreSQL is not working, MariaDB is throwing erros:
image

and we don't test it on MySQL....

**Comment by Ferror** [comment]
@lchrusciel I will open PR with schema validation on pipelines

**Review by wadjeroudi — APPROVED** [review]
having the same problem after sylius 1.11 upgrade.

**Pull request closed without merging**
