### PR TITLE
Fix default sorting for shipping methods on store

### PR DESCRIPTION
**Pull request by dbalabka**
| Q               | A
| --------------- | -----
| Branch?         | 1.7 
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | continuation of #11107
| License         | MIT

### CODE REVIEW

**Comment by pamil** [comment]
The base of this pull-request was changed, you need fetch and reset your local branch 
if you want to add new commits to this pull request. **Reset before you pull, else commits
may become messed-up.**

Unless you added new commits (to this branch) locally that you did not push yet, 
execute `git fetch origin && git reset "shipping_methods_sorting_issue_1.7"` to update your local branch.
 
Feel free to ask for assistance when you get stuck :+1:

**Comment by dbalabka** [comment]
@pamil am I right that you do not support 1.7 any more?

**Comment by dbalabka** [comment]
Do not stale

**Comment by jakubtobiasz** [comment]
Closing, as it's been fixed in #14940.

**Pull request closed without merging**
