### PR TITLE
[Behat] Use StringInflector wherever it can be used

### PR DESCRIPTION
**Pull request by Zales0123**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Related tickets |
| License         | MIT

### CODE REVIEW

**Comment by michalmarcinkowski** [comment]
Many more classes should also use `StringInflector`. Search for all places where `setCode` is used, take a deeper look at `Behat\Context\Setup\*` as there are a lot of these examples :)

**Comment by michalmarcinkowski** [comment]
Thanks Mateusz!

**Comment by michalmarcinkowski** [comment]
@Zales0123 there are still few classes left e.g. `PaymentContext`, `ProductAssociationTypeContext` 😉

**Comment by Zales0123** [comment]
👍 it's hard to find them all 😄  Gonna fix this in the nearest future

**Pull request merged**
