### PR TITLE
[Translation][UIBundle] Translation for filters

### PR DESCRIPTION
**Pull request by plozmun**
| Q               | A
| --------------- | ---
| Bug fix?        | yes |
| New feature?    | no |
| BC breaks?      | no |
| Related tickets |  |
| License         | MIT |

### CODE REVIEW

**Comment by c-revillo** [comment]
:+1:

**Comment by pamil** [comment]
Rerunning Travis CI, good to go when passing :)

**Comment by pamil** [comment]
Finally, Travis got this PR 💃

**Comment by lchrusciel** [comment]
Thanks, Pablo! :)

**Pull request merged**
