### PR TITLE
[Payum] Upgrade up to 0.12 

### PR DESCRIPTION
**Pull request by makasim**
This PR updates Payum up to 0.12 (it is still in development). With this version it is extremely easy to add a payment gateway.
- Configure `PayumBundle` (follow the Payum's [doc](http://payum.org/doc#PayumBundle))

``` yaml
# app/config/config.yml

twig:
    paths:
        %kernel.root_dir%/../vendor/payum/payum/src/Payum/Core/Resources/views: PayumCore
        %kernel.root_dir%/../vendor/payum/payum/src/Payum/Stripe/Resources/views: PayumStripe

payum:
    storages:
        Sylius\Component\Core\Model\Order: { doctrine: orm }
        Sylius\Component\Core\Model\Payment: { doctrine: orm }

    security:
        token_storage:
            Sylius\Bundle\PayumBundle\Model\PaymentSecurityToken: { doctrine: orm }

        stripe_checkout:
            stripe_checkout:
                publishable_key: %stripe.publishable_key%
                secret_key: %stripe.secret_key%
```
- Add `stripe_checkout` to sylius_payment_methods table.
- Add `stripe_checkout` to 

``` yaml
# app/config/config.yml

sylius_payment:
    gateways:
        stripe_checkout: Stripe Checkout
```

That's it. All other [payments supported](http://payum.org/doc/0.12/Core/supported-payments) by Payum could be added similar way.

### CODE REVIEW

**Comment by madc** [comment]
I'm having an issue configuring any kind of new payment. What i'm trying to do is, to add offline or manual payment gateways to my sylius applicaton.

app/config/config.yml
```
sylius_payment:
    gateways:
        offline: Offline Payment
```
Its now possible to add a payment method using this gateway, but when it comes to finalizing an order, i get an exception ('Payum payment named offline does not exist.').

Looking into the payments, the offline gateway was not added:
```
array (size=6)
  'paypal_express_checkout' => string 'payum.context.paypal_express_checkout.payment' (length=45)
  'stripe' => string 'payum.context.stripe.payment' (length=28)
  'be2bill' => string 'payum.context.be2bill.payment' (length=29)
  'be2bill_onsite' => string 'payum.context.be2bill_onsite.payment' (length=36)
  'stripe_checkout' => string 'payum.context.stripe_checkout.payment' (length=37)
  'dummy' => string 'payum.context.dummy.payment' (length=27)
```

It feels like i've forgotten to configure something, but i I'm very certain, this has worked before.
Any hints?

**Comment by makasim** [comment]
This is not enough to configure `sylius_payment`, since it does not actually process any payments. By default Sylius uses Payum to process payments and you have to configure Payum too:

something like this: https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Resources/config/app/payum.yml#L1

The payum bundle is here: http://payum.org/doc#PayumBundle

**Comment by madc** [comment]
Thanks. I really was convinced, that it had worked before.
Just for future reference the configuration for offline payment:

app/config/config.yml
```
sylius_payment:
    gateways:
        offline: Offline Payment

payum:
    contexts:
        offline:
            offline: ~
``
Btw, I think, this should be part of the default sylius config.

**Comment by kayue** [comment]
@makasim Actually which part of the code is using the following config? Because Sylius has a `sylius_payment_method` table, I thought it does everything already.

```
sylius_payment:
    gateways:
        stripe_checkout: Stripe Checkout
```

**Comment by makasim** [comment]
@kayue I believe it is need for the payment choice form type, that's it.

I am working on ability to configure payments in the backend and when I am ready to adopt it to Sylius I will change these parts.

**Comment by kayue** [comment]
@makasim Oh for the backend, I see, thanks.

**Comment by makasim** [comment]
Not only for the backend, it used on the payment step, where you asked to select a payment method.

**Pull request merged**
