### PR TITLE
Remove web installer and clean up InstallerBundle

### PR DESCRIPTION
**Pull request by pjedrzejewski**
Web installer is not working at all and pretty much dead code. We want to rework the installation commands and I think it would be cool to work on a bit cleaner InstallerBundle.

Web installer is of course something that we want to have, but it is not a priority for the first release.

### CODE REVIEW

**Comment by stloyd** [comment]
:+1:

**Comment by Zales0123** [comment]
Big :+1: from me. Of course not because of resigning idea of web installer (it'll be **awesome** in the future), but obviously Sylius install command needs some work to reach the perfection, that we all want to achieve ;)

**Comment by michalmarcinkowski** [comment]
:+1: for removing dead code

**Comment by pjedrzejewski** [comment]
@michalmarcinkowski Good to go then I guess. :)

**Comment by michalmarcinkowski** [comment]
I wish to see more PRs of this type! :+1:

**Pull request merged**
