### PR TITLE
[Maintenance] Launch of `Sylius Sp. z o.o.` copyright owner across project files

### PR DESCRIPTION
**Pull request by Rafikooo**
| Q               | A                                                            |
|-----------------|--------------------------------------------------------------|
| Branch?         | 1.12 and 1.13                   |
| Bug fix?        | no                                                      |
| New feature?    | no                                                      |
| BC breaks?      | no                                                      |
| Deprecations?   | no |
| License         | MIT                                                          |

### CODE REVIEW

**Review by jakubtobiasz — APPROVED** [review]

**Comment by jakubtobiasz** [comment]
Thank you, @Rafikooo!

**Comment by loic425** [comment]
@jakubtobiasz what does this mean? SP. Z o.o?

**Comment by vvasiloi** [comment]
@loic425, it means "Private limited company", like SARL in France.

**Comment by jakubtobiasz** [comment]
@loic425 it's exactly Limited Liability Company. The legal abbreviation in Poland is `Sp. z o.o.`, so we decided to use it. If you look at e.g. JetBrains, their formal name is `JetBrains s.r.o`. We could use `Sylius LLC`, but we decided to stay with the legal form.

**Pull request merged**
