### PR TITLE
[UI] Fix broken checkboxes that dont change state

### PR DESCRIPTION
**Pull request by misaon**
Order (label <=> input) in Semantic UI

| Q               | A
| --------------- | -----
| Branch         | 1.7, 1.8 and master
| Bug fix        | yes
| New feature    | no
| BC breaks      | no
| Deprecations   | no
| License         | MIT

### CODE REVIEW

**Review by lchrusciel — APPROVED** [review]
Hey Ondrej,

thanks for your proposal 👍 Can you point to the place, where the problem occurs? May I see it on our demo?

**Comment by lchrusciel** [comment]
The base of this pull-request was changed, you need fetch and reset your local branch 
if you want to add new commits to this pull request. **Reset before you pull, else commits
may become messed-up.**

Unless you added new commits (to this branch) locally that you did not push yet, 
execute `git fetch origin && git reset "patch-1"` to update your local branch.
 
Feel free to ask for assistance when you get stuck :+1:

**Comment by misaon** [comment]
@lchrusciel I don't think this block is used in your demo, however with us we used this block in custom administration modifications.

**Comment by lchrusciel** [comment]
Thanks, Ondřej! :1st_place_medal:

**Pull request merged**
