### PR TITLE
[BugFix] Add missing argument in metchod

### PR DESCRIPTION
**Pull request by Tomanhez**
| Q               | A
| --------------- | -----
| Branch?         | master
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| License         | MIT

Fix bug: 
Screenshot 2020-12-22 at 16 05 41
Screenshot 2020-12-22 at 16 05 53

### CODE REVIEW

**Review by pamil — APPROVED** [review]

**Comment by pamil** [comment]
Thank you, Tomasz! :tada:

**Comment by Zales0123** [comment]
👍 Shouldn't we then change the version in composer.json to `^2.4`? 2.3.1 [still uses](https://github.com/liip/LiipImagineBundle/blob/2.3.1/Templating/FilterTrait.php) the previous number of arguments

**Comment by FabienSalles** [comment]
Hello,

When will there be a tag available for this fix ?

**Comment by Zales0123** [comment]
Hello @FabienSalles, we should release it today 🖖

**Comment by FabienSalles** [comment]
Thanks for your quick response :).

**Pull request merged**
