### PR TITLE
Coupon generation fix

### PR DESCRIPTION
**Pull request by lchrusciel**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Related tickets | mentioned in [comment](https://github.com/Sylius/Sylius/pull/3339/files#r64144189)
| License         | MIT

### CODE REVIEW

**Comment by pamil** [comment]
This way memory taken by generated codes will never be freed until the process dies. We can remove `$this->generatedCoupons` property and pass a local variable as an argument to the other functions without affecting the performance.

**Comment by pjedrzejewski** [comment]
@pamil 👍 , but in a separate PR.

**Comment by pjedrzejewski** [comment]
Thanks Łukasz! /cc @peteward I will retag v0.18.0 so that it includes this. :)

**Comment by peteward** [comment]
Thanks for the quick turnaround on this guys! 👍

**Pull request merged**
